### PR TITLE
Kiali requires istio 0.7.1+ version

### PR DESCRIPTION
**Pull request by xeviknal**
Both readmes from root and from hack folder updated.
The istio upgrade is done to 0.7.1 since [0.7.0 was buggy](https://github.com/istio/istio/releases/tag/0.7.0).

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by jotak** [comment]
@xeviknal did you try to start kiali on 0.7.1 ? I did but had no metrics at all, I don't know if it's something going wrong in my environment, or if it's due to istio 0.7.1.

**Comment by xeviknal** [comment]
Yes, I did and metrics are working from my side. Do you have all the addons installed (grafana, promotheus, and so on)?
How have you installed that istio version?

istio-0 7 0-graph

istio-0 7 0-metrics

**Comment by jotak** [comment]
@xeviknal I was using our hack script.
I'll try again later

**Comment by jotak** [comment]
FYI it's ok for me, I had to prune docker volume...

**Comment by xeviknal** [comment]
@jmazzitelli, @abonas  It worked for me as well.
Hayk has installed version 0.7.1 with no problem.
I think this is ready to merge.
Thanks

**Comment by jmazzitelli** [comment]
I also tested and all works.

**Pull request merged**
