### PR TITLE
KIALI-2658 Fix missing kind in *Binding Istio CRDs

### PR DESCRIPTION
**Pull request by lucasponce**
Fix missing fields in Istio config mapping.

https://issues.jboss.org/browse/KIALI-2658

### CODE REVIEW

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#790](https://paste.fedoraproject.org/paste/xoVGHhEJK5xH9CGQNyZvtA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1601]](https://paste.fedoraproject.org/paste/oJIGYh7MwZYzfEaX-5PZiA)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#792](https://paste.fedoraproject.org/paste/-lJnPmntvbdiU6Dyzo-P2w)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1603]](https://paste.fedoraproject.org/paste/fbyVq5zujHKQOgO7WxNPug)

**Comment by lucasponce** [comment]
I found another missing. I'll send another commit.

**Comment by lucasponce** [comment]
No, it's fine.
This is ready for review @hhovsepy

**Pull request merged**
