### PR TITLE
KIALI-2048 Don't panic on Grafana error

### PR DESCRIPTION
**Pull request by jotak**
- Better handling of grafana errors & unmarshalling
- Propagate error message
- More tests

JIRA: https://issues.jboss.org/browse/KIALI-2048

### CODE REVIEW

**Comment by jotak** [comment]
Fixing issue #689 cc @leosunmo

**Comment by leosunmo** [comment]
It should be pointed out that the documentation on the main README for `GRAFANA_SERVICE_NAMESPACE` is incorrect as it states that the setting will be ignored if `GRAFANA_URL` is supplied, which is not the case. If I run the above configuration _without_ `external_services.grafana.service_namespace` it does _not_ panic and it simply "can't find grafana service".

**Comment by jotak** [comment]
Thanks @leosunmo 

> It should be pointed out that the documentation on the main README for `GRAFANA_SERVICE_NAMESPACE` is incorrect as it states that the setting will be ignored if `GRAFANA_URL` is supplied, which is not the case.

That's true, I think that was modified after istio 1.0 release, we had to change our way to query grafana but the doc wasn't updated as it should. I'll do it in another PR. Thanks for pointing it out.

**Comment by aljesusg** [comment]
Please @jotak rebase this PR

**Pull request merged**
