### PR TITLE
[v1.73] Upgrade cypress and cucumber libraries

### PR DESCRIPTION
**Pull request by ferhoyos**
### Describe the change

Backport of PR #6980 to version 1.73

### Issue reference

#6975

### CODE REVIEW

**Comment by ferhoyos** [comment]
Do not merge until OSSM 2.5.0 is released.

**Comment by ferhoyos** [comment]
OSSM 2.5 is released, so we can merge backports to v1.73 branch

**Comment by jshaughn** [comment]
@ScriptingShrimp Please take a look now that this is merge-able.

**Review by ScriptingShrimp — APPROVED** [review]
I tested this on OCP with the prod build of v1.73, overall looks good with few fails:

 Sidebar toggle
    1) Close the sidebar
    2) Open the sidebar
```
     AssertionError: Timed out retrying after 40000ms: expected '<div#page-sidebar.pf-c-page__sidebar.pf-m-collapsed.fhjc1z5>' not to be 'visible'
```
  Kiali Services page
    1) The idle status of a service is reported in the list of services
```
     CypressError: `cy.exec('../hack/istio/install-sleep-demo.sh   -a amd64')` timed out after waiting `300000ms`.
```

  Kiali Istio Config page
    1) Create a K8s Gateway scenario
    2) Create multiple K8s Gateways with colliding hostnames and port combinations and check for a reference. Then delete one of them and the reference should be gone.
```
     AssertionError: Timed out retrying after 40000ms: Expected to find element: `[data-test=VirtualItem_Nsbookinfo_k8sgateway_k8sapigateway] svg`, but never found it.
```
Service Details Wizard: K8s Gateway API Routing
    1) See a HTTPRoute generated
    2) Update a K8s Gateway API Routing scenario
    3) See a K8s Gateway generated with warning
    4) Delete the K8s Gateway Routing scenario

```
1) Service Details Wizard: K8s Gateway API Routing
       See a HTTPRoute generated:
     AssertionError: Timed out retrying after 40000ms: Expected to find content: 'HTTP' within the element: <table.fbfhvqo.pf-c-table.pf-m-grid-md.pf-m-compact> and with the selector: 'span' but never did.
      at Context.eval (https://kiali-istio-system.apps.user-rhos-d-2.servicemesh.rhqeaws.com/__cypress/tests?p=cypress/integration/featureFiles/wizard_k8sgw_api_routing.feature:15929:14)

  2) Service Details Wizard: K8s Gateway API Routing
       Update a K8s Gateway API Routing scenario:
     AssertionError: Timed out retrying after 40000ms: Expected to find element: `div[aria-label="Update K8s Gateway API Routing"]`, but never found it.
      at Context.eval (https://kiali-istio-system.apps.user-rhos-d-2.servicemesh.rhqeaws.com/__cypress/tests?p=cypress/integration/featureFiles/wizard_k8sgw_api_routing.feature:16258:12)
      at Registry.runStepDefininition (https://kiali-istio-system.apps.user-rhos-d-2.servicemesh.rhqeaws.com/__cypress/tests?p=cypress/integration/featureFiles/wizard_k8sgw_api_routing.feature:8576:48)
      at Object.fn (https://kiali-istio-system.apps.user-rhos-d-2.servicemesh.rhqeaws.com/__cypress/tests?p=cypress/integration/featureFiles/wizard_k8sgw_api_routing.feature:15043:43)
      at runStepWithLogGroup (https://kiali-istio-system.apps.user-rhos-d-2.servicemesh.rhqeaws.com/__cypress/tests?p=cypress/integration/featureFiles/wizard_k8sgw_api_routing.feature:14655:29)
      at Context.eval (https://kiali-istio-system.apps.user-rhos-d-2.servicemesh.rhqeaws.com/__cypress/tests?p=cypress/integration/featureFiles/wizard_k8sgw_api_routing.feature:15039:62)

  3) Service Details Wizard: K8s Gateway API Routing
       See a K8s Gateway generated with warning:
     AssertionError: Timed out retrying after 40000ms: Expected to find content: 'G' within the element: <table.fbfhvqo.pf-c-table.pf-m-grid-md.pf-m-compact> and with the selector: 'span' but never did.
      at Context.eval (https://kiali-istio-system.apps.user-rhos-d-2.servicemesh.rhqeaws.com/__cypress/tests?p=cypress/integration/featureFiles/wizard_k8sgw_api_routing.feature:15929:14)

  4) Service Details Wizard: K8s Gateway API Routing
       Delete the K8s Gateway Routing scenario:
     CypressError: Timed out retrying after 40050ms: `cy.click()` failed because this element:

`<button tabindex="-1" data-ouia-component-type="PF4/DropdownItem" data-ouia-safe="true" data-ouia-component-id="OUIA-Generated-DropdownItem-8" data-test="delete_traffic_routing" aria-disabled="true" type="button" class="pf-m-disabled pf-c-dropdown__menu-item" role="menuitem">Delete ...</button>`

has CSS `pointer-events: none`

`pointer-events: none` prevents user mouse interaction.

Fix this problem, or use {force: true} to disable error checking.
```

LGTM for now, will rerun and fix the issues as a part of the downstream pipleline

**Comment by ScriptingShrimp** [comment]
Was not able reproduce, no issues with the upgrade. Tested on release pipelines.

**Pull request merged**
