### PR TITLE
KIALI-2748 Support Sidecar Istio resource in Istio Config

### PR DESCRIPTION
**Pull request by josejulio**
** Describe the change **

Adds Sidecar istio resource

UI PR: https://github.com/kiali/kiali-ui/pull/1230

### CODE REVIEW

**Comment by josejulio** [comment]
Please check https://github.com/kiali/kiali-ui/pull/1230 for related ui-changes

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1049](https://paste.fedoraproject.org/paste/yPvQN7DfVS51nYLoP48PJw)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1050](https://paste.fedoraproject.org/paste/yhfOFwkuFetMJX0Yx60Pgw)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1051](https://paste.fedoraproject.org/paste/QB3hzbQ4~ao-uYfN6YhuXg)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1052](https://paste.fedoraproject.org/paste/MDIeV2na9Z3j33oKTWeL2Q)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1053](https://paste.fedoraproject.org/paste/LRjieXT5c~D1HQ83AU-kGQ)
 :red_circle: PRT Failed, Please Contact QE

**Comment by lucasponce** [comment]
@josejulio ok, going to review it.
Please, could you rebase it with master ? 
It seems there is a conflict.

Thanks

**Comment by josejulio** [comment]
> It seems there is a conflict.

Rebased, thanks!

**Comment by josejulio** [comment]
> The List/Details workflows work well but the update/delete are not added.
> There are missing changes on business/istio_config.go in the logic to post/patch Sidecars.

Done

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1065](https://paste.fedoraproject.org/paste/T1~0lNN5ATUQ-qqjg2eR0g)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1965]](https://paste.fedoraproject.org/paste/qAmOLnpLIY9PKbt9w~xdwA)

**Pull request merged**
