### PR TITLE
support ztunnel new label

### PR DESCRIPTION
**Pull request by zirain**
At least start from istio 1.23, the ztunnel daemonset is deployed with new labels `app.kubernetes.io/name=ztunnel`

### Steps to test the PR

- Install Istio Ambient v1.23.1
- Enable waypoint
- Report  waypoint `Gateway API Class not found in configuration`

### Issue reference

Closes https://github.com/kiali/kiali/issues/7825

### CODE REVIEW

**Comment by jmazzitelli** [comment]
Please provide a github issue for this. Please refer to the Kiali community contribution guidelines here for why the Kiali project team asks for this: https://github.com/kiali/kiali/blob/master/CONTRIBUTING.md#making-a-change

**Comment by jshaughn** [comment]
Hi @zirain , why did you close the PR?

**Comment by zirain** [comment]
> Hi @zirain , why did you close the PR?

Sorry, I didn't have enough bandwith to follow the workflow, close first and leave to someone have time.
Or I can came back when I'm free to do that.

**Comment by jshaughn** [comment]
First, thanks for taking time to contribute a PR, @zirain.  The workflow is not too complicated for most things.  Here, we would just like a github issue explaining the bug or RFE, so we can tie it to the actual PR(s).   I can see what you are trying to do, so I created it for you: https://github.com/kiali/kiali/issues/7825.

I will re-open this PR so we can review it.

**Comment by zirain** [comment]
> First, thanks for taking time to contribute a PR, @zirain. The workflow is not too complicated for most things. Here, we would just like a github issue explaining the bug or RFE, so we can tie it to the actual PR(s). I can see what you are trying to do, so I created it for you: #7825.
> 
> I will re-open this PR so we can review it.

I agree, it's not complicated, just because I'm busy this week.

**Review by jshaughn — COMMENTED** [review]
This looks good to me, @zirain.  @josunect,  Should 2.x require 1.23 or higher? If so do we actually need the old labelselector test?

**Comment by josunect** [comment]
In my environment (1.23.2) It still uses the selector app=ztunnel, is also adding the new label, but the new code is not reached. That must be introduced here https://github.com/istio/istio/pull/52463/
image

IMO we should keep the current selector, as it was working in previous versions and also was tested in OpenShift, and has been reliable, unless until this moment.

**Comment by zirain** [comment]
I'm not sure why your tests passed, but pod's labels are different to daemonset's.

```console
k get po -n istio-system --show-labels ztunnel-xx85p
NAME            READY   STATUS    RESTARTS   AGE   LABELS
ztunnel-xx85p   1/1     Running   0          72s   app=ztunnel,controller-revision-hash=87f79c5b5,istio.io/dataplane-mode=none,pod-template-generation=1,sidecar.istio.io/inject=false
```
```console
k get ds -n istio-system ztunnel --show-labels
NAME      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE   LABELS
ztunnel   1         1         1       1            1           kubernetes.io/os=linux   85s   app.kubernetes.io/name=ztunnel,app.kubernetes.io/part-of=istio,install.operator.istio.io/owning-resource-namespace=istio-system,install.operator.istio.io/owning-resource=installed-state,istio.io/rev=default,operator.istio.io/component=Ztunnel,operator.istio.io/managed=Reconcile,operator.istio.io/version=1.23.1
```

**Comment by josunect** [comment]
> ```
> k get ds -n istio-system ztunnel --show-labels
> ```

right, this is checking the daemonset:

```
k describe ds -n istio-system ztunnel 
Name:           ztunnel
Selector:       app=ztunnel
```

**Comment by zirain** [comment]
> right, this is checking the daemonset:

oh, you're right, it's not labels but selector, looks like we're using a old branch, and kiali code from master has changed.

Sorry for the misunderstand.

**Comment by jmazzitelli** [comment]
FWIW: This is why we like to have github issues created first before contributors create PRs... Because in the issue we can have a dialogue with the community and everyone can discuss what the potential issues/solutions are and we can help clear up misunderstandings before a person wastes their time writing code.

**Pull request closed without merging**
