### PR TITLE
KIALI-2639 Support 3scale adapter Istio config

### PR DESCRIPTION
**Pull request by lucasponce**
WIP work to support 3scale adapter Istio operations.
It needs another PR for the UI, and probably this one needs to be updated.

### CODE REVIEW

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1010](https://paste.fedoraproject.org/paste/RcmRglr6xhZmO0ZYOfJCzA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1825]](https://paste.fedoraproject.org/paste/jlxdlQ2WhCDoHRe8k7AH0g)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1011](https://paste.fedoraproject.org/paste/QUuwieiLwG1BrOJ6m4DXQQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1826]](https://paste.fedoraproject.org/paste/orPvc0B24vmAD6q2ufj7IQ)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1013](https://paste.fedoraproject.org/paste/eeTSGBrPMtKAOYtNkqNtDA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1827]](https://paste.fedoraproject.org/paste/6q289sudFEbJYXzJz8h1yQ)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1017](https://paste.fedoraproject.org/paste/DRA7-SfTFhCxGiErPq9ddQ)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1026](https://paste.fedoraproject.org/paste/YGUPewcqgCIA6L1PXLdSJQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1846]](https://paste.fedoraproject.org/paste/v2St6sdDqQ7S0S5xv7OYkQ)

**Comment by rhqci** [comment]
PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1039](https://paste.fedoraproject.org/paste/R5NwzGzWDVbHxoOLe7AKxQ)
 :red_circle: PRT Failed, Please Contact QE

**Comment by lucasponce** [comment]
@aljesusg is this PR ok with you ?

**Comment by aljesusg** [comment]
Yes @lucasponce go ahead with the green button !!!

**Comment by lucasponce** [comment]
Thanks @hhovsepy @aljesusg

**Pull request merged**
