### PR TITLE
[Cypress] added @smoke annotations to related feature files

### PR DESCRIPTION
**Pull request by ScriptingShrimp**
added `@smoke` annotations to related feature files

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I don't think you meant to call out user "@"smoke in the description :)

Perhaps you should say it with backticks -  `@smoke`

**Comment by ScriptingShrimp** [comment]
whoops, sorry :sweat_smile:

**Review by jmazzitelli — APPROVED** [review]
I don't see any issues here.

But, can I ask a question - what does the `@smoke` annotation do? :}

**Comment by ScriptingShrimp** [comment]
Annotations like this will help us separate testing suite into more specific layers; i.e. if we deploy on third party infrastructure, we want to check only basic functionality and do not trigger full testing (functional & regression). Its cheaper and its up to us to decide what are relevant tests for our use. :point_right:  https://en.wikipedia.org/wiki/Smoke_testing_(software)

**Comment by ScriptingShrimp** [comment]
we already use that here - in scripts via `-e TAGS=` 
https://github.com/kiali/kiali/blob/d11b634883cb099d74e9579971f6a62e20fec311/frontend/package.json#L44

**Comment by smoke** [comment]
// offtopic - @ScriptingShrimp don't worry calling me out like that happens all the time, so I don't mind :) @jmazzitelli thank you for caring about that :beers:

**Pull request merged**
