### PR TITLE
Cypress tests for Gateway API validations [rebased] 

### PR DESCRIPTION
**Pull request by jshaughn**
This is a copy of @matejnesuta 's PR: https://github.com/kiali/kiali/pull/7484, rebased on kiali master.  Wondering if this will resolve the unexpected cypress fails...

Matej is no longer around to rebase the PR, so if this works we can merge this and close his PR.

closes https://github.com/kiali/kiali/issues/7218

### CODE REVIEW

**Comment by hhovsepy** [comment]
checking these failures locally

**Comment by hhovsepy** [comment]
Hi @jshaughn I have sent a PR https://github.com/jshaughn/kiali/pull/32 with fixing failing tests, probably to strict of removing conflicting DRs and other objects, but validations are having conflicts when anything is remaining from previous tests.

**Comment by hhovsepy** [comment]
The filing test "KIA1102 validation" is an issue in Kiali https://github.com/kiali/kiali/issues/7522

**Review by hhovsepy — APPROVED** [review]

**Comment by jshaughn** [comment]
> The filing test "KIA1102 validation" is an issue in Kiali https://github.com/kiali/kiali/issues/7522

OK, I merged this work and we can continue with #7522.  Thanks!

**Pull request merged**
