### PR TITLE
Add a standalone/embedded global state from kiosk variable

### PR DESCRIPTION
**Pull request by lucasponce**
Fixes https://github.com/kiali/kiali/issues/5129

PR for the following tasks:
- Add the "kiosk" variable into the global state.
- Use the global state for conditional rendering on the detail pages.
- Adjust the height calculation on embedded mode for the detail pages.
- Make these changes transparent to the standalone mode.

This work can be visualized in the Workload and Services where there are integration points with Kiali:
image

image

Note that the time range, time selector, and actions controllers are hidden on purpose in the context of this PR.

It's part of the iterations with @andrew-ronaldson to discuss how to visualize those controllers in the embedded mode.

### CODE REVIEW

**Review by jmazzitelli — APPROVED** [review]
Looks good within the console plugin:
image

**Review by leandroberetta — DISMISSED** [review]
This looks good.

**Review by jshaughn — COMMENTED** [review]
It seems OK.  Even as a first iteration I wonder whether it should be a little more robust, anyway, see the comments.

**Comment by lucasponce** [comment]
I've updated the changes with @jshaughn suggestion, but the integration to test shouldn't change:
image

The conditional rendering logic is open, as soon as we identify more use cases, these changes could be reverted and added in a different location, but I think it's good to start adding them into the code.

**Comment by lucasponce** [comment]
I've updated the changes with @jshaughn suggestion, but the integration to test shouldn't change:
image

The conditional rendering logic is open, as soon as we identify more use cases, these changes could be reverted and added in a different location, but I think it's good to start adding them into the code.

**Review by jshaughn — APPROVED** [review]
LGTM

**Pull request merged**
