### PR TITLE
Kiali-2477 Enable Gzip compression

### PR DESCRIPTION
**Pull request by josejulio**
** Describe the change **

Allows Kiali server to serve requests with gzip enabled (if the browser supports it, and for requests over 1400 bytes [1])

Here are some compressed requests as reference:

Resource | Uncompressed | Gzipped | Type | Compression Ratio
-- | -- | -- | -- | --
main.xx.css | 1.17MB | 166.28KB | css | 7.17529042791867
main.xx.js | 5.27MB | 1.36MB | js | 3.88358772056163
fontawesome.woff2 | 75.35KB | 75.37KB | font | 0.999779727120774
PatternFlyIcons-webfont.ffbe377e.woff | 38.04KB | 20.46KB | font | 1.85946152377315
Logo-login.xx.svg | 16.96KB | 4.13KB | svg | 4.10934911242604
Overpass-extralight.xx.woff2 | 34.23KB | 34.27KB | font | 0.998917193822306
Overpass-light.xx.woff2 | 33.66KB | 33.7KB | font | 0.998898869892785
Logo-alt.xx.svg | 4.67KB | 1.69KB | svg | 2.76402544823597
Overpass-regular.xx.woff2 | 34.3KB | 34.34KB | font | 0.998919410794517
overpass-semibold.xx.woff2 | 32.63KB | 32.67KB | font | 0.998864111914868
graph api (travel-portal, agency, istio-system) display unused | 31.49KB | 2.75KB | json | 11.4639175257732
health type=workload istio-system | 2.96KB | 316B | json | 9.60759493670886

** Issue reference **

https://issues.jboss.org/browse/KIALI-2477

** Backwards incompatible? **

- Is your change introducing backwards incompatible changes? 
No

** Documentation **

* Does your contribution contain user-visible changes like e.g. new or changed configuration settings?
Yes, new configuration `server.gzip_enabled`

[1] https://github.com/nytimes/gziphandler/blob/master/gzip.go#L36

### CODE REVIEW

**Comment by jshaughn** [comment]
@josejulio Is there a reason this PR has no reviewers assigned?

**Comment by josejulio** [comment]
I was waiting for volunteers, thanks @jshaughn !

--
I was really waiting for travis to pass and got distracted by something else.

**Comment by josejulio** [comment]
As we can see in the table, the gzipped fonts are bigger than the original file in most cases (woff2 vs woff).

The current library doesn't let to blacklist, only to whitelist.
I could 
a) Whitelist css, js, json, html, etc 
or
b) Send a PR to add a blacklisting feature to the library, so we could blacklist woff2 fonts and other resoures tha we find that perform bad when gzipped.

**Comment by mtho11** [comment]
@josejulio probably your solution **a)** would work just fine for now.

**Comment by josejulio** [comment]
I'll add css, html, json and js to the whitelist.

**Comment by josejulio** [comment]
Updated the PR. Now only css, js, json, html and svg files are compressed.

**Comment by josejulio** [comment]
@jshaughn could you review again? I only configured the library to compress css, js, json, html and svg.

**Pull request merged**
