### PR TITLE
Changed the environment variable and the readme exec_client

### PR DESCRIPTION
**Pull request by josunect**
Changed environment variable and README reference CLIENT_EXE for test integrations

https://github.com/kiali/kiali/issues/5093

### CODE REVIEW

**Comment by josunect** [comment]
cc @hhovsepy

**Review by hhovsepy — APPROVED** [review]
thanks @josunect

**Review by aljesusg — APPROVED** [review]
LGFM

**Comment by lucasponce** [comment]
CI passed, merging.

**Pull request merged**
