### PR TITLE
Rebase master istio 0.8

### PR DESCRIPTION
**Pull request by lucasponce**
Master and istio-0.8 start to diverge.
I have rebased locally istio-0.8 with latest master and I tried to resolve conflicts that appeared but this needs close revision before to merge as it is possible that something could be overwritten without notice in the rebase and introduce some regression.

### CODE REVIEW

**Comment by jotak** [comment]
Speaking only about the code I wrote, it looks good. I also reviewed the rest but it's difficult to give an opinion.
I suggest every developer whose name appears in the above commit list checks his own code.

**Comment by lucasponce** [comment]
I marked the commit with "Rebase on master. Conflict resolution on cytoscape.go".
Which I think was something between @xeviknal and @jshaughn .

But the problem is that it is possible that merging PR could brought some old code.
Locally test work (I'm fixing travis), but I think this needs some close test from people just to be sure we don't introduce regressions.

Also, another thing I don't like is that we need to force push as the history is changed, so I'm looking if we can avoid/minimize that.

**Comment by jotak** [comment]
To avoid force-push you would have to `git merge` instead of `rebase`. It also has the advantage that you get only 1 commit where to resolve conflicts, and not each commit individually. So faster to resolve.

**Comment by aljesusg** [comment]
@lucasponce we should change https://github.com/lucasponce/kiali/blob/rebase-master-istio-0.8/config/config.go#L53 to
```go
IstioVersionSupported = ">= 0.8"
```
if we can't support <0.8 after merger, I don't know if we'll continue supporting 0.7

**Comment by lucasponce** [comment]
@aljesusg thanks for the check.
Could you send a minor PR into istio-0.8 ?
I'm still playing with this PR to merge "master" and "istio-0.8" in a clean way.

**Comment by pilhuhn** [comment]
On 14 Jun 2018, at 10:44, Alberto Gutierrez wrote:

> if we can't support <0.8 after merger, I don't know if we'll continue 
> supporting 0.7

We should do a "release" of the branch for the sprint demo, which is the 
best version for 0.7.1.
We then merge the branch after the sprint demo and then fully 
concentrate on 0.8+.
If someone then needs 0.7.1 support, they can use the "release" for 
0.7.1

**Comment by lucasponce** [comment]
Closing this in favor of https://github.com/kiali/kiali/pull/282

**Comment by lucasponce** [comment]
@pilhuhn 
We should do a "release" of the branch for the sprint demo, which is the
best version for 0.7.1.
We then merge the branch after the sprint demo and then fully
concentrate on 0.8+.
If someone then needs 0.7.1 support, they can use the "release" for
0.7.1

Sure. We are talking about istio-0.8 only, not in master.

**Pull request closed without merging**
