### PR TITLE
Fix little disalignments in Kiali UI

### LINKED ISSUE #6639: Little disalignments in Kiali UI
I have noticed some little disalignments in Kiali UI due to recent changes (Dark mode and PF5 upgrade). Since they are minor ones I gather them all in one issue:

- 100% in slider does not fit into numeric box:

Before:
image

After:
image

- Envoy tabs with white background:

Before:
image

After: 
image

- About UI image is not shown and non-sense scrollbar appears:

Before:
image

After:
image

- (Graph) Info icon too far from input box:

Before:
image

After: 
image

- Kiali icon in Mesh page not adapted to dark mode:

Light theme:
image

Dark theme:
image

- Dark mode switch with round borders:

Proposal:
image

Current switch:
image

### PR DESCRIPTION
**Pull request by ferhoyos**
**Describe the change**

Fix little disalignments in Kiali UI:
- 100% in slider does not fit into numeric box:

Before:
image

After:
image

- Kiali icon in Mesh page not adapted to dark mode:

Before:
image

After:
image

- Dark mode switch with round borders:

Proposal:
image

Before:
image

After:
image

- Envoy tabs with white background:

Before:
image

After: 
image

- (Graph) Info icon too far from input box:

Before:
image

After: 
image

Bonus:
- I have removed defaultIconStyle from KialiIcon component (it does not make sense to export a global defaultIconStyle with no content when you are applying default icon styles inside the component)
- Remove checkboxes and radio button margins (not needed with PF5)

About UI modal issue is fixed in #6654 

**Issue reference**

Part of #6639.

### CODE REVIEW

**Review by josunect — COMMENTED** [review]
After doing a visual review, I've just found a small misalignment in the graph search input (Not sure if it was already there): 

image

**Comment by ferhoyos** [comment]
Hi @josunect, this misalignment was already there. If you find more like this, please post them here and I will fix them. 

Take into account that we are currently using deprecated Dropdowns, Selects and Tables components. They will be replaced with new PF components soon, so ignore them if the misalignments are related with such components.

**Review by hhovsepy — APPROVED** [review]
Looks good to me, tested on FF and Chrome.
Only one small thing if can be fixed in this PR, checkboxes padding:
Screenshot from 2023-09-25 11-48-33

**Comment by ferhoyos** [comment]
Thanks for the review @hhovsepy.

Checkbox alignment is quite tricky. If you center them in Chrome, they are disaligned in FF, and the other way round.

I have set checkbox CSS in such a way that alignment is acceptable in both browsers:
Chrome:
image

Firefox:
image

**Review by hhovsepy — APPROVED** [review]
Verified, thanks @ferhoyos :
Screenshot from 2023-09-25 14-48-46

**Review by jshaughn — APPROVED** [review]
Everything looks good/better! Thanks!

**Pull request merged**
