### PR TITLE
KIALI-1730 Unify logic to fetch workload list and workload details

### PR DESCRIPTION
**Pull request by lucasponce**
Fetch workload details was wrongly simplified and some corner cases as described in KIALI-1730 were showing different workloads in list/details pages.

### CODE REVIEW

**Comment by lucasponce** [comment]
@hhovsepy I've added the DNM label; if you could test this one and check if all the corner cases are gone it would be great. Thanks

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#226](https://paste.fedoraproject.org/paste/cjkm8rrcaAn4Le~HT4SnyQ)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1708]](https://paste.fedoraproject.org/paste/Kbou7hMTHF~U5kCLS3CVGA)
  * :heavy_check_mark: Istio-Upstream [#[553]](https://paste.fedoraproject.org/paste/DPHzL6FOii3sdjRX7hoj~Q)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1994, 1995]](https://paste.fedoraproject.org/paste/IcYZDJ65pzl~~l29gSg~Lw)
  * :heavy_check_mark: install-bookinfo [#[1084]](https://paste.fedoraproject.org/paste/Yg681Tzm1Yrgmv0K5UjE5g)
  * :heavy_check_mark: Kiali-on-Openshift [#[1100]](https://paste.fedoraproject.org/paste/IqPuEKelvhV-7pwQcjZn7g)
  * :heavy_check_mark: run-kiali-e2e-tests [#[508]](https://paste.fedoraproject.org/paste/FgAZnwld3d4QSG7g14Aa8w)


KIALI_NAME=kialicorepr579-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#227](https://paste.fedoraproject.org/paste/7VDszGYr0v-HlNdwn8aEyw)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1710]](https://paste.fedoraproject.org/paste/EIFwcI24fjAK4l46YQatuw)
  * :red_circle: Istio-Upstream [#[555]](https://paste.fedoraproject.org/paste/eLTA9CLUA4r1oN9u-LZRAg)


KIALI_NAME=kialicorepr579-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#228](https://paste.fedoraproject.org/paste/lDKi~Pa~~YqmqWbtq9i5Kg)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1712]](https://paste.fedoraproject.org/paste/CL9b08fdyKdkwGL8~xl5ig)
  * :red_circle: Istio-Upstream [#[557]](https://paste.fedoraproject.org/paste/aQYxYDFbT~~JdtQYEasMIA)


KIALI_NAME=kialicorepr579-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#229](https://paste.fedoraproject.org/paste/s~v401tVAQLnJRgeiJd-ug)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1713]](https://paste.fedoraproject.org/paste/~bEe9qnOpajLcmL3IINSdg)
  * :red_circle: Istio-Upstream [#[558]](https://paste.fedoraproject.org/paste/Si-9qPoB6AlY~LB4~PuMig)


KIALI_NAME=kialicorepr579-istio-system

**Pull request merged**
