### PR TITLE
Fix and Optimize Gateway Host Duplicate check for hosts with target namespace

### PR DESCRIPTION
**Pull request by maxbischoff**
** Describe the change **

Up until now, the duplicate Gateway Host only considered Ports and Selectors for separating the Comparison Spaces for Gateways. No special consideration was given for Hosts in the `namespace/host` Syntax (see [hosts in Gateway.spec.servers](https://istio.io/latest/docs/reference/config/networking/gateway/#Server) for a detailed description of this syntax). 

This PR explicitly checks the namespace of a Gateway Host in the duplicate check and thereby accomplishes two improvements:

* The duplicate check for a Gateway in namespace `test` with the host `./example.com` and the host `test/example.com` (in the same Port / Selector) is now correctly identified as duplicate host.
* The number of regex-based comparisons is greatly reduced for Gateways that expose one host to multiple namespaces.

This comes at the small cost of computing the target Namespace for each Host once, and comparing the target Namespaces when iterating over hosts with the same selector.

** Issue reference **

Fixes https://github.com/kiali/kiali/issues/4586

** Backwards incompatible? **

The change is backwards compatible.

** Documentation **

No user-visible changes are introduced.

### CODE REVIEW

**Comment by lucasponce** [comment]
Thanks for the PR @maxbischoff cc-ing @hhovsepy to review this work as he's also currently working on the area.

**Review by hhovsepy — APPROVED** [review]
Code LGTM, verified locally and regression tested. Thank you @maxbischoff for the fix, can you please open an issue for this?

**Comment by hhovsepy** [comment]
Tested all the combinations, good idea is to consider "*" in case of missing namespace:
Screenshot from 2021-12-14 09-49-57
Screenshot from 2021-12-14 09-50-25
Screenshot from 2021-12-14 09-50-54
Screenshot from 2021-12-14 09-51-15
Screenshot from 2021-12-14 09-51-36
Screenshot from 2021-12-14 09-55-43

**Review by skondkar — APPROVED** [review]
LGTM.
Verified with the namespace/host combinations. Also verified that running E2E tests is successful.

Screenshot from 2021-12-15 15-40-44

**Comment by skondkar** [comment]
Polarion test case ->> SWSQE-2175

**Pull request merged**
