### PR TITLE
Fix compatibility issue with go1.13.4

### LINKED ISSUE #1953: "Error trying to get OAuth metadata"
After leaving Kiali idle overnight, twice now the following error has occured.
    "Error trying to get OAuth metadata"

OCP version: 4.3.0-0.nightly-2019-11-07-062654

Kiali pod log:
I1118 19:43:47.678546 1 kiali.go:66] Kiali: Version: v1.10.0-SNAPSHOT, Commit: 220ceb40f803f2d5a903ffb072d769c9628da77d I1118 19:43:47.679029 1 kiali.go:210] Using authentication strategy [openshift] I1118 19:43:47.679058 1 kiali.go:87] Kiali: Console version: 1.10.0-snapshot.1-local-a29de569f402b7e21f9f35b4594a4e23cd32a61c I1118 19:43:47.759300 1 server.go:57] Server endpoint will start at [:20001/] I1118 19:43:47.759316 1 server.go:58] Server endpoint will serve static content from [/opt/kiali/console] I1118 19:43:47.759332 1 metrics_server.go:18] Starting Metrics Server on [:9090] I1118 19:43:47.759436 1 server.go:63] Server endpoint will require https E1118 20:02:40.410752 1 jaeger.go:27] Get https://jaeger-query.istio-system.svc/api/services: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) W1118 20:05:53.577506 1 authentication.go:229] Token error: could not get info from Openshift: the server has asked for the client to provide credentials E1118 21:46:31.832477 1 jaeger.go:27] Get https://jaeger-query.istio-system.svc/api/services: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### PR DESCRIPTION
**Pull request by israel-hdez**
Kiali is hitting an http client issue if built against go1.13.4. The issue seems to be related to some compatibility issue between golang1.13 and the kubernetes client v1.11.1 version which Kiali depends on.

Since Kiali is currently targeting OpenShift 4.2, this PR is:
* Bumping OpenShift client dependencies to version 4.2.
* Bumping Kubernetes client dependencies to version 1.14.6, because OS4.2.4 is based on k8s v1.14.6 (at least, this is what `oc version` reports).
  * Switching to using `kubernetes-*` tags, since this is the recommended approach noted in https://github.com/kubernetes/client-go/#client-go.

Bumping k8s and OS client version is, probably, a good idea anyway because seems to be deprecated (see https://github.com/kubernetes/client-go/#compatibility-matrix).

 This is also:
* Bumping yaml.v2 dependency to v2.2.7, because the k8s client uses a feature that is not available in the older version and Kiali wouldn't compile.
* Removing golang-lru and simplelru, because Glide was issuing the following warning when resolving dependencies: `[WARN]	Conflict: github.com/hashicorp/golang-lru rev is currently a0d98a5f288019575c6d1f4bb1573fef2d1fcdc4, but k8s.io/apimachinery wants 20f1fb78b0740ba8c3cb143a61e86ba5c8669768`
  * These are sub-dependencies that Kiali doesn't depend on directly. Glide seems to correctly resolve and bundle these dependencies. So, this looks safe.
* Removing protobuf dependencies, because Glide was issuing the following warning when resolving dependencies: `[WARN]	Conflict: github.com/golang/protobuf rev is currently v1.2.0, but k8s.io/api wants b4deda0973fb4c70b50d226b1af49f3da59f5265`
  * These are sub-dependencies that Kiali doesn't depend on directly. Glide seems to correctly resolve and bundle these dependencies. So, this looks safe.

Fixes #1953

### CODE REVIEW

**Comment by jmazzitelli** [comment]
> Since Kiali is currently targeting OpenShift 4.2, this PR is: 
> * Bumping OpenShift client dependencies to version 4.2.
> * Bumping Kubernetes client dependencies to version 1.14.6,

Kiali is also targeting upstream Istio users. Upstream Istio users are supported on earlier versions of k8s. See: https://istio.io/docs/setup/getting-started/#platform

```
Before you can install Istio, you need a cluster running a compatible version of Kubernetes. Istio 1.4 has been tested with Kubernetes releases 1.13, 1.14, 1.15.
```

Before we merge this, we need to make sure we still work with the Kubernetes versions that upstream Istio still supports.

**Comment by israel-hdez** [comment]
@FilipB and/or @mattmahoneyrh can you try this PR on your build env to check that it correctly fixes the http2 client issue?

**Comment by jmazzitelli** [comment]
FYI: its the same set of supported k8s versions for Istio 1.3:

https://archive.istio.io/v1.3/docs/setup/platform-setup/

```
Istio 1.3 has been tested with these Kubernetes releases: 1.13, 1.14, 1.15.
```

So Istio 1.3 and Istio 1.4 (the current version and one minor version back) support Kubernetes 1.13 (as well as 1.14 and 1.15) which means that is what we should be supporting, too.

**Comment by israel-hdez** [comment]
> Before we merge this, we need to make sure we still work with the Kubernetes versions that upstream Istio still supports.

@jmazzitelli I'll smoke test this on minikube and report back. But, since OS is based on k8s 1.14, I don't see a reason why it wouldn't work.

**Comment by jmazzitelli** [comment]
> But, since OS is based on k8s 1.14, I don't see a reason why it wouldn't work.

Upstream Istio 1.3 and 1.4 supports one version back (k8s 1.13). If we assume 1.14 is backward compatible, then we are good. But its something we need to make sure just in case.

**Comment by israel-hdez** [comment]
Also, adding @lucasponce as a reviewer to help checking that the caching is not affected. And @jmazzitelli, perhaps you may also want to ensure that the prometheus scrape endpoint is unaffected because you added protobuf for https://github.com/kiali/kiali/pull/598/ (I see that the "Kiali Internal Metrics" tab is working OK, but not sure if that's the way to try it).

**Comment by jmazzitelli** [comment]
> And @jmazzitelli, perhaps you may also want to ensure that the prometheus scrape endpoint is unaffected because you added protobuf for #598 (I see that the "Kiali Internal Metrics" tab is working OK, but not sure if that's the way to try it).

We have a unit test to make sure this stuff works - https://github.com/jmazzitelli/kiali/blob/master/server/server_test.go#L135-L143
So as long as the go unit tests pass, we know this stuff is OK.

**Comment by FilipB** [comment]
kialiqeci

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1078](https://paste.fedoraproject.org/paste/ymKMTElf7aCrIdOjSkjmrA)
 :red_circle: PRT Failed, Please Contact QE

**Comment by mattmahoneyrh** [comment]
This fixed worked when built and tested on OCP4.3 + Service Mesh 1.0.2.

**Comment by FilipB** [comment]
UI and REST tests are passing. I will keep it idle for a while to see if the error appears again.

**Comment by israel-hdez** [comment]
I smoke tested using minikube with kubernetes v1.16.2, v1.15.6, 1.14.9 and 1.13.12 and all k8s versions seem to work OK.
So, I'm merging.

**Comment by lucasponce** [comment]
I was travelling and I coudln't review this part.
Have been the caching work tested ?

**Comment by FilipB** [comment]
@lucasponce Not by me, I just run QE UI and REST tests and verified the issue itself.

**Comment by israel-hdez** [comment]
@lucasponce I checked the code and saw that caching is enabled by default (or that's what I understood). At least, it is not broken. But I didn't do additional checking to ensure that caching is effective. So, I'll appreciate if you can do a quick check.

**Pull request merged**
