### PR TITLE
Check number of clusters to show the cluster badge in details pages

### PR DESCRIPTION
**Pull request by josunect**
Fixes https://github.com/kiali/kiali/issues/6107

### CODE REVIEW

**Comment by hhovsepy** [comment]
@josunect can the check be done by 'isMultiCluster' method? `import { isMultiCluster } from 'config';`

**Comment by josunect** [comment]
Thanks for the review, @hhovsepy. I tried to use that method first, but for some reason it was always returned true - I figured out that the data was not loaded for some reason. But, let me try it again.

**Comment by josunect** [comment]
> Thanks for the review, @hhovsepy. I tried to use that method first, but for some reason it was always returned true - I figured out that the data was not loaded for some reason. But, let me try it again.

Maybe some issues in my env, it is working now. 
Thank you!

**Review by hhovsepy — APPROVED** [review]
@josunect thanks, verified on a single cluster.

**Pull request merged**
