### PR TITLE
KIALI-1598 Support service node detail graph

### PR DESCRIPTION
**Pull request by jshaughn**
- also improve readability:
  - remove some dead code
  - remove escaped-quotes from some query strings
  - use %s (as opposed to %v) where appropriate in sprintf

### CODE REVIEW

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#90](https://paste.fedoraproject.org/paste/Zrpf9ztAsTvD1PwyjLaxTA)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1383]](https://paste.fedoraproject.org/paste/dPZWC7RxIWQ3RWIjqv1bhw)
  * :heavy_check_mark: Istio-Upstream [#[259]](https://paste.fedoraproject.org/paste/1dIm0bw9FjlkNVXK7EtAwA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1316, 1317]](https://paste.fedoraproject.org/paste/Qbb1AzGV8cVr9bm4t4WVGg)
  * :heavy_check_mark: install-bookinfo [#[743]](https://paste.fedoraproject.org/paste/pEue6cqyGjqzTG8WmkEaFg)
  * :heavy_check_mark: Kiali-on-Openshift [#[753]](https://paste.fedoraproject.org/paste/dNr7LEc~01Y1lTZwIVkWzw)
  * :heavy_check_mark: run-kiali-e2e-tests [#[200]](https://paste.fedoraproject.org/paste/mmdMbPuPUZ61Okm~l1-hHg)


KIALI_NAME=kialicorepr517-istio-system

**Comment by jmazzitelli** [comment]
Added DNM label - I think something might be wrong, particularly with TCP services. See: https://github.com/kiali/kiali-ui/pull/703#issuecomment-424399278

**Comment by jshaughn** [comment]
@jmazzitelli The mongo service is fixed, I had to change to source-side reporting as destination-side reporting was not setting the destination_service_name.

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#93](https://paste.fedoraproject.org/paste/PJlEyh4lrcQQxNz73AiODg)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1396]](https://paste.fedoraproject.org/paste/chXb4MVvh9FgqC2LIZgOCA)
  * :heavy_check_mark: Istio-Upstream [#[271]](https://paste.fedoraproject.org/paste/6v6XNShKFbbV4iYcaASELg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1344, 1345]](https://paste.fedoraproject.org/paste/08vny6zHG1jI96upPxu8vw)
  * :heavy_check_mark: install-bookinfo [#[758]](https://paste.fedoraproject.org/paste/B2jeY-KIMBAa8M2enEPwuQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[766]](https://paste.fedoraproject.org/paste/CcIGrQu4dFWfWb5RrbR1ZQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[212]](https://paste.fedoraproject.org/paste/zqkJjRjxjWAo8sxfRDRgoA)


KIALI_NAME=kialicorepr517-istio-system

**Pull request merged**
