### PR TITLE
Disabling (for now) integrations test due to stability issues

### PR DESCRIPTION
**Pull request by leandroberetta**

### CODE REVIEW

**Review by jmazzitelli — COMMENTED** [review]
I'm not comfortable approving this. I would want someone who is familiar with these tests to look at them and confirm these are truly false positives. We don't want to release something that is truly breaking our tests.

**Comment by lucasponce** [comment]
the last run seems progressing https://github.com/kiali/kiali/runs/6864567151?check_suite_focus=true

**Comment by lucasponce** [comment]
Perhaps the action item could be to have a backup of release from a local laptop?
I mean if for some reason the CI is unstable for reasons that we can't control, a manual built and push from any laptop could be a backup?

**Comment by lucasponce** [comment]
Put on hold, the merge, as it seems the latest run passed. So this is not necssary

**Pull request closed without merging**
