### PR TITLE
[KIALI-781] Multiple/All namespace support

### PR DESCRIPTION
**Pull request by jshaughn**
@jmazzitelli, note that there is some stuff in here that is outside the scope of kiali-781, specifically the stuff related to the Overview graph, that's really for kiali-756 and the "traffic light" stuff.  But it's here because I thought there would be more overlap.  And then there sort of wasn't.  But I don't really want to take it out because 756 is also in progress.

@cfcosta , I ask mazz to review because he is interested but if you have comments feel free to add.

### CODE REVIEW

**Comment by jshaughn** [comment]
Added DNM, I think there may be a small issue with the merge of namespaces.  need to verify

**Comment by jshaughn** [comment]
Removed DNM.  Removed duplicate edge issue (sort of a bear).  Here is a view of combined graph for istio-system and bookinfo...

screenshot

**Comment by abonas** [comment]
this looks like a PR that mixes a few different things. it is hard to understand what it is about this way, from description (or lack of ;)) and the code itself. it would be much better to separate it to several PRs or at least to separate commits.

**Comment by jshaughn** [comment]
I explained above why this 781 PR has some code that is more applicable to kiali-756.  If the reviewer requests changes I'll split it up, otherwise I'd prefer to just move on with things. The "Overview" graph stuff is relevant to 756.  Both 781 and 756 are subtasks of 655.

**Comment by cfcosta** [comment]
Fixed merge conflicts.

**Pull request merged**
