### PR TITLE
New KIA0107 for ServiceAccounts on remote cluster

### PR DESCRIPTION
**Pull request by hhovsepy**
### Describe the change
Actual for multicluster mode only. Kiali does not have validations for multicluster configs.
Currently, when ServiceAccount is created on a workload on remote cluster and the access is configured by spiffe: https://spiffe.io/docs/latest/try/getting-started-k8s/
Kiali is complaining on AuthPolicy that the ServiceAccount for the principal is not found. But in fact the SA exists.
Added a support of checking SA existence on remote clusters, and if exists, show warning message only on principals that "Service Account for this principal is on remote cluster"
Screenshot from 2024-04-05 10-47-57

### Steps to test the PR

Create a multicluster environment.

On `east` cluster create a Deployment with 'serviceAccountName', like in a SPIRE described in steps here: https://istio.io/latest/docs/ops/integrations/spire/

On `west` cluster create  AuthPolicy which points to a ServiceAccount on `east` cluster:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: productpage-viewer
  namespace: bookinfo
spec:
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/east/sa/default
  selector:
    matchLabels:
      app: productpage
```
The AuthorizationPolicy will show a Warning message instead of Error that the ServiceAccount is found on remote cluster.
When referring to a ServiceAccount which does not exit, the original Error message is still shown.

TBD An Epic to support SPIRE Integration to Istio in Kiali as well: https://github.com/kiali/kiali/issues/7261

### Automation testing

Unit tests added.

### Issue reference
https://github.com/kiali/kiali/issues/7152

### CODE REVIEW

**Review by josunect — APPROVED** [review]
Without this PR: 
image

With the PR: 
image

Code looks good. 
I think it good be great to clarify why if this is a warning in the docs.

**Review by josunect — CHANGES_REQUESTED** [review]
When the PA is in local cluster but the sa is just in the remote, the PA for the local cluster is not showing any warning: 

Local cluster: 
image

Remote cluster: 
image

sa from east: 
image

sa from west: 
image

The request send the cluster parameter: 
image

If we change it for bookinfo-ratings (In both clusters), the warning is just shown for the local cluster: 
image

**Comment by hhovsepy** [comment]
The issue happens by design, when ServiceAccount Names are loaded from Pod's, not from ServiceAccount objects (which in fact is not integrated into Kiali): Historical code: https://github.com/kiali/kiali/pull/5057/files#diff-d3d5bb00d54bcd1a9a0596fda3687c2019e0135f81a3c9e4f56856b57545bd11R76
Does anybody remember why we avoided loading ServiceAccounts directly from cluster? Some security reasons?

**Comment by hhovsepy** [comment]
@josunect so the Kiali is designed to load SA not directly from K8s but from pods 'ServiceAccountName'.
The correct testing scenario will be to refer AuthPolicy to service account which is mentioned in pods.

**Comment by hhovsepy** [comment]
@jshaughn wdyt to keep this newly added validation "Service Account for this principal is on remote cluster" as a `Warning` or make it an `Info` ? Before we implement Kiali integration with SPIFFY.

**Review by josunect — APPROVED** [review]
LGTM, tests added, work as expected

Thanks for clarifying, @hhovsepy !

**Comment by jshaughn** [comment]
> wdyt to keep this newly added validation "Service Account for this principal is on remote cluster" as a Warning or make it an Info ? Before we implement Kiali integration with SPIFFY.

@hhovsepy, sorry, I missed this question.  It seems you chose Warning, and that seems good to me.

**Pull request merged**
