### PR TITLE
fmt.Sprintf is missing istioNamespace

### PR DESCRIPTION
**Pull request by burmanm**
commit 8e51f83ba8c0cf82b9cc28fbd6464d1d89bf9b58 broke the ``make test`` as the Sprintf has wrong number of parameters

### CODE REVIEW

**Comment by jotak** [comment]
btw, I wonder if using explicit "%s" or "%d" wouldn't be better than "%v", as I guess it allows type checks via static code analysis

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#37](https://paste.fedoraproject.org/paste/nFHzCUPHLDdiQnEEQ2xgFg)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1267]](https://paste.fedoraproject.org/paste/NFQgsVc6kL9Jq2jfSMbZAw)
  * :heavy_check_mark: Istio-Upstream [#[152]](https://paste.fedoraproject.org/paste/pEuhIienfJt2ZZUNFpCF0w)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1048, 1049]](https://paste.fedoraproject.org/paste/Py~O~U4GyFdO5K8nBSHbCw)
  * :heavy_check_mark: install-bookinfo [#[617]](https://paste.fedoraproject.org/paste/Eqv4Tj-9XFEQP97jcQMSpQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[611]](https://paste.fedoraproject.org/paste/rPPcHLE5Y5ZP9IqWqF4-og)
  * :heavy_check_mark: run-kiali-e2e-tests [#[84]](https://paste.fedoraproject.org/paste/r4Q2YKGAeuuFeVY0-8Pqow)


KIALI_NAME=kialicorepr497-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#38](https://paste.fedoraproject.org/paste/M8K8x-~kezb~Sw4k-zhRwA)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1268]](https://paste.fedoraproject.org/paste/2HGEXmifWSH25Ma4I9jUHg)
  * :heavy_check_mark: Istio-Upstream [#[153]](https://paste.fedoraproject.org/paste/ztPqAuzBl7HmgE-wQZzsbg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1050, 1051]](https://paste.fedoraproject.org/paste/bEXC3RLdN39ULyvhtZ5Taw)
  * :heavy_check_mark: install-bookinfo [#[618]](https://paste.fedoraproject.org/paste/mrohmo0bK98~03RHnIYpzQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[612]](https://paste.fedoraproject.org/paste/VBiSnpIHmEQYijSvqQRtUA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[85]](https://paste.fedoraproject.org/paste/GSpwFUCZjZn9srdHMoicTQ)


KIALI_NAME=kialicorepr497-istio-system

**Comment by abonas** [comment]
@jotak can you please update the JIRA with the link to PR and close it

**Comment by jshaughn** [comment]
@burmanm & @jotak, kiitos & merci.

**Pull request merged**
