### PR TITLE
Remove ambient tests from jenkins pipeline tests

### PR DESCRIPTION
**Pull request by josunect**
### Describe the change

Remove ambient tests from jenkins pipeline tests, as Ambient requires another environment.

### Steps to test the PR

Run yarn cypress:run:junit, `@ambient `tests should not run.

### Automation testing

N/A

### CODE REVIEW

**Review by matejnesuta — COMMENTED** [review]
I think we should add the same condition for the target on the line 42 and add a separate `cypress:ambient` target as well. Not that it's important for Jenkins, but it might be handy. Otherwise lgtm.

**Comment by josunect** [comment]
> I think we should add the same condition for the target on the line 42 and add a separate `cypress:ambient` target as well. Not that it's important for Jenkins, but it might be handy. Otherwise lgtm.

You mean, this one, right, @matejnesuta ? https://github.com/kiali/kiali/blob/master/frontend/package.json#L42
There is already one for Ambient here: https://github.com/kiali/kiali/blob/master/frontend/package.json#L50

**Comment by matejnesuta** [comment]
> You mean, this one, right,
Yes
>There is already one for Ambient here
Yes, but this one is for the headless mode. I just thought it might be useful to add one for the GUI runner too.

**Review by matejnesuta — APPROVED** [review]
LGTM

**Pull request merged**
