### PR TITLE
KIALI-2716 [operator] avoid using cluster roles for kiali - only deploy roles/binds on accessible namespaces

### PR DESCRIPTION
**Pull request by jmazzitelli**
see https://issues.jboss.org/browse/KIALI-2716

Kiali is no longer required to be granted clusterrole roles. It can be configured to only be granted roles for those namespaces marked as accessible in the Kiali CR. If the user wants to grant Kiali access to namespaces in the mesh without requiring a clusterrole, they need to add this to the Kiali CR:

```
spec:
  deployment:
    accessible_namespaces:
    - bookinfo
    - mesh_*
    - yet_another_ns
```

or this syntax:

```
spec:
  deployment:
    accessible_namespaces: ['bookinfo', 'mesh_*', 'yet_another_ns']
```

Re-install Kiali (you can delete the old Kiali CR and create the new one to do this).

Note that it is still possible for the operator to give Kiali a clusterrole so it has access to all namespaces in the cluster (i.e. remain backward compatible with how Kiali works today - this is how upstream Istio installs Kiali for example). This requires you to define the accessible_namespaces with a single namespace entry of `"**"` (two asterisks). If you wish to do this, it requires you to give the operator itself the permissions to create clusterroles/clusterrolebindings. The deploy-kiali-operator.sh script will do this for you if you set the accessible namespaces to the special two asterisks value.

### 1. Test the New Feature That Gives Kiali Access to Only a Limited List of Accessible Namespaces

Before testing, make sure you check out this PR, and build it and the operator (make sure you run `make docker-build`).

Now install things. Note because this PR is not in master and we do not have a release for it, you need to tell the installer to pick up the "dev" image version that you just built.

```
./operator/deploy/deploy-kiali-operator.sh \
  --operator-image-version dev \
  --kiali-image-version dev \
  --auth-strategy login \
  --credentials-username kiali \
  --credentials-passphrase kiali
```

Now wait for the operator to install Kiali.  This will install Kiali with individual roles and the operator's cluster role does not have the ability to create new clusterroles or clusterrolebinds.

First look at the configmap and see the deployment/accessible_namespaces list and see it has a list of namespaces (the list will be something like "default", "istio-system", "myproject", "bookinfo" (if you have bookinfo installed):

```
oc get configmap kiali -n istio-system -o yaml
```

should show something like:

```
   deployment:
      accessible_namespaces:
      - bookinfo
      - default
      - istio-system
      - myproject
```

(NOTE: There should also be `api.namespaces.label_selector` set to something like `kiali.io/member-of: istio-system`).

For each of those accessible namespaces, there should be two roles and a role binding (note: NOT clusterroles or clusterrolebindings):

```
$ oc get role -l app=kiali -n bookinfo
NAME           AGE
kiali          4m02s
kiali-viewer   4m01s

$ oc get role -l app=kiali -n default
NAME           AGE
kiali          4m17s
kiali-viewer   4m16s

$ oc get role -l app=kiali -n istio-system
NAME           AGE
kiali          4m35s
kiali-viewer   4m34s

$ oc get role -l app=kiali -n myproject
NAME           AGE
kiali          4m20s
kiali-viewer   4m20s

$ oc get rolebinding -l app=kiali -n bookinfo
NAME    AGE
kiali   7m7s

$ oc get rolebinding -l app=kiali -n default
NAME    AGE
kiali   7m32s

$ oc get rolebinding -l app=kiali -n istio-system
NAME    AGE
kiali   7m58s

$ oc get rolebinding -l app=kiali -n myproject 
NAME    AGE
kiali   7m58s
```

For those namespaces, there should also be a label something like `kiali.io/member-of: istio-system` - for example:

```
$ oc get namespace myproject -o yaml
...
labels:
  kiali.io/member-of: istio-system
...
```

There should not be roles or rolebindings in any other namespace:

```
$ oc get role -l app=kiali -n kube-public
No resources found.

$ oc get role -l app=kiali -n openshift-node
No resources found.

$ oc get rolebinding -l app=kiali -n kube-public
No resources found.

$ oc get rolebinding -l app=kiali -n openshift-node
No resources found.
```

There should be no clusterrole or clusterrolebindings for Kiali:

```
$ oc get clusterrole -l app=kiali -n istio-system
No resources found.

$ oc get clusterrolebinding -l app=kiali -n istio-system
No resources found.
```

Now go to the Kiali UI and make sure you can log in as user "kiali" with passphrase "kiali".

Look at the list of namespaces in the Overview - you should see one card for each accessible namespace. 

Now create a new namespace - call it "foo": `oc create ns foo`

And now refresh the Kiali UI - you should NOT see a new "foo" card show up in Overview - you should not be able to see the foo namespace in the graph either.

Delete the foo namespace: `oc delete ns foo`

Now uninstall Kiali:

```
$ oc delete kiali kiali -n kiali-operator
kiali.kiali.io "kiali" deleted
```

At this point, the operator is uninstalling Kiali and all its roles and role bindings as well as the namespace labels. These should no longer exist:

```
$ oc get role -l app=kiali -n bookinfo
No resources found.

$ oc get role -l app=kiali -n default
No resources found.

$ oc get role -l app=kiali -n istio-system
No resources found.

$ oc get role -l app=kiali -n myproject
No resources found.

$ oc get rolebinding -l app=kiali -n bookinfo
No resources found.

$ oc get rolebinding -l app=kiali -n default
No resources found.

$ oc get rolebinding -l app=kiali -n istio-system
No resources found.

$ oc get rolebinding -l app=kiali -n myproject 
No resources found.
```

And if you get the namespace yamls, there should be no `kiali.io/member-of` labels - so look at the namespace yamls and see that those labels are gone:

```
$ oc get namespace myproject -o yaml
```

Next up will be instructions on how to test this to bring back the old functionality of allowing Kiali to see every namespace in the cluster, including new ones added while Kiali is still running.

### 2. Test That Shows Kiali Can Access All Namespaces Just Like Its Current Behavior

The purpose of this test is to show Kiali can run in the same way as it can currently - this means Kiali is given a cluster role/cluster role binding so it can view any and all namespaces in the entire cluster.

Before continuing, this assumes you followed the instructions earlier (check out this PR, build Kiali and the operator, etc).

You should start this round of testing with no install of Kiali or Kiali operator currently deployed - to clean everything, run `make -C operator operator-delete` - this will purge all Kiali resources.

Here is how you can install Kiali operator and Kiali to run in this backward-compat mode. The special option `--accessible-namespaces '**'` is what triggers this (alternatively, `-an '**'`). Note because this PR is not in master and we do not have a release for it, you need to tell the installer to pick up the "dev" image version that you built on your local machine.

```
./operator/deploy/deploy-kiali-operator.sh \
  --accessible-namespaces '**' \
  --operator-image-version dev \
  --kiali-image-version dev \
  --auth-strategy login \
  --credentials-username kiali \
  --credentials-passphrase kiali
```

Now wait for the operator to install Kiali.  This will install Kiali with a single cluster role/rolebinding giving it access to all namespaces. The operator's cluster role WILL have the ability to create new clusterroles or clusterrolebinds (because it needs to create that Kiali cluster role/role binding).

First look at the configmap and see the deployment/accessible_namespaces list and see it has a single value of `**`:

```
oc get configmap kiali -n istio-system -o yaml
```

should show this:

```
   deployment:
      accessible_namespaces:
      - '**'
```

There will not be a `api.namespaces.label_selector` set in the configmap (unless you explicitly set it).

There should be two cluster roles and a cluster role binding for Kiali:

```
$ oc get clusterrole -l app=kiali -n istio-system
NAME           AGE
kiali          62s
kiali-viewer   61s

$ oc get clusterrolebinding -l app=kiali -n istio-system
NAME    AGE
kiali   65s
```

There should not be roles or rolebindings in any namespace. For example:

```
$ oc get role -l app=kiali -n istio-system
No resources found.

$ oc get role -l app=kiali -n default
No resources found.

$ oc get rolebinding -l app=kiali -n istio-system 
No resources found.

$ oc get rolebinding -l app=kiali -n default
No resources found.
```

There should be no `kiali.io/member-of` labels in any namespace. For example, you should not see that label in the output of:

```
$ oc get namespace istio-system -o yaml
$ oc get namespace default -o yaml
```
Now go to the Kiali UI and make sure you can log in as user "kiali" with passphrase "kiali".

Look at the list of namespaces in the Overview - you should see one card for each namespace in the cluster (minus the ones we hide via the exclusion list -- api/namespaces/exclude.)

Now create a new namespace - call it "foo": `oc create ns foo`

And now refresh the Kiali UI - you should see a new "foo" card show up in Overview. You should also be able to see the selection "foo" in the graph's namespace drop down menu.

Delete the foo namespace: `oc delete ns foo`

Now notice the "foo" card disappears in the Overview page and you will not see the "foo" option in the namespace drop down in the graph page.

Now uninstall Kiali:

```
$ oc delete kiali kiali -n kiali-operator
kiali.kiali.io "kiali" deleted
```

At this point, the operator is uninstalling Kiali and its cluster roles and cluster role binding. They should no longer exist:

```
$ oc get clusterrole -l app=kiali -n istio-system
No resources found.

$ oc get clusterrolebinding -l app=kiali -n istio-system
No resources found.
```

This shows that Kiali can work in the original mode that it has been working in since day 1 - that being it is given a cluster role/cluster role binding to see every namespace in the cluster.

### CODE REVIEW

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#918](https://paste.fedoraproject.org/paste/lyDSmks4hzHhgJsGIqVHsQ)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#920](https://paste.fedoraproject.org/paste/eEnueRZ-6Bpb5WNP-FQzwQ)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#921](https://paste.fedoraproject.org/paste/Z17B9vPLoLkGaCS8V6FJJA)
  * :red_circle: run-kiali-e2e-tests [#[1727]](https://paste.fedoraproject.org/paste/wjLPUnncrmCUWHBkBJbZuw)

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Comment by jmazzitelli** [comment]
This is essentially done. It would be nice to allow the user to tell the deploy .sh script what accessible namespaces are at the time of installation. So we'd need to pass some kind of comma-separated list of namespaces via env. var to the script.

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#924](https://paste.fedoraproject.org/paste/H9VXqBQqRWXdEeamXcixsg)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#928](https://paste.fedoraproject.org/paste/vwMApXLxQxz61d7qs5mOLw)
  * :red_circle: run-kiali-e2e-tests [#[1735]](https://paste.fedoraproject.org/paste/DBC13K9oNqg2-c-d9P3PAA)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#934](https://paste.fedoraproject.org/paste/GrQsprXm6mIbOTxAJ-1Fbg)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#938](https://paste.fedoraproject.org/paste/NUPWjBeieegCVvuFGlarPw)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#940](https://paste.fedoraproject.org/paste/W0x2ALqD6dKskyqoIY6YWg)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#964](https://paste.fedoraproject.org/paste/o1MApJBduYljJsypEP7AlQ)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#976](https://paste.fedoraproject.org/paste/CTXhu4z2d06BeZvcFDZ1sQ)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#981](https://paste.fedoraproject.org/paste/ZmLAPt7aaw2Usl5D1y28vw)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#982](https://paste.fedoraproject.org/paste/YEbIwGeN9h58~BFjjUPsUg)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1020](https://paste.fedoraproject.org/paste/HjZnFe1EOJKo7KVavLV9sQ)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1036](https://paste.fedoraproject.org/paste/FyRsAtIgWXQIyJxjI4hJGw)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1037](https://paste.fedoraproject.org/paste/KAGcqcVvaz6IP~trhel9bA)
 :red_circle: PRT Failed, Please Contact QE

**Comment by jmazzitelli** [comment]
preliminary testing shows this working. I'll document some test procedures to illustrate what I did.

**Comment by jmazzitelli** [comment]
Before testing, make sure you check out this PR, and build it and the operator (make sure you run `make docker-build`).

**Test the New Feature That Gives Kiali Access to Only a Limited List of Accessible Namespaces**

Now install things. Note because this PR is not in master and we do not have a release for it, you need to tell the installer to pick up the "dev" image version that you just built.

```
./operator/deploy/deploy-kiali-operator.sh \
  --operator-image-version dev \
  --kiali-image-version dev \
  --auth-strategy login \
  --credentials-username kiali \
  --credentials-passphrase kiali
```

Now wait for the operator to install Kiali.  This will install Kiali with individual roles and the operator's cluster role does not have the ability to create new clusterroles or clusterrolebinds.

First look at the configmap and see the deployment/accessible_namespaces list and see it has a list of namespaces (the list will be something like "default", "istio-system", "myproject", "bookinfo" (if you have bookinfo installed):

```
oc get configmap kiali -n istio-system -o yaml
```

should show something like:

```
   deployment:
      accessible_namespaces:
      - bookinfo
      - default
      - istio-system
      - myproject
```

For each of those accessible namespaces, there should be two roles and a role binding (note: NOT clusterroles or clusterrolebindings):

```
$ oc get role -l app=kiali -n bookinfo
NAME           AGE
kiali          4m02s
kiali-viewer   4m01s

$ oc get role -l app=kiali -n default
NAME           AGE
kiali          4m17s
kiali-viewer   4m16s

$ oc get role -l app=kiali -n istio-system
NAME           AGE
kiali          4m35s
kiali-viewer   4m34s

$ oc get role -l app=kiali -n myproject
NAME           AGE
kiali          4m20s
kiali-viewer   4m20s

$ oc get rolebinding -l app=kiali -n bookinfo
NAME    AGE
kiali   7m7s

$ oc get rolebinding -l app=kiali -n default
NAME    AGE
kiali   7m32s

$ oc get rolebinding -l app=kiali -n istio-system
NAME    AGE
kiali   7m58s

$ oc get rolebinding -l app=kiali -n myproject 
NAME    AGE
kiali   7m58s
```

There should not be roles or rolebindings in any other namespace:

```
$ oc get role -l app=kiali -n kube-public
No resources found.

$ oc get role -l app=kiali -n openshift-node
No resources found.

$ oc get rolebinding -l app=kiali -n kube-public
No resources found.

$ oc get rolebinding -l app=kiali -n openshift-node
No resources found.
```

There should be no clusterrole or clusterrolebindings for Kiali:

```
$ oc get clusterrole -l app=kiali -n istio-system
No resources found.

$ oc get clusterrolebinding -l app=kiali -n istio-system
No resources found.
```

Now go to the Kiali UI and make sure you can log in as user "kiali" with passphrase "kiali".

Look at the list of namespaces in the Overview - you should see one card for each accessible namespace. 

Now create a new namespace - call it "foo": `oc create ns foo`

And now refresh the Kiali UI - you should NOT see a new "foo" card show up in Overview - you should not be able to see the foo namespace in the graph either.

Delete the foo namespace: `oc delete ns foo`

Now uninstall Kiali:

```
$ oc delete kiali kiali -n kiali-operator
kiali.kiali.io "kiali" deleted
```

At this point, the operator is uninstalling Kiali and all its roles and role bindings. They should no longer exist:

```
$ oc get role -l app=kiali -n bookinfo
No resources found.

$ oc get role -l app=kiali -n default
No resources found.

$ oc get role -l app=kiali -n istio-system
No resources found.

$ oc get role -l app=kiali -n myproject
No resources found.

$ oc get rolebinding -l app=kiali -n bookinfo
No resources found.

$ oc get rolebinding -l app=kiali -n default
No resources found.

$ oc get rolebinding -l app=kiali -n istio-system
No resources found.

$ oc get rolebinding -l app=kiali -n myproject 
No resources found.
```

Next up will be instructions on how to test this to bring back the old functionality of allowing Kiali to see every namespace in the cluster, including new ones added while Kiali is still running.

**Comment by jmazzitelli** [comment]
Before continuing, this assumes you followed the instructions earlier (check out this PR, build Kiali and the operator, etc).

You should start this round of testing with no install of Kiali or Kiali operator currently deployed - to clean everything, run `make -C operator operator-delete` - this will purge all Kiali resources.

**Test That Shows Kiali Can Access All Namespaces Just Like Its Current Behavior**

The purpose of this test is to show Kiali can run in the same way as it can currently - this means Kiali is given a cluster role/cluster role binding so it can view any and all namespaces in the entire cluster.

Here is how you can install Kiali operator and Kiali to run in this backward-compat mode. The special option `--accessible-namespaces '**'` is what triggers this (alternatively, `-an '**'`). Note because this PR is not in master and we do not have a release for it, you need to tell the installer to pick up the "dev" image version that you built on your local machine.

```
./operator/deploy/deploy-kiali-operator.sh \
  --accessible-namespaces '**' \
  --operator-image-version dev \
  --kiali-image-version dev \
  --auth-strategy login \
  --credentials-username kiali \
  --credentials-passphrase kiali
```

Now wait for the operator to install Kiali.  This will install Kiali with a single cluster role/rolebinding giving it access to all namespaces. The operator's cluster role WILL have the ability to create new clusterroles or clusterrolebinds (because it needs to create that Kiali cluster role/role binding).

First look at the configmap and see the deployment/accessible_namespaces list and see it has a single value of `**`:

```
oc get configmap kiali -n istio-system -o yaml
```

should show this:

```
   deployment:
      accessible_namespaces:
      - '**'
```

There should be two cluster roles and a cluster role binding for Kiali:

```
$ oc get clusterrole -l app=kiali -n istio-system
NAME           AGE
kiali          62s
kiali-viewer   61s

$ oc get clusterrolebinding -l app=kiali -n istio-system
NAME    AGE
kiali   65s
```

There should not be roles or rolebindings in any namespace. For example:

```
$ oc get role -l app=kiali -n istio-system
No resources found.

$ oc get role -l app=kiali -n default
No resources found.

$ oc get rolebinding -l app=kiali -n istio-system 
No resources found.

$ oc get rolebinding -l app=kiali -n default
No resources found.
```

Now go to the Kiali UI and make sure you can log in as user "kiali" with passphrase "kiali".

Look at the list of namespaces in the Overview - you should see one card for each namespace in the cluster (minus the ones we hide via the exclusion list -- api/namespaces/exclude. 

Now create a new namespace - call it "foo": `oc create ns foo`

And now refresh the Kiali UI - you should see a new "foo" card show up in Overview. You should also be able to see the selection "foo" in the graph's namespace drop down menu.

Delete the foo namespace: `oc delete ns foo`

Now notice the "foo" card disappears in the Overview page and you will not see the "foo" option in the namespace drop down in the graph page.

Now uninstall Kiali:

```
$ oc delete kiali kiali -n kiali-operator
kiali.kiali.io "kiali" deleted
```

At this point, the operator is uninstalling Kiali and its cluster roles and cluster role binding. They should no longer exist:

```
$ oc get clusterrole -l app=kiali -n istio-system
No resources found.

$ oc get clusterrolebinding -l app=kiali -n istio-system
No resources found.
```

This shows that Kiali can work in the original mode that it has been working in since day 1 - that being it is given a cluster role/cluster role binding to see every namespace in the cluster.

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1044](https://paste.fedoraproject.org/paste/FHLbZdJdRxW71Ssp12Ix8w)
 :red_circle: PRT Failed, Please Contact QE

**Comment by jmazzitelli** [comment]
this is built on top of https://github.com/kiali/kiali/pull/1107 - don't merge this PR until that one is merged

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1048](https://paste.fedoraproject.org/paste/4Tvpt7F3eItNcg8I1GCiJg)
 :red_circle: PRT Failed, Please Contact QE

**Comment by jmazzitelli** [comment]
When in that restricted mode, you can also test removing and adding namespaces in the Kiali CR work as expected.

Edit the Kiali CR:

```
oc edit kiali kiali -n kiali-operator
```

and change the list of accessible_namespaces. For example, delete `myproject` from accessible_namespace list and save the CR. After a minute or so, look at the Kiali UI and notice it can't show the "myproject" namespace.

Edit the CR again, and add that namespace back in (see that regex expressions work by adding `myproj.*`). After a minute or so, see that the Kiali UI can see the myproject namespace again.

**Comment by jmazzitelli** [comment]
> At that time I added 'foo' and removed 'default'. After the operator ran the 'foo' ns was added but 'default' did not go away

this worked for me. Make sure you refresh and make sure "default" is really visible. I suspect the UI didn't refresh itself or the list.

**Comment by jmazzitelli** [comment]
> At that time I added 'foo' and removed 'default'.

do not edit the configmap...ever. Only edit the Kiali CR.

**Comment by gbaufake** [comment]
Hi @jmazzitelli 
I ran this PR through QE automation on a single tenant scenario and saw the following on kiali-operator
```
Deploy Operator
OPERATOR_IMAGE_NAME="quay.io/kiali-qe/operator" \
OPERATOR_IMAGE_VERSION="latestcore1010" \
OPERATOR_NAMESPACE="kiali-operator" \
OPERATOR_INSTALL_KIALI="true" \
ACCESSIBLE_NAMESPACES="" \
AUTH_STRATEGY="openshift" \
CREDENTIALS_USERNAME="admin" \
CREDENTIALS_PASSPHRASE="admin" \
KIALI_IMAGE_VERSION="latestcore1010" \
NAMESPACE="istio-system" \
deploy/deploy-kiali-operator.sh
Using 'oc' located here: /usr/bin/oc
envsubst is here: /usr/bin/envsubst
=== OPERATOR SETTINGS ===
OPERATOR_IMAGE_NAME=quay.io/kiali-qe/operator
OPERATOR_IMAGE_PULL_POLICY=Always
OPERATOR_IMAGE_VERSION=latestcore1010
OPERATOR_INSTALL_KIALI=true
OPERATOR_SKIP_WAIT=false
OPERATOR_VERSION_LABEL=latestcore1010
OPERATOR_NAMESPACE=kiali-operator
OPERATOR_ROLE_CLUSTERROLES=# The operator does not have permission to manage cluster roles
OPERATOR_ROLE_CLUSTERROLEBINDINGS=# The operator does not have permission to manage cluster role bindings
```


```
TASK [kiali-deploy : Find all namespaces (this is limited to what the operator has permission to see)] ***
[1;30mtask path: /opt/ansible/roles/kiali-deploy/tasks/main.yml:177[0m
[0;32mok: [localhost] => {"ansible_facts": {"all_namespaces": ["default", "istio-operator", "istio-system", "kiali-operator", "kube-public", "kube-system", "openshift", "openshift-apiserver", "openshift-apiserver-operator", "openshift-authentication", "openshift-authentication-operator", "openshift-cloud-credential-operator", "openshift-cluster-machine-approver", "openshift-cluster-node-tuning-operator", "openshift-cluster-samples-operator", "openshift-cluster-storage-operator", "openshift-cluster-version", "openshift-config", "openshift-config-managed", "openshift-console", "openshift-console-operator", "openshift-controller-manager", "openshift-controller-manager-operator", "openshift-dns", "openshift-dns-operator", "openshift-etcd", "openshift-image-registry", "openshift-infra", "openshift-ingress", "openshift-ingress-operator", "openshift-kube-apiserver", "openshift-kube-apiserver-operator", "openshift-kube-controller-manager", "openshift-kube-controller-manager-operator", "openshift-kube-scheduler", "openshift-kube-scheduler-operator", "openshift-machine-api", "openshift-machine-config-operator", "openshift-marketplace", "openshift-monitoring", "openshift-multus", "openshift-network-operator", "openshift-node", "openshift-operator-lifecycle-manager", "openshift-operators", "openshift-sdn", "openshift-service-ca", "openshift-service-ca-operator", "openshift-service-catalog-apiserver-operator", "openshift-service-catalog-controller-manager-operator"]}, "changed": false}[0m

TASK [kiali-deploy : Determine all accessible namespaces, expanding regex expressions to matched namespaces] ***
[1;30mtask path: /opt/ansible/roles/kiali-deploy/tasks/main.yml:183[0m

TASK [kiali-deploy : fail] *****************************************************
[1;30mtask path: /opt/ansible/roles/kiali-deploy/tasks/main.yml:191[0m
[0;31mfatal: [localhost]: FAILED! => {"changed": false, "msg": "Kiali has not been granted access to any namespaces. Check the deployment.accessible_namespaces setting."}[0m
```

I guessed if I have an empty ``ACCESSIBLE_NAMESPACES`` it will fail the kiali installation, but I needed to look into kiali-operator ansible container to figure it out.


Is that expected from this PR behavior or is it something specific for hack script?

**Comment by gbaufake** [comment]
@jmazzitelli 
I wonder if it needs to be included on defaults of ansible role the control plane namespace (istio-system) or it will be passed through the cr.

**Comment by gbaufake** [comment]
@jmazzitelli 
After including `ACCESSIBLE_NAMESPACES="istio-system"`. 

I also see the default as part of namespace list. Is that expected?


Captura de Tela 2019-06-05 às 14 09 23


Captura de Tela 2019-06-05 às 14 09 34

Parameters used:

```
OPERATOR_IMAGE_NAME="quay.io/kiali-qe/operator" \
OPERATOR_IMAGE_VERSION="latestcore1010" \
OPERATOR_NAMESPACE="kiali-operator" \
OPERATOR_INSTALL_KIALI="true" \
ACCESSIBLE_NAMESPACES="istio-system" \
AUTH_STRATEGY="openshift" \
CREDENTIALS_USERNAME="admin" \
CREDENTIALS_PASSPHRASE="admin" \
KIALI_IMAGE_VERSION="latestcore1010" \
NAMESPACE="istio-system" \
deploy/deploy-kiali-operator.sh
Using 'oc' located here: /usr/bin/oc
envsubst is here: /usr/bin/envsubst
=== OPERATOR SETTINGS ===
OPERATOR_IMAGE_NAME=quay.io/kiali-qe/operator
OPERATOR_IMAGE_PULL_POLICY=Always
OPERATOR_IMAGE_VERSION=latestcore1010
OPERATOR_INSTALL_KIALI=true
OPERATOR_SKIP_WAIT=false
OPERATOR_VERSION_LABEL=latestcore1010
OPERATOR_NAMESPACE=kiali-operator
OPERATOR_ROLE_CLUSTERROLES=# The operator does not have permission to manage cluster roles
OPERATOR_ROLE_CLUSTERROLEBINDINGS=# The operator does not have permission to manage cluster role bindings
=== OPERATOR SETTINGS ===
```

```
The Kiali operator is installed!
Kiali will now be installed.
Using auth strategy [openshift] - a secret is not needed so none will be created.
=== KIALI SETTINGS ===
ACCESSIBLE_NAMESPACES=istio-system
AUTH_STRATEGY=openshift
CREDENTIALS_CREATE_SECRET=false
GRAFANA_URL=
KIALI_IMAGE_NAME=quay.io/kiali-qe/kiali
KIALI_IMAGE_PULL_POLICY=Always
KIALI_IMAGE_VERSION=latestcore1010
ISTIO_NAMESPACE=
JAEGER_URL=
NAMESPACE=istio-system
SECRET_NAME=kiali
UNINSTALL_EXISTING_KIALI=false
_SECRET_EXISTS=
=== KIALI SETTINGS ===
Deploying Kiali CR to namespace [kiali-operator]
kiali.kiali.io "kiali" created
Done.

```

**Comment by jmazzitelli** [comment]
> I also see the default as part of namespace list. Is that expected?

this is because your tests were using auth_strategy of "openshift" not "login" and you were logging in as some openshift user, and thus circumventing the roles/role bindings the operator created (which are assigned to the service account, not openshift user accounts).

We need to discuss this to find out how this is going to work when using strategy of "openshift"

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1075](https://paste.fedoraproject.org/paste/IBqHbjdTav2MsjPD~nY2~w)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1076](https://paste.fedoraproject.org/paste/oRwljn-hhT74gn-tdp~3RA)
 :red_circle: PRT Failed, Please Contact QE

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1077](https://paste.fedoraproject.org/paste/kQwYaU2-V7sVoWpPdaYtAA)
 :red_circle: PRT Failed, Please Contact QE

**Comment by jmazzitelli** [comment]
I tested this on kubernetes (minikube 1.0) and it works.

Due to the changes to the server code itself in this PR, I also tested installing without the operator but instead used the upstream Istio helm charts. The server will default to accessible_namespaces=** and so assume it has cluster role access to namespace list (which is does have when installed via upstream helm).

This means that my quick smoke tests show that whether using the operator or the upstream helm charts, this stuff works on Kubernetes.

**Comment by lucasponce** [comment]
Thanks @jmazzitelli !
This morning I asked @hhovsepy @skondkar to make a regression test in minikube.

But, I'm fine if we merge (if this is blocking other areas), as this is also in the QE radar I think we are good.

**Pull request merged**
