### PR TITLE
Merge kiali

### PR DESCRIPTION
**Pull request by aljesusg**
Issue https://github.com/kiali/kiali/issues/4825

- [X] Merge CI
- [X] Make changes Makefile
- [x] Merge Readme like templates, code of conduct, style...
- [X] Remove LICENSE from frontend
- [x] Check hacks
- [x] Check linter in frontend folder

### CODE REVIEW

**Comment by jmazzitelli** [comment]
FYI: I will be testing these shortly:

* make test
* make build-ui
* make clean-all
* make -e CLUSTER_TYPE=minikube build build-ui cluster-push operator-create kiali-create (and see that Kiali UI is available in your cluster)
* make format
* openshift CI hack script (I don't have Kind on my machine that works, so I can't test that other CI hack script).
* run-kiali.sh

I'll do those tests and report back if I see any errors.

**Review by jmazzitelli — CHANGES_REQUESTED** [review]
Some more -- this cleans up the UI better. https://github.com/aljesusg/kiali/pull/13

**Comment by jmazzitelli** [comment]
I tested everything as before - things are working. The only thing I request is the change in https://github.com/aljesusg/kiali/pull/13 which fixes up the cleaning of the UI.

**Review by jmazzitelli — APPROVED** [review]
lgtm

**Review by lucasponce — APPROVED** [review]
The structure looks ok.
It's too large and I think it can be consolidated and fix any pending config in minor and follow-ups PRs.

Note, that the "kiali-ui" repo will continue being used for 1.48.x.

Thanks for the work.

**Pull request merged**
