### PR TITLE
[WIP] KIALI-1661 Provide endpoints to check Kiali authorization

### PR DESCRIPTION
**Pull request by jotak**
Uses k8s "SelfSubjectAccessReview"
+ additional readonly flag from config

JIRA: https://issues.jboss.org/browse/KIALI-1661

TODO:

- [ ] Decide on readonly flag
- [ ] Swagger doc
- [ ] Unit tests

### CODE REVIEW

**Comment by jotak** [comment]
I'm suggesting two different approaches to restrict Kiali capabilities in the frontend:

- Using the Kubernetes API to check what Kiali can actually do
- With a "readonly" config flag that would override (if true) the kube permissions

I'm not 100% sure about the latter, so discussion is welcomed. I think it can be helpful to restrict Kiali globally without having to fine-tune kube's permissions. On the other hand it adds more configure options so can eventually add confusion. What do you think?

@mwringe , @jmazzitelli you may want to have a look too

**Comment by pilhuhn** [comment]
I think the readonly-flag (also) needs to be enforced in the backend. Otherwise it is possible for a user to open the JS console and send requests that way even if the user would have the restrict flag set in the frontend.

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#157](https://paste.fedoraproject.org/paste/9bhzL2dTHFfC2nt8KUbhpA)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1550]](https://paste.fedoraproject.org/paste/eDegP19wWAZa~DtiAg6Jrw)
  * :heavy_check_mark: Istio-Upstream [#[407]](https://paste.fedoraproject.org/paste/pW7pxy4Rd5Pd-5P6UTyoNQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1654, 1655]](https://paste.fedoraproject.org/paste/zl8dmgvhMwO8bnJwmMvAkQ)
  * :heavy_check_mark: install-bookinfo [#[920]](https://paste.fedoraproject.org/paste/pDraHWMvUJk3II2GOKAVug)
  * :heavy_check_mark: Kiali-on-Openshift [#[927]](https://paste.fedoraproject.org/paste/lKZfmISzLtZz5wbTIkp7lw)
  * :heavy_check_mark: run-kiali-e2e-tests [#[348]](https://paste.fedoraproject.org/paste/~51k84fHXaX~b87WS15wiw)


KIALI_NAME=kialicorepr549-istio-system

**Comment by mwringe** [comment]
Why do we want a readonly option?

The RBAC of OpenShift/K8S should be the single source for determining if a user has these permissions or not. If you don't want to have Kiali have write permissions, they you shouldn't grant the Kiali service account write permissions.

In OpenShift we are also updating things to allow individual users to use their own tokens to access things. In this case a system wide readonly flag doesn't make a lot of sense (some users may have read, some may also have write).

We also shouldn't have a new endpoint to check things here. It should be returned as part of the request to get the information.

Eg when I go to the istio detail page I get a list of the detail objects (eg api/namespaces/istio-bookinfo/istio) this should include in there if I have read/write permissions or not. From there there UI can figure out if the user should be presented with an option to edit or just read the yaml.

**Comment by jotak** [comment]
> Why do we want a readonly option?
> 
> The RBAC of OpenShift/K8S should be the single source for determining if a user has these permissions or not. If you don't want to have Kiali have write permissions, they you shouldn't grant the Kiali service account write permissions.

I don't necessarily disagree (and that's why I opened the discussion), but a global readonly flag would just be an easy and helpful shortcut for people who don't want to spend too much time on finding out all kiali permissions. Think about it: they would have to analyze the whole kiali deployment yaml to search for "delete", "create", "update" verbs across potentially several different groups and apis ... it's quite easy to miss one. That's the argument to put in balance, now I'm not saying we have to do it.

> 
> In OpenShift we are also updating things to allow individual users to use their own tokens to access things. In this case a system wide readonly flag doesn't make a lot of sense (some users may have read, some may also have write).

I would say on the contrary, it's a good scenario where it makes sense. Ability to deactivate writes system-wide, for whatever reason, instead of reviewing all permissions on a user basis one by one.

> 
> We also shouldn't have a new endpoint to check things here. It should be returned as part of the request to get the information.
> 
> Eg when I go to the istio detail page I get a list of the detail objects (eg api/namespaces/istio-bookinfo/istio) this should include in there if I have read/write permissions or not. From there there UI can figure out if the user should be presented with an option to edit or just read the yaml.

Agree, it makes sense.

**Comment by mwringe** [comment]
> I don't necessarily disagree (and that's why I opened the discussion), but a global readonly flag would just be an easy and helpful shortcut for people who don't want to spend too much time on finding out all kiali permissions. Think about it: they would have to analyze the whole kiali deployment config to search for "delete", "create", "update" verbs across potentially several different groups and apis ... it's quite easy to miss one. That's the argument to put in balance, now I'm not saying we have to do it.

We should have roles to help define this (eg 'kiali-read' and 'kiali-write', or something like that). The admin would then be able to configure which roles they want to grant to users.

Users shouldn't have to know more than that. I wouldn't expect them to look through the yaml and need to understand that or figure out how that should work and make modifications themselves.

> I would say on the contrary, it's a good scenario where it makes sense. Ability to deactivate writes system-wide, for whatever reason, instead of reviewing all permissions on a user basis one by one.

I don't know if I really understand this use case properly. Can you please explain this a bit more as to why it is needed?

I see this as we now have two things that we need to keep in sync: the value in the configmap to enable/disable readonly mode, and the roles that we grant to users (either a read role or a write role). This is going to potentially introduce more frustration to users as thing could get out of sync (eg they grant a write role to the user but the readonly parameter is still set).

I would think just setting the role would make things a lot easier. I would expect users would be more concerned over the permissions it needs to grant the Kiali service account. Granting the service account the ability to do a write and disabling it with the readonly configuration wouldn't necessarily alleviate their concerns. It still has permissions to do the write, so something like a bug or if the pod got compromised would still present problems.

If its a performance issue, then maybe we want to make sure we can do things in a way that we only ever fetch if a user has read/write permission when its necessary. I suspect most people will be running with the write ability enabled, so we need to make sure it works well in that situation.

**Comment by jotak** [comment]
> > I would say on the contrary, it's a good scenario where it makes sense. Ability to deactivate writes system-wide, for whatever reason, instead of reviewing all permissions on a user basis one by one.
> 
> I don't know if I really understand this use case properly. Can you please explain this a bit more as to why it is needed?

I cannot foresee all potential usages. One example:
You notice that some Istio objects are modified unexpectedly through Kiali. You want to investigate. First step: turn off the modification switch (readonly flag). Second step: investigate who has more privilege than it should, and fix permissions. Third step: remove readonly flag.

The thing is we haven't focused a lot on security from the beginning for an obvious reason, all that we are doing til a near future is read-only actions. Introducing modification capabilities will undoubtedly bring more security concerns. A readonly flag is also a security switch.

> 
> I see this as we now have two things that we need to keep in sync: the value in the configmap to enable/disable readonly mode, and the roles that we grant to users (either a read role or a write role). This is going to potentially introduce more frustration to users as thing could get out of sync (eg they grant a write role to the user but the readonly parameter is still set).
> 

There's nothing to keep in sync, why would anyone set the readonly flag if he's not willing to put the whole in readonly? It's quite self-explanatory, I don't see the ambiguity. it's much like a general water valve that takes priority over all the taps in your house.

Again, I don't have myself a clear preference for a solution over the other. So as the interest of a read-only flag is not obvious (looks like it's not) - then no problem I'll remove it, question solved.

**Comment by jotak** [comment]
will reopen another one

**Pull request closed without merging**
