### PR TITLE
Add tooltip in envoy tabs

### PR DESCRIPTION
**Pull request by aljesusg**
Fix https://github.com/kiali/kiali/issues/5162

Screenshot from 2022-06-24 11-14-10
Screenshot from 2022-06-24 11-14-19
Screenshot from 2022-06-24 11-14-27
Screenshot from 2022-06-24 11-14-31

cc @lucasponce

### CODE REVIEW

**Comment by aljesusg** [comment]
> > What do you think?
> 
> The last picture looks good!
> 
> I can start reviewing it when you move it from the draft state.

I am going to move this to review but I am working in add more info

**Comment by lucasponce** [comment]
A couple of comments from an early review:
image

And:
image

**Comment by aljesusg** [comment]
> A couple of comments from an early review: image
> 
> And: image

Well divider is in the Stateful filters. Are we sure that we want to remove dividers? this is going to affect to all pages where this component is used (https://github.com/kiali/kiali/pull/5249/files#diff-c9e72b19200a9e95c5e80da85c6d89a1680124586c7af50815b7f26db9c96882R340)

**Comment by aljesusg** [comment]
Screenshot from 2022-06-28 12-25-02
Screenshot from 2022-06-28 12-24-55

**Comment by lucasponce** [comment]
> Well divider is in the Stateful filters. Are we sure that we want to remove dividers? this is going to affect to all pages where this component is used

No, don't touch that component. You can implement that tooltip with a floating div or a different technique, but it should show dividers.

It should be more clean row like this with a tooltip at the end of the row.
image

**Review by lucasponce — APPROVED** [review]
image
image

**Pull request merged**
