### PR TITLE
add metric to track processing time for each individual checker

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/4230

### CODE REVIEW

**Comment by jmazzitelli** [comment]
Screenshot from 2021-08-02 16-23-23

**Comment by jmazzitelli** [comment]
Screenshot from 2021-08-02 16-28-36

**Comment by jmazzitelli** [comment]
Here's how you can get the average checker duration time (for all checkers) during the last 15 minutes

`rate(kiali_checker_processing_duration_seconds_sum[15m])/rate(kiali_checker_processing_duration_seconds_count[15m])`

Results in something like:

```
{checker="checkers.AuthorizationPolicyChecker"} | 0.000001995499999999991
{checker="checkers.DestinationRulesChecker"} | 0.0000030944999999999883
{checker="checkers.GatewayChecker"} | 0.000001648999999999997
{checker="checkers.NoServiceChecker"} | 0.00008785599999999997
{checker="checkers.PeerAuthenticationChecker"} | 0.000002906499999999983
{checker="checkers.RequestAuthenticationChecker"} | 0.000001309500000000005
{checker="checkers.ServiceEntryChecker"} | 0.0000008304999999999982
{checker="checkers.SidecarChecker"} | 0.000003406000000000014
{checker="checkers.VirtualServiceChecker"} | 0.00000806750000000001


```

**Comment by jmazzitelli** [comment]
There is now also this - tracks how long it takes to validate an entire namespace (or a service within the namespace):

`rate(kiali_validation_processing_duration_seconds_sum[15m])/rate(kiali_validation_processing_duration_seconds_count[15m])`

**Comment by jmazzitelli** [comment]
I do not know the difference between GetValidations and GetIstioObjectValidations (I see a function comment for GetValidations - but nothing for GetIstioObjectValidations). The `kiali_validation_processing_duration_seconds` tracks the time within GetValidations - that seems to be an important one since it validates an entire namespace potentially (or at least a service in a namespace - but that goes through all the checkers).

**Comment by jmazzitelli** [comment]
There are two new metrics in this PR currently. One tracks the processing time for each individual checker, the second tracks the time it takes to prepare and run validation for a namespace (or a service in a namespace if a specific service was to be validated):

Here's two prom queries you can invoke to see the data:

* rate(kiali_checker_processing_duration_seconds_sum[5m])/rate(kiali_checker_processing_duration_seconds_count[5m])
* rate(kiali_validation_processing_duration_seconds_sum[5m])/rate(kiali_validation_processing_duration_seconds_count[5m])

**Comment by jmazzitelli** [comment]
> I do not know the difference between GetValidations and GetIstioObjectValidations

From @xeviknal : `One applies for the whole namespace, the other for one specific object. One is used in the istio object list  page, the other in the istio object details page`

**Comment by jmazzitelli** [comment]
added a third metric to track that other method that validates a single istio object. e.g.

`kiali_single_validation_processing_duration_seconds_count{name="foo", namespace="alpha", type="authorizationpolicies"}`

**Review by xeviknal — APPROVED** [review]
LGTM! Minimum changes, maximum impact. It'll definitely be useful for troubleshooting.

**Pull request merged**
