### PR TITLE
[hack] update CRC and provide a user network mode option

### PR DESCRIPTION
**Pull request by jmazzitelli**
The name of the ssh identify file changed in recent versions of CRC - this updates the name (this allows us to ssh into the VM - this feature is used when obtaining status of the cluster, for example).

This also adds the option to enable user network mode in case you need to tell the VM to use the host's own networking.

And of course this also updates to the latest version of CRC.

### CODE REVIEW

**Review by ferhoyos — COMMENTED** [review]
In default mode, CRC works fine with the updated version.

When I enable the user network mode option I receive a permission denied issue:
```
INFO Starting CRC VM for openshift 4.17.7...      
failed to expose port :443 -> 192.168.127.2:443: listen tcp :443: bind: permission denied
HACK: ERROR: failed to start the VM.
```
Maybe any command has to be run with sudo?

**Comment by jmazzitelli** [comment]
@ferhoyos I have not seen that. What was the command you ran (all the command line options)?

**Comment by jmazzitelli** [comment]
I run the script with the `start` command along with the `-p` option (to tell it my pull secret) and with the new option set to true... (`-eunm true`)... Almost at the start, I get asked to enter my password to get sudo (this is done by `crc` itself):

```
INFO Using root access: Setting CAP_NET_BIND_SERVICE capability for /home/jmazzite/bin/crc executable 
[sudo] password for jmazzite:
```

After I enter that, CRC continues to start up, and I eventually see this (which is where you got the error, but I kept going):

```
INFO Starting CRC VM for openshift 4.17.7...      
INFO CRC instance is running with IP 127.0.0.1    
INFO CRC VM is running                            
```

So I wonder if you don't have sudo set up? Were you not asked for your password to get sudo access?

**Comment by ferhoyos** [comment]
I just run `./crc-openshift.sh start --enable-user-network-mode true`. The command without the enable mode works fine for me.

At the start, I get asked to enter my password to get sudo like you, so not sure what it is happening here...

**Comment by jmazzitelli** [comment]
@ferhoyos try to do a full cleanup first. It is possible you have some older stuff that might be causing problems.

`hack/crc-openshift.sh cleanup`

Then try again.

**Review by ferhoyos — APPROVED** [review]
I have cleaned up everything and now it works fine. I have checked that CRC runs on localhost:

```
Domain Name: crc.testing
Console:     https://console-openshift-console.apps-crc.testing
API URL:     https://api.crc.testing:6443
IP address:  127.0.0.1
Image Repo:  default-route-openshift-image-registry.apps-crc.testing (image-registry.openshift-image-registry.svc:5000)
OAuth Host:  oauth-openshift.apps-crc.testing
```

**Pull request merged**
