### PR TITLE
Add initial Quarkus dashboard

### PR DESCRIPTION
**Pull request by pilhuhn**
Provide an initial dashboard for Quarkus

### CODE REVIEW

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#663](https://paste.fedoraproject.org/paste/GD6QFrlCO3w2D728F8rw5g)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1396]](https://paste.fedoraproject.org/paste/ElFF5qQcg7ZgWh4VH3iW1w)

**Comment by jmazzitelli** [comment]
Everything is in the all.yaml now - https://github.com/kiali/kiali/blob/master/deploy/dashboards/all.yaml

There are no more individual dashboard yamls. So you'll want to put this in the all.yaml.

This has the added benefit of not having to update the install scripts everytime we add a new one (I see this PR didn't modify the two getLatestKiali[Kubernetes] scripts) - if you put this in all.yaml, you don't have to worry about that.

**Comment by pilhuhn** [comment]
On 7 Mar 2019, at 21:14, John Mazzitelli wrote:

> jmazzitelli requested changes on this pull request.
>
> Move to all.yaml file. @jotak can explain more about the reasons why 
> he moved to all.yaml

I know about all.yaml and think this is the wrong approach.
Having dashboard per file allows for users to browse them
easily look at them and learn from them.
All.yaml is just a faceless blob

This is why @jotak asked you in a comment in the *->all.yaml
pr if there is a way to create all.yaml on release and then upload
to GH release pages.

**Comment by jmazzitelli** [comment]
Then we need to be consistent and pick one way to do it, because if we merge this PR then we'll have "all.yaml" and a "quarkus.yaml" and the two install scripts for [k8s](https://github.com/kiali/kiali/blob/master/deploy/kubernetes/deploy-kiali-to-kubernetes.sh) and [os](https://github.com/kiali/kiali/blob/master/deploy/openshift/deploy-kiali-to-openshift.sh) won't install quarkus.yaml

If we want individual files and just mash them together at install time, then the install script will need to figure out how to know what all the individual files are up in the github repo's dashboard directory (I don't know how to do what off the top of my head). Or, we go back and list them all individually in the install scripts.

**Comment by jotak** [comment]
@pilhuhn is your intention to have it merged just to have it available / hosted on our repo, or do we need to first implement the index file or the generation script solution so that it's installed with Kiali?

**Comment by pilhuhn** [comment]
@jotak Well, it does not expose (most of ) the usual base metrics . But yes it could include the gc ones.

```
$ curl  -HAccept:application/json localhost:9080/metrics
"base" :
{
  "gc.young generation scavenger.time" : 0,
  "gc.complete scavenger.count" : 1,
  "gc.young generation scavenger.count" : 0,
  "gc.complete scavenger.time" : 7
}
,"vendor" :
{
  "thread.count" : 5,
  "memory.heap.usage" : 11221400,
  "memory.nonHeap.usage" : 11043536
}

```

**Comment by pilhuhn** [comment]
@jmazzitelli I am talking about kiali-bot adding all the individual files into all.yaml and then putting it  on https://github.com/kiali/kiali/releases via e.g. https://gist.github.com/stefanbuck/ce788fee19ab6eb0b4447a85fc99f447

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#668](https://paste.fedoraproject.org/paste/HO4FmFBDrpXDQMAEsS-9Ow)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1402]](https://paste.fedoraproject.org/paste/6Vl0ZEwGS-u74jCOnXqPcQ)

**Comment by jmazzitelli** [comment]
let's wait for PR #905 to get merged, then we can adjust this PR to add quarkus.yaml to the dashboards.txt index file. This PR has the individual quarkus.yaml which will work as-is with that PR 905 - so that doesn't have to change.

**Comment by jmazzitelli** [comment]
PR #905 is ready to be merged - let's get that in and then we can tweak this PR (add this quarkus.yaml to the dashboards.txt index file) and then merge it.

**Comment by jmazzitelli** [comment]
> Add more commits by pushing to the `[quarkus-dashboard](/pilhuhn/kiali/tree/quarkus-dashboard)` branch on [pilhuhn/kiali](/pilhuhn/kiali).

I tried to do this, but it is failing - not letting me push. So I need @pilhuhn to do this directly to his PR branch.

It simply involves:

1) git rebase origin/master
2) edit dashboard.txt and insert "quarkus.yaml" on line #4

**Comment by pilhuhn** [comment]
Here you go @jmazzitelli

**Pull request merged**
