### PR TITLE
KIALI-1661 Provide permissions on istio objects

### PR DESCRIPTION
**Pull request by jotak**
Add permission information to the istio models.
This is Kiali permissions (SelfSubjectAccessReview), not user permissions.
Add some tests

JIRA: https://issues.jboss.org/browse/KIALI-1661

### CODE REVIEW

**Comment by jotak** [comment]
Example of json output in istio objects list :

```
"permissions":{"destinationrules":{"create":false,"delete":true,"update":false},
"gateways":{"create":false,"delete":true,"update":false},
"quotaspecbindings":{"create":false,"delete":false,"update":false},
"quotaspecs":{"create":false,"delete":false,"update":false},
"rules":{"create":false,"delete":false,"update":false},
"serviceentries":{"create":false,"delete":true,"update":false},
"virtualservices":{"create":false,"delete":true,"update":false}}}
```

For istio details object, we would have something like `"permissions":{"create":false,"delete":true,"update":false}` (without the key on object type)

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#171](https://paste.fedoraproject.org/paste/0dbYQDhcrCM6eP5T4eY3RQ)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1588]](https://paste.fedoraproject.org/paste/dftEa7BAoE6s4NHUX~f5hQ)
  * :heavy_check_mark: Istio-Upstream [#[441]](https://paste.fedoraproject.org/paste/0qI-8hiZ0Esx78lwi2LmoQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1740, 1741]](https://paste.fedoraproject.org/paste/lDqE0cJZj56wApCkGsv3iQ)
  * :heavy_check_mark: install-bookinfo [#[962]](https://paste.fedoraproject.org/paste/LOnyfFosJvHKP5ij-XmDtw)
  * :heavy_check_mark: Kiali-on-Openshift [#[976]](https://paste.fedoraproject.org/paste/Q6HG0YMLe3sFOr1tTPFE1Q)
  * :red_circle: run-kiali-e2e-tests [#[386]](https://paste.fedoraproject.org/paste/WIbbMnkqFbzSZIcceP3u0Q)


KIALI_NAME=kialicorepr554-istio-system

**Comment by lucasponce** [comment]
I wonder if we could assume that having permissions for writting in one type of istio object could work for others, and reduce the number of checks. At least in a first stage of this feature.
Having granularity per namespace sounds enough.
It's hard to see that at the moment we want to restrict to edit virtualservices and destinationrules for namespaceA but read only gateways.

Your approach is more complete, I agree, but I think that assumption could be valid.

**Comment by jotak** [comment]
Swagger doc screenshot:
swagger

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#186](https://paste.fedoraproject.org/paste/aueAXR3AMRNCcwvvlQ6f2Q)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1616]](https://paste.fedoraproject.org/paste/M2nNlHkm8FJIdBsOw3fzFA)
  * :heavy_check_mark: Istio-Upstream [#[465]](https://paste.fedoraproject.org/paste/ZPGKKUl3nSg0SWg5igGTog)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1792, 1793]](https://paste.fedoraproject.org/paste/xFuPhLzmAVK2ETAPedb2xA)
  * :heavy_check_mark: install-bookinfo [#[989]](https://paste.fedoraproject.org/paste/talT8AO9230~ZpsyfzAblg)
  * :heavy_check_mark: Kiali-on-Openshift [#[1001]](https://paste.fedoraproject.org/paste/CAoMskpR5n0DXq2KWRu3rw)
  * :red_circle: run-kiali-e2e-tests [#[413]](https://paste.fedoraproject.org/paste/SUhJUpRxebO-7Pj561Rgag)


KIALI_NAME=kialicorepr554-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#187](https://paste.fedoraproject.org/paste/mmzdyqeA-B~YmbTdG-s-9g)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1617]](https://paste.fedoraproject.org/paste/SLTFPyX6zWV--wCnlWJLsQ)
  * :heavy_check_mark: Istio-Upstream [#[466]](https://paste.fedoraproject.org/paste/WoJQvsSsG1CZM9C4cr3gNw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1794, 1795]](https://paste.fedoraproject.org/paste/yibgDF8K3kxk74a~7RnoyQ)
  * :heavy_check_mark: install-bookinfo [#[990]](https://paste.fedoraproject.org/paste/-b5~1~DsixzGkTGMEz1vrQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[1002]](https://paste.fedoraproject.org/paste/KeWKnEZL~4TJb~YH3dUdiA)
  * :red_circle: run-kiali-e2e-tests [#[414]](https://paste.fedoraproject.org/paste/n20DhpAt3BAnFK23bV5WCw)


KIALI_NAME=kialicorepr554-istio-system

**Comment by lucasponce** [comment]
@jotak This seems ok to me.
One last comment to @mattmahoneyrh, please could you review if the e2e tests are failing due some needed change on this PR or the problem is different ?

**Comment by jotak** [comment]
@lucasponce I'm not sure (not familiar with e2e tests yet) but it seems there was some timeout issues here (seeing a bunch of `urllib.error.HTTPError: HTTP Error 504: Gateway Time-out` in https://paste.fedoraproject.org/paste/n20DhpAt3BAnFK23bV5WCw )

**Comment by lucasponce** [comment]
Ok, merging to block this work.
I think @mattmahoneyrh has enough info to take a look and confirm is there are some WIP on e2e/pipeline.

**Pull request merged**
