### PR TITLE
Not found messages in body page for workloads and Apps

### PR DESCRIPTION
**Pull request by josunect**
Not found messages may have a better message in the body page.
Done for apps and workloads. 

Screenshot from 2022-06-16 13-56-33

Fixes https://github.com/kiali/kiali/issues/5206

### CODE REVIEW

**Comment by hhovsepy** [comment]
Hi @josunect, a suggestion, can the Service details page also be changed to show this message? Because current empty props in confusing.

**Comment by hhovsepy** [comment]
Thank you for the fixes @josunect 
Screenshot from 2022-06-16 17-17-24

**Comment by lucasponce** [comment]
I wonder if we could put something similar in the IstioConfig details:
image

Then all the details will look similar, I forgot to mention in the original issue but after testing it locally I think it makes sense.

**Comment by josunect** [comment]
> I wonder if we could put something similar in the IstioConfig details: image
> 
> Then all the details will look similar, I forgot to mention in the original issue but after testing it locally I think it makes sense.

Thanks, @lucasponce ! Changes added.

**Comment by hhovsepy** [comment]
Verified with config details.

**Review by hhovsepy — APPROVED** [review]

**Pull request merged**
