### PR TITLE
[hack] be able to enable OLM in minikube

### PR DESCRIPTION
**Pull request by jmazzitelli**
We should be able to do this and get the operator to install via OLM subscription:
```
minikube addons enable olm --images "UpstreamCommunityOperators=operator-framework/upstream-community-operators:latest"
```

This operator PR is also needed: https://github.com/kiali/kiali-operator/pull/335

### CODE REVIEW

**Comment by jmazzitelli** [comment]
This "technically" works in that it will enable the olm addon. But I'm seeing the olm addon crash when it starts. It might be due to not enough memory I give to the minikube cluster, but I am not sure. Could just be an OLM bug.

It should be that the pods in the "olm" namespace can get to the "Running" phase, at which time you should be able to do this to install the Kiali Operator published on [OperatorHub.io](https://operatorhub.io/operator/kiali):

```
$ kubectl create -f https://operatorhub.io/install/kiali.yaml
$ kubectl get csv -n operators my-kiali
```

**Comment by jmazzitelli** [comment]
Use minikube 1.20 and you get further. Still wasn't able to see the CSV get created, but I was able to get stable Running pods for OLM

**Comment by jmazzitelli** [comment]
Well, the olm addon is still broken, even the latest. But if I install the latest OLM release (not the minikube addon), I am getting further along - but not until [yet another bug needed to be fixed locally on my box.](https://github.com/operator-framework/operator-lifecycle-manager/issues/2210) LOL.

But at least I see the operator pod running now.

**Comment by jmazzitelli** [comment]
I have this working now.

```
./hack/k8s-minikube.sh start --olm-enabled true
```

That starts minikube with the latest OLM release installed. Now you can install any operator from OperatorHub.io that you want, e.g. Kiali:

```
kubectl create -f https://operatorhub.io/install/stable/kiali.yaml
```

You can see the operator is installed:
```
$ kubectl get pods -n operators 
NAME                              READY   STATUS    RESTARTS   AGE
kiali-operator-86d49c56b8-c4dwr   1/1     Running   0          15m
```

**Comment by jmazzitelli** [comment]
along with https://github.com/kiali/kiali-operator/pull/335 this passes molecule tests when using olm

**Review by jshaughn — APPROVED** [review]
LOK

**Pull request merged**
