### PR TITLE
Single loading of multiple istiod registry services and configs

### PR DESCRIPTION
**Pull request by hhovsepy**
Fix for https://github.com/kiali/kiali/issues/4711

When there are multiple istiod pods, Registry Services and Configs were loading multiple times, so causing duplicates and odd errors in validations.
Now Registry Configs and Services are loaded only for the first istiod pod.

For QE:
Increase istiod pods count.
List istio configs for bookinfo.
Before: all configs were having warnings and references to themselves.
Now: no additional warnings and duplicate references in configs.

### CODE REVIEW

**Review by Xunzhuo — COMMENTED** [review]
Generally LGTM! But I got one question, besides parsing services and configs, should we just parse one time when parsing registry endpoints and proxy status?

**Comment by hhovsepy** [comment]
> Generally LGTM! But I got one question, besides parsing services and configs, should we just parse one time when parsing registry endpoints and proxy status?

For proxy status, the state is not shared between pods.

**Comment by Xunzhuo** [comment]
> > Generally LGTM! But I got one question, besides parsing services and configs, should we just parse one time when parsing registry endpoints and proxy status?
> 
> For proxy status, the state is not shared between pods.

Thanks for your quick response @hhovsepy ! But what about the endpoints?

**Comment by hhovsepy** [comment]
Added single load for Registry Endpoints. Thanks for review @Xunzhuo

**Review by lucasponce — APPROVED** [review]
LGTM

Tested on minikube + Istio 1.13:
- Scale "istiod" deployment (i.e. 3 pods).
- Create a simple configuration under the "reviews" service in the "bookinfo" demo.
- Reproduce the error:
image
- Prepare a Kiali with this PR and validate that error is gone:
image

**Review by Xunzhuo — APPROVED** [review]
looks good

**Review by skondkar — APPROVED** [review]
LGTM
The warnings are not visible after scaling istiod deployments.

Screenshot from 2022-03-04 19-02-01

**Pull request merged**
