### PR TITLE
KIALI-3036 Update to use UBI7 base image

### PR DESCRIPTION
**Pull request by mwringe**
**Describe the change**

Move to UBI7 Base image.

On the 0.20 branch since we want to have this change pushed out for users on Istio 1.2.x

** Issue reference **

https://issues.jboss.org/browse/KIALI-3036

### CODE REVIEW

**Comment by lucasponce** [comment]
Don't we want similar UBI7 changes in v1.0 and master ?

**Comment by mwringe** [comment]
@lucasponce Its already in master (https://github.com/kiali/kiali/blob/master/deploy/docker/Dockerfile#L1) and v1.0 (https://github.com/kiali/kiali/blob/v1.0/deploy/docker/Dockerfile#L1)

**Comment by lucasponce** [comment]
Ok, I was asking because according to 

https://quay.io/repository/kiali/kiali/manifest/sha256:1d7d5241d633328ab82ea6c64d01b65ec0f66cc7a1d7cedc8b8ffd42a3982a2c?tab=vulnerabilities&fixable=true

There are some vulnerabilities there, and I was wondering if with the UBI7 those could be updated.

Anyway, thanks @mwringe I guess if it's in master/v1.0 then it's a different topic.

**Comment by mwringe** [comment]
I am going to close this issue as we are going to try and get a newer Kiali version in to Istio 1.2

**Pull request closed without merging**
