### PR TITLE
KIALI-3011 give a custom CR to the script

### PR DESCRIPTION
**Pull request by jmazzitelli**
This allows you to pass `-kcr <file.yaml>` to the deploy script and that will be used when creating a Kiali CR rather that using the cmdline opts/env vars to build the CR.

This has some yaml parsing magic to try to extract the auth-strategy and the accessible-namespaces from the Kiali CR - the script needs to know these two things so it can do special things (like know if it has to create the secret or if it needs to grant the operator special cluster-admin-like permissions).

### CODE REVIEW

**Comment by jmazzitelli** [comment]
@lucasponce I'm not crazy about the way I had to use `grep` to extract out auth_strategy and accessible_namespaces values, but feel free to give this a try and see what you think. It should be working.

**Comment by lucasponce** [comment]
Testing in OpenShift 3.11:

deploy/deploy-kiali-operator.sh -kcr /home/lponce/Tests/test-kiali-cr.yaml 
https://gist.github.com/lucasponce/a2e32391759882e13c3718a3eb716b62

With this error back in the in the CR:

```
      Failed to patch object: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"customresourcedefinitions.apiextensions.k8s.io \"monitoringdashboards.monitoring.kiali.io\" is forbidden: User \"system:serviceaccount:kiali-operator:kiali-operator\" cannot patch customresourcedefinitions.apiextensions.k8s.io at the cluster scope: no RBAC policy matched","reason":"Forbidden","details":{"name":"monitoringdashboards.monitoring.kiali.io","group":"apiextensions.k8s.io","kind":"customresourcedefinitions"},"code":403}
```

Can you confirm I didn't miss anything in the command nor in the yaml ?

**Comment by jmazzitelli** [comment]
> With this error back in the in the CR:
> 
> ```
>       Failed to patch object: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"customresourcedefinitions.apiextensions.k8s.io \"monitoringdashboards.monitoring.kiali.io\" is forbidden: User \"system:serviceaccount:kiali-operator:kiali-operator\" cannot patch customresourcedefinitions.apiextensions.k8s.io at the cluster scope: no RBAC policy matched","reason":"Forbidden","details":{"name":"monitoringdashboards.monitoring.kiali.io","group":"apiextensions.k8s.io","kind":"customresourcedefinitions"},"code":403}
> ```

OK, so I assume the deploy script split this error out (NOT the operator itself). I think that is true because this error is about patching the dashboard CRD and the operator doesn't do anything with CRDs.

Now, the error here says failed to "patch" - so what I think happened is you already had the dashboard CRD and the script tried to create it again but your user running the script doesn't have permissions to "patch" CRDs??? So what I suspect happened is - you already had run this script before and you already had the dashboard CRD. Then you ran the script a second time, but because your k8s user did not have permission to patch existing CRDs, this failed.

Ultimately, what this means is I need to implement this: https://issues.jboss.org/browse/KIALI-2924
This will add a feature to the script that enables it to know if you already ran this script before and the operator is already installed. If it is, it will have to either abort and tell you that you have to uninstall everything first. We need an "uninstaller" - or maybe this script can do the uninstall for you. 

But for now, make sure you uninstall everything before running the script a second time. I think that was the problem (I am basing this solely on the error message you posted. I can't think of any other reason why that would happen).

**Comment by jmazzitelli** [comment]
FYI: I just ran this with the your test YAML (with one change - "jaeger:" is now called "tracing:"):

`./deploy/deploy-kiali-operator.sh -oiv dev -kcr LUCAS.yaml`

And things deployed fine:

```
$ kubectl get pods -l app=kiali -n istio-system
NAME                     READY   STATUS    RESTARTS   AGE
kiali-7b4679c6b6-j8g7h   1/1     Running   0          2m
```

```
$ kubectl get kiali kiali -n kiali-operator -o yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kiali.io/v1alpha1","kind":"Kiali","metadata":{"annotations":{},"name":"kiali","namespace":"kiali-operator"},"spec":{"auth":{"strategy":"login"},"deployment":{"accessible_namespaces":["**"],"image_version":"latest"},"external_services":{"grafana":{"url":"http://fake-grafana"},"tracing":{"service":"tracing","url":"http://fake-tracing"}}}}
  creationTimestamp: "2019-06-13T13:25:45Z"
  finalizers:
  - finalizer.kiali
  generation: 1
  name: kiali
  namespace: kiali-operator
  resourceVersion: "733813"
  selfLink: /apis/kiali.io/v1alpha1/namespaces/kiali-operator/kialis/kiali
  uid: c0201173-8dde-11e9-9ac7-54e1addf59b3
spec:
  auth:
    strategy: login
  deployment:
    accessible_namespaces:
    - '**'
    image_version: latest
  external_services:
    grafana:
      url: http://fake-grafana
    tracing:
      service: tracing
      url: http://fake-tracing
status:
  conditions:
  - ansibleResult:
      changed: 10
      completion: 2019-06-13T13:26:12.279454
      failures: 0
      ok: 53
      skipped: 33
    lastTransitionTime: "2019-06-13T13:25:45Z"
    message: Awaiting next reconciliation
    reason: Successful
    status: "True"
    type: Running
```

**Comment by lucasponce** [comment]
> But for now, make sure you uninstall everything before running the script a second time.

Yes. What is or should be the official way to uninstall things when something go wrong ?

Following kiali.io only points to 

https://www.kiali.io/documentation/getting-started/#_uninstall

Which I guess it's not enough, perhaps we need a purge process more consistent, I'm sure that at same way I failed in the yaml due the lack of scheme checking, other users will face this scenario as well.

**Comment by jmazzitelli** [comment]
> Yes. What is or should be the official way to uninstall things when something go wrong ?

That doc page should tell us all that is needed. If it doesn't, we need to fix this. @jshaughn was updating this page, we can ask him to update this, too.

I'm also in the process of testing an implementation for https://issues.jboss.org/browse/KIALI-2924 so the deploy script will uninstall any old operator it detects. So that should help. Stay tuned for a PR for that.

**Comment by lucasponce** [comment]
Probably this PR depends on https://github.com/kiali/kiali/pull/1140

**Pull request merged**
