### PR TITLE
Update trace data on hover 

### PR DESCRIPTION
**Pull request by josunect**
Fixes https://github.com/kiali/kiali/issues/6699

### CODE REVIEW

**Review by hhovsepy — COMMENTED** [review]
@josunect code lgtm, the feature is very useful. Just found one issue, when hover over for the first time without clicking, it tries to load trace, very obvious in incognito window when empty Trace Details is shown:
Screenshot from 2023-10-17 20-22-04

**Comment by josunect** [comment]
> @josunect code lgtm, the feature is very useful. Just found one issue, when hover over for the first time without clicking, it tries to load trace, very obvious in incognito window when empty Trace Details is shown: Screenshot from 2023-10-17 20-22-04

Thanks for catching this, @hhovsepy ! Updated now.

**Review by hhovsepy — APPROVED** [review]
Now all works fine.
The hover-over on a trace loaded the data in tooltip.
Trace tab does not load Trace Details by default.
Trace details are shown only when clicking on a trace.

**Comment by jshaughn** [comment]
@josunect Can you make sure of one more thing here, please verify that as a user moves the mouse across the chart, that we do not launch concurrent requests to the backend.  Probably it is fine, but just to make sure...

**Comment by josunect** [comment]
> @josunect Can you make sure of one more thing here, please verify that as a user moves the mouse across the chart, that we do not launch concurrent requests to the backend. Probably it is fine, but just to make sure...

With Tempo we don't have the all the trace data, if we want to load it on hover, we need to do a request to the backed - one per trace - in order to get all the trace information and be able to show that in the Tooltip. Not sure if concurrent, but , if there are many traces, it can perform many requests to the backend. 

The other alternative, the previous behavior, would be to keep the "Click to load" Message and just perform this request if the user request it...  But, it will look different.

**Pull request merged**
