### PR TITLE
KIALI-2880 KIALI-2879 Modify the FQDN parsing

### PR DESCRIPTION
**Pull request by burmanm**
** Describe the change **

Modify the FQDN parsing to parse ServiceEntries to fqdn.Service part only, as the SEs are global scoped and do not adhere to the cluster parsing otherwise

This simplifies our code in some parts and makes it hopefully more reliable when catching SEs. Also, change certain parsing to use prefix matching instead of only "*" to avoid false positives.

Same PR adds support for wildcard ServiceEntries, which would in certain cases fail otherwise.

** Issue reference **

KIALI-2879, KIALI-2880

** Backwards incompatible? **

Yes.

### CODE REVIEW

**Comment by hhovsepy** [comment]
"gateway.namespace" format is not supported anymore?
Screenshot from 2019-05-21 10-54-44

**Comment by burmanm** [comment]
It has never been.

**Comment by hhovsepy** [comment]
Then what about this in master?
Screenshot from 2019-05-21 16-55-43

**Comment by hhovsepy** [comment]
And what are the expected functionalities by this PR?

**Comment by burmanm** [comment]
``servicename.namespace`` working is previously was just an accident (a problem in parsing the FQDN), it didn't work everywhere. It's not a documented supported format by Istio and thus shouldn't be used. Some Istio components use format such as ``servicename/namespace``, thus it is unwise to use any non-official format.

The change is to catch few edge cases of ServiceEntries, since they support wildcards also - but must be different from Service wildcards. With old master, you can create a ServiceEntry that will match "*" for example for ServiceName - and that's wrong.

**Comment by burmanm** [comment]
I was going to create the additional tests with (upcoming) KIALI-2880 PR.

**Comment by burmanm** [comment]
So for now, if everything works correctly (FQDN, short names, ServiceEntry domain names etc) then that's the proper use. So ``google.com`` should be ``google.com`` and not service: google, namespace: com.

**Comment by burmanm** [comment]
Added KIALI-2880 also here and some tests to, to make sure we can support ServiceEntries with wildcards also. This PR hopefully now addresses all the edge cases with ServiceEntries (other than visibility in cluster).

**Pull request merged**
