### PR TITLE
Allow multiple metrics per chart (model update)

### PR DESCRIPTION
**Pull request by jotak**
Depends on https://github.com/kiali/k-charted/pull/87 (merged) and https://github.com/kiali/kiali-ui/pull/1730 (the frontend PR)

Fixes https://github.com/kiali/kiali/issues/1778

### CODE REVIEW

**Comment by jotak** [comment]
@aljesusg @hhovsepy this is the k-charted lib upgrade to integrate https://github.com/kiali/k-charted/pull/87 in kiali

**Comment by jotak** [comment]
Reviewers: there should be no visible impact in standard Kiali, so if you test it's essentially to check non-regression.

When building custom dashboards, it will allow to show several different metrics within a single chart. For instance, with this spec:

```yaml
spec:
  title: HTTP Federated
  items:
  - chart:
      name: "Request duration (1 min-rate)"
      # ...
      metrics:
        - metricName: istio_request_duration_milliseconds:p50:rate1m
          displayName: p50
        - metricName: istio_request_duration_milliseconds:p95:rate1m
          displayName: p95
        - metricName: istio_request_duration_milliseconds:p99:rate1m
          displayName: p99
```

Would now result in this kind of charts:

Capture d’écran de 2020-04-27 20-43-02 (copie)

**Comment by hhovsepy** [comment]
Also facing this error on other Metrics page:
Screenshot from 2020-04-28 12-12-19

**Comment by jotak** [comment]
@hhovsepy interesting, let me see ...

**Comment by jotak** [comment]
@hhovsepy some errors in backend logs?

**Comment by hhovsepy** [comment]
no error in backend logs

**Comment by jotak** [comment]
@hhovsepy I was able to reproduce when I had some errors while fetching prometheus from the backend. For instance, when scale prometheus to 0.
However, the error was silently ignored and we had this javascript issue you saw.

So I changed a little bit the error handling, now it's not ignored anymore and will appear on charts instead (like it already was for non-istio dashboards). Also, the javascript error should not appear anymore.

**Pull request merged**
