### PR TITLE
Ignore cache files from pytest e2e suite

### PR DESCRIPTION
**Pull request by xeviknal**
** Describe the change **
Running `pytest` produces some files for caching purposes. As they are not intended to be tracked, I propose to add them into gitignore.

** Backwards incompatible? **
yep.

### CODE REVIEW

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#77](https://paste.fedoraproject.org/paste/k-kPV5MK~A9ownShjFageg)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1355]](https://paste.fedoraproject.org/paste/V9lbA0RCr5EGwnYlmf5WQQ)
  * :heavy_check_mark: Istio-Upstream [#[234]](https://paste.fedoraproject.org/paste/fH5w0ZlhAqH9v-wFEcW56Q)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1248, 1247]](https://paste.fedoraproject.org/paste/-eqHCoBY1XocengAD4B98g)
  * :heavy_check_mark: install-bookinfo [#[711]](https://paste.fedoraproject.org/paste/72vjzazsUehxQfghWdso2w)
  * :heavy_check_mark: Kiali-on-Openshift [#[725]](https://paste.fedoraproject.org/paste/BJmGHhpi0ID4YH0xcK9HnA)
  * :red_circle: run-kiali-e2e-tests [#[172]](https://paste.fedoraproject.org/paste/-Fs3u43-uqn0PWDd8pYtZA)


KIALI_NAME=kialicorepr512-istio-system

**Comment by mattmahoneyrh** [comment]
The e2e failure is due to test case test_kiali_endpoint.py, which has since been removed from the repo. Please rebase and then run the Jenkins CI tests again.

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#78](https://paste.fedoraproject.org/paste/~y22pYg0N4LNc6W5gnYVhw)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1357]](https://paste.fedoraproject.org/paste/1RJsv-qS1it7ejjTiWQgIw)
  * :heavy_check_mark: Istio-Upstream [#[236]](https://paste.fedoraproject.org/paste/5vWx3jb1A7kBZIJNGIuvEg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1252, 1253]](https://paste.fedoraproject.org/paste/N9C5t9ANpVIvkGko4zDr9g)
  * :heavy_check_mark: install-bookinfo [#[713]](https://paste.fedoraproject.org/paste/Je-a8sLFfdDBcNianJGj2A)
  * :heavy_check_mark: Kiali-on-Openshift [#[727]](https://paste.fedoraproject.org/paste/waKE-a~6t2pkUtX5kIVlGg)
  * :heavy_check_mark: run-kiali-e2e-tests [#[174]](https://paste.fedoraproject.org/paste/Ok6uzvA6NbVPQQdmsNKT0Q)


KIALI_NAME=kialicorepr512-istio-system

**Comment by xeviknal** [comment]
@mattmahoneyrh rebased and test passing.

**Pull request merged**
