### PR TITLE
remove the requirement to have an internal Grafana running

### PR DESCRIPTION
**Pull request by aosterkamp**
check if GRAFANA_SERVICE or GRAFANA_SERVICE_NAMESPACE are not empty before using the internal Grafana API

** Describe the change **

There is absolutely no way to use an external Grafana instance with Kiali. Kiali always tries to discover the cluster-internal API-URL for Grafana.
This change removes this requirement. It checks if GRAFANA_SERVICE and GRAFANA_SERVICE_NAMESPACE are set to empty Strings, if so it uses the external Grafana URL.
If one of the environmental variables is nonempty (or uses the default values) it still tries to discover the internal API-URL.

** Issue reference **

* If this is a fix for a JIRA, please put JIRA-reference in the PR title like _`KIALI-7 New icons`_ (Jira-id, one space, description)
* If this is a fix for a GH-issue, please link it here

https://github.com/kiali/kiali/issues/865

** Backwards incompatible? **

no

** Documentation **

* Does your contribution contain user-visible changes like e.g. new or changed configuration settings?

Did that.

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by abonas** [comment]
@jotak

**Comment by jotak** [comment]
@aljesusg does it play well with your ongoing work on #968 ?

**Comment by aosterkamp** [comment]
@jotak of course and you are very welcome. I have to thank you for your amazing work.

**Comment by aosterkamp** [comment]
@jotak thanks! I planned on doing it last week and testing it with the operator, but my employer had other plans.

**Pull request merged**
