### PR TITLE
Discovery of Kiali instances in remote clusters

### PR DESCRIPTION
**Pull request by israel-hdez**
To find Kiali instances, Services are fetched filtering by the `app.kubernetes.io/name=kiali` label. It's assumed that Services with that label are an indication of the presence of Kiali.

The new generated JSON will be like the following one:

```json
[
  {
    "apiEndpoint": "https://192.168.128.4:6443",
    "isKialiHome": false,
    "kialiInstances": [
      {
        "serviceName": "kiali",
        "namespace": "istio-system",
        "operatorResource": "kiali-operator/kiali",
        "url": "",
        "version": "dev"
      }
    ],
    "name": "tzotz",
    "network": "netTwo",
    "secretName": "istio-remote-secret-tzotz"
  },
  {
    "apiEndpoint": "https://172.21.0.1:443",
    "isKialiHome": true,
    "kialiInstances": [
      {
        "serviceName": "kiali",
        "namespace": "istio-system",
        "operatorResource": "kiali-operator/kiali",
        "url": "https://192.168.129.3/kiali",
        "version": "dev"
      }
    ],
    "name": "kukulcan",
    "network": "netOne",
    "secretName": ""
  }
]
```

Fixes kiali/kiali#3718

### CODE REVIEW

**Comment by israel-hdez** [comment]
For now, the UI is not showing the result of the discovery. I'll deal with that as part of #3526.

**Comment by israel-hdez** [comment]
@jshaughn Looks like you are "the guy" who can review this :)
As you can see, the JSON has `kialiInstances` populated. Although this is discovering Kiali, I'm not sure how we could find the URL of the remote Kialis to provide a link in the UI. So, I'm only dealing with back-end for now and will deal with UI in #3526 once I can think a way to find and provide the URL.

**Review by jshaughn — APPROVED** [review]
Code looks fine, I like seeing the distinct log messages.  Tested in single cluster w/ no problems.

**Comment by israel-hdez** [comment]
@jshaughn Thanks. I'm merging.

**Pull request merged**
