### PR TITLE
get CA cert data from remote cluster if it cannot be obtained from the local kubeconfig

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/7926

### CODE REVIEW

**Comment by jmazzitelli** [comment]
To test:

1. Start east and west minikube clusters. We don't really need Istio installed but you do need istio-system namespace in the east cluster, so create that after the east cluster has started.
```
hack/k8s-minikube.sh -mp east start
hack/k8s-minikube.sh -mp west start
kubectl --context east create ns istio-system
```
2.  Install remote cluster resources on the west cluster (do this separately just so we can exercise the new code in a separate run - also shows how you can create the kiali remote cluster secret if you create the remote resources via the operator / Kiali CR)
```
helm repo update # just makes sure you have the latest kiali helm chart
helm install --create-namespace --kube-context=west -n istio-system --set deployment.remote_cluster_resources_only=true kiali-server kiali/kiali-server
```
3. We need to create a secret in the remote cluster in order to generate a token that can be used by Kiali. We can create a secret of type service-account-token so it can store a token for the kiali SA that was created in the previous step:
```sh
kubectl --context=west apply -f - <<EOM
apiVersion: v1
kind: Secret
metadata:
  name: "kiali"
  namespace: "istio-system"
  annotations:
    kubernetes.io/service-account.name: "kiali"
type: kubernetes.io/service-account-token
EOM
```
If you do not do this step, then an error will result in the next step below - the error message will tell you that you can create a secret using the command above. That's actually a good test if you want to skip this step and go on to the next step. When you see the error, come back to this step.

4. Create the kiali "remote cluster secret" in the kiali (east) cluster
```
./hack/istio/multicluster/kiali-prepare-remote-cluster.sh --kiali-cluster-context east --remote-cluster-context west --remote-cluster-namespace istio-system --remote-cluster-name west --kiali-resource-name kiali --process-remote-resources false
```
5. At this point, you should have a kiali remote cluster secret created. Look at the script output and it will tell you what its name is and where it is. You should see this:
```
INFO: A remote cluster secret named [kiali-remote-cluster-secret-west] has been created in the Kiali cluster namespace [istio-system]. It can be used by Kiali to access the remote cluster.
```
Look at that secret's yaml and confirm is has the data that is expected.
```
kubectl --context east get secret kiali-remote-cluster-secret-west -n istio-system -oyaml
```
It should look something like this:
```yaml
apiVersion: v1
data:
  west: YXBpVmVy [...chomp...] RDZz09Cg==
kind: Secret
metadata:
  annotations:
    kiali.io/cluster: west
...
  creationTimestamp: "2024-11-15T20:31:00Z"
  labels:
    kiali.io/multiCluster: "true"
  name: kiali-remote-cluster-secret-west
  namespace: istio-system
  resourceVersion: "3643"
  uid: 93c9efe6-c43e-445d-bd5a-248d20aa55c0
type: Opaque
```

**Comment by jmazzitelli** [comment]
The above test just shows the script working normally. In order to test generating the script using the remote cluster configmap, somehow you have to get a kubeconfig that uses `insecure-skip-tls-verify: true`. By default, setting up minikube does not do this. I will show how to do this test now.

1. Delete the kiali remote cluster secret we created in east cluster that was done in the last test - just to clean that up:
```
kubectl --context east delete secret kiali-remote-cluster-secret-west -n istio-system 
```

2. Edit your `~/.kube/config` and change the "west" cluster to use the insecure setting. Find the "west" cluster, remove the `certificate-authority:` line and replace it with the line `insecure-skip-tls-verify: true`. For example, I went from this:
```yaml
- cluster:
    certificate-authority: /home/jmazzite/.minikube/ca.crt
...
  name: west
```

to this:

```yaml
- cluster:
    insecure-skip-tls-verify: true
...
  name: west
```

3. Now run the script again - this tests the new code that this PR is introducing:
```
./hack/istio/multicluster/kiali-prepare-remote-cluster.sh --kiali-cluster-context east --remote-cluster-context west --remote-cluster-namespace istio-system --remote-cluster-name west --kiali-resource-name kiali --process-remote-resources false
```
This should now result in the kiali remote cluster secret being created - it gets the information from the remote cluster's ConfigMap. You will see this in the output telling you what happened:
```
INFO: Create the remote cluster secret in the Kiali cluster
INFO: remote_cluster_server_url=https://192.168.50.209:8443
INFO: WARNING: Unable to read the remote cluster CA bytes or file specified in the kubeconfig remote cluster named [west].
INFO: Obtaining the remote cluster CA cert data from the remote cluster itself
secret/kiali-remote-cluster-secret-west created
INFO: A remote cluster secret named [kiali-remote-cluster-secret-west] has been created in the Kiali cluster namespace [istio-system]. It can be used by Kiali to access the remote cluster.
```

4. Just like in the last test, confirm the secret looks OK:
```
kubectl --context east get secret kiali-remote-cluster-secret-west -n istio-system -oyaml
```

**Comment by jmazzitelli** [comment]
Finally, the above tests only show that the kiali remote cluster secret can be created. If you want to confirm it actually works, you would have to install and run Kiali such that it loads this remote secret (which it should be able to via auto-discovery since the secret has the necessary labels that Kiali looks for when detecting remote clusters) and accesses the remote cluster (west). I'll leave this test as an exercise for the reader to complete.

**Review by hhovsepy — APPROVED** [review]
Verified on `kind` cluster locally.
Screenshot From 2024-11-19 08-39-22
Screenshot From 2024-11-19 08-40-14

**Comment by nrfox** [comment]
The script works great but now speciying `--allow-skip-tls-verify true` causes this failure:
```
./kiali-prepare-remote-cluster.sh: line 256: remote_cluster_ca_bytes: unbound variable                                                                                                                                                                                                    
```

**Comment by jmazzitelli** [comment]
> The script works great but now speciying `--allow-skip-tls-verify true` causes this failure:
> 
> ```
> ./kiali-prepare-remote-cluster.sh: line 256: remote_cluster_ca_bytes: unbound variable                                                                                                                                                                                                    
> ```

Yeah, I found that already and it is fixed - git pull master again.

**Pull request merged**
