### PR TITLE
Run Kiali as non-root user

### PR DESCRIPTION
**Pull request by israel-hdez**
To follow container best practices, run Kiali as a regular user by default.

Fixes kiali/kiali#2745

### CODE REVIEW

**Comment by israel-hdez** [comment]
@nhinds Hopefully, this is what you need.

**Comment by jmazzitelli** [comment]
Are we planning on merging this to get it into the 1.18.1 release that will be built today?

**Comment by israel-hdez** [comment]
Yes, but I'm waiting for @mattmahoneyrh review. I'll merge if he doesn't have time as I think this is quite low risk.

**Comment by pbajjuri20** [comment]
Tested and Passed!

**Comment by israel-hdez** [comment]
Thanks! Merging.

**Pull request merged**
