### PR TITLE
Return 404, not 500, when service is not found in apidoc call

### PR DESCRIPTION
**Pull request by jshaughn**
Fixes https://github.com/kiali/kiali/issues/1713

### CODE REVIEW

**Comment by jotak** [comment]
How can we query for apidoc on a service that doesn't exist? isn't it something else that is flawed?

**Comment by jshaughn** [comment]
> How can we query for apidoc on a service that doesn't exist? isn't it something else that is flawed?

@jotak We can't, so with this change you get a 404 if the service does not exist or if it does exist but has no apidoc.  Is that not correct?

**Comment by jotak** [comment]
Well, I mean we should be *trying* to run that query in a first place if the service doesn't exist, that's where I think there's another problem.
If the service has no apidoc you won't get an error on `in.k8s.GetService(namespace, service)` call so it's probably handled at another place.

**Comment by jotak** [comment]
@jshaughn it's ok, I've read more carefully the issue and it seems the bug is not reproducible (or not easily?) so it was probably something more like a timing issue with a deleted service or something like that?

So I'm ok with this fix as it just forwards the k8s error to the frontend (hence returning 404 when service is not found) - but it would not solve the original bug if it comes to be reproducible, as a code 200 was actually expected in e2e test.

**Comment by jshaughn** [comment]
@jotak OK, thanks.  I can only guess that the original problem had to do with a typo of a manual api call in the browser.  Otherwise, I agree, it is something odd.

**Pull request merged**
