### PR TITLE
Remove aggressive filtering of bad telemetry from DeadNodeAppender

### LINKED ISSUE #976: Not seeing edges for kafka events
Hello, 

I have some microservices communicating between each other using kafka events but these connections are not shown in kiali graph. Is there a way the take these events into account in kiali ?

thank you very much

### PR DESCRIPTION
**Pull request by jshaughn**
Remove aggressive filtering of bad telemetry from DeadNodeAppender because it was also removing good telemetry for headless services.  Instead, filter unwanted telemetry immediately when building the TrafficMap.

This change is based on the discussion in https://github.com/kiali/kiali-ui/pull/1680

Fixes #976

@jotak Try out this change and see how it affects the Kafka situation.

### CODE REVIEW

**Comment by jotak** [comment]
Just tested the initial use case with headless services, it looks good!

Capture d’écran de 2020-03-12 17-46-09
_(messaging-kafka-brokers is the headless service that was previously unseen)_

I will run a couple of other tests...

**Comment by jotak** [comment]
@jshaughn perhaps this is too aggressive because when I remove all workloads I keep seeing dead (service) nodes:

Capture d’écran de 2020-03-12 17-55-52

**Comment by jotak** [comment]
I believe what we should continue to filter out here, are services that don't show incoming telemetry for the considered time period (meaning, with rate == 0), no?

**Comment by jshaughn** [comment]
> I believe what we should continue to filter out here, are services that don't show incoming telemetry for the considered time period (meaning, with rate == 0), no?

Good point. Now we can treat the surviving service nodes like other nodes and set them dead when they have no incoming or outgoing traffic.  I'll add that back.

**Comment by jshaughn** [comment]
@jotak Pushed another try.    My AWS cluster got reaped while I was testing but I think it may be good.

**Comment by jotak** [comment]
@jshaughn I continue to see the same, but turns out, also on master, so it's not actually a regression. I see this when I delete all objects in my namespace.

There's still a difference between how dead nodes are checked for workloads versus services: deleted workloads are removed by dead node, but deleted services are not.

So I believe there's two things that could be done:
- Either do same as for Workloads, check if the service still exists (with the price of querying k8s, but at least it's cached now by default)
- Or continue to show deleted Workloads (so, I guess the service-to-workload edge would appear, in grey). In any case, it should go away by itself when the selected time frame stops to include past traffic on these nodes.

Since it doesn't look like a regression I guess it's fine to merge this as is. I've retested the case with kafka out-of-mesh, and it still works well!

**Comment by jshaughn** [comment]
@jotak I'll merge this as is so we can get this in for today's 1.15 sprint build and get that headless handling in better shape.  I'll create a new issue to enhance DNA with your first suggestion, filter out service nodes without a backing service.  We definitely do not want to show the deleted workload nodes, that's why we added this appender in the first place, those nodes are unwanted.  Merci!

**Pull request merged**
