### PR TITLE
Fix header in overview page for large names

### LINKED ISSUE #6133: UI - Styling in the Overview page in the UI for cards with long namespace names pushes out kebab menu into adjacent card
In the Kiali UI
On the Overview page
If you have some namespaces that are relatively long (for example: `capi-kubeadm-control-plane-system` or something like that)
The kebab menu action button for that card
Is pushed out and flows into the adjacent card.

*Browser version* – Most recent chrome

*App area* – Overview page in the Kiali UI

*Version information* – I believe this is image: quay.io/kiali/kiali:v1.57.1

*Expected Behavior*
The kebab menu button will stay in the card that it is for

*Actual behavior* 
The kebab menu button is getting pushed out to the left if the namespaces are long

_Steps to Reproduce_
- Install Kiali
- Have some long namespaces that you're going to be looking at in Kiali
- View the overview page in the UI

**Screen capture:
https://github.com/kiali/kiali/assets/5703649/435c3bad-135f-4ae2-9cc8-a2d371b8db6f

I'm not familiar with the styling all that much for this project, but I did see that if I added this locally it seemed to address this issue (though it may not be the best solution, just something I've found):

```css

.pf-c-title.pf-m-lg {
    display: flex;
    overflow: hidden;
    margin-right: -200px;
}
```

### PR DESCRIPTION
**Pull request by josunect**
I have tested with Chrome and Firefox, but probably it would worth a try with other screen / browser versions, ...

image

image

Fixes #6133

### CODE REVIEW

**Comment by hhovsepy** [comment]
tested locally:
Screenshot from 2023-05-18 14-22-44
Screenshot from 2023-05-18 14-22-23

**Comment by josunect** [comment]
> tested locally: Screenshot from 2023-05-18 14-22-44 Screenshot from 2023-05-18 14-22-23

Thanks for the review, @hhovsepy !

**Review by leandroberetta — APPROVED** [review]
Looks good!

**Review by hhovsepy — APPROVED** [review]

**Comment by msdolbey** [comment]
This is great - Thank you so much!

**Pull request merged**
