### PR TITLE
OpenID Azure AKS+AAD support

### PR DESCRIPTION
**Pull request by israel-hdez**
Azure requires:
* Usage of access_token rather than the id_token. This is because Azure doesn't use a real "openid" configuration. Instead, it uses webhooks to validate bearer tokens and check privileges.
* A target resource_id when redirecting the user for authentication. However, rather than adding a specific setting for this, an additional_request_params configuration is added to make it more generic.

Authentication with azure is going to work **only on the authorization code flow**.

Operator PR: https://github.com/kiali/kiali-operator/pull/289

Related #3294

### CODE REVIEW

**Comment by israel-hdez** [comment]
@jmazzitelli I need a review here. Perhaps, can you dispatch your molecule tests?
I'll also work on #3874 (multi-cookies for large tokens), which is also required for auth to work properly on Azure.

**Comment by jmazzitelli** [comment]
> Perhaps, can you dispatch your molecule tests?

I can install this on our minikube/dex setup and run the molecule tests - is that good?

**Comment by israel-hdez** [comment]
> I can install this on our minikube/dex setup and run the molecule tests - is that good?

@jmazzitelli I'm good with that.

**Comment by jmazzitelli** [comment]
I have the operator PR and this PR pulled on my box. I build and pushed to my minikube+dex setup. I then ran `hack/run-molecule-tests.sh -at openid-test -ce $(which kubectl) -ct minikube -mp ci -udi true` and the openid-test passed successfully. I will now run the full test suite to check that all the tests pass.

**Comment by jmazzitelli** [comment]
All tests pass on minikube:
```
              accessible-namespaces-test... success [7m 31s]
     affinity-tolerations-resources-test... success [6m 23s]
                                api-test... success [4m 28s]
                      config-values-test... success [8m 5s]
                  default-namespace-test... success [3m 14s]
                        header-auth-test... success [3m 2s]
                            metrics-test... success [6m 26s]
                     null-cr-values-test... success [3m 47s]
                only-view-only-mode-test... success [5m 19s]
                             openid-test... success [3m 7s]
                     openshift-auth-test... skipped
                   os-console-links-test... skipped
                              roles-test... success [10m 39s]
                    rolling-restart-test... success [4m 47s]
                              token-test... success [2m 54s]
```

**Review by jmazzitelli — APPROVED** [review]

**Comment by israel-hdez** [comment]
@jmazzitelli Thanks for checking. I'll merge shortly.

**Comment by israel-hdez** [comment]
@jmazzitelli BTW, I'm wondering if a single node setup with "kind" has a small resources hit.
If so, we could probably setup a GitHub Action to run molecules for kuberentes on each PR, leaving OS molecules the only remaining checks to be done.

**Pull request merged**
