### PR TITLE
whenever the server detects the client is unauthorized, delete the token cookies

### PR DESCRIPTION
**Pull request by jmazzitelli**
delete the token cookies so the client never uses them again

fixes: https://github.com/kiali/kiali/issues/3643

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I believe I got it now. This is working in my tests. See the replication procedures in the issue https://github.com/kiali/kiali/issues/3643

**Review by jshaughn — APPROVED** [review]
This makes sense to me.  In the past we cleared the cookies only on logout, but we should also be clearing the [bad/stale] cookies whenever there is an auth problem with the token.

I see a couple of `RespondWithError(w, http.StatusUnauthorized, err.Error())` instances without additional messages, is that OK?

**Comment by jmazzitelli** [comment]
> I see a couple of `RespondWithError(w, http.StatusUnauthorized, err.Error())` instances without additional messages, is that OK?

I didn't touch that stuff - I assume its all OK.

**Comment by jmazzitelli** [comment]
The openshift-auth and token-auth molecule tests pass. I think this is good to go for merge.

**Pull request merged**
