### PR TITLE
Add client and server timeouts

### PR DESCRIPTION
**Pull request by jotak**
- Add http client timeout to istio version call
- Add server 30s timeouts

Fixes https://github.com/kiali/kiali/issues/3406

### CODE REVIEW

**Review by jshaughn — APPROVED** [review]
This all looks good to me.   The fixed server timeouts are hopefully OK, I guess we'll see if anyone runs into trouble.  Note that there is a separate effort going on to investigate applying timeouts and/or cancelation to Prom queries.  A server timeout in Kiali may need to coordinate with lower level handling.

**Comment by jotak** [comment]
Yes I've seen this ticket about prom timeouts, to be honest I though we *did already* have timeouts on those. Though I don't really know about context cancellation. Is there a specific reason why you started this investigation, a known impact?

**Comment by jshaughn** [comment]
>  Is there a specific reason why you started this investigation, a known impact?

There was anissue a while back where it was theorized that prom connections were used up.  In the end I don't think that was true, but in the recent context of timeout investigation and perf/scale in general, it seemed like good knowledge to have.  If we are timing out in the server after 30s, yet the prom calls live on, it seems like it could be an issue.

**Comment by jotak** [comment]
DNM: I'd like to wait next week before merging, so that it doesn't get released without being tested for some time.

**Pull request merged**
