### PR TITLE
Use downloaded Helm instead of the packed in the VM

### PR DESCRIPTION
**Pull request by leandroberetta**
Always use the Helm chart downloaded from Kiali scripts.

Helm charts PR: https://github.com/kiali/helm-charts/pull/193

### CODE REVIEW

**Comment by jmazzitelli** [comment]
This looks to be a dup of https://github.com/kiali/kiali/pull/5781

See my comments in that PR for something we need to think about.

**Review by jmazzitelli — COMMENTED** [review]
see my previous comment about the existing PR. Feel free to close that one and we can work in this one.

But my comment in the other PR still stands - I think we need to make sure "helm" isn't in PATH already - because if it is (in the CI environment) then this change will be a no-op because the make target will not download helm if there is already a helm in PATH (it presumes the user wants to use his own helm).

So we could change this such that we should remove helm from PATH if it exists, prior to building the helm chart. That will assure we are building with a helm version that we want and helm will be downloaded.

**Comment by jmazzitelli** [comment]
> So we could change this such that we should remove helm from PATH if it exists

 Or the alternative would be to change the helm chart Makefile so it always downloads helm if it is missing from the _output directory (i.e. ignore what is in PATH and always use what is in _output)

**Comment by leandroberetta** [comment]
> This looks to be a dup of #5781 - we can close that one and use this one if you want. But see my comments in that PR for something we need to think about.

Sorry @jmazzitelli I didn't realize of the other PR. As you say, we can continue on this one and also improve what you're indicating.

To me, the best option is to always use the downloaded one, and avoid future errors with versions incompatbilities. If you're ok, I will add this change.

**Comment by jmazzitelli** [comment]
> If you're ok, I will add this change.

sounds good

**Review by jmazzitelli — APPROVED** [review]
LGTM.

This should always do what we expect now that the helm Makefile will always download helm regardless of what is in PATH

**Pull request merged**
