### PR TITLE
Changes necessary to move to Ansible Operator SDK 1.x

### PR DESCRIPTION
**Pull request by jmazzitelli**
part of: https://github.com/kiali/kiali/issues/2983

### CODE REVIEW

**Comment by jmazzitelli** [comment]
4.7 is now based on upstream 1.3 SDK - so that is what we should target:

```
$ docker run --entrypoint /usr/local/bin/ansible-operator --rm -i -t registry.redhat.io/openshift4/ose-ansible-operator:v4.7 version

ansible-operator version: "v1.3.0-ocp", commit: "648f8a1ce22e7e838ecdd395d2589a6bcbbfb13b", kubernetes version: "v1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"
```

**Comment by jmazzitelli** [comment]
This is ready. We can merge it.

**Review by jshaughn — APPROVED** [review]
LOK.  Can we get rid of the local operator_sdk that we have under _output?

**Comment by jmazzitelli** [comment]
> Can we get rid of the local operator_sdk that we have under _output?

yes. currently, not needed.

**Pull request merged**
