### PR TITLE
KIALI-2783 up required istio/maistra versions

### PR DESCRIPTION
**Pull request by jshaughn**
update versions to ensure necessary telemetry

### CODE REVIEW

**Comment by mwringe** [comment]
@mattmahoneyrh Can you verify this works properly with Maistra?

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1005](https://paste.fedoraproject.org/paste/JUPAZ1F9bGcQULXr57YbJA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1817]](https://paste.fedoraproject.org/paste/BfZvybccT7xtCZsA0OiFgA)

**Comment by abonas** [comment]
is this updated on Kiali website along with this change?

**Comment by jshaughn** [comment]
> is this updated on Kiali website along with this change?

@abonas I'll prepare a kiali.io PR with the analogous change.

**Comment by rhqci** [comment]
PRT Failed, Please Contact QE

**Pull request merged**
