### PR TITLE
[KIALI-1559] _js.go is a reserved filenaming syntax in go1.11

### PR DESCRIPTION
**Pull request by burmanm**
Go 1.11 added experimental support for WebAssembly which also meant that _js.go and _wasm.go are actually reserved keywords for filenames. Thus, Kiali will no longer compile with go1.11 unless the config_to_js.go is renamed.

### CODE REVIEW

**Comment by abonas** [comment]
is there a link to Go docs that declare those changes? 
is there a Kiali JIRA referring to preparation for support of Go 1.11?

**Comment by burmanm** [comment]
https://golang.org/doc/go1.11#wasm

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#39](https://paste.fedoraproject.org/paste/kaWctKfBy4R0Zwey1nN0Bg)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1270]](https://paste.fedoraproject.org/paste/ZHrNL897YCdeQHxAhAZn7g)
  * :heavy_check_mark: Istio-Upstream [#[155]](https://paste.fedoraproject.org/paste/4MPRWy2HITzxakRCdAZriA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1054, 1055]](https://paste.fedoraproject.org/paste/lKK~AeIo4bqhSljSkA~i3w)
  * :heavy_check_mark: install-bookinfo [#[620]](https://paste.fedoraproject.org/paste/Cu97kDj0v5gz3SagxKr6gg)
  * :heavy_check_mark: Kiali-on-Openshift [#[614]](https://paste.fedoraproject.org/paste/J~v~VaRtjI3ITcSsekF9Rw)
  * :heavy_check_mark: run-kiali-e2e-tests [#[87]](https://paste.fedoraproject.org/paste/B8Q5lrRkcfU41kPUFS~ykA)


KIALI_NAME=kialicorepr498-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#43](https://paste.fedoraproject.org/paste/euE5zthkng1lN3cVLqQXYA)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1277]](https://paste.fedoraproject.org/paste/TBSR1du3e31cnL8AQ7NTvA)
  * :heavy_check_mark: Istio-Upstream [#[162]](https://paste.fedoraproject.org/paste/VSXGn7pNs9FDi-OD7xd8SQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1070, 1071]](https://paste.fedoraproject.org/paste/OwZl1-IL-NnJhH1qgIC2KA)
  * :heavy_check_mark: install-bookinfo [#[627]](https://paste.fedoraproject.org/paste/JRugIhivOqRwnj5Krdfa0A)
  * :heavy_check_mark: Kiali-on-Openshift [#[625]](https://paste.fedoraproject.org/paste/9hXMOALwpdJ8oBennaQBpw)
  * :heavy_check_mark: run-kiali-e2e-tests [#[94]](https://paste.fedoraproject.org/paste/3UbALG28i-tbPlgfRu8lgQ)


KIALI_NAME=kialicorepr498-istio-system

**Pull request merged**
