### PR TITLE
Update istio.io/client to 1.13.2 + bump istio/networking/v1alpha3 -> istio/networking/v1beta1

### PR DESCRIPTION
**Pull request by lucasponce**
It looks good, but I'm still reviewing any side effect on this bump

Related to
https://github.com/kiali/kiali/issues/4894

### CODE REVIEW

**Comment by lucasponce** [comment]
It seems the swagger ci has some issue when running on local vs in the pipeline:
image

But every time I update the "swagger.json" file, the ci fails.

**Comment by lucasponce** [comment]
@hhovsepy would you like to give this a try to this PR?

It doesn't completely solve the issue in https://github.com/kiali/kiali/issues/4894 but it will update the Istio client and the "v1alpha3" API to "v1beta1" for the networking API (except the EnvoyFilters).

In short, the kubernetes API machinery doesn't allow to manage of two different versions, and when using the old v1alpha3 the API (i.e. kubectl) would use the v1beta1:
image

I think this PR would help to update the codebase.

**Review by hhovsepy — DISMISSED** [review]
Regression tested. Run validation tests and integration tests.

**Comment by lucasponce** [comment]
Thanks, @hhovsepy, I'm going to move to draft and update the swagger to fix the CI.

**Review by hhovsepy — APPROVED** [review]
Verified.

**Comment by lucasponce** [comment]
Thanks!

**Pull request merged**
