### PR TITLE
Migrate to GoModules

### PR DESCRIPTION
**Pull request by israel-hdez**
Replacing Glide with GoModules

Fixes kiali/kiali#2909

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I see the makefile and README show you no longer have to run make targets to get dependencies to be installed. Does this "just work" now without any additional steps?

**Comment by israel-hdez** [comment]
@jmazzitelli Yes it should work. Building Kiali or running tests should automatically download dependencies.

**Comment by israel-hdez** [comment]
@hhovsepy I think this will need a regression testing for the back-end.

**Comment by jotak** [comment]
About the snyk error, I think we can safely ignore:

Capture d’écran de 2020-07-01 09-57-40

It basically complains that it doesn't find anymore some dependencies that it had registered manifests from, which were located in vendors. Once this PR is merged we can edit snyk project config to remove them, I guess.

**Comment by israel-hdez** [comment]
> About the snyk error, I think we can safely ignore:

I think so. It should catch up once this is merged into `master`.

**Comment by israel-hdez** [comment]
@mattmahoneyrh  I asked for regression testing for the back-end. Although, this is mostly a "dev" change, so you could approve and defer testing for later, if you want.

**Comment by mattmahoneyrh** [comment]
Kiali started fine, with no errors in the Message Console. However, there are errors in the pod log such as " http2: server: error reading preface from client"

See attached log for more details.
[kiali-74f4d55b8d-vmrvk-kiali.log](https://github.com/kiali/kiali/files/4859979/kiali-74f4d55b8d-vmrvk-kiali.log)

**Comment by israel-hdez** [comment]
Since @mattmahoneyrh reports no errors when trying Kiali, I'm merging...

I see the `http2` errors are present also in `master` branch.
They are also present in the log file provided by Hayk in issue #2905. I think this `http2` error is the consequence of hanging connections leading to Kiali becoming unusable as reported in #2905. So, those errors seems to be unrelated to this PR.

Thanks for the reviews!

**Pull request merged**
