### PR TITLE
Feature/go 1.17.7 update

### PR DESCRIPTION
**Pull request by sukrit007wawa**
**Describe the change**

This updates the GO version to 1.17.7 that includes security fixes

**Issue reference**

Reported to kiali-security@googlegroups.com

**Backwards incompatible?**

- Changes are backward compatible

**Documentation**

* Does your contribution contain user-visible changes like e.g. new or changed configuration settings?
It does not require README updates as it is a patch version change for golang.

### CODE REVIEW

**Review by lucasponce — COMMENTED** [review]
I don't see a problem bumping to these versions.
Any comment @jshaughn? 
I remember there was a discussion related Golang versions, but probably the z releases are safe?

**Comment by jshaughn** [comment]
@lucasponce We can bump this upstream but I'm not sure if the downstream build env can handle it.  Does anyone know if this go version is avail for the cpaas builds?  @aljesusg @leandroberetta @jmazzitelli ?

**Comment by lucasponce** [comment]
> I'm not sure if the downstream build env can handle it

Well, I think that upstream/downstream should have different settings, not sure if a bump like this should be conditioned from a downstream constraint.

Perhaps it's a good moment to introduce some kind of "build profiles" that can keep separated both?

**Comment by jshaughn** [comment]
I agree the upstream should not be affected by downstream constraints.  I'm in favor of the bump, I brought it up mainly to get clarity on whether there is an issue.

**Comment by jmazzitelli** [comment]
shouldn't be an issue - especially since no code changes are being done here, so it should be compatible even if something else wants to use another 1.17.x version.

**Review by lucasponce — APPROVED** [review]
I'm using 1.17.7 in my local env for some time:
image

And I've built multiple PRs, so, I haven't seen any problem.

P.S.: Clean well the old dependencies with the golang.

**Pull request merged**
