### PR TITLE
[v1.36] Fix missing Grafana Workload and Service links

### PR DESCRIPTION
**Pull request by leandroberetta**
Backport of #4236.

### CODE REVIEW

**Review by jmazzitelli — APPROVED** [review]
lgtm

**Comment by prachiyadav** [comment]
Can not see this fixed in 1.36.3

Screenshot from 2021-08-06 16-24-55

Screenshot from 2021-08-06 16-28-26

**Comment by prachiyadav** [comment]
http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-redhat-operator-bundle-image-validation-test/openshift-istio-kiali-operator-metadata-container-3.0-30/56f75059-a772-49d4-9dd5-e0edb0f6a44a/cvp-test-report.html

**Comment by prachiyadav** [comment]
Test case >> SWSQE-89

**Pull request merged**
