### PR TITLE
KIALI-3096 Fix runtimes metrics w/ maistra (v1.1.x)

### PR DESCRIPTION
**Pull request by jotak**
Need to check the UseKialiToken field to pass token to k-charted

JIRA: https://issues.jboss.org/browse/KIALI-3096

### CODE REVIEW

**Comment by lucasponce** [comment]
cc @hhovsepy as he has a TP12 environment with more easy to check oath scenarios.

**Comment by hhovsepy** [comment]
it seems kiali UI is broken on master

**Comment by jotak** [comment]
@hhovsepy I'm not sure when master will be fixed, but for the time being I would suggest to rebase from tag v1.2 (that's just a couple of commits away from master)

**Comment by jotak** [comment]
thanks @hhovsepy

**Pull request merged**
