### PR TITLE
KIALI-665 SSL Support

### PR DESCRIPTION
**Pull request by jotak**
- Get Openshift generates certificate
- Mount in  pod volume and configure to use them in kiali config
- Use them also for jaeger proxy
- Route: use reencrypting termination

### CODE REVIEW

**Comment by mwringe** [comment]
> So, this would set our default openshift deployment to use https. This is not something that was explicit in the JIRA (should it be default or not). Maybe I could clone the kiali.yml file to a kiali-secured.yml , and our default would still be unsecured?

There was some concern that using https might introduce some problems, so we should be able to configure it. I think having it enabled by default is probably the right action, we should default to the more secure options.

I am -1 to having multiple configuration files if we don't need it.

> I'm using reencrypting termination for the openshift route, however I do not explicitly provide the server certificates in that route (the ones created from the annotation service.alpha.openshift.io/serving-cert-secret-name) , so, I don't know if openshift is automagically doing the correlation but... it works.

With a re-encrypting route there are two sets of certificates. The one used internally by Kiali and the one exposed to external users of the route.

If you don't specify the one used by Kiali, I believe it will automagically grab the one that is created as part of the secret for that service.

If you don't specify the one that is exposed externally, it should use the default certificate of the router.

You should be able to easily check this. If you curl -v to the service ip address and not the route you should be able to see information about the certificates. Same if you do the same curl command with the route's ip address.

**Comment by jotak** [comment]
The certificates are the expected ones:
- For the route:
```
curl -vk https://kiali-istio-system.127.0.0.1.nip.io
[... TLS Handshake ...]
* Server certificate:
*  subject: CN=*.127.0.0.1.nip.io
*  start date: Jul 24 11:27:10 2018 GMT
*  expire date: Jul 23 11:27:11 2020 GMT
*  issuer: CN=openshift-signer@1530105370
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
```

- For the service:
```
curl -vk https://172.30.224.209:20001
[... TLS Handshake ...]
* Server certificate:
*  subject: CN=kiali.istio-system.svc
*  start date: Jul 24 11:29:35 2018 GMT
*  expire date: Jul 23 11:29:36 2020 GMT
*  issuer: CN=openshift-service-serving-signer@1530105370
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
```

So this part seems pretty ok.

Now, given I want to test out of the box Kiali without valid certificates, it doesn't work well with the jaeger proxying. I have different behaviours depending on the browser I use: In chrome it's ok as long as I explicitly ignore the certificate, but I have to do it twice: once for kiali, once for jaeger proxy url that I have to type manually in the address bar.

In Firefox it won't allow to display the iframe content because the certificate that we try to use for "kiali-istio-system.127.0.0.1.nip.io:32439" (the jaeger proxy url) is issued for names "kiali.istio-system.svc", "kiali.istio-system.svc.cluster.local", which doesn't match.

...so I'm trying to find a solution for that.

**Comment by mwringe** [comment]
> In Firefox it won't allow to display the iframe content because the certificate that we try to use for "kiali-istio-system.127.0.0.1.nip.io:32439" (the jaeger proxy url) is issued for names "kiali.istio-system.svc", "kiali.istio-system.svc.cluster.local", which doesn't match.

What is the url for the kiali console and what is the url for jaeger?

**Comment by jmazzitelli** [comment]
Due to changes to the two yaml files, we must also prepare PRs for the upstream Istio's helm chart and ansible installer as well as the openshift-istio (istiooc) ansible installer. @gbaufake has information on that.

**Comment by jotak** [comment]
@mwringe I think I've come up with something acceptable. Basically I made jaeger proxy configurable, and disable by default. Turning on proxy + SSL is a bit tricky but I guess it would work with valid certificates properly configured. I dropped a word about it in the readme

**Comment by gbaufake** [comment]
@jotak  @jmazzitelli 

Probably, I will need to update the ansible installer on istio (which install for openshift context) and on openshift-istio as well.

Since there is no changes on Kubernetes, Helm installer should be ok.

**Comment by gbaufake** [comment]
What is going to be the standard for Istio Upstream Installer?

I assume SSL enabled

**Comment by jotak** [comment]
@gbaufake I think so, yes. @mwringe you confirm?

BTW @mwringe @jmazzitelli this is ready to merge for me.

**Comment by mwringe** [comment]
@gbaufake I would assume we would want to makes SSL enabled by default when using OpenShift. This only affects the OpenShift installation and not the k8s one (since k8s can't give us the certificates like how OpenShift can)

**Comment by lucasponce** [comment]
Any status on this PR ?

**Comment by jotak** [comment]
waiting for merge. But honestly I would recommend to wait for the next release if we want to reduce the amount of thing to test & stabilize right now

**Comment by jotak** [comment]
[adding DNM label to not send it to release]

**Comment by jotak** [comment]
DNM: after rebase, Jaeger Proxying is not working anymore. Something wrong within TLS handshakes...

**Comment by mwringe** [comment]
Another other option is to use the same host and port as Kiali and serve the Jaeger console under a different path (eg https://kiali/jaeger)

With this everything just 'works', but the catch is that we have to be in control of the Jaeger installation since we need to set a prefix path as a configuration option.

**Comment by lucasponce** [comment]
> Another other option is to use the same host and port as Kiali and serve the Jaeger console under a different path (eg https://kiali/jaeger)

> With this everything just 'works', but the catch is that we have to be in control of the Jaeger installation since we need to set a prefix path as a configuration option.

I think this was tested before, but it has a technical problem when embedded the static content of jaeger UI.

@aljesusg can you confirm that this was tested when the proxy was developed ?

**Comment by aljesusg** [comment]
Yes @lucasponce , the problem about the route is that jaeger try to get static files like js, css from static route. 

We tried creating a new route like @mwringe proposed but for example in this case the jaeger try get the statics from https://kiali/jaeger/static/... and fails, this is why we add another port to redirect all to the jaeger url.

**Comment by mwringe** [comment]
> We tried creating a new route like @mwringe proposed but for example in this case the jaeger try get the statics from https://kiali/jaeger/static/... and fails, this is why we add another port to redirect all to the jaeger url.

Jaeger I believe has an option you can pass so that it knows about the prefix, so we can configure Jaeger to work this way. I think the problem is that we are not in 'control' of the Jaeger install so its an extra step someone needs to take

**Comment by JStickler** [comment]
Is that Jaeger option for the prefix something that can be configured in
the custom resource file that Istio uses?    Someone was just saying on IRC
yesterday that the cr defines everything that gets set up in istio-system.
It replaces all of the old-CE style ENVs.

JULIE STICKLER

TECHNICAL WRITER

Red Hat

<https://www.redhat.com/>

Westford – 3S353

jstickle@redhat.com    T: 1(978)-399-0463-(812-0463)     IRC: jstickler

**Comment by lucasponce** [comment]
Closed in favor of #469

**Pull request closed without merging**
