### PR TITLE
Remove Iter8 extension

### PR DESCRIPTION
**Pull request by lucasponce**
Fixes https://github.com/kiali/kiali/issues/4643
It requires https://github.com/kiali/kiali-ui/pull/2284

And also there should be another PR for the operator.

### CODE REVIEW

**Comment by lucasponce** [comment]
I need to think about this about the operator https://github.com/kiali/kiali-operator/blob/master/DEVELOPING.adoc#maintain-backward-compatibility

I don't know if removing this may cause some backward compatibility in the operator ?

I'll prepare a PR to discuss it.

**Review by jshaughn — COMMENTED** [review]
LGTM.  Will wait for operator PR before testing and final approval.

**Comment by jshaughn** [comment]
Note, there is also a small removal on kiali.io.  See content/en/docs/FAQ/general.md

**Review by jshaughn — APPROVED** [review]
Built and sanity checked with operator, server and ui prs.

**Comment by lucasponce** [comment]
Thanks, adding to QE flow.

**Comment by pbajjuri20** [comment]
Tested E2E's test cases, Iter8 API was removed successfully. 

Tested the Kiali_UI, nothing was broken, everything looks great!

**Review by pbajjuri20 — APPROVED** [review]

**Pull request merged**
