### PR TITLE
Cherry pick some PRs to v1.0

### PR DESCRIPTION
**Pull request by jmazzitelli**
This cherry picks the following PRs to the v1.0 branch:

- https://github.com/kiali/kiali/pull/1171
- https://github.com/kiali/kiali/pull/1177
- https://github.com/kiali/kiali/pull/1156
- https://github.com/kiali/kiali/pull/1185
- https://github.com/kiali/kiali/pull/1206
- https://github.com/kiali/kiali/pull/1224
- https://github.com/kiali/kiali/pull/1221
- https://github.com/kiali/kiali/pull/1227
- https://github.com/kiali/kiali/pull/1238 
- https://github.com/kiali/kiali/pull/1241
- https://github.com/kiali/kiali/pull/1242
- https://github.com/kiali/kiali/pull/1245
- https://github.com/kiali/kiali/pull/1250
- https://github.com/kiali/kiali/pull/1254

The following performed these cherry picks:

```
git cherry-pick -x 3a53b12
git cherry-pick -x d86c574
git cherry-pick -x 6023d34
git cherry-pick -x c59c55f
git cherry-pick -x 258d53d
git cherry-pick -x 62c3b0c
git cherry-pick -x c0367b9
git cherry-pick -x f10df74
git cherry-pick -x be994fa
git cherry-pick -x d9522c3 
git cherry-pick -x d96cbb1
git cherry-pick -x a8c989e
git cherry-pick -x 177a780
git cherry-pick -x 77baf26
```

### CODE REVIEW

**Comment by hhovsepy** [comment]
Seeing this error on Kiali pod:
"Error: container create failed: container_linux.go:336: starting container process caused "exec: \"/opt/kiali/kiali\": stat /opt/kiali/kiali: no such file or directory" "

**Comment by jmazzitelli** [comment]
@hhovsepy how are you building the image?

**Comment by gbaufake** [comment]
@jmazzitelli problem solved on our building process
Testing this PR now

**Comment by jmazzitelli** [comment]
Merging as a "merge pull request" to maintain all 14 cherry-picks individually.

**Pull request merged**
