### PR TITLE
Added back validation message on workload list and details pages.

### PR DESCRIPTION
**Pull request by hhovsepy**
Issue https://github.com/kiali/kiali/issues/6020
Operator PR: https://github.com/kiali/kiali-operator/pull/647
Helm PR https://github.com/kiali/helm-charts/pull/210

Original feature PR: https://github.com/kiali/kiali/pull/4409

Validation warning "KIA1301" will be by default ignored instead of KIA1201 which was set by typo (or by mistake).
And when not ignored, it will be shown in Workload List and Details pages:
Screenshot from 2023-05-17 20-03-55
Screenshot from 2023-05-17 20-03-27

### CODE REVIEW

**Comment by hhovsepy** [comment]
Test is failing because the error message is not ignored by default.
Dependent PRs needed to be merged.
https://github.com/kiali/helm-charts/pull/210
https://github.com/kiali/kiali-operator/pull/647

**Comment by hhovsepy** [comment]
Hi @leandroberetta , the code for message "This workload is not covered by any authorization policy" was changed from KIA1201 to KIA1301 in docs, then synced up in code, but in ignoring list it was not changed.

**Review by jshaughn — APPROVED** [review]
This looks good to me.

**Review by leandroberetta — APPROVED** [review]
And me!.

**Pull request merged**
