### PR TITLE
KIALI-2207 Do not round timeseries when rounded result affect signifi…

### PR DESCRIPTION
**Pull request by jotak**
…cant decimals

JIRA: https://issues.jboss.org/browse/KIALI-2207

Screenshot before:
Before

Screenshot after:
After

### CODE REVIEW

**Comment by jotak** [comment]
@jshaughn / @israel-hdez I think this should be ok with graph side-panel too, but let me know if you think it's not

**Comment by jshaughn** [comment]
@jotak That's interesting PromQL.  It doesn't cause the inner query to be performed twice, right?  So, no real perf impact?

**Comment by jotak** [comment]
@jshaughn I'm not sure if Prometheus caches the result internally, I hope so, but at least I guess it wouldn't run the right operand of "OR" if the left operand is true, which should stands for the vast majority of the cases.

**Comment by jotak** [comment]
@simonpasquier any idea about the performance impact of this?

**Comment by simonpasquier** [comment]
So unless I'm mistaken, Prometheus is going to evaluate twice the inner query as it doesn't do deduplicating when parsing the whole query.

In practice if we run `round(rate(foo[1m]), 0.1) > 0.1 or rate(foo[1m])`, Prometheus should evaluate the first `rate(foo[1m])` then `round(..., 0.1) > 0.1` drops all samples below the threshold then it will evaluate the second `rate(foo[1m])`and finally it will return all series from the first query + all series from the second query that aren't already present in the first set.

Obviously it is a performance hit but I think it should be reasonable and hardly noticeable unless you're returning 10s of thousands of series.

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#382](https://paste.fedoraproject.org/paste/g91nhwyQqDgAbas7JQs5ig)
  * :heavy_check_mark: run-kiali-e2e-tests [#[963]](https://paste.fedoraproject.org/paste/73pmC59lOdJTPqjdnJAutg)

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Comment by jotak** [comment]
@jshaughn @israel-hdez so I'm merging it but also opened a ticket here for client-side rounding: https://issues.jboss.org/browse/KIALI-2217
I haven't assigned a team so feel free to take it if you want, or I will do later.

**Pull request merged**
