### PR TITLE
Fixed validation message position, fixed failing KIA1102 validation.

### PR DESCRIPTION
**Pull request by hhovsepy**
### Describe the change

Fixed failing cypress test 'KIA1102 validation'
Also fixed the validation messages position in YAML editor. Which was introduced after ' - manager:' fields are added in YAML editor inside collapsed "managedFields:".
Before:
Screenshot from 2024-07-09 11-04-32

After:
Screenshot from 2024-07-09 11-06-03

Added missing "cluster" param in ValidationKey and Validations.

### Steps to test the PR
Make sure you have a VS or any other objects with validation messages or warnings.
Check that all messages in YAML editor are shown in correct lines.

### Automation testing

fixed failing test

### Issue reference
https://github.com/kiali/kiali/issues/7522

### CODE REVIEW

**Review by josunect — COMMENTED** [review]
image

That should not be validating the spec.hosts? foo is a not existent one. 

I think it would be interesting that the multi clusters e2e tests cover some of this validations.

**Comment by hhovsepy** [comment]
> 
> That should not be validating the spec.hosts? foo is a not existent one.
> 

KIA1101 and KIA1107 are for `spec.route.hosts`.
For `spec.hosts` there is 'KIA1106 More than one Virtual Service for same host'

**Comment by josunect** [comment]
> > That should not be validating the spec.hosts? foo is a not existent one.
> 
> KIA1101 and KIA1107 are for `spec.route.hosts`. For `spec.hosts` there is 'KIA1106 More than one Virtual Service for same host'

So, the validations looks correct, then.

**Review by josunect — APPROVED** [review]
LGTM

**Pull request merged**
