### PR TITLE
Versions must be aligned

### PR DESCRIPTION
**Pull request by aljesusg**
Versions in Makefile and frontend/package.json must be aligned

Screenshot from 2022-05-03 11-38-05

### CODE REVIEW

**Comment by lucasponce** [comment]
Ok, so I think that is missing in the release pipeline to release the frontend/package.json version

**Review by lucasponce — APPROVED** [review]
It makes sense.
But also it may need to be synced in the process of bumping/updating the release.
So, @leandroberetta can take a look to update that (probably in a different PR).

**Comment by leandroberetta** [comment]
> It makes sense. But also it may need to be synced in the process of bumping/updating the release. So, @leandroberetta can take a look to update that (probably in a different PR).

Yes, this is missing in the pipeline. I will update it.

**Review by leandroberetta — APPROVED** [review]
LGTM

**Pull request merged**
