### PR TITLE
Do not return error 500 on missing cookie during logout

### PR DESCRIPTION
**Pull request by jotak**
Return 401 instead, so that Kiali UI will get back to the login screen
Also, fixes an issue with response being written twice (`RespondWithError` call followed by `RespondWithCode`)

Closes https://github.com/kiali/kiali/issues/1662

### CODE REVIEW

**Comment by jotak** [comment]
Note for testers: the issue described in #1662 happens on "openshift" login strategy.

To reduce the expiration duration, on openshift 3.x you need to edit your `master-config.yml` file (I've 3 of them in my openshift data directory, not sure which one matters, I edited all of them) and change `accessTokenMaxAgeSeconds` to something smaller.

In openshift 4 I haven't tried but it seems there's a `OAuth` resource where it can be managed: https://docs.openshift.com/container-platform/4.1/authentication/configuring-internal-oauth.html#oauth-configuring-internal-oauth_configuring-internal-oauth

**Comment by hhovsepy** [comment]
@jotak is it expected to auto-logout when session has timeout? This is what I saw on my env.

**Comment by jotak** [comment]
@hhovsepy you mean at the end of the timer countdown? I think it is. WDYT @lucasponce @aljesusg  ?

**Comment by lucasponce** [comment]
> is it expected to auto-logout when session has timeout?

That sounds correct, unless I missed something.
Or not sure if "auto", but if on a request the token/session is not valid, it should logout (I guess it gets the "auto" behaviour when it's polling health).

**Pull request merged**
