### PR TITLE
KIALI-2260 Improve validation rules for DR and VS

### PR DESCRIPTION
**Pull request by burmanm**
** Describe the change **

Currently the validation might show an error in the subset only for DRs, even when the host itself was the issue. Change the validation order to catch the host error first and stop checking the subsets if the host itself is invalid.

With VirtualServices, the host checking was happy if any destination had a valid host. Changed to check all the hosts for validity and make the path for those errors the host instead of the protocol. Also, remove code from kubernetes package as that wasn't used by anything.

** Issue reference **

KIALI-2260

### CODE REVIEW

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#414](https://paste.fedoraproject.org/paste/Lna6uCKrXLifq3FPCBTJDw)
  * :red_circle: run-kiali-e2e-tests [#[1006]](https://paste.fedoraproject.org/paste/oYhMP6~wWq3Is1KA6vq~6Q)

**Comment by hhovsepy** [comment]
Bug in VS, when the first destination host is invalid, the Error icon is shown on the second/valid host
screenshot from 2019-01-18 09-33-51

**Comment by lucasponce** [comment]
@hhovsepy good point, @burmanm ^

**Comment by hhovsepy** [comment]
In DR, when spec host is invalid, it shows error on that spec, and also error on every subset does not matter their value.
This was the designed behavior right?
screenshot from 2019-01-18 09-36-27

**Comment by hhovsepy** [comment]
It is correct, let's keep that secondary one.

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#422](https://paste.fedoraproject.org/paste/TjTIpuZi4z~JXL3og~pg0g)
  * :red_circle: run-kiali-e2e-tests [#[1023]](https://paste.fedoraproject.org/paste/hOZG~SuLsqCuCyBzIQoFjQ)

**Comment by hhovsepy** [comment]
Still see the problem found on previous comment: https://github.com/kiali/kiali/pull/789#issuecomment-455468792

**Comment by burmanm** [comment]
Okay, works on my machine with the UI now.

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#426](https://paste.fedoraproject.org/paste/XrKw-alu4-oJIx93JwYbzw)
  * :red_circle: run-kiali-e2e-tests [#[1029]](https://paste.fedoraproject.org/paste/wlCebF01SdtV8o3aN9LduA)

**Comment by hhovsepy** [comment]
Verified:
VS
screenshot from 2019-01-22 10-46-53

DR:
screenshot from 2019-01-22 10-49-39

VS when DR is broken:
screenshot from 2019-01-22 10-49-21

**Pull request merged**
