### PR TITLE
Incorporate k-charted backend into kiali backend

### PR DESCRIPTION
**Pull request by jotak**
Includes some merge of models & functions that were duplicated.

Fixes https://github.com/kiali/kiali/issues/3422
Frontend PR: https://github.com/kiali/kiali-ui/pull/2002

### CODE REVIEW

**Comment by jotak** [comment]
Note, there will also be a frontend PR, but they're technically independent.

**Review by jshaughn — APPROVED** [review]
LGTM

**Review by lucasponce — APPROVED** [review]
LGTM

Perhaps in future steps some naming can be unified, but it's good to have it in the same repo.

**Comment by israel-hdez** [comment]
@jotak We can archive k-charted repo, right?

**Comment by lucasponce** [comment]
> We can archive k-charted repo, right?

I'd say not yet, or at least until we don't need it for Kiali 1.26.x which is shipped in downstream.
It's unlikely that will need a patch there, but just in case.

**Comment by israel-hdez** [comment]
> I'd say not yet, or at least until we don't need it for Kiali 1.26.x which is shipped in downstream.
> It's unlikely that will need a patch there, but just in case.

Oh! Right, Yes!
Fair enough.

**Pull request merged**
