### PR TITLE
OSSM-1224: adding junit reporter

### PR DESCRIPTION
**Pull request by FilipB**
** Describe the change **
This is changing default behavior: Output a spec report to STDOUT, while saving a JUnit XML file for each spec file.

** Issue reference **
https://issues.redhat.com/browse/OSSM-1224

### CODE REVIEW

**Comment by FilipB** [comment]
Other option is to create new script e.g. `cypress:run:junit` and do not change default behavior of `cypress:run`. But only difference in behavior is that it's also reporting xml results to `cypress/results` dir

**Comment by nrfox** [comment]
> Other option is to create new script e.g. `cypress:run:junit` and do not change default behavior of `cypress:run`. But only difference in behavior is that it's also reporting xml results to `cypress/results` dir

I'd prefer that option since the reports won't be used by people who run cypress locally or in GH actions. Should the `cypress/results` dir also be added to `.gitignore`? We don't want to commit the results of individual test runs ever right?

**Review by nrfox — APPROVED** [review]

**Comment by ScriptingShrimp** [comment]
```bash
[scsh@fedora frontend]$ pwd
/home/scsh/work/filipB/kiali/frontend
[scsh@fedora frontend]$ yarn cypress:run:junit
yarn run v1.22.18
$ npm run cypress:delete:reports

> @kiali/kiali-ui@1.51.0 cypress:delete:reports
> rm cypress/results/* || true

rm: cannot remove 'cypress/results/*': No such file or directory
$ cypress run --reporter cypress-multi-reporters --reporter-options configFile=reporter-config.json
Could not load reporter by name: cypress-multi-reporters

We searched for the reporter in these paths:

- /home/scsh/work/filipB/kiali/frontend/cypress-multi-reporters
- /home/scsh/work/filipB/kiali/frontend/node_modules/cypress-multi-reporters

The error we received was:

Cannot find module '/home/scsh/work/filipB/kiali/frontend/node_modules/cypress-multi-reporters'
Require stack:
- /home/scsh/.cache/Cypress/9.2.1/Cypress/resources/app/packages/server/lib/reporter.js
- /home/scsh/.cache/Cypress/9.2.1/Cypress/resources/app/packages/server/lib/project-base.js
- /home/scsh/.cache/Cypress/9.2.1/Cypress/resources/app/packages/server/lib/open_project.js
- /home/scsh/.cache/Cypress/9.2.1/Cypress/resources/app/packages/server/lib/cypress.js
- /home/scsh/.cache/Cypress/9.2.1/Cypress/resources/app/packages/server/index.js
- /home/scsh/.cache/Cypress/9.2.1/Cypress/resources/app/index.js
- 

Learn more at https://on.cypress.io/reporters
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
executing yarn command from /frontend folder fails for some reason

**Review by ScriptingShrimp — APPROVED** [review]
LGTM! Verified locally

**Pull request merged**
