### PR TITLE
Fix CI branching issue for PRs

### PR DESCRIPTION
**Pull request by leandroberetta**
Fixing CI when run agains PR branches.

### CODE REVIEW

**Comment by lucasponce** [comment]
Mmm why the CI are skipped in the PR ?
image

**Comment by leandroberetta** [comment]
> Mmm why the CI are skipped in the PR ? image

So, the last commit was to fix some thing related to the release pipeline (not related to this problem). I'm fixing the value of a variable when the release_type is auto. As it was not related, I cancelled the CI, because for the previous commit it worked:

https://github.com/kiali/kiali/actions/runs/2244737308

We can start the jobs again if you want.

**Comment by lucasponce** [comment]
Ah, I was expecting to see all CIs in green :), that confused me.
Yes, let's update the PR to see that the normal/default flow of the CI works.

(Typically we look when a PR is merged that all CI was ok)

**Review by lucasponce — APPROVED** [review]

**Comment by lucasponce** [comment]
I've merged because I'm going to rebase my previous (tiny) PR to check that the CI flow works as expected.

**Pull request merged**
