### PR TITLE
Filtering auto generated DR when a config option is set

### PR DESCRIPTION
**Pull request by josunect**
This PR filters auto generated DRs. 
It checks if it is maistra autogenerated by checking the label `maistra.io/owner`

Fixes https://github.com/josunect/kiali/pull/new/issue5991

### CODE REVIEW

**Comment by josunect** [comment]
> Hi @josunect , the autogenerated VirtualServices are filtered out by default, I just wander can we make DRs also filter by default without a config option?



> Hi @josunect , the autogenerated VirtualServices are filtered out by default, I just wander can we make DRs also filter by default without a config option?

Sure, you mean, just the auto generated, right?

**Comment by hhovsepy** [comment]
Right, I mean like this.

**Comment by josunect** [comment]
> Right, I mean like this.

Thank you, @hhovsepy !

**Review by hhovsepy — APPROVED** [review]
Verified on Kiali and Istio upstream:
Screenshot from 2023-04-11 16-53-57

The original issue needs QE verification on Maistra.

**Comment by josunect** [comment]
> Verified on Kiali and Istio upstream: Screenshot from 2023-04-11 16-53-57
> 
> The original issue needs QE verification on Maistra.

Thank you, Hayk! Do we need a jira or how to document this requirement for this additional validation?

**Pull request merged**
