### PR TITLE
Fix missing Grafana Workload and Service links

### PR DESCRIPTION
**Pull request by leandroberetta**
This PR fixes the missing Grafana links in Workloads and Service metrics pages.

### CODE REVIEW

**Review by jmazzitelli — APPROVED** [review]
did you go through the rest of the configs to see if we need json identifiers elsewhere?

**Review by nrfox — APPROVED** [review]
Good eye!

**Comment by leandroberetta** [comment]
> did you go through the rest of the configs to see if we need json identifiers elsewhere?

I checked the others and they don't seem to be used the way this struct was used, so I don't see any potential issue, but would be nice to have another pair of eyes in that code just to check.

**Comment by jmazzitelli** [comment]
to confirm, the links should be here, right?

image

I don't see it.

**Comment by jmazzitelli** [comment]
My eyes can't move that far right :)
image

**Comment by prachiyadav** [comment]
Test case >> SWSQE-89

**Pull request merged**
