### PR TITLE
Refactor: Change FormSelect to Select from @patternfly/react-core

### PR DESCRIPTION
**Pull request by besalraj30**
### Describe the change

Explanation of what this PR does

Migrate from FormSelect to Select to ensure uniformity

### Steps to test the PR

Render K8sGatewaySelector component

Recommendations for how to test this PR. Reminder that each PR should also include a "Test" label.

### Automation testing

If applicable, explain the case scencarios covered by **unit / integration / e2e** tests created for this PR.

### Issue reference : https://github.com/kiali/kiali/issues/7277

If this PR is related to a github issue, please link it here ([more info](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))

selectedGateway : 

image

gatewayClass : 

image

### CODE REVIEW

**Review by ferhoyos — COMMENTED** [review]
Nice work @besalraj30! Glad to see you again, this time with the `k8sGatewaySelector`. Your code is good, but there is a collateral issue because the gateway property in `k8sGRPCRouteHosts` and `k8sRouteHosts` is not properly defined.

I have created a PR of your PR fixing this issue and other lint fixes. If you agree with the PR, merge it and we will run the final test.

**Comment by besalraj30** [comment]
> @besalraj30 , Can you please move this forward by merging in the PR from @ferhoyos , so that we can re-review and merge? Thanks!

HI @jshaughn, I'll get started on this right away, had been caught up due to some reasons. Will respond with code changes and merging ASAP

**Comment by besalraj30** [comment]
> Nice work @besalraj30! Glad to see you again, this time with the `k8sGatewaySelector`. Your code is good, but there is a collateral issue because the gateway property in `k8sGRPCRouteHosts` and `k8sRouteHosts` is not properly defined.
> 
> I have created a PR of your PR fixing this issue and other lint fixes. If you agree with the PR, merge it and we will run the final test.

Hi @ferhoyos ,

Thank you for pointing this out and for the fixes! I couldn't find the PR you mentioned that fixes the gateway property issue and includes the lint fixes. Could you please share the link to the PR?

Looking forward to reviewing it.

**Comment by besalraj30** [comment]
@ferhoyos I have merged your PR, will finalise the testing today and let you know ASAP when this PR is ready to be merged

**Comment by besalraj30** [comment]
Hi @ferhoyos  @jshaughn ,

Update on Progress:

1. I merged @ferhoyos's PR into my branch.
2. Pulled the latest changes on my local environment (VSCode), performed a fresh build, and tested the functionalities of the K8sGatewaySelector component.

- I'm happy to report that everything is working as expected.
- Attached screenshots demonstrate the tested functionality for reference.

image


image


Next Steps:

- I will raise a PR for the remaining changes involving the migration from FormSelect to Select from @patternfly/react-core.
- Apologies for the delay on this; I’ve been occupied over the past few days but will prioritize it now.

Merge Readiness:
This PR is now good to merge, as all functionalities have been tested and are working fine.

Thank you for your patience! Please let me know if there’s anything else I should address.

**Review by ferhoyos — APPROVED** [review]
LGTM

**Pull request merged**
