### PR TITLE
Improve graph labels with PF badges instead of parentheses

### LINKED ISSUE #6123: Improve graph node labels - remove parentheses
To add necessary discriminators to Graph node labels we append namespace and/or cluster names in parentheses.  This has proven to be confusing and can also be hard to read.  It originated before we used PF badges and can now be improved by using fully-badged information.

This is related to https://github.com/kiali/kiali/issues/5922, which suggests that we add back single-node parent-boxes.  But that approach has proven to be cumbersome for larger graphs.  Hopefully this will be sufficient.  If not, we could add single-node boxing back, as a configurable ui-option (but I don't really want to).

Before:
image

After:
TBD

### PR DESCRIPTION
**Pull request by jshaughn**
Closes #6123 
Relates To #5922

In the graph, replace parenthesized label information with properly PF badged content.  This is for when labels add namespace and/or cluster disciminators to ensure label uniqueness.  

To test you need to generate situations where labels would previously use the parenthesized information for namespace/cluster discriminator.  Some ways of doing this:
- multi-cluster
- select multiple namespaces for the graph
- remove namespace and/or cluster boxing

Negative testing may also be useful, to ensure unnecessary badging doesn't now appear.  Different graph types, enable boxing, single namespace, single cluster, etc.

### CODE REVIEW

**Review by leandroberetta — COMMENTED** [review]
I've been testing this and looks good but I noticed that there is not badge for the home cluster:

image

I think we need to add it.

**Comment by jshaughn** [comment]
> I've been testing this and looks good but I noticed that there is not badge for the home cluster:

I understand your point, because it means the user has to be aware of his context (i.e. he needs to realize the home-cluster is the default),  but we do everything we can to minimize what's on-screen because of the issues with larger graphs.  I wouldn't make the change unless users say they find it confusing.  Or if there is a mutiny of engineers :-)

**Comment by josunect** [comment]
Testing the PR and it looks good to me: 

image

I think not including the home cluster name could be confusing at the beginning. But once you know, I think it is more clear, as it makes a differentiation about which one is the home cluster. Also, if the cluster boxes are added, it is possible to see all the cluster names:

image

**Review by leandroberetta — APPROVED** [review]
LGTM.

**Comment by jshaughn** [comment]
> I still think adding it won't hurt but I'm ok if we document this, or at least document it on the first question we receive in the future.

It's analogous to not showing the namespace-name for the single namespace selected in the namespace-selector dropdown.  In that case the user is expected to infer the namespace from the dropdown.  In this case the user is expected to infer the cluster from the masthead.  Anyway, if people report that they are confused I will support the change.

**Pull request merged**
