### PR TITLE
Update README with recent config changes

### PR DESCRIPTION
**Pull request by jotak**
... and remove unused config

### CODE REVIEW

**Comment by jotak** [comment]
This is just a readme update that was forgotten from a previous PR.
Also, I removed a config that is unused in code, I think it's an old relics of ancient times. (was "IstioSidecarAnnotation")

**Comment by jmazzitelli** [comment]
@jotak while we are here, can you update the two TOKEN_ ones? First, I have no idea what these are (WHAT? token?). The descriptions are also not very clear.  Can we just get more detail on these?

**Comment by jmazzitelli** [comment]
Can I ask why the sidecar annotation config entry went away? Do we assume it will always be the same value? (I'm thinking of things like the Red Hat product that could potentially use a different annotation - is that even possible?)

**Comment by jotak** [comment]
@jmazzitelli actually... I was about to write that we're not relying anymore on the annotation for a while, but looking at the presence if istio containers instead.

But I just check in the code and see that to get the istio containers we do actually rely on an annotation, although it is now hardcoded and not dependant on the config.

So maybe we should keep that config and remove the hard-coded part instead.

**Comment by jmazzitelli** [comment]
> So maybe we should keep that config and remove the hard-coded part instead.

+1 - I think we should be able to have this config and not hardcode.

**Comment by jotak** [comment]
@jmazzitelli done - I wired the istio config in the same commit, if it's ok with you...

**Pull request merged**
