### PR TITLE
Configurable label aggregations in metric tabs

### PR DESCRIPTION
**Pull request by israel-hdez**
Adding possibility to configure _additional_ label aggregations in metric tabs.

For example, a Kiali CR with the following configuration:

```yaml
spec:
  kiali_feature_flags:
    ui_defaults:
      metrics_inbound:
        aggregations:
        - display_name: Istio Network
          label: topology_istio_io_network
        - display_name: Istio Revision
          label: istio_io_rev

```

will generate the following options in the metrics menu:

image

Fixes kiali/kiali#2911.

### CODE REVIEW

**Comment by israel-hdez** [comment]
@lucasponce @jshaughn I'm wondering if it's acceptable to provide defaults and let the user override, if needed?

In the original issue, it is suggested to only allow adding custom aggregations. But I wonder why negate removing aggregation that you may not want? These few changes are allowing full override, thus allowing removing any aggregation you may not need.

If we are OK by allowing overriding defaults, I need to do more changes (both to the front- and back-end). So, I want to know your thought before I continue.

**Comment by lucasponce** [comment]
Hi @israel-hdez, thanks for the PR.

I put a comment in the issue when we revisited the scope of this work https://github.com/kiali/kiali/issues/2911#issuecomment-893410726 . I don't think we want to increase the level of personalization of the Kiali dashboards, Grafana does a better job for that scenario. The idea if that Kiali offers a default opionanted dashboards that we think that they help to the Istio domain with certain level of personalization (custom dashboards) but this would be more a corner case rather than a first class feature.

So any minor step that sounds interesting, like this one, to allow some personalization through configuration, looks ok, but I wouldn't go beyond as that may potentially require a re-design of the current model.

**Comment by jshaughn** [comment]
My understanding is that this issue was just to add custom aggregations and not to remove or override the existing aggegations.  I think that just the addition of non-default aggregations is sufficient scope.  Anything further could be considered later, if asked for by the community.

**Comment by israel-hdez** [comment]
OK, I did the changes to allow only _adding_ custom label aggregations.

This is ready for review.

**Comment by israel-hdez** [comment]
Operator PR: https://github.com/kiali/kiali-operator/pull/428

**Comment by pbajjuri20** [comment]
I have deployed and tested on my environment.


cr_pr


Input_q

**Comment by lucasponce** [comment]
Sorry @israel-hdez I missed the review.
I'll fetch it locally today.

**Review by lucasponce — APPROVED** [review]
LGTM

**Review by pbajjuri20 — COMMENTED** [review]
LGTM!

**Comment by pbajjuri20** [comment]
Tested and Verified on the Kiali UI 1.41.0 (51b548beaf7ee8e2ddb501f99b1c8f82836e9910) and Kiali Server v1.41.0-SNAPSHOT (396b11384343a71083f8d579567aee89e2e76307)

**Comment by israel-hdez** [comment]
Thanks for the reviews!

**Pull request merged**
