### PR TITLE
Use ignorecluster global for tracing

### PR DESCRIPTION
**Pull request by josunect**
Ref. #6844

https://github.com/kiali/kiali/issues/6844#issuecomment-1854504377

In order to get a sample of the traces from different times and a limited number of results, in some calls (Like the node graph for traces), splits the search query in 10, this is, will perform up to 10 concurrent requests to the tracing platform. 

When there are no cluster tags, each query is repeated, which in a busy environment can be translated in a worst performance. This PR tries to get this information when the tracing client is created and avoid the duplication of calls to the backend.

### CODE REVIEW

**Comment by hhovsepy** [comment]
@josunect the solution looks good, should it be applied for Jaeger GRPC client as well?

**Comment by josunect** [comment]
Tested with MC. It uses the cluster tag and no duplicated queries in the backend. 

Testing procedures: 

- `istio/multicluster/install-primary-remote.sh -c kubectl`
- `istio/multicluster/deploy-kiali.sh -c kubectl -kas anonymous`
- Update the istio cm: 

```
data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      meshId: mesh-hack
      proxyMetadata: {}
      tracing:
        sampling: 100
    defaultProviders:
      metrics:
      - prometheus
      tracing:
      - localtrace
    enableAutoMtls: true
    enablePrometheusMerge: true
    extensionProviders:
    - name: "localtrace"
      zipkin:
        service: zipkin.istio-system.svc.cluster.local
        port: 9411
```

And create a Telemetry to add the cluster tag: 

```
kubectl apply -f - <<EOF
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  # no selector specified, applies to all workloads
  tracing:
  -  customTags:
      cluster:
        environment:
          name: "ISTIO_META_CLUSTER_ID"
EOF
```

**Comment by josunect** [comment]
> @josunect the solution looks good, should it be applied for Jaeger GRPC client as well?

Good catch, @hhovsepy ! I will add it also there, thanks.

**Comment by josunect** [comment]
> > @josunect the solution looks good, should it be applied for Jaeger GRPC client as well?
> 
> Good catch, @hhovsepy ! I will add it also there, thanks.

@hhovsepy, I've included it in the Jaeger GRPC client. Thanks!

**Review by hhovsepy — APPROVED** [review]
@josunect looks good , tested locally.

**Pull request merged**
