### PR TITLE
feat: provide recycleChan to clean expired clients

### PR DESCRIPTION
**Pull request by Xunzhuo**
Signed-off-by: Xunzhuo <mixdeers@gmail.com>

** Describe the change **

provide recycleChan to clean expired clients

** Issue reference **

related to https://github.com/kiali/kiali/issues/4849

### CODE REVIEW

**Comment by Xunzhuo** [comment]
One more questions need to be confirmed, is it a good idea to let user to configure the expiration time?

**Comment by lucasponce** [comment]
@Xunzhuo I've read and reviewed the PR several times.
I don't still see the benefit of this approach compared with the current design.

What penalty will cause to review all clients in the "watchClients" in a scenario with few clients?

Perhaps do you have any other scenario that we are not seeing and it's causing a problem that would need this approach?

Without more info that justifies it, I'm not sure this one could progress.

General comment, the code base of Kiali can be optimized (no doubt on that) but typically it's driven by some business/priorities; and also some tradeoffs are considered unless there is a clear penalty or feature that we want to address.

**Comment by Xunzhuo** [comment]
> @Xunzhuo I've read and reviewed the PR several times. I don't still see the benefit of this approach compared with the current design.
> 
> What penalty will cause to review all clients in the "watchClients" in a scenario with few clients?
> 
> Perhaps do you have any other scenario that we are not seeing and it's causing a problem that would need this approach?
> 
> Without more info that justifies it, I'm not sure this one could progress.
> 
> General comment, the code base of Kiali can be optimized (no doubt on that) but typically it's driven by some business/priorities; and also some tradeoffs are considered unless there is a clear penalty or feature that we want to address.

Hi @lucasponce , sorry for replying lately for busy jobs recently.
The reason I want to refactor this is both to optimize the logic and meet some specific scenario:
For now, I believe that the expiration time is a const and can not be configured, but sometimes the expiration time should be able to be configured, for example, in some clusters, we should expire the client more frequently for some dynamically changes with apiserver, and in some clusters, we may do not want kiali to expire and create clients frequently.
So I think this is the reason that I do the refactoring in this area.

**Comment by lucasponce** [comment]
Please @Xunzhuo, would you mind rebasing this one with the master branch? Thanks

**Comment by Xunzhuo** [comment]
@lucasponce  sure~

**Review by lucasponce — DISMISSED** [review]
I've reviewed and tested the proposal.
I think we can accept this change if it helps other scenarios where @Xunzhuo is working.

**Comment by lucasponce** [comment]
Sorry to ask you again @Xunzhuo, would you mind rebasing again?
I'm fine consolidating this work and checking that there are no other use cases that may affect it.

The project is in a transition phase where we added new CI pipelines for the UI and those are not yet 100% stable and it would require updating the branches.

Thanks!

**Review by lucasponce — APPROVED** [review]
Re-approved.
The UI test failing is unrelated to this work and it's being addressed in a separate effort.

**Comment by Xunzhuo** [comment]
> Re-approved.
> 
> The UI test failing is unrelated to this work and it's being addressed in a separate effort.

@lucasponce thanks!

**Pull request merged**
