### PR TITLE
KIALI-2960 Add config to skip verify insecure https

### PR DESCRIPTION
**Pull request by jotak**
Both for Grafana and Prometheus

JIRA: https://issues.jboss.org/browse/KIALI-2960
See also #786

### CODE REVIEW

**Comment by jotak** [comment]
I've haven't fully tested with a self-signed certificate yet.

**Comment by jotak** [comment]
Config are:
- For Prometheus:  `external_services.prometheus.insecure_skip_verify` (true/false)
- For Grafana: `external_services.grafana.insecure_skip_verify` (true/false)

**Comment by hhovsepy** [comment]
Tested with Prometheus over https route and custom signed certificate:
The metrics are shown, error mentioned in issue is gone, but the Prometheus is not shown in About -> Version:
Screenshot from 2019-06-06 11-49-00
Screenshot from 2019-06-06 11-49-34

**Comment by jotak** [comment]
@hhovsepy i've spotted the issue and it should be fixed
Note that i'm developing blindly cause of something wrong in my cluster/host config, and my pods cannot connect to external URL :-( So i'm only testing the nominal case with everything in-cluster.

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1070](https://paste.fedoraproject.org/paste/xd-RzvX11ru6gB2moLx37Q)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1979]](https://paste.fedoraproject.org/paste/8~MB1bBfr4oq~2IoJvLLMw)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1071](https://paste.fedoraproject.org/paste/20OSDtJikajhIGh0-roIjw)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1980]](https://paste.fedoraproject.org/paste/TLc2WnSoP6DEg~e6QyvVyg)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1072](https://paste.fedoraproject.org/paste/XyFw11eW7pkcUOxRBJIshg)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1981]](https://paste.fedoraproject.org/paste/VbgtwD18t9bV2EaH0FUQvQ)

**Comment by jotak** [comment]
thanks @hhovsepy

**Pull request merged**
