### PR TITLE
Tracing is disabled by default

### PR DESCRIPTION
**Pull request by josunect**
### Describe the change

Tracing is disabled by default now

### Steps to test the PR

Run Kiali without any additional config (And without the operator).
Tracing should be disabled. 

### Automation testing
Update setup for tests

### Issue reference
#7332

### CODE REVIEW

**Comment by hhovsepy** [comment]
QE Jenkins pipeline installs with default traces disabled. It needs to be adjusted to consider default param.

**Comment by ScriptingShrimp** [comment]
do we need to enable the traces in the Jenkins job? Its related only to integration tests? Or more things could go wrong?

**Comment by josunect** [comment]
> Do we need to enable the traces in the Jenkins job? Its related only to integration tests? Or more things could go wrong?

It will affect all the jobs that are installing Kiali and traces are needed...

**Review by hhovsepy — APPROVED** [review]
works fine now on Jenkins pipeline, kudos to @mkralik3 for the fix

**Pull request merged**
