### PR TITLE
Update go dependencies and bump protobuf

### PR DESCRIPTION
**Pull request by jotak**
Also minor upgrade of prometheus client.

Related to https://github.com/kiali/kiali/issues/2599#issuecomment-610333499

### CODE REVIEW

**Comment by lucasponce** [comment]
Adding Hayk.
A change like this requires detailed regression testing as it may trigger side effects in some features (specially related to config ones which invoke many different APIs through kubernetes/client-go).

**Comment by jotak** [comment]
@mtho11 do you know what's wrong with snyk? Can I get access to the report? (currently i don't)

**Comment by jotak** [comment]
@mtho11 I accepted the invitation and am able to see kiali dashboards in snyk ... however I still can't access to the snyk check performed on this PR (this link: https://app.snyk.io/org/kiali/pr-checks/bb9a2958-d1a9-44ef-ae22-53eac2a9bcfc ) ; are you able to get there?

**Comment by mtho11** [comment]
@jotak no I can't see it either: I get the "Unable to see organization"
Unable_to_display_this_organization___Snyk

**Comment by mtho11** [comment]
I wonder if there could be a different version of snyk (different account) that Travis CI is running?

**Comment by israel-hdez** [comment]
This is what I get:

image

I think it isn't important. Probably, related to the bump in k-charted.

Snyk is checking the deps of our vendorized dependencies. I think I'll disable Snyk from this repo, at least until we move to go modules. I don't see it useful in our current state.

**Comment by jotak** [comment]
Ok, so this PR can be merged (and yes, the error about k-charted-pf3 can be ignored, actually snyk should stop processing it).

Looking closely at your screenshot @israel-hdez I notice you have Kiali org (with capital K) ; I'm in kiali org with minus k. Could it be the issue?

**Comment by israel-hdez** [comment]
> Looking closely at your screenshot @israel-hdez I notice you have Kiali org (with capital K) ; I'm in kiali org with minus k. Could it be the issue?

I think it is the issue. We had to re-setup snyk because it stopped working some time ago. I think the org you are in is the one created by Thomas that may no longer have privileges in Kiali repos, thus not working. I think I can give privs to you and also to @mtho11 if you want for next reports.

**Comment by jotak** [comment]
@israel-hdez yes, please. Plus, it's not only for reports, but also to get the details of the issues for checks that run on PRs. In that regard I'd even think the whole team should have access.

**Comment by israel-hdez** [comment]
@jotak I sent the invite to you and also @mtho11 .
You are admins (it's the only privilege allowed in the free plan), so feel free to invite others in the team :)

**Comment by jotak** [comment]
@israel-hdez thanks!

**Pull request merged**
