### PR TITLE
Create annotations in workloads and services

### PR DESCRIPTION
**Pull request by aljesusg**
Require https://github.com/kiali/kiali-operator/pull/608
Fix https://github.com/kiali/kiali/issues/4179

Option **_istio_annotation_action_** must be true to perform this action

# Demo
## Menu
Screenshot from 2023-02-01 10-48-28
## Annotations Wizard
workloads
## Add new annotation
Screenshot from 2023-02-09 10-58-24
Screenshot from 2023-02-09 10-58-38
Screenshot from 2023-02-09 10-58-49
Screenshot from 2023-02-09 10-59-04

### CODE REVIEW

**Comment by hhovsepy** [comment]
Early review result: Facing issues while typing or pasting text in Add more annotation key field.

**Comment by aljesusg** [comment]
> Screencast.from.2023-02-01.13-50-21.webm

well I set a verification there...you can't have the same key . Let met address that with a message instead remove the row

**Comment by hhovsepy** [comment]
@aljesusg ok good idea with validation message on duplicate key, but still the typing does not work for me, it types the first letter only then it unfocuses the text input. hapens on FF and chrome

**Comment by aljesusg** [comment]
> @aljesusg ok good idea with validation message on duplicate key, but still the typing does not work for me, it types the first letter only then it unfocuses the text input. hapens on FF and chrome

Fixed and added new things

Screenshot from 2023-02-01 20-56-50

**Comment by hhovsepy** [comment]
The moving width of columns while typing or saving a new annotation is not good from UX perspective. Can the widths of columns and inputs be fixed?
Also the workload annotations save fails for me with "ERR Error fetching Deployment per namespace bookinfo and name mongodb-v1: error decoding patch: json: cannot unmarshal array into Go value of type map[string]interface {}".

**Comment by aljesusg** [comment]
Can you tell me the value that you tried?

**Comment by hhovsepy** [comment]
`"kubectl.kubernetes.io/last-applied-configuration" {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"details","version":"v1"},"name":"details-v1","namespace":"bookinfo"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"details","version":"v1"}},"template":{"metadata":{"labels":{"app":"details","version":"v1"}},"spec":{"containers":[{"image":"docker.io/istio/examples-bookinfo-details-v1:1.17.0","imagePullPolicy":"IfNotPresent","name":"details","ports":[{"containerPort":9080}],"securityContext":{"runAsUser":1000}}],"serviceAccountName":"bookinfo-details"}}}}`

Screenshot from 2023-02-02 11-09-26

**Comment by hhovsepy** [comment]
But also fails when deleting existing annotation:
Screenshot from 2023-02-02 11-11-42

**Comment by aljesusg** [comment]
> But also fails when deleting existing annotation: Screenshot from 2023-02-02 11-11-42

Omg this only happen in workloads not in services so this is something related with deployments I need to do some research about

**Comment by aljesusg** [comment]
@hhovsepy I found the problem, i forgot to change the services/api params for workload case.
About columns width...What do you mean?. This design is like CRC has. the with don't change.

**Comment by hhovsepy** [comment]
I mean this:
[Screencast from 2023-02-03 10-24-36.webm](https://user-images.githubusercontent.com/604313/216562737-b9e2d1b5-9afe-4f01-86de-a1b99d4e49c8.webm)

**Comment by hhovsepy** [comment]
@aljesusg the workloads annotations saving is working now

**Review by hhovsepy — DISMISSED** [review]
Tested, works fine.

**Comment by aljesusg** [comment]
Latest update
Screenshot from 2023-02-09 10-58-24
Screenshot from 2023-02-09 10-58-38
Screenshot from 2023-02-09 10-58-49
Screenshot from 2023-02-09 10-59-04

@andrew-ronaldson Can you take a look?

**Comment by hhovsepy** [comment]
"Clear" button does not clear errors section, and "Cancel" then again "Edit Annotations" reload the Errors section:
Screenshot from 2023-02-09 13-43-29

**Comment by hhovsepy** [comment]
Now it works fine

**Review by hhovsepy — APPROVED** [review]

**Review by andrew-ronaldson — APPROVED** [review]
LGTM. Thanks!

**Comment by aljesusg** [comment]
> LGTM. Thanks!

Thanks @andrew-ronaldson

**Pull request merged**
