### PR TITLE
Improve hack scripts for Ambient

### LINKED ISSUE #7402: Improve hack scripts for Ambient
### What do you want to improve?

- When installing bookinfo with Ambient and a Waypoint proxy, it does not work. 
- Update Travel agency demo to be able to create an Ambient and Sidecar mixed namespaces.

### What is the current behavior?

The namespace needs to be enrolled, also needs a gateway api GW and the authorization policy is not working. 

### What is the new behavior?

Adapt to the latest changes to Istio 1.22: 

- Install CRDs if Ambient is enabled
- Enrolled the waypoint into the namespace
- Update the gateway when Ambient is enabled
- Remove authorization policy

### PR DESCRIPTION
**Pull request by josunect**
### Describe the change

Updated bookinfo and travel portal demo

### Steps to test the PR
Deploy demos in Ambient mesh: 

- `hack/istio/install-travel-agency-demo.sh -c kubectl -di travel-agency`
- `istio/install-bookinfo-demo.sh -c kubectl -ai false -tg -w true`

image
image

To include also waypoint in travel agency: 

- `hack/istio/install-travel-agency-demo.sh -c kubectl -di travel-agency,travel-portal -w true`

### Automation testing

If applicable, explain the case scencarios covered by **unit / integration / e2e** tests created for this PR.

### Issue reference

Fixes #7402

### CODE REVIEW

**Comment by josunect** [comment]
TODO: More testing and add waypoint option to travels.

**Comment by jmazzitelli** [comment]
> Deploy demos in Ambient mesh:

Those steps assume Ambient is enabled, correct? So how do I install Istio for this test? Would it be like this:

1. Install minikube: `hack/k8s-minikube.sh start`
2. Install Istio: `hack/istio/install-istio-via-istioctl.sh -cp ambient -c kubectl`

**Comment by josunect** [comment]
> > Deploy demos in Ambient mesh:
> 
> Those steps assume Ambient is enabled, correct? So how do I install Istio for this test? Would it be like this:
> 
>     1. Install minikube: `hack/k8s-minikube.sh start`
> 
>     2. Install Istio: `hack/istio/install-istio-via-istioctl.sh -cp ambient -c kubectl`

Yes, that's right. (I haven't tried it with minikube hack script, but I guess that should be doing something similar than minikube start). 
That should be tested with Istio 1.22

**Comment by jmazzitelli** [comment]
I don't see any http data in the graph for travels. My graph doesn't look like yours:

image

**Comment by jmazzitelli** [comment]
Overview cards look OK
Screenshot from 2024-06-03 15-52-43

Bookinfo doesn't have http data past productpage:
image

**Comment by josunect** [comment]
@jmazzitelli , I think that looks good. This is how my bookinfo looks like: 

image

I was talking with @jshaughn about separate the work from https://github.com/kiali/kiali/pull/7345, and for one side add the logic to modify the scripts (Bookinfo and include also Travels) and for the other PR update the Telemetry (https://github.com/kiali/kiali/pull/7345/files), so in case someone needs to test Ambient, that is ready. 

The motivation to have Travels with sidecars/Ambient namespaces is to test different combinations and see how the graphs looks like.

**Review by jmazzitelli — APPROVED** [review]
For the purposes of this PR (just to start demos with Ambient) this is good and ready for merge.

**Pull request merged**
