### PR TITLE
Format links for Grafana Tempo

### LINKED ISSUE #6531: Tempo integration - Use link format for Grafana Tempo
The Kiali UI has several links to the tracing backend in the Traces details tab:

image

Tempo uses Grafana as the default UI. The URL format for a particular trace: 

`
http://localhost:13000/explore?left={"datasource":"Tempo","queries":[{"refId":"A","queryType":"traceId","query":"bb4bdcda9c2a57e5ee45e1ab50f93dd7"}],"range":{"from":"now-1h","to":"now"}}&orgId=1`

So, probably Kiali would need to include at least the datasource name configuration. Also, the frontend would need to know the tracing provider to create the right URL. The urls that the frontend is using: 

- http://localhost:16686/trace/10683e5f054e98bd05061d224d3fb6f4
- http://localhost:16686/trace/10683e5f054e98bd05061d224d3fb6f4...1a2f2bef8cb690b98ab69128a08b202b?cohort=10683e5f054e98bd05061d224d3fb6f4&cohort=1a2f2bef8cb690b98ab69128a08b202b&cohort=11043be5de037970042c2f1d968a3b8a&cohort=5031117aebddb22fa4a90619e633c073&cohort=c346300e3dd96540bef0ffd2fe30c01c&cohort=a766ded68287420a553045c2738b2746&cohort=1a542d983dd780fc3064d6a33c4c149d&cohort=2dc4f4e4b6803bd4ddffa8e5b426ab81&cohort=db95e770222604d7669c166d81b70a7d&cohort=ac32825c5c78c2012e06349c26fcdad2&cohort=76fdaaa94022de7d1b8f30dccb1188a9
- http://localhost:16686/trace/EGg+XwVOmL0FBh0iTT+29A==?uiFind=BQYdIk0/tvQ=

### PR DESCRIPTION
**Pull request by josunect**
Fixes #6531 

How to test it: 
- run `istio/tempo/install-tempo-env.sh` to install the environment
- Setup Kiali config: 

```
  tracing:
    enabled: true
    provider: "tempo"
    in_cluster_url: http://localhost:3200
    url: http://localhost:3200

...
  grafana:
    in_cluster_url: http://localhost:13000
    url: http://localhost:13000

```
(Grafana url needs to be set, as Tempo will use Grafana UI with the datasource)

- Create a Grafana Tempo Datasource. In Grafana, go to Connections > Select Tempo > Create Tempo datasources.
- Set up `default` and put a name, and a url. It should be the internal url for the tempo service `query-frontend` and port `3200`. 
image

Go to an application in Kiali, click in Traces Tab, click in `View in tracing`. The result should be something similar to: 

image

Click on a Trace, in the `Trace Details`, click in "View in Tracing". The result should be something similar to: 

image

Click in the `Span Details` tab, click in More Span Details, the result should be something similar to: 

image

(It redirects to the trace, as I don't see the spans are bookmarkable). 

Note: There is the assumption that if the provider is Tempo, grafana will be used as the Tempo UI

### CODE REVIEW

**Review by hhovsepy — COMMENTED** [review]
Tested, all three URLs are working fine.
Just one more place to fix the link in Graph page Service Trace details:
Screenshot from 2023-10-02 13-12-25

**Comment by josunect** [comment]
> Tested, all three URLs are working fine. Just one more place to fix the link in Graph page Service Trace details: Screenshot from 2023-10-02 13-12-25

Thank you, @hhovsepy ! Good catch!

**Review by jshaughn — COMMENTED** [review]
Perhaps unrelated but When I do trace overlay on the graph, I am getting a lot of disconnected but highlighted nodes.  Most edges are not being highlighted.

**Comment by josunect** [comment]
> Perhaps unrelated but When I do trace overlay on the graph, I am getting a lot of disconnected but highlighted nodes. Most edges are not being highlighted.

I will review, thanks @jshaughn .
I've just rebased.

**Comment by josunect** [comment]
> Perhaps unrelated but When I do trace overlay on the graph, I am getting a lot of disconnected but highlighted nodes. Most edges are not being highlighted.

I was able to reproduce it, but, as this is not related directly with this issue, I opened a new one: https://github.com/kiali/kiali/issues/6674

**Review by hhovsepy — APPROVED** [review]
The links in graph is also fixed, thanks.

**Pull request merged**
