### PR TITLE
Add No Labels checker for DR

### PR DESCRIPTION
**Pull request by lucasponce**
Needed for https://github.com/kiali/kiali/issues/3336

### CODE REVIEW

**Comment by xeviknal** [comment]
I think you might have a Subset in a DestinationRule which has no labels:

The istio.io doc says:

> One or more labels are typically required to identify the subset destination, however, when the corresponding DestinationRule represents a host that supports multiple SNI hosts (e.g., an egress gateway), a subset without labels may be meaningful. In this case a traffic policy with ClientTLSSettings can be used to identify a specific SNI host corresponding to the named subset.

I am not familiar with SNI scenario, and I am wondering if you might have a specific subset that just point to a host but with no different labels but different trafficPolicy. For instance,

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: destination-rule-reviews-test
spec:
  host: reviews
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
  - name: oultlierdetection
    trafficPolicy:
      outlierDetection:
        consecutiveErrors: 7
        interval: 5m
        baseEjectionTime: 15m
```

I don't know if that makes sense though.

**Comment by lucasponce** [comment]
> I don't know if that makes sense though.

One thing could be to move this to a warning, what do you think ?
It sounds very specific to me.

Perhaps we can put a warning and see how it goes.

**Comment by hhovsepy** [comment]
> Perhaps we can put a warning and see how it goes.

+1 on warning

**Review by xeviknal — APPROVED** [review]
LGTM!

**Review by xeviknal — APPROVED** [review]
LGTM

**Comment by xeviknal** [comment]
@lucasponce forgot to mention that this PR would need an update on the validation documentation page.

**Review by hhovsepy — APPROVED** [review]
Verified in a scope of UI PR.

**Comment by lucasponce** [comment]
> @lucasponce forgot to mention that this PR would need an update on the validation documentation page.

Right, I'm going to merge this one and prepare the doc's PR.

**Pull request merged**
