### PR TITLE
KIALI-918 Fix pod's "created by" field absent in recent k8s API

### PR DESCRIPTION
**Pull request by jotak**
It was deprecated and replaced with "OwnerReferences"

### CODE REVIEW

**Comment by lucasponce** [comment]
Shouldn't be this for Openshift 3.9 + Istio 0.8.0 ?
Then I guess it should go into the istio 0.8.0 branch, isn't it ?

Or we are going to setup OS 3.9 with Istio 0.7.1 ?

**Comment by aljesusg** [comment]
I think that this should go to master & istio 0.8.0 if it works with 0.8

**Comment by lucasponce** [comment]
> I think that this should go to master & istio 0.8.0 if it works with 0.8

If this PR works in OS 3.7.1 and OS 3.9, it can go on master and master will be rebased on istio-0.8.

But if not, it is necessary to clarify which version is compatible in master.

**Comment by jotak** [comment]
I wouldn't focus on master with OS 3.9 as it's meant to be replaced with istio-0.8 branch

**Pull request closed without merging**
