### PR TITLE
Fix prettier pre-commit hook

### LINKED ISSUE #5803: Prettier pre-commit hook is not working correctly
Although there is a prettier pre-commit hook, multiple lines of code are modified after executing manually "yarn prettier". This means that prettier pre-commit hook is not working correctly.

### PR DESCRIPTION
**Pull request by ferhoyos**
Fix #5803

### CODE REVIEW

**Review by aljesusg — APPROVED** [review]
LGFM tested and now precommit find changed files

**Comment by jshaughn** [comment]
@ferhoyos You should assign youself to the issue if you are going to do do work, so that nobody else duplicates what you are doing.  And it's best to have the issue on the sprint backlog before doing work.  And finally, you should assign youself to the PR as well, and also add that to the project so that everything shows up on the project board. Thanks.

**Comment by jmazzitelli** [comment]
I wondered why the precommit hook didn't take the many seconds it used to take :) 

This is probably going to cause alot of changes to the frontend/ files, right? We'll want to include those changes in either this PR or a separate one just for the reformatting.

**Comment by ferhoyos** [comment]
@jshaughn ok, I thought only maintainers could assign users to issues. I will do that next time.

**Comment by jshaughn** [comment]
> @jshaughn ok, I thought only maintainers could assign users to issues. I will do that next time.

Maybe you are right, I can't recall.  Just ping me or some other maintainer if you need it done.

**Pull request merged**
