### PR TITLE
Reworked some jaeger error handling and enabling workflow

### PR DESCRIPTION
**Pull request by jotak**
- "Integration" flag removed in favour or just the "enabled" user config. Kiali assumes Jaeger integration is always turned on as long as the user set it to "enabled" in config (which is the default)
- Because of that, some prior checks are not necessary anymore - so removing the "GetJaegerInfo" functions in business/client layers as it now just maps jaeger config to some info exposed for UI. The idea is that Kiali keeps trying to reach Jaeger when it's configured as enabled. Some mechanisms can be setup in the UI to avoid repeating popups.
- Also remove GetJaegerServices that is unused
- Fix issues with returned http code from client calls: some errors were silently ignored because the code was "0". Basically an http code resulting from client queries should not be reused as-is in Kiali UI-backend API. It must be caught in backend and eventually reinterpreted. Here, it's added to the error message.

UI PR: https://github.com/kiali/kiali-ui/pull/1645

Fixes https://github.com/kiali/kiali/issues/2187 and, I think, all the various points discussed in that ticket

### CODE REVIEW

**Comment by aljesusg** [comment]
So are we going to remove the "check integration" ? So the point is if user set this to enable so throw one time the error (in metrics/spans and in traces tab). If user disable the configuration but he has the url so kialis shows the links. Am I right @jotak ?

My concern is about the "traces tab" and the behaviour I'll comment in the PR. 

For example if there is no integration (we check this in errTraces errChan <- err2) the traces tab should be disable or a link to the external tracing I think. And again we have the problem that if this fail the serviceDetails fetch fail so I think taht we should have this fetch in another endpoint

**Comment by jotak** [comment]
> For example if there is no integration (we check this in errTraces errChan <- err2) the traces tab should be disable or a link to the external tracing I think.

Yes, I think this is still working as you say, no?

> And again we have the problem that if this fail the serviceDetails fetch fail so I think taht we should have this fetch in another endpoint

Either different endpoints or have the ServiceDetails endpoint able to not fail in this case (but still report an issue) .. i thought actually it was already done as we had the discussion previously, but I can do that

**Comment by aljesusg** [comment]
> > For example if there is no integration (we check this in errTraces errChan <- err2) the traces tab should be disable or a link to the external tracing I think.
> 
> Yes, I think this is still working as you say, no?
mmm I am not sure I need to check the UI PR that you sent, we can discuss this in the UI PR because is more related with the behaviour of the UI.
> 
> > And again we have the problem that if this fail the serviceDetails fetch fail so I think taht we should have this fetch in another endpoint
> 
> Either different endpoints or have the ServiceDetails endpoint able to not fail in this case (but still report an issue) .. i thought actually it was already done as we had the discussion previously, but I can do that

yes...this is why I requested a bj for talk about this . I agree about have another endpoint for this. Do you agree @lucasponce ?

**Comment by aljesusg** [comment]
Tested in minikube, with the UI I only see one "error message" but the traces tab is active and enable if we get some error, I think that we should merge this because fix some problems that we have but we should talk about what behaviour we want to have for this tab. What do you think @lucasponce @jotak ? 
Screenshot from 2020-02-03 12-49-29

**Pull request merged**
