### PR TITLE
KIALI-1754 Update documentation for v0.9.0

### PR DESCRIPTION
**Pull request by xeviknal**
** Describe the change **

I do find that we have swagger.json unsync'ed with what we have documented in the codebase.
We do need this merged before launching v0.9.0 or we will be inconsistent.

I see in the diff, that there are some endpoint additions and deletions. Can you reviewers make sure that is fully right?

** Issue reference **
https://issues.jboss.org/browse/KIALI-1754

### CODE REVIEW

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#203](https://paste.fedoraproject.org/paste/RGLTGYAmVDOpCTe45mvsnA)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1648]](https://paste.fedoraproject.org/paste/59LtvWmWXcVLSTx6ivFmBA)
  * :heavy_check_mark: Istio-Upstream [#[494]](https://paste.fedoraproject.org/paste/7pj96UW32jR~6PUDTL7CHg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1865, 1866]](https://paste.fedoraproject.org/paste/RHVtBH69FtCdkNzMHCTEIw)
  * :heavy_check_mark: install-bookinfo [#[1023]](https://paste.fedoraproject.org/paste/X3wCZTGnto16cLO7Jfm9rg)
  * :heavy_check_mark: Kiali-on-Openshift [#[1042]](https://paste.fedoraproject.org/paste/I-bQRtqP6420dgCFEBhQjQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[446]](https://paste.fedoraproject.org/paste/uHUYjDbQj5l4d6MLYg4aJA)


KIALI_NAME=kialicorepr569-istio-system

**Comment by lucasponce** [comment]
Review in progress.

**Comment by lucasponce** [comment]
- default: genericError should be moved to 400: StatusBadRequest error instead.
- Root, getStatus and GetToken only returns 200 and or 500. Swagger points to 404 and 400. 
- istioConfigList, serviceList, workloadList, appList doesn't return a 404 error. Only 200 and 500.
- serviceDetails, workloadDetails, appDetails doesn't return 400.
- workloadDetails and appDetails don't return 404 (this is something to fix, they should return also a 404 in the code).
- NamespaceList is missing in swagger doc
- serviceMetrics, getAppMetrics, getWorkloadMetrics returns also a 503 instead of 500
- getServiceValidation doesn't return a 404 (it should, this is something to fix in the code).
- NamespaceMetrics are not documented
- namespaceValidations doesn't return a 404 (it should, this is something to fix in the code).
- generateGraph, graphAppVersion, graphApp, graphService, graphWorkload doesn't return 404.
- GrafanaURL, JaegerURL are not documented

**Comment by xeviknal** [comment]
@lucasponce thank you for going one step further in the documentation revision. Comments approached.

**Comment by lucasponce** [comment]
@xeviknal Thanks, could you rebase ? I've just merge a PR from Alberto that also re-generated the swagger doc.

**Comment by xeviknal** [comment]
@lucasponce done!

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#210](https://paste.fedoraproject.org/paste/uciKpFGJT6VwI98RjZ2b~Q)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1660]](https://paste.fedoraproject.org/paste/phUVAVtpUZGCQtdbFPKzEA)
  * :heavy_check_mark: Istio-Upstream [#[505]](https://paste.fedoraproject.org/paste/fUnZLJJUy9~sVX1WtFuWoA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1891, 1892]](https://paste.fedoraproject.org/paste/DXPw2J329KdHV~lSMGIt-g)
  * :heavy_check_mark: install-bookinfo [#[1035]](https://paste.fedoraproject.org/paste/tEho0TpQjJSjs0Skv4CD-A)
  * :heavy_check_mark: Kiali-on-Openshift [#[1054]](https://paste.fedoraproject.org/paste/kQUDlgtFBLai5FdTENTlaw)
  * :heavy_check_mark: run-kiali-e2e-tests [#[460]](https://paste.fedoraproject.org/paste/RXFtzxH68ZOSsejJ2dTmbw)


KIALI_NAME=kialicorepr569-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#211](https://paste.fedoraproject.org/paste/6CdVDYdkhRQccY3x0E6H9Q)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1661]](https://paste.fedoraproject.org/paste/0~nR0A4a9jRU5bkeFNwYBw)
  * :heavy_check_mark: Istio-Upstream [#[506]](https://paste.fedoraproject.org/paste/ZKXAYwfaxz3gCVhKkfNPVA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1893, 1894]](https://paste.fedoraproject.org/paste/LvQhk-0s6esAUSIGE2r9WQ)
  * :heavy_check_mark: install-bookinfo [#[1036]](https://paste.fedoraproject.org/paste/O2WkMP8QIX2df681G0bLqQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[1055]](https://paste.fedoraproject.org/paste/onlewrkppcUIwDV0uloGRg)
  * :heavy_check_mark: run-kiali-e2e-tests [#[461]](https://paste.fedoraproject.org/paste/SbpnJUWS0tj4PIVK5QUP6g)


KIALI_NAME=kialicorepr569-istio-system

**Pull request merged**
