### PR TITLE
Fixed Istio Config links in App pages, Name/Namespace params swap.

### PR DESCRIPTION
**Pull request by hhovsepy**
Based on a conversation https://github.com/kiali/kiali/pull/4535#issuecomment-989830113

### CODE REVIEW

**Review by lucasponce — APPROVED** [review]
Minor fix but important.

image

**Comment by lucasponce** [comment]
@mattmahoneyrh this PR is minor but it may have some change in some UI test as the reference Istio objects were broken before.

**Review by skondkar — APPROVED** [review]
LGTM,
Verified manually the Istio Config links in details column on Applications/Workloads and Services list pages.
also verified with UI automation run and E2E tests.

**Comment by skondkar** [comment]
Polarion Test case ->> SWSQE-2174

**Pull request merged**
