### PR TITLE
[operator] move to 0.16 of the operator base image/operator-sdk

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes https://github.com/kiali/kiali/issues/2484

### CODE REVIEW

**Comment by jmazzitelli** [comment]
All molecule tests pass (well, I found some problems, but unrelated - I created PRs for those additional problems). But for the purposes of this PR, this new base image doesn't appear to cause any issues so we can merge this.

**Comment by FilipB** [comment]
kialiqeci

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Comment by FilipB** [comment]
kialiqeci

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1082](https://paste.centos.org/view/89ca8ef4 )
  * :heavy_check_mark: run-kiali-e2e-tests [#[744]](https://paste.centos.org/view/ed41442a )

**Pull request merged**
