### PR TITLE
Fix port number and add unique identifiers for in some wizards

### LINKED ISSUE #5834: Duplicate IDs for the text inputs + high port value breaks the UI (Istio Config wizard page)
Some things I noticed while I was working today on the #5811 issue.

On the wizard page for ServiceEntry, I wanted to do a test on a 2 port specification with a same port name on the Istio Config wizard page. The issue here is that when multiple port specifications are present, the IDs in the HTML code for the text inputs and selects of the same category are identical. 
image

On the wizard page for the Gateway, a port number little higher than 65535 will break the UI.
image

### PR DESCRIPTION
**Pull request by josunect**
Fixes #5834 

- Use constant for MAX and MIN port numbers
- Use unique identifiers by row in form wizards
- Fix React warning

### CODE REVIEW

**Comment by hhovsepy** [comment]
It seems ServiceEntryForm.tsx also needs the constant MAX_PORT to be consistent:

**Review by hhovsepy — APPROVED** [review]
Verified now.

**Comment by josunect** [comment]
> Verified now.

Thanks for your review, @hhovsepy !

**Review by hhovsepy — APPROVED** [review]

**Comment by matejnesuta** [comment]
LGTM

**Pull request merged**
