### PR TITLE
explicitly declare support for HTTP2

### PR DESCRIPTION
**Pull request by jmazzitelli**
see: https://issues.redhat.com/browse/OSSM-3438

### CODE REVIEW

**Comment by jmazzitelli** [comment]
It isn't clear to me if the way we setup the Go net/http server inside Kiali has HTTP2 enabled by default. This PR will avoid the ambiguity and add code to explicitly declare both HTTP2 and HTTP1.1 is supported.

I still haven't been able to actually talk to Kiali over HTTP2 :) but according to the docs, this should be ensuring HTTP2 is enabled.

**Comment by hhovsepy** [comment]
Still the original error message is in logs
Screenshot from 2023-02-21 11-26-39

**Comment by jmazzitelli** [comment]
notice the messages appears 5 second apart... smells like a health check (which would be expected).

**Comment by jmazzitelli** [comment]
I can confirm that Kiali supports HTTP 2.0 with this PR. Here's how to quickly test:

1. Start Minikube, install Istio: `hack/k8s-minikube.sh start && hack/k8s-minikube istio`
2. Build and install Kiali so it has this PR: `make -e CLUSTER_TYPE=minikube build build-ui cluster-push operator-create kiali-create`
3. Use `curl` to send a http2 request into the Kiali UI and confirm HTTP 2.0 is used:
```
$ curl -kv --http2 "https://$(minikube ip)/kiali/api"
```

should return something like this (important: see the first line of the response `HTTP/2 200` - that indicates the server replied with an HTTP 2 protocol response).

```
...
* Connected to 192.168.59.254 (192.168.59.254) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
...
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
...
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
...
> GET /kiali/api HTTP/2
> Host: 192.168.59.254
> User-Agent: curl/7.61.1
> Accept: */*
> 
...
< HTTP/2 200 
< date: Tue, 21 Feb 2023 19:57:42 GMT
< content-type: application/json
< content-length: 671
< vary: Accept-Encoding
< 
{
  "status": {
    "Kiali commit hash": "9600262ce1f739ed46fb96b6a619afc1059fc411",
    "Kiali container version": "v1.64.0-SNAPSHOT",
...
```

**Comment by jmazzitelli** [comment]
I'm taking this out of draft, ready for review.

**Comment by jmazzitelli** [comment]
Note - if you can't get this to work, it likely means the client is not sending an HTTP 2 request or the server-side environment is not able to support passing through HTTP 2 traffic to the Kiali app. But that is not the concern of this PR - this PR is to ensure the Kiali server itself is able to explicitly declare it supports HTTP 2 and that it can actually participate in the HTTP 2 protocol. My test procedures above will show that Kiali itself does support HTTP 2.

**Comment by jmazzitelli** [comment]
(and, frankly, I'm not even sure this PR is required in order for HTTP 2 to be supported. However, I think it is best to explicitly declare HTTP2 support rather than rely on some Go default behavior, since it isn't guaranteed that this behavior won't change in the future.)

**Comment by jmazzitelli** [comment]
Here's a better way to test this.. this is on OpenShift.

1. Deploy an OpenShift cluster and install Istio
2. Checkout this PR, but also make another change - change the base image to `ubi8-minimal` (this is so the kiali pod can have `curl`):
```diff
diff --git a/deploy/docker/Dockerfile-distroless b/deploy/docker/Dockerfile-distroless
index 78b96774b..017c0162a 100644
--- a/deploy/docker/Dockerfile-distroless
+++ b/deploy/docker/Dockerfile-distroless
@@ -1,5 +1,5 @@
 FROM registry.access.redhat.com/ubi8/openssl as ca-certs-source
-FROM registry.access.redhat.com/ubi8-micro
+FROM registry.access.redhat.com/ubi8-minimal
 
 LABEL maintainer="kiali-dev@googlegroups.com"
```
3. Build and deploy Kiali via `make build build-ui cluster-push operator-create kiali-create`
4. Run bash within the Kiali pod: `kubectl exec -n istio-system --stdin --tty deploy/kiali -- bash`
5. From within the Kiali pod, curl to itself making sure you send an HTTP2 request over https: `curl -kv --http2 https://localhost:20001/api`. You should see this (notice HTTP2 protocol being used):
```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 20001 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=kiali.istio-system.svc
*  start date: Feb 21 20:48:13 2023 GMT
*  expire date: Feb 20 20:48:14 2025 GMT
*  issuer: CN=openshift-service-serving-signer@1673451569
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.3 (OUT), TLS app data, [no content] (0):
* TLSv1.3 (OUT), TLS app data, [no content] (0):
* TLSv1.3 (OUT), TLS app data, [no content] (0):
* Using Stream ID: 1 (easy handle 0x565089e3e9c0)
* TLSv1.3 (OUT), TLS app data, [no content] (0):
> GET /api HTTP/2
> Host: localhost:20001
> User-Agent: curl/7.61.1
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS app data, [no content] (0):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
* TLSv1.3 (OUT), TLS app data, [no content] (0):
* TLSv1.3 (IN), TLS app data, [no content] (0):
* TLSv1.3 (IN), TLS app data, [no content] (0):
* TLSv1.3 (IN), TLS app data, [no content] (0):
< HTTP/2 200 
< content-type: application/json
< vary: Accept-Encoding
< content-length: 919
< date: Tue, 21 Feb 2023 20:58:43 GMT
< 
* TLSv1.3 (IN), TLS app data, [no content] (0):
{
  "status": {
    "Kiali commit hash": "9600262ce1f739ed46fb96b6a619afc1059fc411",
    "Kiali container version": "v1.64.0-SNAPSHOT",
    "Kiali state": "running",
    "Kiali version": "v1.64.0-SNAPSHOT",
    "Mesh name": "OpenShift Service Mesh",
    "Mesh version": "2.3.1"
  },
  "externalServices": [
    {
      "name": "OpenShift Service Mesh",
      "version": "2.3.1"
    },
    {
      "name": "Prometheus",
      "version": "2.23.0"
    },
    {
      "name": "Kubernetes",
      "version": "v1.24.6+5658434"
    },
    {
      "name": "Grafana",
      "url": "https://grafana-istio-system.router-default.apps.jmazziteos4.lab.upshift.rdu2.redhat.com"
    },
    {
      "name": "Jaeger",
      "url": "https://jaeger-istio-system.router-default.apps.jmazziteos4.lab.upshift.rdu2.redhat.com"
    }
  ],
  "warningMessages": [],
  "istioEnvironment": {
    "isMaistra": true,
    "istioAPIEnabled": true
  }
```

**Comment by jmazzitelli** [comment]
And for the record, I ran this test on OpenShift using the master branch (i.e. without this PR) ... and it is still using HTTP 2. So, in the end, it looks like the Go default behavior is in use inside Kiali (which is to use HTTP2 when possible). So technically it doesn't appear this PR is needed. I still think it isn't a bad thing, since it means we'll explicitly declare "h2" as well as "http/1.1" support. But if the Kiali team opts not to merge this PR to avoid churn, that's OK, too.

**Comment by jmazzitelli** [comment]
I also ran a quick test on Kiali v1.57 and it, also, supports HTTP2.

**Comment by hhovsepy** [comment]
The error messages are harmless and  typically a health check TCP connection. https://access.redhat.com/solutions/6999058

**Review by hhovsepy — APPROVED** [review]
lgtm

**Pull request merged**
