### PR TITLE
[1.57] Upgrade go to 1.20

### PR DESCRIPTION
**Pull request by aljesusg**
Fix https://github.com/kiali/kiali/issues/6218

I just remembered all the lints that had to be fixed...

### CODE REVIEW

**Comment by aljesusg** [comment]
Why don't tests run on these branches?

**Comment by jmazzitelli** [comment]
> Why don't tests run on these branches?

Change the `branches` setting in `kiali-ci.yml` -- lines 6 and 12 here:

https://github.com/kiali/kiali/blob/master/.github/workflows/kiali-ci.yml

I think those regexes are bad (see the github docs on this [here](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-filters-to-target-specific-branches-or-tags-for-push-events)).

I would try this:

```
    branches:
    - master
    - v*.*
```

**Comment by jmazzitelli** [comment]
@aljesusg rebase this PR on the latest branch and the tests should now run

**Comment by jmazzitelli** [comment]
@aljesusg Do you think this is OK to merge?

**Comment by aljesusg** [comment]
Do we want to add the go-restful too?

**Comment by jmazzitelli** [comment]
> Do we want to add the go-restful too?

Since this is for OSSM 2.3, it might be a good idea to also add go-restful update, too. So I would say `yes`.

**Comment by jmazzitelli** [comment]
@jshaughn what do you think?

**Review by jshaughn — APPROVED** [review]
@jmazzitelli , I think we can merge this.  The CI failure is due to a problem in the CI config (see https://github.com/kiali/kiali/pull/6282 for the solution to that problem).  I don't think we need to backport the go-restful update as there is no formal issue.

**Comment by jmazzitelli** [comment]
the backend int. tests pass, the front end can't start for some reason. Looks like a CI issue. I think this is mergeable

**Pull request merged**
