### PR TITLE
update patternfly-react and other dependencies

### PR DESCRIPTION
**Pull request by jshaughn**
Closes https://github.com/kiali/kiali/issues/4836

This PR looks to update dependencies to be more in-line with OpenShift Console, help with security violations, and where possible remove unnecessary styling.  It is not intended to leave things looking *exactly* the same, but differences should be reasonable.

### CODE REVIEW

**Comment by lucasponce** [comment]
I fetched locally and I can have first feedback: a lot of styles broken as expected, but fewer things broken than I thought :).
So we need to work, but I think it's approachable with reasonable tradeoffs.

But yes, some styles are broken badly.

Thanks for the work, I'll add more feedback with more details as soon as I find issues.

**Comment by ScriptingShrimp** [comment]
That is major update. @pbajjuri20 I'm wondering if we can execute current selenium suite against this draft PR, to have an idea what is affected. 
If the UI regression test will have a lot of failures, we might prioritize them in migration to Cypress.

**Comment by lucasponce** [comment]
@pavolloffay @pbajjuri20 I'd wait to start any testing exploration on this PR until it progressed.
It's still a draft and it will have more changes, especially affecting styles.

**Comment by pavolloffay** [comment]
@lucasponce I am not sure what should I be looking at in this PR? Could you please clarify?

**Comment by lucasponce** [comment]
Sorry @pavolloffay ! My bad the cc was for Pavel alias cc @ScriptingShrimp !

**Comment by pbajjuri20** [comment]
> That is major update. @pbajjuri20 I'm wondering if we can execute current selenium suite against this draft PR, to have an idea what is affected. If the UI regression test will have a lot of failures, we might prioritize them in migration to Cypress.

@ScriptingShrimp : will look about this

**Comment by jshaughn** [comment]
@pbajjuri20 @ScriptingShrimp , no problem to be aware of this effort but this is still a draft PR, no need to take any action right now.  we will evaluate how we want to proceed here and keep you up to date.

**Pull request closed without merging**
