### PR TITLE
KIALI-1627 Prevent failure when no virtual services presented

### PR DESCRIPTION
**Pull request by xeviknal**
** Describe the change **
Fixing failures of E2E tests.

** Issue reference **
https://issues.jboss.org/browse/KIALI-1627

** Backwards incompatible? **
Yes.

### CODE REVIEW

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Comment by xeviknal** [comment]
kialiqeci

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Comment by xeviknal** [comment]
First failed assertion fixed: checked that service_details has virtualServices before asking for its length.
```python
test_kiali_service_endpoint.py::test_service_detail_with_virtual_service
if service_details != None and len (service_details.get('virtualServices')) > 0:
TypeError: object of type 'NoneType' has no len()
```

Second failed assertion: 
```python
 test_kiali_service_endpoint.py::test_service_detail_with_destination_rule()
> assert destination_rule.get('name') == 'reviews'
AssertionError: assert 'circuitbreak...eviews-all-cb' == 'reviews'
```
This failure is caused due to a deleting failure in previous test. Specifically, the failure comes from `test_kiali_service_endpoint.py::test_kiali_circuit_breakers_workload`. We might have a silent failure at that point. Therefore, it might cause the impression that `test_kiali_service_endpoint.py::test_service_detail_with_virtual_service` and `test_kiali_service_endpoint.py::test_service_detail_with_destination_rule` are the actual problems.

I see one jenkins run with problems: http://jenkins2.bc.jonqe.lab.eng.bos.redhat.com:8080/job/run-kiali-e2e-tests/233/console
In that run, we have a timeout in `test_kiali_circuit_breakers_versioned_app` which leave the system in different state as before starting the run.

Checking some other jenkins runs:
screenshot of run-kiali-e2e-tests jenkins
The next ones are the failing ones:
[#230](http://jenkins2.bc.jonqe.lab.eng.bos.redhat.com:8080/job/run-kiali-e2e-tests/230/console)
[#231](http://jenkins2.bc.jonqe.lab.eng.bos.redhat.com:8080/job/run-kiali-e2e-tests/231/console)
[#232](http://jenkins2.bc.jonqe.lab.eng.bos.redhat.com:8080/job/run-kiali-e2e-tests/232/console)
[#233](http://jenkins2.bc.jonqe.lab.eng.bos.redhat.com:8080/job/run-kiali-e2e-tests/232/console)

First of all, 230 and 231 looks like they have outdated test suite: only 2 test files and 17 tests instead of  7 files and 27 tests we have in master. Date: September, 27th.

In second place, we have both of the runs have a failed assertion. Which it means that the test finishes before the expected and then it won't perform the destination rule deletion, therefore it leave the environment polluted.

In third place, in the run 232 we have a failure assertion because the test `test_service_detail_with_destination_rule` doesn't expect to have a destination rule already existing.

So, after this, I propose to have a tear_down method that erases all the assets in the project after each session. This way, each suite run will start clean and fresh.

**Comment by xeviknal** [comment]
cc/ @mattmahoneyrh

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Comment by xeviknal** [comment]
Two changes finally applied:

1. All methods that apply a oc yaml, now has its deletion in a finally statement. This way, all the failure assertions won't skip it and will leave the environment clean.

2. I added a tear_down method which apply a `oc delete -f asset/rule-n.yaml -n bookinfo` for each asset in `assets` folder. Ensuring that at the end of each suite run, all the configs will be removed.
However, the output of this tear_down is not fancy.

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#116](https://paste.fedoraproject.org/paste/2l1NO680RZ8Zs3GjNg7H5w)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1431]](https://paste.fedoraproject.org/paste/NmBG37nf-GCWPRaS-uFl-w)
  * :heavy_check_mark: Istio-Upstream [#[302]](https://paste.fedoraproject.org/paste/vyNcTMMUqi--HfOmfgg3fw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1409, 1410]](https://paste.fedoraproject.org/paste/0fSbwStDpIUS7Ob4OQDFQw)
  * :heavy_check_mark: install-bookinfo [#[798]](https://paste.fedoraproject.org/paste/svZGsW3gMVsPX-UYVLT8-w)
  * :heavy_check_mark: Kiali-on-Openshift [#[796]](https://paste.fedoraproject.org/paste/ft79Hud-8S76aThnXhoueA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[240]](https://paste.fedoraproject.org/paste/ifuHBuZlo8ZKlskfoF546A)


KIALI_NAME=kialicorepr525-istio-system

**Pull request merged**
