### PR TITLE
Fix overview services health showing inexisting services

### PR DESCRIPTION
**Pull request by jotak**
It was adding services based on istio metrics in addition to the ones strictly resulting from k8s api

Fixes https://github.com/kiali/kiali/issues/2772

### CODE REVIEW

**Comment by jotak** [comment]
I started to fix that right away, but actually, perhaps it needs a little bit of discussion before merging.
Here, we're showing health of services within a namespace. At a first glance, only "real" services should be counted, the ones that actually refer to a k8s object.

BUT if we don't show health related to istio's "special" services, such as passthrough/blackhole clusters, then we're going to hide potentially unhealthy things.

What's the best thing to do according to you? cc @lucasponce @jshaughn ...

**Comment by jotak** [comment]
perhaps the right thing to do would be to ignore them unless they're unhealthy

**Comment by jshaughn** [comment]
@jotak Passthrough and BlackHole are not really services but sort of request handlers.  As entities themselves I'd ignore them.    As an indicator of health, anything going to BlackHole is likely a problem, but those requests will already return with a failure status.

**Comment by jotak** [comment]
@jshaughn yes, but then in that particular view (namespaces, service-based health) we would see everything fine because we're only looking at heath of services. We would have to switch to app/workload-based health to see the errors.

Actually I start wondering if having a service-based health in overview makes any sense at all to be honest.

**Comment by jshaughn** [comment]
@jotak   Service health is a little hard to define, I guess it comes down to the success rate of requests for that destination service.  But only for destination services that have an explicit k8s service defined.  I don't think health applies to every "terminal node" that shows up in the graph, which is to say that I don't think every request maps to the health of some service.  Long way of saying that I think the initial fix is the right one.  The removal of service health itself is probably overkill.

**Comment by jotak** [comment]
I'll merge this change, but I still think we could simplify this overview page a little bit. What I think people expect from an overview is something that offers a complete overview from a single place, and not having some particularities depending on the angle of view that we're taking.

**Comment by jotak** [comment]
PS @jshaughn while you're here could you review? It's a small one :-)

**Comment by jotak** [comment]
Thanks!

**Pull request merged**
