### PR TITLE
Add references to IstioValidation type and validators

### PR DESCRIPTION
**Pull request by burmanm**
** Describe the change **

As described in the issue #1419, certain resources are causing each other validation errors. This change adds links to those other objects which could have caused the validation issue to each other (since we don't know which one the user has incorrectly defined).

This PR includes only a sample for multimatch gateway validations, nothing else so far. Waiting for input first.

Also makes the logic in multi_match_checker a little more sane (instead of relying only on the duplicate removal).

** Issue reference **

Closes issue #1419 

** Backwards incompatible? **

Yes. If we want to take advantage of the feature in the UI, then UI will require changes.

### CODE REVIEW

**Comment by lucasponce** [comment]
I've added the do not merge and UI frontend changes required.
But if this PR can be consolidated in backend without impact UI, then please, don't hesitate to update them.

Thanks !

**Comment by burmanm** [comment]
Removal of labels meant that this should be ready for review and does not need frontend changes (it does not break current frontend)

**Comment by hhovsepy** [comment]
As discussed in a chat, the namespace adding can cause problems, as it requires much more changes and is out of scope.

**Comment by hhovsepy** [comment]
It seems "More than one virtual service for same host" validation is gone. I can not see that by the same steps before.

**Comment by burmanm** [comment]
Can you list your steps? It worked for me (so might be something related to input material / key creation)

**Comment by hhovsepy** [comment]
Screenshot from 2019-09-30 09-39-11
Screenshot from 2019-09-30 09-41-46

**Comment by xeviknal** [comment]
@burmanm I know it is one more thing to take care of but it looks like you need to re-build the swagger files. If you want me to do it, I can take this PR from now on, no probs.
I'll do the review today or perhaps Monday, I want to make sure I understand all the changes.
Thanks for the patience on this one.

**Pull request merged**
