### PR TITLE
Filter traces by cluster, show warning otherwise

### PR DESCRIPTION
**Pull request by hhovsepy**
Issue https://github.com/kiali/kiali/issues/6710

Follow up after discussion on https://github.com/kiali/kiali/pull/6749

In a multi-cluster primary-remote mode, when Jaeger is configured to have Cluster ID [(Multi-cluster Setup)](https://kiali.io/docs/configuration/multi-cluster/#setup) and the Istio installation includes the [workaround for Telemetry setup](https://github.com/istio/istio/issues/35750#issuecomment-1165988761).
The Jaeger traces are including a `cluster` tag.
As in the multi-cluster env, the Tracing service supposed to be setup at once and during the installation, then it will be configured to support traces per cluster. This is the expected behavior, otherwise all Traces will be duplicated per service name which exists in all clusters.

What is done: 
In Multi-cluster mode, the Traces are first filtered by the `cluster` tag. This is the expected behavior.
However if no traces are found for particular cluster, then all traces are loaded and a warning message is shown to user saying that 'Loading traces for all clusters. Tracing is not configured to store traces per cluster.'. This is a sign to user to setup Jaeger to support traces per cluster.

Screenshot from 2023-10-31 18-30-00

Currently done for the Jaeger only.

### CODE REVIEW

**Review by josunect — COMMENTED** [review]
It works as expected: 

When the cluster is included: 

image

But, I'm not able to see traces from the remote cluster: 
image

There are no tags. Maybe this is some issue related to my configuration. 

When the cluster tag is not included: 

image

I think we should create a follow up task to include the same behavior for Tempo.

**Review by josunect — APPROVED** [review]
Tested and LGTM. Thank you, @hhovsepy !

I think we should create a follow up task to include the same behavior for Tempo.

**Review by leandroberetta — APPROVED** [review]
Looks good!, I like the implementation. Thanks @hhovsepy !

**Comment by hhovsepy** [comment]
Thank you @josunect and @leandroberetta , have added 2 checkboxes for https://github.com/kiali/kiali/issues/6710, second for Tempo.

**Pull request merged**
