### PR TITLE
[mesh page] [graph] Fix issue with laying out on an element change

### PR DESCRIPTION
**Pull request by jshaughn**
Fix issue with laying out on an element change in both the traffic graph and the mesh page.

Also, fix a resize issue for mesh page.

Fixes https://github.com/kiali/kiali/issues/7835

To test:
- try the repro steps in the issue.  
- for the resize issue on the mesh page, try collapse and expand of the side panel
- also try resizing, graph hide/unhide (refresh with hide), eliminating/adding things via the Traffic dropdown, refreshing when you have changed the default layout (like zooming in/out, dragging etc) and make sure your custom view is maintained (unless there is an element change).

### CODE REVIEW

**Comment by nrfox** [comment]
This fixes the problem for the mesh page but it looks like the graph page still doesn't adjust the layout when a new node is added:
layout

**Comment by jmazzitelli** [comment]
I don't know how this happened but --- an edge going to nowhere out of productpage:
image

**Comment by jmazzitelli** [comment]
Crazy edge going to and from nowhere - I click it but the sidepanel has no indication of what its for
image

**Comment by jmazzitelli** [comment]
Finally, set hide and find expressions (I used this:)
image

Zoom in or out, hit refresh - that works fine - the zoom level stays.
But move some of the nodes and boxes around for a custom layout, hit refresh - the graph snaps back to the way it was originally. From the description of this PR, it seems like that should not happen.

**Comment by jshaughn** [comment]
I have not seen that sort of weird edge behavior on hide. That would be independent of this PR, I think.  Not sure how you'd get a ghost edge.  

Anyway, your other thing, the snap back on "node drag with hide" was a good find.  This code is so tricky to get right.  But, I think I have it fixed.  I pushed the changes.  Also, as part of this I fixed the mesh page label issue you mentioned (the clipped labels and the hard to read badges in dark mode).  That's also pushed.

**Review by jmazzitelli — APPROVED** [review]
I'm going to approve this now. I didn't re-test since the latest commit, but it isn't going to be made worse, so let's get this in the release now if possible. If we miss the release with this PR, we can get this in for the 2.1 release.

**Pull request merged**
