### PR TITLE
Bump go version and istio/kube api versions

### PR DESCRIPTION
**Pull request by nrfox**
### Describe the change

Bumps versions of go and istio/kube APIs to the latest Kiali supports.

### Steps to test the PR

Regression testing.

### Automation testing

N/A

### CODE REVIEW

**Comment by jshaughn** [comment]
@nrfox Looks like Linter issues...

**Comment by nrfox** [comment]
> @nrfox Looks like Linter issues...

I probably need to update the version of go in CI

**Review by jshaughn — DISMISSED** [review]
This looks fine to me.  I'm not sure whether this will be a problem for downstream builds, but if so we'll deal with that when it happens.

**Comment by aljesusg** [comment]
Well let me check if have available in downstream

**Comment by aljesusg** [comment]
We have until 1.21 I am goong to request 1.22

**Comment by jshaughn** [comment]
@aljesusg Where do you look to check what we have available?

**Comment by aljesusg** [comment]
I saw a 1.22.1 version I AM GOING TO REQUEST 1.22.2

**Comment by nrfox** [comment]
> I saw a 1.22.1 version I AM GOING TO REQUEST 1.22.2

1.22.1 works too. I'll just adjust the version in this PR.

**Review by jshaughn — APPROVED** [review]
Also good.  We may get 1.22.2 anyway, since I think Alberto already requested it.  It seems the way we can tell what is available is to look at the golang packages that have been built in brew: https://brewweb.engineering.redhat.com/brew/packageinfo?packageID=70135

**Pull request merged**
