### PR TITLE
Move version check message to the About dialog

### LINKED ISSUE #5457: Move Kiali<->Istio version checks to the "About" dialog
We, yet again, screwed up the compatibility matrix for the latest release. Someone installed 1.56.1 on Istio 1.14 (which should work) but got a warning in the UI.

I call for a vote. We need to do one of two things:

1. Get serious about the compat. matrix in the code (and by serious, I suggest we automate updating the compat matrix file in the code during the build/release CI workflow)

or 

2. Get rid of it.

Right now, it isn't working. It is a maintenance headache to get right. Everytime Istio or kiali does a release, it screws up. No one is taking the lead on making sure it is correct/testing it.

### PR DESCRIPTION
**Pull request by israel-hdez**
image

Fixes #5457

### CODE REVIEW

**Review by aljesusg — APPROVED** [review]
LGFM

**Review by Xunzhuo — COMMENTED** [review]
Looks like a CI job failed, other than that, LGTM.

**Review by jmazzitelli — COMMENTED** [review]
I am trying to test on OpenShift 4.11 and I see this in the logs:
```
2022-09-22T10:12:13Z WRN failed to get mesh version, please check if url_service_version is configured correctly.
```
Which normally was OK before, but the pod is failing to start with:
```
Readiness probe failed: Get "https://10.128.0.177:20001/healthz": dial tcp 10.128.0.177:20001: connect: connection refused
Liveness probe failed: Get "https://10.128.0.177:20001/healthz": dial tcp 10.128.0.177:20001: connect: connection refused
```
Since this PR only affected the UI, I don't see how this PR could cause this. But I'm tracking this down. I want to see what this looks like when running in OSSM environment.

_UPDATE: found the issues with this - not related to this PR. When I get those issues corrected, I'll re-test_

**Comment by jmazzitelli** [comment]
works:
image

**Comment by israel-hdez** [comment]
CI passing after 2nd run. Merging.

Thanks for the proactive reviews!

**Pull request merged**
