### PR TITLE
KIALI-2349 Thorntail dashboard

### PR DESCRIPTION
**Pull request by jotak**
JIRA https://issues.jboss.org/browse/KIALI-2349

### CODE REVIEW

**Comment by jotak** [comment]
Testers: a Thorntail sample app with metrics enabled is available here: https://github.com/jotak/mesh-microprofile-2018

Steps do deploy provided in project's readme.
As always, you need to deploy the dashboards too (from kiali sources) :
```
oc apply -f deploy/dashboards
```

**Comment by jotak** [comment]
@hhovsepy I've updated the sample app to allow prometheus fetch on http non secure

**Comment by hhovsepy** [comment]
Verified:
screenshot from 2019-02-18 12-54-33

**Comment by jotak** [comment]
Removing DNM, I think it can be merged, if TT people ask later to change something in the dashboard we can still do it later.

**Pull request merged**
