### PR TITLE
KIALI-2655 kiali operator using the ansible operator framework

### PR DESCRIPTION
**Pull request by jmazzitelli**
** Describe the change **

Introduces a new Kiali operator that is used to install Kiali instances.

** Issue reference **
 
https://issues.jboss.org/browse/KIALI-2655

** Documentation **

This is going to need some substantial documentation changes and additions.

### CODE REVIEW

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#779](https://paste.fedoraproject.org/paste/DLHU94oG-~U33cMx-vf7UA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1589]](https://paste.fedoraproject.org/paste/un1Le-EYwBav-ix1GfNvMQ)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#778](https://paste.fedoraproject.org/paste/8t8VFZowz5uewcAi2VyBmQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1591]](https://paste.fedoraproject.org/paste/RoA964C0byHoZLXfCgiXkA)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#780](https://paste.fedoraproject.org/paste/LxTVb3qSxIJnsnwg15dmmg)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1592]](https://paste.fedoraproject.org/paste/GwUMlNYpDOUFOfAc4egpWw)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#783](https://paste.fedoraproject.org/paste/YXTZpejz33yNbPNOvdTmqA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1593]](https://paste.fedoraproject.org/paste/Durs79lgNFcOfrAixHjh5Q)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#784](https://paste.fedoraproject.org/paste/AgvdUdgNeEH3faMDR7cxDA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1594]](https://paste.fedoraproject.org/paste/Uklfc4NfLhWqLquHTsKzYA)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#782](https://paste.fedoraproject.org/paste/wB2jattoKrSHwuoo-KZCoQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1595]](https://paste.fedoraproject.org/paste/LGOL2zCN7wGQBMCHjNgqQA)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#785](https://paste.fedoraproject.org/paste/318VBzHvJZsYdPYT-xOJkw)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1596]](https://paste.fedoraproject.org/paste/Qz6tG7mQrvLuCAhFd0vkSw)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#796](https://paste.fedoraproject.org/paste/pB4KQKlcPcm1VbcdCsECoA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1607]](https://paste.fedoraproject.org/paste/~jFfP1ScVjiR7PciP95PYg)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#797](https://paste.fedoraproject.org/paste/dcFaFpYpKsMxFt~MIVDz4g)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1609]](https://paste.fedoraproject.org/paste/WjXSl5hvnkB7LCgCZb0AUA)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#798](https://paste.fedoraproject.org/paste/ydKaz6diBDUl6R-RQCJAAA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1612]](https://paste.fedoraproject.org/paste/ss32K9zHKfF6mNTVkuku6A)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#799](https://paste.fedoraproject.org/paste/07IuBvHrawW5VzAfKSWQ9w)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1613]](https://paste.fedoraproject.org/paste/0fn50z1Cpc8kRQbJXfr9EA)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#800](https://paste.fedoraproject.org/paste/N7b039RkVauzwIzb55esqw)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1614]](https://paste.fedoraproject.org/paste/2qnmb1eanVT0OuQTR2KBOQ)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#801](https://paste.fedoraproject.org/paste/S151cZywDEpmyzbTc9JBnA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1615]](https://paste.fedoraproject.org/paste/rRqLihKefkve2HWLp3TuPQ)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#802](https://paste.fedoraproject.org/paste/YmhjmM8pEBc0OQJTlVrucQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1616]](https://paste.fedoraproject.org/paste/ebSRmx2CunQaOrHYh4ul3g)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#803](https://paste.fedoraproject.org/paste/t7fkUJjw3tGq~ET2~pcrrQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1617]](https://paste.fedoraproject.org/paste/1V8lPCFie5s~KbHIDXSZBg)

**Comment by jmazzitelli** [comment]
This is working pretty good now. The only issue left that I can't figure out is if I use auth-strategy = login, it seems the pod refuses to start because it can't find the service account, but i see the service account get created by ansible. however, when i look, the service account is missing. this only happens sometimes, and i never see it happen when i run the ansible playbook locally, so i know my ansible tasks are correct.

**Comment by jmazzitelli** [comment]
another thing was the finalizer stuff - I tried adding that, but it hung openshift really bad when trying to delete the CRD. It hung from what I could see indefinitely. I had to go into the CRD and remove the finalizer attribute, re-apply and then it would delete. Very weird.

Also, if you delete the kiali CR, the operator does delete all kiali resources EXCEPT the OAuthClient resource - i do not know why. But the way you are supposed to uninstall kiali is simply edit the kiali CR and change state to "absent" - this will correctly uninstall everything (including that OAuthClient resource).

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#804](https://paste.fedoraproject.org/paste/UO1DYRjkL0rcLMbvLsdGTQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1619]](https://paste.fedoraproject.org/paste/g5W01kqHTY~M2dFL2ZKY9Q)

**Comment by gbaufake** [comment]
> another thing was the finalizer stuff - I tried adding that, but it hung openshift really bad when trying to delete the CRD. It hung from what I could see indefinitely. I had to go into the CRD and remove the finalizer attribute, re-apply and then it would delete. Very weird. Might be related to this - this at least told me how to workaround the hang and get my resource to delete: [kubernetes/kubernetes#64002 (comment)](https://github.com/kubernetes/kubernetes/issues/64002#issuecomment-462288482)
> 
> Also, if you delete the kiali CR, the operator does delete all kiali resources EXCEPT the OAuthClient resource - i do not know why. But the way you are supposed to uninstall kiali is simply edit the kiali CR and change state to "absent" - this will correctly uninstall everything (including that OAuthClient resource).

I think the best way to delete is by removing the CR, since you want that resource to modified on your cr files somehow.

**Comment by jmazzitelli** [comment]
> I think the best way to delete is by removing the CR, since you want that resource to modified on your cr files somehow.

Right - but then I get the bug where the oauth isn't deleted. Something isn't right with the ability of the ansible operator to purge everything when the CR is removed. I don't know if its a bug in the framework or the kiali tasks - but I am pretty sure I saw "state=present" being set when the CR is removed - which isn't right. Still need to research that problem.

But at least we still have the feature of setting "state=absent" and the delete works fine.

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#805](https://paste.fedoraproject.org/paste/F08N9MtzzzVJpm71-bNZpA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1620]](https://paste.fedoraproject.org/paste/IY5ntMSvq8nFI2ILPiQflQ)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#806](https://paste.fedoraproject.org/paste/~Ees8N40bue-Xmg~8~iVPA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1621]](https://paste.fedoraproject.org/paste/3wGPjRcpYar5tCyXElCDDg)

**Comment by gbaufake** [comment]
I think these lines https://github.com/kiali/kiali/blob/e38853fa17af84f5587e00e87572a6c3e8e5c8f7/operator/roles/kiali/tasks/process-resource.yml#L12-L21

should be moved to different role

**Comment by jmazzitelli** [comment]
I fixed a small bug in remove-pod.yaml and that fixes the hanging issue I had with the finalizer. Finalizer is put back in. The state var is still used, but is not user-facing. To uninstall kiali, you just "oc delete" the kiali CR. This solves all the issues related to https://github.com/kiali/kiali/pull/967#issuecomment-479550874

Summary of the problem: when the ansible script fails to complete successfully, the ansible operator will NOT remove the "finalizer" tag in the CR. And you can't delete a resource with a non-empty finalizer list. So that's where my hanging came from. And because I didn't have the finalizer setting the state to absent (because I took out the finalizer because it was hanging), my OAuth resource wasn't getting removed because state was set to present by default when the ansible operator framework called my ansible role when it detected the kiali CR was deleted. All of this is now fixed and working.

**Comment by jmazzitelli** [comment]
I still have the service account problem. SOMETIMES when I run "make operator-deploy", the pod fails to start because the service-account isn't accessible/missing, even though the ansible script shows no errors when creating the SA. When it happens again, I'll post the error message here.

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#808](https://paste.fedoraproject.org/paste/UyR1ZsLamQ5-H0vfOeFH2w)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1623]](https://paste.fedoraproject.org/paste/uqYP1X~yBBBY40pXKsqgFw)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#809](https://paste.fedoraproject.org/paste/NkFvc27T-FjkdBsI9woodQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1624]](https://paste.fedoraproject.org/paste/BlplNS9S9xckFDQ8-cvQ-Q)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#810](https://paste.fedoraproject.org/paste/2gSkt4u-pd3qtLwZJng-4g)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1625]](https://paste.fedoraproject.org/paste/naFI3te~2bXW5N1rwYotqA)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#811](https://paste.fedoraproject.org/paste/76yLkZJnrtF5lbw0pvgRcA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1626]](https://paste.fedoraproject.org/paste/jyw8NSEDoq7r1dIhplzgQA)

**Comment by jmazzitelli** [comment]
I pushed the operator image to quay.io - once we get this merged, we can be able to test the script by letting people do something like:

IMAGE_NAME=quay.io/jmazzitelli/kiali-operator IMAGE_VERSION=0.1 bash <(curl -L https://raw.githubusercontent.com/kiali/kiali/master/operator/deploy/deploy-kiali-operator.sh)

That should install the operator and Kiali in your cluster. This should work for OpenShift or Kubernetes (no need to point to different scripts now).

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#812](https://paste.fedoraproject.org/paste/6NhLiIF9K4KqLKB4WUYOXQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1627]](https://paste.fedoraproject.org/paste/k-QrB3SAnljay8GwUNTdGg)

**Comment by jmazzitelli** [comment]
I'm going to merge this. All of the new stuff is under a new "operator" directory - no changes to any existing files (other than .gitignore) is done in this PR.

**Pull request merged**
