### PR TITLE
Migrate PF5 deprecated Dropdowns

### PR DESCRIPTION
**Pull request by ferhoyos**
**Describe the change**

Migrate deprecated Dropdowns components to new PF5 ones.

Dropdown locations:
- Namespace dropdown (any list page):

image

- Cluster dropdown (new Istio Config page, only for multicluster):

image

- Istio config details action:

image

- Istio config list action:

image

- Service details action:

image

- Workload details action:

image

- RequestMatching and Route Filtering Wizard:

image

image

- Display options in Trace tab:

image

- Metric Settings in Inbound/Outbound Metrics:

image

- Help dropdown:

image

- User dropdown:

image

- Find/Hide Graph options (both in Cy and PF):

image

image

- Graph Display Settings:

image

- Graph Traffic Settings

image

**Kebab Toggle**
- Overview namespace card:

image

- Minigraph card (both Cytoscape and Patternfly):

image

- Trace details: 

image

- Graph Summary Application Panel:

image

Graph Summary Service Panel:

image

- Workload Pod Log:

image

**Bonus:**
- Some dropdown components migrated to hooks (plain components, straightforward conversions).
- I have set filter name in namespace and cluster dropdown to be non case-sensitive. This kind of filter process should not take into account capital letters.

image

- Removed RightActionBar component (not used in Kiali application)
- Formatting and fix some CSS style disalignments (margin and paddings) after Dropdown replacement.

**Minor Patternfly issues found**
- https://github.com/patternfly/patternfly-react/issues/9699
- https://github.com/patternfly/patternfly-react/issues/9703

**Issue reference**

Closes https://github.com/kiali/kiali/issues/6448.

### CODE REVIEW

**Comment by aljesusg** [comment]
I am seeing more commits  ping me to review it when ready

**Comment by ferhoyos** [comment]
@aljesusg the PR is ready, I have just rebased the code with master branch due to conflict.

**Review by jshaughn — APPROVED** [review]
@ferhoyos A lot of work!  All good for me:

- I couldn't break anything when testing the UI
- some dropdowns are positioned better (like the graph find preselects)
- more components moved to hooks
- more type safety
- more alphabetized props lists
- more consistent use for `rem` vs `px` styling

**Review by aljesusg — APPROVED** [review]
LGFM

**Pull request merged**
