### PR TITLE
Fix apps labels being incomplete when duplicates are found

### PR DESCRIPTION
**Pull request by jotak**
When a duplicate is found, it must just be ignored, not erase the previous values

Adding some unit tests

Fixes https://github.com/kiali/kiali/issues/2670

### CODE REVIEW

**Comment by jotak** [comment]
PS: I've found another (small) problem that I can try to fix in the same PR: labels are not sorted and their ordering may change upon refresh. We could sort them to display more consistently

**Comment by jotak** [comment]
@aljesusg I've pushed a new one to sort labels by value.
Example, `jaeger-infra: agent-service,collector-service,jaeger-service`, values are sorted alphabetically to avoid changing order on refresh

**Comment by aljesusg** [comment]
> @aljesusg I've pushed a new one to sort labels by value.
> Example, `jaeger-infra: agent-service,collector-service,jaeger-service`, values are sorted alphabetically to avoid changing order on refresh

Maybe we should sort the values from backend.. I thought that istio had them sorted

**Comment by jotak** [comment]
(oops sorry I edited your comment instead of quoting it, my bad)

I don't know if they come sorted after being fetched, but since they're stored in a map, their order isn't guaranteed anyway

**Comment by aljesusg** [comment]
> (oops sorry I edited your comment instead of quoting it, my bad)
> 
> Hmm actually it's the order of workloads/services related to the app that may change, and make the ordering of related labels changing

I thought that go lets sort when transform to json for marshall...ok so from me side is ok tos ort them in UI

**Comment by jotak** [comment]
It's sorted in my last commit so no need to do it from UI

**Comment by jotak** [comment]
thanks @hhovsepy @aljesusg

**Pull request merged**
