### PR TITLE
Remove padding from navigation list

### LINKED ISSUE #6810: Extra space between left nav and top nav
There's extra space between the left nav and top nav that shouldn't be there.

image

image

From an earlier screenshot it should look like this where there's no space between the two:
image

Kiali version: v1.76

### PR DESCRIPTION
**Pull request by ferhoyos**
**Describe the change**

Remove extra space between left nav and top nav.

image

**Issue reference**

Fixes #6810.

### CODE REVIEW

**Review by nrfox — APPROVED** [review]
LGTM

**Comment by nrfox** [comment]
I think this needs a backport to 1.73 as well

**Comment by ferhoyos** [comment]
The solution it is a bit different because I have to addapt it to PF4, but not very complicated.

**Comment by ferhoyos** [comment]
Also I think that according to documentation guidelines, the `backport needed` labels are to be added to issues, not to PRs

**Comment by nrfox** [comment]
> The solution it is a bit different because I have to addapt it to PF4, but not very complicated.

Ah ok well then is this still an issue if 1.73 is PF4?

> Also I think that according to documentation guidelines, the backport needed labels are to be added to issues, not to PRs

Whoops I'll adjust it to be correct. Thanks!

**Pull request merged**
