### PR TITLE
Skip loading requests health for apps and workloads without sidecar

### PR DESCRIPTION
**Pull request by hhovsepy**
Issue https://github.com/kiali/kiali/issues/6372

The issue can be reproduced on multicluster env, for 'east' cluster's 'istio-system' namespace (easiest way).
It shows 1 Error on the 'istio-system' namespace card for 'east' cluster in Overview page for Apps and Workloads, for the workload 'istio-ingressgateway', but in fact when checking Apps list or details, all are healthy.
The failure is because there is some 'outbound' request with '403' for that workload 'istio-ingressgateway'.
The issue is in inconsistency when calculating health for App/Workloads and for Namespace in Overview page.
For individual or list of Apps/Workloads, those workloads which does not have sidecars, the health does not include Requests.
But in Overview page there was a bug, if at least one workload has a sidecar, then load Requests for all Apps/Workloads in that namespace.
And in 'istio-system' namespace there is one workload 'istio-eastwestgateway' which has a sidecar. This causes loading Requests for 'istio-ingressgateway' workload as well, and in fact I am not sure why there is that Request for this workload, but as it does not have a sidecar, the Requests should be ignored.
The fix is to introduce a map of App/Workload names and sidecars, so for each App or Workload while calculating Namespace health in Overview page, keep loading Requests only for those which has sidecars.

### CODE REVIEW

**Review by leandroberetta — APPROVED** [review]
After a clean installation, I couldn't reproduce this, that 403 request it's missing here for sure, it's rare you have it, because I don't know where it comes from but this code looks good and makes sense to me.

**Comment by hhovsepy** [comment]
w.IstioSidecar for istio-ingressgateway is false when I debug locally.

**Comment by jshaughn** [comment]
> w.IstioSidecar for istio-ingressgateway is false when I debug locally.

I can believe that's correct, because it does not have a sidecar.  But, it IS a sidecar :-)

**Review by jshaughn — COMMENTED** [review]
@hhovsepy I understand there is an inconsistency in the way the health is performed for the overview namespace and the list/detail.  My concern here is that I think the solution makes both the overview card and the app show green, when actually I think they should both show red.  Is that true or am I confused?  I'm not able to quite reproduce it as I don't have the MC setup.

So, it's possible this PR is correct as-is.  But my concern was that the handling for istio-ingressgateway (or istio-egressgateway) may not be correct.  Those gateways don't have a sidecar but are themselves proxies, and they do generate request telemetry.  So even though currently they will show `IstioSidecar: false`, I think we may need to update the `HasIstioSidecar()` functions to set to `true` for these istio gateways.

**Comment by hhovsepy** [comment]
@jshaughn yes you are are right, now I have added a new method 'IsGateway', and used in health calculation for App/Workload Details and  in Overview pages. Just that check is used for health calculations only, not in general 'HasIstioSidecar' where it touches a lot of areas.

**Review by jshaughn — APPROVED** [review]
@hhovsepy Looks good, I like the solution to my previous feedback.

**Pull request merged**
