### PR TITLE
Support setting history mode by parameter 

### PR DESCRIPTION
**Pull request by aimuz**
** Describe the change **

Write will no longer be required env.js

https://github.com/kiali/kiali-ui/pull/1882

** Issue reference **

https://github.com/kiali/kiali-ui/pull/1882

** Backwards incompatible? **

- No, Fully compatible

_describe the changes if appropriate_

** Documentation **

* Does your contribution contain user-visible changes like e.g. new or changed configuration settings?
If so, please also update README.adoc

### CODE REVIEW

**Review by jmazzitelli — DISMISSED** [review]
This requires a good amount of testing. We tried fixing this in the past and always hit cases where things broke.

These must pass:

1. Using OpenShift Route to access Kiali
2. Using K8s Ingress to access Kiali
3. Using Istio Gateway/VirtualService/DestinationRule to access Kiali
4. Test 1 through 3 using server.web_root setting with value of "/"
5. Test 1 through 3 using server.web_root setting with value of "/kiali"
6. Test 1 through 3 using server.web_root setting with value of "/foo/bar"

I have no suggested changes, however, I am marking this as "request changes" only to block this PR from being merged until we verify those sets of tests pass.

**Review by israel-hdez — APPROVED** [review]
This part looks and works OK on my env.

**Comment by israel-hdez** [comment]
@jmazzitelli I think we can merge this back-end counterpart of the other PR. I see no conflict given our current behavior will remain as the default.

**Comment by jmazzitelli** [comment]
> @jmazzitelli I think we can merge this back-end counterpart of the other PR. I see no conflict given our current behavior will remain as the default.

OK, I will remove my block.

**Pull request merged**
