### PR TITLE
KIALI-2387 Custom dashboards: add grouping over version

### PR DESCRIPTION
**Pull request by jotak**
For app-based dashboards, automatically add a possible aggregation/grouping over versions

JIRA: https://issues.jboss.org/browse/KIALI-2387

Screenshot:
sshot

### CODE REVIEW

**Comment by jotak** [comment]
Note for tester: use any of the custom dashboard (sample apps: https://github.com/jotak/mesh-microprofile-2018 , https://github.com/jotak/nodejs-metrics-example , https://github.com/jotak/demo-mesh-arena)

As always, to deploy dashboards: from kiali sources run `oc apply -f deploy/dashboards`

**Comment by xeviknal** [comment]
@jotak there is a minor thing in the test suite on travis. Do you mind checking it out?

**Comment by jotak** [comment]
oops, you're right, i'll check that tomorrow

**Comment by jotak** [comment]
@xeviknal this is fixed

**Pull request merged**
