### PR TITLE
[WIP] Support deploying dualStack Kind Clusters

### PR DESCRIPTION
**Pull request by sridhargaddam**
Part-of #7902 

This PR enables support for deploying KIND and Istio in dualStack mode using the flag IP_FAMILY. For a dualStack cluster, export IP_FAMILY=dual (default is ipv4).

### CODE REVIEW

**Comment by nrfox** [comment]
Hey @sridhargaddam thanks for looking at this. I think it makes a lot of sense to use the same `kind-provisioner` script that istio and sail use. It would be nice to deploy both clusters into the same network since that would simplify the multi-cluster setup. iirc the `start-kind.sh` script doesn't support that today.

There are a couple of requirements that Kiali has which I'm not sure if that script supports:
1. oidc opts: https://github.com/kiali/kiali/blob/6a9061b6492eb439c5f7d64ef51021a2e01fd3c1/hack/start-kind.sh#L147C1-L154C62. Kiali supports login with oidc but in order to test this, you have to configure the kube API server on startup with these oidc flags. This is kind of a chicken and egg problem because the oidc server, keycloak, runs inside of one of the kind clusters meaning that the kind cluster needs to know the public ip of the keycloak server running inside of it when the kind cluster starts. To get around this we just assume that the first public ip allocated in the range we setup in metallb will be the keycloak server's public ip. The oidc server doesn't actually have to be online or resolvable when you start the kind cluster so normally you'd just use an FQDN instead of an ip address but we didn't want to use some external service like `nip.io` and now I forget why we didn't use something like `dnsmasq`. At any rate, we need to be able to pass the oidc flags to the kind cluster setup.
2. Local registry. We need the [local kind registry](https://kind.sigs.k8s.io/docs/user/local-registry/) setup for CI and local testing.

**Comment by jmazzitelli** [comment]
`hack/configs` -- are these  KinD only configuration files? Please rename this to be more explicit what this is for. Right now someone sees "configs" under hack directory and it isn't clear what configuration files these are for.

i.e. `hack/kind-config-files` would be something more explicit.

**Comment by jshaughn** [comment]
@jmazzitelli @nrfox , can we get together to figure out what we need to do here?  This PR has just sort of languished and I think it needs an assignee to take it over.

**Comment by jmazzitelli** [comment]
I think we can close this - this PR gives us ipv6 in our kind setup script https://github.com/kiali/kiali/pull/8008

**Comment by jshaughn** [comment]
> I think we can close this - this PR gives us ipv6 in our kind setup script

Agreed.  We may still want to reference some things here, but the PR does not need to move forward.

**Pull request closed without merging**
