### PR TITLE
Fix cypress login on openshift

### PR DESCRIPTION
**Pull request by nrfox**
### Describe the change

Validates cookie is present in `cy.session`. Fixes `my_htpasswd_provider` environments.

### Steps to test the PR

Deploy kiali on openshift. Run cypress with:
```
CYPRESS_BASE_URL=<kiali_route>
CYPRESS_USERNAME=<username>
CYPRESS_PASSWD=<pass>
```

### Automation testing

Fixes existing tests.

### CODE REVIEW

**Comment by matejnesuta** [comment]
Tested on upstream OCP: 

the last test fails with this, but I am not sure, if the failure is related to this PR:
image

**Comment by matejnesuta** [comment]
Oh, there is a missing gherkin step in the last scenario. That's why it failed.

Also the 4th scenario should have a demo app tag like `@bookinfo-app`. I tried to run the test against an env without any apps and the test failed because of that. 

Not sure if these changes should be addressed here, or in a separate PR.

**Comment by nrfox** [comment]
> Oh, there is a missing gherkin step in the last scenario. That's why it failed.

Good catch! I'll update.

> Also the 4th scenario should have a demo app tag like @bookinfo-app. I tried to run the test against an env without any apps and the test failed because of that.

It should still work even without apps deployed and all of these tests are smokes so should run in envs without apps. You should still be able to go to the overview page. Maybe the assertion about the overview page is busted?

**Comment by nrfox** [comment]
@matejnesuta would you try running the tests again?

**Review by matejnesuta — APPROVED** [review]
Passing. LGTM.

**Pull request merged**
