### PR TITLE
Add rq/rs throughput in metrics page

### PR DESCRIPTION
**Pull request by jotak**
Related to https://github.com/kiali/kiali/issues/2897

Fix / add tests

### CODE REVIEW

**Comment by jotak** [comment]
Screenshot:
Capture d’écran de 2020-06-15 14-38-50



@lucasponce this is a small and interesting addition to add rq/rs throughput to the list of metrics.

Throughput adds value from requests per second in several situations ; for instance when streaming data or high volume of data per request, it can be an interesting metric.

**Comment by lucasponce** [comment]
@jotak It looks great to me

**Comment by lucasponce** [comment]
I've found something that is not related to this PR but perhaps worth to take a look.
From this PR I get the metrics:
image

But when I enable the spans:
image

The scale changes.

It seems correct, because:
image
image

The peak is shown in a very short scale when a single metric.

Anyway, the PR looks ok, just commenting this in case it may help for other refinment in the charts.

**Comment by jotak** [comment]
Thanks @lucasponce 
About this spike that disappears: yet, this is a side-effect of having the y-axis autoscaled. A possibility could be to have y-axis always 0-based. It may not make sense for every metrics in general, but for the istio metrics that we display here, I think it should be fine.

**Pull request merged**
