### PR TITLE
Adding  E2E VirtualService Create/Delete Test

### PR DESCRIPTION
**Pull request by gbaufake**
- Adding E2E Istio Config Create Testing

@xeviknal, after preforming the request as you've shown me, I am getting ``'{"error":"invalid character \'m\' looking for beginning of value"}'``.

I already debugged it doesn't make the response to me.

### CODE REVIEW

**Comment by xeviknal** [comment]
@gbaufake I've just tried the same formula for getting the examples as last week.
It worked to me. after calling both commands, Kiali shows both the DR and the VR.

cURL examples for DestinationRules:
```bash
curl 'https://kiali-istio-system.my.cluster.com/api/namespaces/bookinfo/istio/destinationrules' -H 'Origin: https://kiali-istio-system.my.cluster.com' -H 'Accept-Encoding: gzip, deflate, br' -H 'X-Auth-Type-Kiali-UI: 1' -H 'Accept-Language: en-US,en;q=0.9,es;q=0.8,ca;q=0.7' -H 'User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/json, text/plain, */*' -H 'Referer: https://kiali-istio-system.my.cluster.com/console/namespaces/bookinfo/services/details?list=workloads' -H 'Cookie: kiali-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzA1MjYwMTAsImlzcyI6ImtpYWxpLWxvZ2luIiwic3ViIjoiYWRtaW4ifQ.gYegM0WD0XjqLPm-ibcCxCC8VbXzwtiwRKiWmgz7vi4; d5b5278d6ecca213a6cda3f6cfaa8cef=75ffd7aa49e739f3be3e06d60a6c5f8e' -H 'Connection: keep-alive' --data '{"metadata":{"namespace":"bookinfo","name":"details","labels":{"kiali_wizard":"suspend_traffic"}},"spec":{"host":"details","subsets":[{"name":"v1","labels":{"version":"v1"}}],"trafficPolicy":null}}' --compressed --insecure
```

And for VirtualServices:
```bash
curl 'https://kiali-istio-system.my.cluster.com/api/namespaces/bookinfo/istio/virtualservices' -H 'Origin: https://kiali-istio-system.my.cluster.com' -H 'Accept-Encoding: gzip, deflate, br' -H 'X-Auth-Type-Kiali-UI: 1' -H 'Accept-Language: en-US,en;q=0.9,es;q=0.8,ca;q=0.7' -H 'User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/json, text/plain, */*' -H 'Referer: https://kiali-istio-system.my.cluster.com/console/namespaces/bookinfo/services/details?list=workloads' -H 'Cookie: kiali-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzA1MjYwMTAsImlzcyI6ImtpYWxpLWxvZ2luIiwic3ViIjoiYWRtaW4ifQ.gYegM0WD0XjqLPm-ibcCxCC8VbXzwtiwRKiWmgz7vi4; d5b5278d6ecca213a6cda3f6cfaa8cef=75ffd7aa49e739f3be3e06d60a6c5f8e' -H 'Connection: keep-alive' --data '{"metadata":{"namespace":"bookinfo","name":"details","labels":{"kiali_wizard":"suspend_traffic"}},"spec":{"http":[{"route":[{"destination":{"host":"details"}}],"fault":{"abort":{"httpStatus":503,"percentage":{"value":100}}}}],"hosts":["details"],"gateways":null}}' --compressed --insecure
```

In order to see more examples, you can get to a service details page and try the actions dropdown with the Network tab (developer tools) opened. You should see there more examples of calls to IstioObjectCreate.

btw, I am using:

```
Kiali-ui 1.7.0-snapshot.1 (c66f0ae640c152b5e93cb3f1f06c7ec1f2215061)
Kiali v1.6.0-SNAPSHOT (194eb62c6fb75838fc482bff1fd78249bb9f2967)
```

**Comment by gbaufake** [comment]
@xeviknal 
Thanks for the help.

I was forgetting a `'` on the data.

**Comment by jshaughn** [comment]
Any update on this for Sprint 30?

**Comment by gbaufake** [comment]
@jshaughn 
Working on it.

**Pull request merged**
