### PR TITLE
Add NPM registry parameter

### PR DESCRIPTION
**Pull request by israel-hdez**
Adds NPM_CONFIG_REGISTRY parameter to the sample job.

Unfortunately, since different envs may need to use different package registries it's no longer possible to hardcode the parameters to make the Pipeline to "auto configure" itself if created manually (harcoding configs replaces any customized configs of the Pipeline on every run)

This means, that the Pipeline will need to be configured manually if the config.xml file cannot be placed in the Jenkins instance.

### CODE REVIEW

**Comment by josejulio** [comment]
Can't we default to `NPM_CONFIG_REGISTRY` not being set and only override that one as needed?

**Comment by israel-hdez** [comment]
@josejulio I think I don't understand :/

**Comment by josejulio** [comment]
> Adds NPM_CONFIG_REGISTRY parameter to the sample job.
> 
> Unfortunately, since different envs may need to use different package registries it's no longer possible to hardcode the parameters to make the Pipeline to "auto configure" itself if created manually (harcoding configs replaces any customized configs of the Pipeline on every run)

I saw that you commented all the defaults (I think that's what you did :P) 
But is not clear to me why we can't let the pipeline to "auto configure" with the param `NPM_CONFIG_REGISTRY` being "unset" and only set when we need it.

> 
> This means, that the Pipeline will need to be configured manually if the config.xml file cannot be placed in the Jenkins instance.

**Comment by israel-hdez** [comment]
@josejulio Oh! I think I understand... So you want the NPM_CONFIG_REGISTRY to be present in the `properties` but without the `defaultValue` attribute...
That may work and will remove the need of commenting out. I'll check.

**Comment by israel-hdez** [comment]
@josejulio It didn't work.

Basically, Jenkins is syncing the config with whatever is specified in the `properties`, if present. This happens on every run. I just tried and it sets the default to empty even if no `defaultValue` is specified.

Perhaps "auto configure" is the wrong term. It syncs on each run. Since we need a specific NPM_CONFIG_REGISTRY default value on our "prod" Jenkins instance, the `properties` become a problem.

My goal with the `properties` was to avoid setting up all those parameters each time I need to recreate my local dev env. So, what I was doing is to create a "bare" pipeline (only configuring the repo) and run it once so that it fetches the configs and in subsequent runs the parameters will be there. But since I already made some work to have a pre-configured Jenkins docker image, I think the hardcoded properties are no longer needed and the config.xml may enough?

I don't know... you say :)

**Comment by josejulio** [comment]
> I think the hardcoded properties are no longer needed and the config.xml may enough?

+1

**Pull request merged**
