### PR TITLE
fix: add read lock when getting status

### PR DESCRIPTION
**Pull request by Xunzhuo**
Signed-off-by: Xunzhuo <mixdeers@gmail.com>

**Describe the change**

fix concurrent map reads

**Issue reference**

fix: https://github.com/kiali/kiali/issues/4842

### CODE REVIEW

**Comment by jmazzitelli** [comment]
@FilipB I added you as a reviewer since you mentioned you are running tests on this PR.

**Review by jmazzitelli — APPROVED** [review]
I looked at the code and ran the unit tests - all pass. I'm OK with this.
Will wait for @FilipB to provide his review before merging.

**Review by FilipB — APPROVED** [review]
Fix seems to be working. I'm not able to reproduce the issue anymore.
E2E rest test are also passing.
Thank you

**Comment by jmazzitelli** [comment]
backport PR: https://github.com/kiali/kiali/pull/4858

**Pull request merged**
