### PR TITLE
KIALI-3111 delete deployment if the image name or version is changing

### PR DESCRIPTION
**Pull request by jmazzitelli**
https://issues.jboss.org/browse/KIALI-3111

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I'm going to see if I can write a molecule test for this.

**Comment by jmazzitelli** [comment]
I need this reviewed and tested. @gbaufake this was also something @mattmahoneyrh reported. See how this works. I was going to try to create a molecule test, but you guys can see if this works, too (rather than wait for me to write the molecule test).

**Comment by gbaufake** [comment]
You can execute `molecule test -s multi-tenancy --destroy never` once with an image version and then re-run `molecule prepare` with a different version.

It worked for me.
Before it was the problem of immutable.

**Comment by lucasponce** [comment]
@jmazzitelli @gbaufake this PR can't be cherry-picked into v1.0.
I requires manual step.

Please, could you prepare proper PR with these changes on that branch ?
Thanks.

**Pull request merged**
