### PR TITLE
Fix validation for K8s gateway hosts

### LINKED ISSUE #5802: K8s Gateway wizard hostname is valid in frontend but rejected in Kiali server
If you set a hostname value in K8s gateway wizard with pattern "string/string.string", the value is set as valid in frontend wizard:

image

But Kiali server returns error with following message:
{"error":"Gateway.gateway.networking.k8s.io \"test\" is invalid: spec.listeners.hostname: Invalid value: \"test/test.test\": spec.listeners.hostname in body should match '^(\\*\\.)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'"}

image

The same validation should be both in frontend wizard and server backend.

### PR DESCRIPTION
**Pull request by ferhoyos**
** Describe the change **

Applies different hostname validations for Istio Gateways and K8s Gateways:
- Istio Gateway hosts have namespace/dnsName with namespace optional (https://istio.io/latest/docs/reference/config/networking/gateway/)
- K8s Gateway hosts have only dnsName (https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1beta1.Hostname)

K8s gateway host validations obtained from K8s Gateway API library (shared_types.go):

// Hostname is the fully qualified domain name of a network host. This matches
// the RFC 1123 definition of a hostname with 2 notable exceptions:
//
// 1. IPs are not allowed.
// 2. A hostname may be prefixed with a wildcard label (`*.`). The wildcard
//    label must appear by itself as the first label.
//
// Hostname can be "precise" which is a domain name without the terminating
// dot of a network host (e.g. "foo.example.com") or "wildcard", which is a
// domain name prefixed with a single wildcard label (e.g. `*.example.com`).
//
// Note that as per RFC1035 and RFC1123, a *label* must consist of lower case
// alphanumeric characters or '-', and must start and end with an alphanumeric
// character. No other punctuation is allowed.
//
// +kubebuilder:validation:MinLength=1
// +kubebuilder:validation:MaxLength=253
// +kubebuilder:validation:Pattern=`^(\*\.)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$`
type Hostname string

** Issue reference **

Fixes #5802 

** Testing **

Checks that valid hostnames in Istio Gateways are no longer valid in K8s Gateways, like for example:
- \*
- test/test.test
- test/*
- TEST.test

### CODE REVIEW

**Comment by ferhoyos** [comment]
mmmm that means the istio validation regex in the API is not restricted enough for IP addresses and names without fqdn. Thanks @hhovsepy, I will double check this and the K8sRouteHost wizard too.

**Comment by ferhoyos** [comment]
Same validation must be applied to K8sHTTPRouteHosts too (https://gateway-api.sigs.k8s.io/api-types/httproute/)

image

**Comment by hhovsepy** [comment]
Code lgtm and works as expected. Waiting for cypress tests for final approve.

**Comment by ferhoyos** [comment]
@hhovsepy Input validation has been added to Cypress test. Since it is the same validation I have only added to K8s Gateway creation test. If you think this validation need to be added to Service K8s Gateway wizard advanced settings too please let me know.

**Comment by ferhoyos** [comment]
Closing PR due to bad resolution of master merge conflicts. Created new one with correct changes (#5863).

**Pull request closed without merging**
