### PR TITLE
KIALI-2524 Fix setting headers for audit info

### PR DESCRIPTION
**Pull request by israel-hdez**
Kiali-User was being set to response headers but it is expected to be in the request headers.

### CODE REVIEW

**Comment by israel-hdez** [comment]
@lucasponce This should solve the issue for openshift and kiali login strategies. May you need it also when anonymous login is enabled?

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#956](https://paste.fedoraproject.org/paste/Srrj1H~j497VfsQuBI5Oqg)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1767]](https://paste.fedoraproject.org/paste/3HgV~0NTlG-vqgyrQ-3Leg)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#957](https://paste.fedoraproject.org/paste/b~By78hhY7GIyDJttwmR2g)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1768]](https://paste.fedoraproject.org/paste/fy8XgFKlQBKyDW3z9GpHiQ)

**Comment by lucasponce** [comment]
Tested:

```
I0423 08:29:51.981806       1 istio_config.go:352] AUDIT User [admin] Msg [CREATE on Namespace: travel-agency Type: virtualservices Subtype:  Object: {"metadata":{"namespace":"travel-agency","name":"discounts","labels":{"kiali_wizard":"weighted_routing"}},"spec":{"hosts":["discounts"],"http":[{"route":[{"destination":{"host":"discounts","subset":"v1"},"weight":100}]}]}}]
```

Thanks @israel-hdez !

**Pull request merged**
