### PR TITLE
KIALI-761 Support self-invoking services in the graph

### PR DESCRIPTION
**Pull request by jshaughn**

### CODE REVIEW

**Comment by jshaughn** [comment]
screenshot

**Comment by josejulio** [comment]
@jshaughn I suspect the animation is broken with this (on loops) I didn't added support for curves, but can work on this after this PR

**Comment by jshaughn** [comment]
The animation is kind of funny with what it does bit it's ok.  Doesn't do anything crazy.  But you are right. there is no dot moving on the self-referencing edge.

**Comment by lucasponce** [comment]
> When I look at this PR, it takes me back to when I was a child frolicking in the meadows smelling the sweet fragrance of wild flowers.

Nice that a PR makes you remember those poems of Walt Whitman :D

**Pull request merged**
