### PR TITLE
KIALI-2752 bump up the base image of operator-sdk to 0.8.0

### PR DESCRIPTION
**Pull request by jmazzitelli**
Hopefully this fixes the problem we had with the operator being unable to install dashboards

### CODE REVIEW

**Comment by jmazzitelli** [comment]
@jotak with this PR, the operator should be able to install the runtime dashboards. IIRC, the current operator is unable to do this because the operator fails to detect the CRD so it gets an error when it tries to install the runtime dashboard CRs. The [operator-sdk 0.8.0 has a bug fix](https://github.com/operator-framework/operator-sdk/pull/1329) that should correct that issue.

**Comment by jotak** [comment]
@jmazzitelli how can I test? I guess I need to rebuild the operator (not just redeploy), is that achieved with `make operator-create` ?

**Comment by jmazzitelli** [comment]
This isn't fixing the problem it is supposed to fix:

Make sure I'm running 0.8.0:

```
{"level":"info","ts":1558465126.8952413,"logger":"cmd","msg":"Go Version: go1.12.5"}
{"level":"info","ts":1558465126.8952928,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1558465126.895298,"logger":"cmd","msg":"Version of operator-sdk: v0.8.0"}
{"level":"info","ts":1558465126.895325,"logger":"cmd","msg":"Watching namespace.","Namespace":"kiali-operator"}
```

But I still see the error:

```
{"level":"error","ts":1558465170.3098834,"logger":"proxy","msg":"Could not get rest mapping for: monitoring.kiali.io/v1alpha1, Kind=MonitoringDashboard","error":"no matches for kind \"MonitoringDashboard\" in version \"monitoring.kiali.io/v1alpha1\"","stacktrace":"github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\tsrc/github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/proxy.shouldAddOwnerRef\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/proxy/inject_owner.go:151\ngithub.com/operator-framework/operator-sdk/pkg/ansible/proxy.(*injectOwnerReferenceHandler).ServeHTTP\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/proxy/inject_owner.go:89\ngithub.com/operator-framework/operator-sdk/pkg/ansible/proxy.(*cacheResponseHandler).ServeHTTP\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/proxy/cache_response.go:127\nnet/http.serverHandler.ServeHTTP\n\t/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1878"}
{"level":"error","ts":1558465170.309941,"logger":"proxy","msg":"Could not determine if we should add owner ref","error":"no matches for kind \"MonitoringDashboard\" in version \"monitoring.kiali.io/v1alpha1\"","stacktrace":"github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\tsrc/github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/proxy.(*injectOwnerReferenceHandler).ServeHTTP\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/proxy/inject_owner.go:92\ngithub.com/operator-framework/operator-sdk/pkg/ansible/proxy.(*cacheResponseHandler).ServeHTTP\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/proxy/cache_response.go:127\nnet/http.serverHandler.ServeHTTP\n\t/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1878"}
```

**Comment by jmazzitelli** [comment]
I think we should still merge this, at least to get the latest operator-sdk

**Comment by jmazzitelli** [comment]
> I've tested and dashboards are there!

It isn't working for me :(

**Comment by jmazzitelli** [comment]
OK, according to Shawn Hurley, this isn't fixed in ansible operator 0.8.0 - the operator-sdk has a fix, but ansible operator needs to use it. See: https://github.com/operator-framework/operator-sdk/issues/1330#issuecomment-494529607 and related comments there.

So I'll merge this, but it doesn't fix the problem. We'll need to wait some more for another release.

**Comment by jotak** [comment]
So I don't understand why I saw the dashboards. They were not present before I install the operator, and they were after... there's something here i don't get

**Comment by jmazzitelli** [comment]
> So I don't understand why I saw the dashboards. They were not present before I install the operator, and they were after... there's something here i don't get

The only way you will see this IIRC is if you installed the CRD separately first, then asked the operator to install kiali. If the CRD exists prior to the operator running, then it will work. If the operator is the one that creates the CRD, then this bug appears.

**Comment by jotak** [comment]
Ah, that must be it. I probably installed the CRD before, and didn't cleanup the whole cluster.

**Pull request merged**
