### PR TITLE
Refactor globals out of auth controllers

### PR DESCRIPTION
**Pull request by nrfox**
### Describe the change

Cleans up the auth controllers so that they no longer use global variables. 

### Steps to test the PR

Login with each auth strategy. Confirm that nothing is broken.

### Automation testing

Included with existing automation. ~Note that not every auth strategy has automated testing. The `header` auth strategy is not yet covered by testing automation.~

### Issue reference

This is a pre-req to #4890.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
> Note that not every auth strategy has automated testing. The header auth strategy is not yet covered by testing automation

We do have automated testing for it -- header auth is passing [as of last week](https://github.com/jmazzitelli/kiali-molecule-test-logs/blob/minikube/molecule-tests-2024-04-03_01-00-02/results.log#L39) - see [the molecule test `header-auth-test`](https://github.com/kiali/kiali-operator/tree/master/molecule/header-auth-test)

**Comment by nrfox** [comment]
> > Note that not every auth strategy has automated testing. The header auth strategy is not yet covered by testing automation
> 
> We do have automated testing for it -- header auth is passing [as of last week](https://github.com/jmazzitelli/kiali-molecule-test-logs/blob/minikube/molecule-tests-2024-04-03_01-00-02/results.log#L39) - see [the molecule test `header-auth-test`](https://github.com/kiali/kiali-operator/tree/master/molecule/header-auth-test)

That's great! I always forget about the molecule tests.

**Comment by jmazzitelli** [comment]
Ran header-auth-test and got a failure (but I don't think its related to this PR):
```
TASK [Assert that we were able to get the list of namespaces] ******************
fatal: [localhost]: FAILED! => {
    "assertion": "kiali_output.json | length > 0",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
```

How I ran the test:

1. Start minikube with Dex and Istio:
```
./hack/k8s-minikube.sh --dex-enabled true -mp ci start && ./hack/k8s-minikube.sh -mp ci istio
```
2. Build this PR branch, push it to the cluster, and run test with that dev image (this attempts to run the three non-OpenShift auth tests - but when the one fails, it doesn't go to the others. But use this command to test header auth, openid auth, and token auth):
```
make -e CLUSTER_TYPE=minikube -e MINIKUBE_PROFILE=ci -e MOLECULE_SCENARIO="header-auth-test openid-test token-test" -e MOLECULE_USE_DEV_IMAGES=true build build-ui cluster-push molecule-test
```

If you run that command above with `MOLECULE_USE_DEV_IMAGES` set to `false`, all three tests should pass (this would show that the latest nightly image published on quay is OK). But that also failed for me.

**Comment by jmazzitelli** [comment]
I also ran openid-test which failed (with the PR dev image and with the latest master build). token-test passed. 
openid-test failure is this:

```
TASK [With the updated login cookie, make a request that requires authentication (should now return 200)] ***
fatal: [localhost]: FAILED! => {"changed": false, "connection": "close", "content": "Unauthorized\n", "content_length": "13", "content_type": "text/plain; charset=utf-8", "date": "Thu, 11 Apr 2024 23:56:37 GMT", "elapsed": 0, "msg": "Status code was 401 and not [200]: HTTP Error 401: Unauthorized", "redirected": false, "status": 401, "url": "https://192.168.50.32/kiali/api/namespaces", "vary": "Accept-Encoding", "x_content_type_options": "nosniff"}
```

**Comment by jmazzitelli** [comment]
(_ignore previous comments that I just deleted - I forget to run the auth molecule tests, you need to do some setup. That's what ["run-molecule-tests.sh"](https://github.com/kiali/kiali/blob/master/hack/run-molecule-tests.sh#L299-L304) does. So to run the auth molecule tests, you need to run that script rather than the make target directly._)

So just to confirm - the nightly latest build image all pass the three auth tests - run this:

```
./hack/ci-minikube-molecule-tests.sh --client-exe $(which kubectl) --minikube-exe $(which minikube)  -dorp podman --upload-logs false -ir "" --rebuild-cluster true --all-tests "token-test header-auth-test openid-test"
```

Once you run that and confirm the latest image passes those tests (which tell us master branch is ok), use the run-molecule-tests.sh script to run the tests with this PR's dev image:

1. Build and push this PR's image (note: the ci-minikube-molecule-tests.sh script creates a minikube cluster with profile named "ci" hence why we need the MINIKUBE_PROFILE env var set): `make -e CLUSTER_TYPE=minikube -e MINIKUBE_PROFILE=ci build build-ui cluster-push`
2. Now run the run-molecule-tests.sh script, telling it to use the dev image produced by this PR:  `./hack/run-molecule-tests.sh --client-exe "$(which kubectl)" --minikube-exe $(which minikube) -dorp podman --all-tests "token-test header-auth-test openid-test" --cluster-type minikube --minikube-profile ci --use-dev-images true`

**Comment by jmazzitelli** [comment]
Here's how I tested on OpenShift

1. Create an OpenShift cluster using CRC: `hack/crc-openshift.sh start`
2. Log into the cluster: `oc login -u kiali -p kiali --server https://api.crc.testing:6443`
3. Set up the image registry: `make cluster-status` (in the output, find the "podman" command to log into the image registry)
4. Log into the image registry using the "podman" command you see in the "make cluster-status" output (for CRC it will typically be this: `podman login --tls-verify=false -u kiali -p $(oc whoami -t) default-route-openshift-image-registry.apps-crc.testing`)
5. Build this PR's image and push it to the cluster: `make build build-ui cluster-push`
6. If you did not use the CRC hack script to create the cluster, create the kiali user and password that the molecule test will use: `make cluster-add-users`
7. Install Istio: `hack/istio/install-istio-via-istioctl.sh`
8. Run the molecule test: `./hack/run-molecule-tests.sh --client-exe "$(which oc)" -dorp podman --all-tests "openshift-auth-test" --cluster-type openshift --use-dev-images true`

But I get an error:
```
^[[31mfatal: [localhost]: FAILED! => {"cache_control": "no-cache", "changed": false, "connection": "close", "content": "<html><body><h1>502 Bad Gateway</h1>\nThe server returned an invalid or incomplete response.\n</body></html>\n", "content_length": "107", "content_type": "text/html", "elapsed": 0, "msg": "Status code was 502 and not [200]: HTTP Error 502: Bad Gateway", "redirected": false, "status": 502, "url": "https://kiali-istio-system.apps-crc.testing/api/auth/info"}^[[0m^M
```

I tried this on a second OpenShift cluster I had access to and got the same error.

But if I run the same command in step 8 except with `--use-dev-images false` (which means it uses the nightly latest build), it passes. Also, last night's test on the nightly latest build also passed: https://github.com/jmazzitelli/kiali-molecule-test-logs/blob/openshift/molecule-tests-2024-04-12_02-00-02/results.log#L84

So it looks like something in this PR has broken the openshift auth.

**Review by jmazzitelli — CHANGES_REQUESTED** [review]
openshift-auth is broken. See my last comment for how you can test using the `run-molecule-tests.sh` script.

**Comment by nrfox** [comment]
> openshift-auth is broken. See my last comment for how you can test using the run-molecule-tests.sh script.

Thanks for taking a look. I'm surprised that CI passed while the molecule tests failed. I'll run those molecule tests locally to see why they're failing.

**Comment by jmazzitelli** [comment]
> I'll run those molecule tests locally to see why they're failing.

Just to be clear, only one is failing (`openshift-auth-test`) ... the others are passing.

**Comment by jmazzitelli** [comment]
Test now passes:
```
                     openshift-auth-test... success [1m 57s]
```

**Review by jmazzitelli — APPROVED** [review]

**Pull request merged**
