### PR TITLE
added tag for kiali tests

### PR DESCRIPTION
**Pull request by ScriptingShrimp**
added tag to Junit reporter for better distinguish in Jenkins results

### CODE REVIEW

**Comment by ScriptingShrimp** [comment]
Need to verify Jenkins before merging

**Comment by ScriptingShrimp** [comment]
image
Displays in Jenkins as intended. 

@ferhoyos  can we use different [frontend/reporter-config.json](https://github.com/kiali/kiali/pull/7965/files#diff-8f0906992e90de531848eca81636c8e5517692d7206af6bff64f6eda35ebfa54) for OSSMC? Will help dramatically to identify failed tests in Jenkins .

**Review by ferhoyos — APPROVED** [review]
@ScriptingShrimp I like the idea to add separate prefix to distinguish the different cypress tests from core and OSSMC. Could you apply the same change in OSSMC repo?

**Comment by ScriptingShrimp** [comment]
> @ScriptingShrimp I like the idea to add separate prefix to distinguish the different cypress tests from core and OSSMC. Could you apply the same change in OSSMC repo?

Will do :+1:

**Pull request merged**
