### PR TITLE
Add validation references to K8S Gateways validations

### LINKED ISSUE #5708: References for K8s Gateways
Epic #5501 

Analysis of the objects in the k8s Gateways to point to other objects. 

image

For a k8s Gateway, it can reference: 

- Services.

A Gateway is autogenerated when a k8s GW is created. The GW will have a reference to the k8s GW. Ex.

`internal.istio.io/parents: Gateway/gw/test.bookinfo`

### PR DESCRIPTION
**Pull request by leandroberetta**
Resolves https://github.com/kiali/kiali/issues/5769

image

### CODE REVIEW

**Comment by leandroberetta** [comment]
Test procedure:

Pre-requisites: 

Install Gateway API CRDs:

```
kubectl get crd gateways.gateway.networking.k8s.io &> /dev/null || \
  { kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v0.6.1" | kubectl apply -f -; }
```

Install bookinfo demo on bookinfo namespace

Then, create the following K8s Gateway objects that has some colliding hostnames and host port combinations:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gatewayapi-1
  labels:
    app: gatewayapi
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    hostname: "bookinfo-istio-system.apps.ocp4-kqe1.maistra.upshift.redhat.com"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  addresses:
    - type: Hostname
      value: "google.com"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gatewayapi-2
  labels:
    app: gatewayapi
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    hostname: "bookinfo-istio-system.apps.ocp4-kqe1.maistra.upshift.redhat.com"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  addresses:
    - type: Hostname
      value: "google.com"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gatewayapi-3
  labels:
    app: gatewayapi
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    hostname: "bookinfo-istio-system.apps.ocp4-kqe1.maistra.upshift.redhat.com"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  addresses:
    - type: Hostname
      value: "google.com"
```

Expect to see the same validations references as shown in the PR description.

**Review by josunect — COMMENTED** [review]
It works as expected and code looks good: 

image

Just a comment, I think it will be valuable to include some additional checks in [the multi_match_checker_test.go](https://github.com/kiali/kiali/blob/master/business/checkers/k8sgateways/multi_match_checker_test.go) test, like: 

`assert.Equal(validation.References[0].Name, "validk8sgateway")`

**Comment by hhovsepy** [comment]
+1 on adding new test checks

**Comment by hhovsepy** [comment]
Code lgtm:
Screenshot from 2023-02-20 09-57-13

**Comment by leandroberetta** [comment]
> +1 on adding new test checks

Sure, I'll add them.

**Review by hhovsepy — APPROVED** [review]
lgtm

**Comment by matejnesuta** [comment]
Hello. Is there a need to cover this PR in Cypress as well? I created a separate issue last week, but looking at it now, I am not so sure. Help would be much appreciated.

**Comment by leandroberetta** [comment]
> Hello. Is there a need to cover this PR in Cypress as well? I created a separate issue last week, but looking at it now, I am not so sure. Help would be much appreciated.
> 
> I also wanted to ask if the already added tests are integration tests and if there is something, that needs to be covered.

Yes, I think it would be a nice thing to have, because with these PR, we are showing more information in the UI.

**Pull request merged**
