### PR TITLE
KIALI-2920 Make Grafana off-cluster still accessible

### PR DESCRIPTION
**Pull request by jotak**
- Also fix KIALI-2921 for Grafana / potential race condition while setting config.
- Add a new config "InCluster" to tell if Grafana is in cluster or not
- Factorize code for access to service account token, and fix test failing while running that code

JIRA: https://issues.jboss.org/browse/KIALI-2920
See also #865

### CODE REVIEW

**Comment by jotak** [comment]
To test Grafana not in cluster, we now have to explicitly set the config `in_cluster` to `false`:

```yaml
  external_services:
    grafana:
      in_cluster: false
      url: "http://my-grafana-server:3000/"
```

**Comment by jotak** [comment]
@hhovsepy between 2 and 3, the same URL is used for link generation, however when it's in-cluster, Kiali uses the cluster domain name (with "http://service.namespace") to connect to the grafana API instead of the external URL. This is done to avoid issues like when Kiali is not able to reach the outside.

**Comment by hhovsepy** [comment]
> Verified:
> 
>     1. The default case when url is not provided and in_cluster=true. Grafana is recognised.
> 
>     2. URL is provided off-cluster and in_cluster=true. Grafna URL is set correctly.
> 
>     3. URL is provided off-cluster and in_cluster=false. Still uses that URL. Is this the expected behavior?
> 
>     4. Wrong URL and in_cluster=false. Error message is shown.

@jotak sorry I had commented wrongly here, should be:

2. URL is provided to off-cluster and in_cluster=false. Grafna URL is set correctly.
3. URL is provided to off-cluster and in_cluster=true. Still uses that off-cluster provided URL. Is this the expected behavior? Or it should set the internal URL?

**Comment by hhovsepy** [comment]
4.  in_cluster: true, url: 'off-cluster url' , in-cluster Grafana is down:  the off-cluster URL is set.

**Pull request merged**
