### PR TITLE
Merge Kiali-UI with Kiali

### PR DESCRIPTION
**Pull request by aljesusg**
Issue https://github.com/kiali/kiali/issues/4825

- [X] Merge CI
- [X] Make changes Makefile
- [x] Merge Readme like templates, code of conduct, style...
- [X] Remove LICENSE from frontend
- [x] Check hacks
- [x] Check linter in frontend folder

### CODE REVIEW

**Comment by jmazzitelli** [comment]
Merge in the changes from PR https://github.com/kiali/kiali/pull/4831 to this PR to get the hack changes.

**Comment by aljesusg** [comment]
Merged @jmazzitelli

**Comment by jmazzitelli** [comment]
PR https://github.com/aljesusg/kiali/pull/12 has additional changes we need. I tested that by running the openshift CI script and all works now. Also, the make test targets now work as well as the make format. We now have `make build-ui` target at the top level to let you run the yarn build without having to cd into frontend and running it manually (though you can still do that if you want).

_NOTE: in a separate PR we should run "make format" - I'm seeing changes in the imports. I guess our CI github action checks aren't picking that up_

**Review by jmazzitelli — CHANGES_REQUESTED** [review]
@aljesusg see https://github.com/aljesusg/kiali/pull/12

**Comment by israel-hdez** [comment]
Rather than doing bare copy-pasting of files, I would like to know if you can do a `git merge` of the front-end into the back-end.
This article may help: https://spences10.medium.com/git-allow-unrelated-histories-a39a3814b981

That way, history will be preserved.

**Comment by jmazzitelli** [comment]
Things I tested:

* `make test`
* `make build-ui`
* `make clean-all`
* `make -e CLUSTER_TYPE=minikube build build-ui cluster-push operator-create kiali-create` (and see that Kiali UI is available in your cluster)
* `make format`

I also tested the openshift CI hack script (I don't have Kind on my machine that works, so I can't test that).

I have not tested the run-kiali.sh - I'll do that and report back if I see any errors. I don't expect any.

**Comment by jmazzitelli** [comment]
> Rather than doing bare copy-pasting of files, I would like to know if you can do a `git merge` of the front-end into the back-end

Ooo.. I didn't notice that. I thought history would be preserved. Yeah, this is important. We did the same when we split the operator out of the main kiali repo - there are ways to preserve git history for things like this. Just need to find the magical commands. You can see how I did it for the operator here - this might help: https://github.com/kiali/kiali-operator/blob/master/DEVELOPING.adoc#the-initial-kiali-operator-git-repo-creation

**Comment by israel-hdez** [comment]
> I thought history would be preserved.

Not in this PR as is :-)
AFAIK, you would see all the transferred commits on this PR. But it's only 11 commits so far... So, nope... no history.

**Comment by aljesusg** [comment]
Ok let me check it I didn't know about that way

**Comment by aljesusg** [comment]
Closed in favor of https://github.com/kiali/kiali/pull/4837

**Pull request closed without merging**
