### PR TITLE
[UI] bump node to 16

### PR DESCRIPTION
**Pull request by jmazzitelli**
support node 16 and above, run tests on 16

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I am not seeing this locally (using Node 16.19.1) but this error shows in the CI logs. I can't explain it, but I think this is the crux of the failure.

```
/home/runner/work/kiali/kiali/frontend/node_modules/react-dom/cjs/react-dom.development.js:1451
        return doc.body;
                   ^

TypeError: Cannot read properties of null (reading 'body')
    at getActiveElement (/home/runner/work/kiali/kiali/frontend/node_modules/react-dom/cjs/react-dom.development.js:1451:20)
    at getActiveElementDeep (/home/runner/work/kiali/kiali/frontend/node_modules/react-dom/cjs/react-dom.development.js:7800:21)
    at getSelectionInformation (/home/runner/work/kiali/kiali/frontend/node_modules/react-dom/cjs/react-dom.development.js:7834:25)
    at prepareForCommit (/home/runner/work/kiali/kiali/frontend/node_modules/react-dom/cjs/react-dom.development.js:10186:30)
    at commitRootImpl (/home/runner/work/kiali/kiali/frontend/node_modules/react-dom/cjs/react-dom.development.js:22918:33)
    at unstable_runWithPriority (/home/runner/work/kiali/kiali/frontend/node_modules/scheduler/cjs/scheduler.development.js:465:16)
    at runWithPriority$1 (/home/runner/work/kiali/kiali/frontend/node_modules/react-dom/cjs/react-dom.development.js:11325:14)
    at commitRoot (/home/runner/work/kiali/kiali/frontend/node_modules/react-dom/cjs/react-dom.development.js:22825:7)
    at performSyncWorkOnRoot (/home/runner/work/kiali/kiali/frontend/node_modules/react-dom/cjs/react-dom.development.js:22167:7)
    at /home/runner/work/kiali/kiali/frontend/node_modules/react-dom/cjs/react-dom.development.js:11379:30
    at unstable_runWithPriority (/home/runner/work/kiali/kiali/frontend/node_modules/scheduler/cjs/scheduler.development.js:465:16)
    at runWithPriority$1 (/home/runner/work/kiali/kiali/frontend/node_modules/react-dom/cjs/react-dom.development.js:11325:14)
    at flushSyncCallbackQueueImpl (/home/runner/work/kiali/kiali/frontend/node_modules/react-dom/cjs/react-dom.development.js:11374:13)
    at flushSyncCallbackQueue (/home/runner/work/kiali/kiali/frontend/node_modules/react-dom/cjs/react-dom.development.js:11362:7)
    at scheduleUpdateOnFiber (/home/runner/work/kiali/kiali/frontend/node_modules/react-dom/cjs/react-dom.development.js:21731:13)
    at Object.enqueueSetState (/home/runner/work/kiali/kiali/frontend/node_modules/react-dom/cjs/react-dom.development.js:12502:9)
    at WorkloadPodLogsComponent.Object.<anonymous>.Component.setState (/home/runner/work/kiali/kiali/frontend/node_modules/react/cjs/react.development.js:358:20)
    at /home/runner/work/kiali/kiali/frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx:1073:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

**Comment by jmazzitelli** [comment]
@jshaughn before we merge this (it looks like tests are passing now), let's see if we can revert this line (thus allowing people to keep using Node 14 if they want). I have a feeling this will all work with Node 14 through 16:

From `frontend/package.json`:
```
  "node": "^16.19.1",
```

**Comment by jmazzitelli** [comment]
ok. it's all green. let me push this change that allows node 14 users to keep it.

**Review by jshaughn — APPROVED** [review]
Let there be ARM!

**Comment by jmazzitelli** [comment]
Using the online version calculator https://semver.npmjs.com/ if we use `^14.17.0 || >= 16.0.0` that will enable us to use our old node 14, plus node 16 and node 18 (which apparently also works).
I will add that in the next commit.

**Review by aljesusg — APPROVED** [review]
LGFM tested it locally

**Review by ferhoyos — APPROVED** [review]
LGTM

**Review by jshaughn — APPROVED** [review]
Still good.

**Pull request merged**
