### PR TITLE
Fix Jenkins releases

### PR DESCRIPTION
**Pull request by israel-hdez**
Jenkins was still using the kiali/kiali-ui repo and bundling that. These
changes should update Jenkins to only use the unified kiali/kiali repo.
This is a simple "patch" since it is know that we are already in the
process of phasing out Jenkins (i.e. this is just best effort patches).

Related to #4827

### CODE REVIEW

**Comment by israel-hdez** [comment]
Currently, I don't have a way to setup a Jenkins box to test. So, I'm simply hoping this is right.
I'll see if this works if the edge image is pushed.

**Comment by jmazzitelli** [comment]
partial dup of https://github.com/kiali/kiali/pull/4903

**Comment by israel-hdez** [comment]
@jmazzitelli OK, I'll remove my changes to the front-end, because that other PR is more complete.

**Comment by israel-hdez** [comment]
@jmazzitelli Changes to front-end are now removed from this PR.

**Review by jmazzitelli — APPROVED** [review]
this looks correct.

**Comment by israel-hdez** [comment]
@jmazzitelli I had to fix a path. I hope you can re-approve.

**Pull request merged**
