### PR TITLE
[OSSM-5715] be able to deploy error-rates and bookinfo demo on arm64 hardware

### PR DESCRIPTION
**Pull request by jmazzitelli**

### CODE REVIEW

**Review by FilipB — APPROVED** [review]
Assuming arm images are available in dockerhub - https://hub.docker.com/r/istio/examples-bookinfo-productpage-v1/tags
OS/ARCH
linux/amd64
linux/arm64

**Comment by FilipB** [comment]
Actually we don't have arm image for traffic generator - https://github.com/kiali/kiali/blob/8b8b6677a331b1e6e52b396e90d0e9c3ede3787e/hack/istio/install-bookinfo-demo.sh#L439

**Comment by FilipB** [comment]
@ScriptingShrimp What's the plan with traffic generator image?

**Comment by ScriptingShrimp** [comment]
> @ScriptingShrimp What's the plan with traffic generator image?

I think we will need build image for traffic generator for bookinfo, since a lot of regression scenarios is dependent on a generated traffic in bookinfo app.

**Comment by ScriptingShrimp** [comment]
see [OSSM-5734](https://issues.redhat.com/browse/OSSM-5734) traffic generator for ARM

**Comment by FilipB** [comment]
Thanks, merging.

**Comment by jmazzitelli** [comment]
> We will need build ARM image for traffic generator for bookinfo

This is available now: https://quay.io/repository/kiali/kiali-test-mesh-traffic-generator?tab=tags

**Pull request merged**
