### PR TITLE
Upgrade patternfly to 5.0.4

### PR DESCRIPTION
**Pull request by aljesusg**
Fix https://github.com/kiali/kiali/issues/6587

Remove CI=false
Fix some issues relted with patternfly 5.0.2

### CODE REVIEW

**Review by jshaughn — CHANGES_REQUESTED** [review]
It builds and runs for me locally but it won't build in CI because it treats warnings like errors:

```
Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.

Failed to compile.

Warning
(1[50](https://github.com/kiali/kiali/actions/runs/6113553385/job/16594175197?pr=6588#step:4:51):3) autoprefixer: start value has mixed support, consider using flex-start instead
```

Looks like we need to either get rid of the warning or ignore it.

**Comment by aljesusg** [comment]
> It builds and runs for me locally but it won't build in CI because it treats warnings like errors:
> 
> 
> 
> ```
> 
> Treating warnings as errors because process.env.CI = true.
> 
> Most CI servers set it automatically.
> 
> 
> 
> Failed to compile.
> 
> 
> 
> Warning
> 
> (1[50](https://github.com/kiali/kiali/actions/runs/6113553385/job/16594175197?pr=6588#step:4:51):3) autoprefixer: start value has mixed support, consider using flex-start instead
> 
> ```
> 
> 
> 
> Looks like we need to either get rid of the warning or ignore it.

I opened an issue, they didn't update the deps in react-topology library. I added the issue to the epic so let's wait until they make the release

**Comment by aljesusg** [comment]
Found the problem, they need to update the deps but we had in the yarn.lock both react-styles installed. yarn management is not upgrading correctly this. So ...FIXED !

**Review by ferhoyos — APPROVED** [review]
LGTM, tested locally. Glad to check that autoprefixer warnings have been removed.

**Pull request merged**
