### PR TITLE
[v1.73] remove the usage of istiod /debug/endpointz entirely (#6673)

### PR DESCRIPTION
**Pull request by hhovsepy**
Cherry-pick of https://github.com/kiali/kiali/pull/6673
Original issue https://github.com/kiali/kiali/issues/6510

Initial requirement of Kiali v1.73 support in Istio 1.20.0 https://github.com/kiali/kiali/issues/7090

### CODE REVIEW

**Comment by ferhoyos** [comment]
Will we be able to run Istio 1.18 with Kiali 1.73 if we merge this PR? Or is it a breaking change?

**Comment by hhovsepy** [comment]
It still runs on Istio 1.18.

**Review by josunect — APPROVED** [review]
LGTM

Tested with Istio 1.18.9 & 1.20.1

**Review by jmazzitelli — APPROVED** [review]
LGTM

**Pull request merged**
