### PR TITLE
[pft graph] Selection based zoom

### LINKED ISSUE #7929: Enable the Selection-based zoom in PFT
### What do you want to improve?

The latest version of the `react-topology` library (v5.4.1) has introduced selection-based zoom, a feature previously used in the Cytoscape graph. It would be great to enable selection-based zoom in the PFT graph as well.

### What is the current behavior?

Selection-based zoom is not currently active in the PFT graph.

### What is the new behavior?

When the user holds the **Shift** or **Ctrl** key and drags to select an area, the graph will zoom into the selected region.

### PR DESCRIPTION
**Pull request by ferhoyos**
### Describe the change

The latest version of the `react-topology` library (v5.4.1) introduces selection-based zoom, a feature previously available in the Cytoscape graph. This PR enables selection-based zoom functionality in the Patternfly Traffic and Mesh graphs.

Kooha-2024-11-18-17-06-16

**Bonus:**
- Hide the kebab toggle menu in nodes without relying on CSS tricks, thanks to the new `react-topology` parameter `hideContextMenuKebab`. The kebab toggle menu for groups is still pending (https://github.com/patternfly/react-topology/issues/254).

- Increase the font size of the node labels on the Mesh page.

Before:

image

After:

image

- Hide the context menu for the namespace box (no options are available to select).

image

### Steps to test the PR

Verify that the selection based zoom works correctly.

### Automation testing

N/A

### Issue reference

Closes #7929

### CODE REVIEW

**Review by jshaughn — CHANGES_REQUESTED** [review]
Code looks good. Feature tested and looks good. I submitted a small sub-pr to just add the new feature to the graph and mesh shortcuts help. https://github.com/ferhoyos/kiali/pull/7

CI is failing, I'll re-run it, looks like flakes.

**Comment by jshaughn** [comment]
Also, I noticed a separate issue when testing.  I don't think it's the PR. I'll have to test and see if it's the upgrade, but when the graph is large, performing a "reset view" (click on the leftmost control-planel icon) does not return it to the original size, it's too big.

**Comment by ferhoyos** [comment]
Thanks @jshaughn for the sub-PR, good catch

**Review by jshaughn — APPROVED** [review]
Ah, thanks for fixing the CI. Everything looks great.

**Pull request merged**
