### PR TITLE
[CI] K8s Gateway API integration tests

### PR DESCRIPTION
**Pull request by hhovsepy**
RFE https://github.com/kiali/kiali/issues/5726

Installing K8s Gateway API on CI env.
Added Gateway API Objects validations tests.

### CODE REVIEW

**Comment by hhovsepy** [comment]
It seems cypress failure is not a flake. Checking...

**Review by jshaughn — COMMENTED** [review]
The same cypress test has failed twice in a row.  I don't see why these changes would affect the cypress test, but it is related to gateways:  "1) KIA1102 validation".

**Comment by hhovsepy** [comment]
Ok, rechecked the failing tests, the relation to gateways "KIA1102" validation is just a coincidence.
The test creates a VS but while checking the status icon it timeouts loading newly created object.
So this requires a separate issue.

**Comment by hhovsepy** [comment]
@jshaughn tests are passing in 2 runs in a raw.

**Comment by jshaughn** [comment]
@hhovsepy Excellent news, that one was a pita.  I will test locally and let you know the result.

**Review by jmazzitelli — COMMENTED** [review]
the hack script changes look good. I'll defer to jay for his review/approval.

**Review by jshaughn — APPROVED** [review]
LG, thanks @hhovsepy !

**Pull request merged**
