### PR TITLE
fix bug when doing cluster-scoped lookups when not authorized to do so [OSSM-3868]

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/6114

### CODE REVIEW

**Comment by jmazzitelli** [comment]
This PR is now in a state where it looks like the errors are averted. However, you will now see things like this:

```
2023-05-08T13:44:25-04:00 ERR GetIstioConfigList needs a non empty Namespace
```

This is because the code is written in such a way that it doesn't look valid when we do not have cluster wide access permissions. When cluster_wide_access is false, it means we cannot query for resources unless a non-empty string namespace is specified - and in some cases that rule is violated.

**Comment by jmazzitelli** [comment]
I would like a review of this. With `deployment.accessible_namespaces` set to something like `['istio-system']` (i.e. NOT `**`), and `deployment.cluster_wide_access` set to `false` (which is the default if AN is not `**`), and `external_services.istio.istio_api_enabled` set to `false` this will no longer spew out errors in the logs or the UI. It will log a debug message saying you are losing capabilities with that setup.

One thing I don't understand is why, when I go to a specific namespace's Istio Config page in the UI, it still wants to access "AllNamespaces" when querying resources.

**Comment by josunect** [comment]
Thanks, @jmazzitelli ! I will have a look

**Comment by josunect** [comment]
@jmazzitelli , I have applied these changes in this PR https://github.com/kiali/kiali/pull/6116/files to merge with master and test in OCP pipeline. I have to merge in order to have the no_istiod tests running, as the code before the last commit in master had no working istio config tests that prevented to run the no_istiod tests. 

I'm afraid the tests are still failing with not a lot of information about the error. But I do think your changes makes sense, it would probably be another call with that parameter. I think this change wouldn't be needed after this PR but I think it will be required: https://github.com/kiali/kiali/blob/master/kubernetes/cache/kube_cache.go#L358

**Comment by josunect** [comment]
I'm re running the tests. I think this must work and there was just an error in the validations test. The validations should be available now with your changes.

**Review by josunect — APPROVED** [review]
Test no_istiod passed in OCP

**Pull request merged**
