### PR TITLE
KIALI-1578 KIALI-1136 Show WARN on all DRs with duplicate hosts

### PR DESCRIPTION
**Pull request by burmanm**
All offending DestinationRules should be flagged with WARN, not just the last one. Also, fix a typo that caused the warnings to be filtered and add the warns to the config listing also.

### CODE REVIEW

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#100](https://paste.fedoraproject.org/paste/4JYmb125YySJVA8CzHOPfg)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1418]](https://paste.fedoraproject.org/paste/YKcdQyjYdKWNouQamWoQ2g)
  * :heavy_check_mark: Istio-Upstream [#[291]](https://paste.fedoraproject.org/paste/ImFBhtlG0KPOg4ncTTjNkg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1378, 1379]](https://paste.fedoraproject.org/paste/xXTSDTktWbLNykK4z4R~Xw)
  * :heavy_check_mark: install-bookinfo [#[779]](https://paste.fedoraproject.org/paste/3Do2U6L3NT2SVxSENxqQdw)
  * :heavy_check_mark: Kiali-on-Openshift [#[781]](https://paste.fedoraproject.org/paste/pNWXP39WUsEamn49SOQz9w)
  * :heavy_check_mark: run-kiali-e2e-tests [#[225]](https://paste.fedoraproject.org/paste/fIcBqqbfEfBtfRsG1vSMdQ)


KIALI_NAME=kialicorepr521-istio-system

**Comment by hhovsepy** [comment]
Warn Icon is shown on Istio Config list and details page.
But it is missing in Service Detail's "Destination Rules" tab:
screenshot from 2018-09-27 09-17-14

**Comment by burmanm** [comment]
As I commented on JIRA, the Service Details is not intended to display other than pod-type validations at this point.

**Comment by lucasponce** [comment]
Sorry for my delay to jump on the review.
@hhovsepy is right that in the service validations used by the UI:
```
    let promiseValidations = API.getServiceValidations(
      authentication(),
      this.props.match.params.namespace,
      this.props.match.params.service
    );
```
We invoke the ServiceValidations which includes the VR validations from the backend:
```
// GetServiceValidations returns an IstioValidations object with all the checks found when running
// all the enabled checkers.
func (in *IstioValidationsService) GetServiceValidations(namespace, service string) (models.IstioValidations, error) {
	// Get Gateways and ServiceEntries to validate VirtualServices
	var err error
	wg := sync.WaitGroup{}
	errChan := make(chan error, 2)

	vs := make([]kubernetes.IstioObject, 0)
	dr := make([]kubernetes.IstioObject, 0)

	wg.Add(2)
	go fetch(&vs, namespace, service, in.k8s.GetVirtualServices, &wg, errChan)
	go fetch(&dr, namespace, service, in.k8s.GetDestinationRules, &wg, errChan)
	wg.Wait()
	if len(errChan) != 0 {
		err = <-errChan
		return nil, err
	}
	objectCheckers := []ObjectChecker{
		checkers.VirtualServiceChecker{namespace, dr, vs},
	}

	// Get group validations for same kind istio objects
	return runObjectCheckers(objectCheckers), nil
}
```

So, I think DR should also apply here as well, and potentially the UI should also shown same scheme of icons as happens in the Istio Config.

Also, I am not sure if perhaps we can change this to avoid inconsistencies between the Istio Config validations vs the Service Validations and perhaps the Service Details UI should get the list of services and invoke the same logic used in the Istio Config (I see some duplication here we introduced in the past, not on this PR).

Anyway, let me know what do you think.

Perhaps it's a good moment to refactor this area, clean the duplication between validation and simplify the endpoints used.

I.e. instead to have a validation for istio_config and other for service details; service details can provide the vs/dr and UI invoke the istio_config validations (as similar way it happens with the health).
Then validation would happen from only a single endpoint.

**Comment by burmanm** [comment]
Yes, I think the validation should happen in a refactored way. That serviceValidations is missing multiple validations, including noServiceChecker for VirtualServices since these are all defined in different places. Thus, the whole code is quite spaghetti with duplication of data.

**Comment by lucasponce** [comment]
> That serviceValidations is missing multiple validations, including noServiceChecker for VirtualServices since these are all defined in different places. 

+1

> Thus, the whole code is quite spaghetti with duplication of data.

This is a known technical debt because original design was to validate per object, at the moment we introduced two views for same object (VS can be shown under ServiceDetails and Istio Config) we maintained the backend endpoint for validations trying to sync on the backend.

But we don't have goto sentences in the code :-) jumping from one place to another without logic.

So, now it is good moment to refactor and simplify this.

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#117](https://paste.fedoraproject.org/paste/WqHLAf~sB3JcgNN01KkD1Q)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1434]](https://paste.fedoraproject.org/paste/LB~NqwAPcTJpMebookZ1nA)
  * :heavy_check_mark: Istio-Upstream [#[305]](https://paste.fedoraproject.org/paste/1MeEDZgwILDmVn2sGOWKpg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[1416, 1415]](https://paste.fedoraproject.org/paste/TUY5ow3GbG4knHr8ferGUg)
  * :heavy_check_mark: install-bookinfo [#[801]](https://paste.fedoraproject.org/paste/v9MZSa4K5x~t7VTfWbyulw)
  * :heavy_check_mark: Kiali-on-Openshift [#[799]](https://paste.fedoraproject.org/paste/BgfC0py5ZZuZikeKTVL4wA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[243]](https://paste.fedoraproject.org/paste/sul4WOZabdpskJOULM9BUg)


KIALI_NAME=kialicorepr521-istio-system

**Comment by hhovsepy** [comment]
PR verified:
kiali-ui 0.8.0 (45044cb29f7fbb5e1cf9d3e9f3d6d328dde3515c)
kiali v0.8.0-SNAPSHOT (4dc40b2facf64d9ce571221c38c6a18a94ecc27f)

**Comment by lucasponce** [comment]
Thanks @burmanm and @hhovsepy

**Pull request merged**
