### PR TITLE
Multicluster - Service details view

### PR DESCRIPTION
**Pull request by josunect**
Fixes https://github.com/kiali/kiali/issues/5964

### CODE REVIEW

**Comment by hhovsepy** [comment]
It seems we are doing duplicate work https://github.com/kiali/kiali/pull/5994/

**Comment by josunect** [comment]
> It seems we are doing duplicate work #5994

Thanks for pointing at this, @hhovsepy !

**Comment by josunect** [comment]
Many things were addressed in other PRs. I will open a new PR with what is missing.

**Comment by josunect** [comment]
Many things were addressed in other PRs. I will open a new PR with what is missing.

**Pull request closed without merging**
