### PR TITLE
[multi-cluter] Resolve the network of discovered clusters

### PR DESCRIPTION
**Pull request by israel-hdez**
In multi-cluster enabled meshes, each cluster is assigned to a network. The Control Plane requires a logical network ID to be assigned to each network in the mesh.

This changes find what's the logical network ID configured on each discovered cluster and is reported in the response JSON.

Related kiali/kiali#3448
Front-end PR: https://github.com/kiali/kiali-ui/pull/2012

### CODE REVIEW

**Comment by israel-hdez** [comment]
@xeviknal Your IRC comments are fixed.

**Review by xeviknal — APPROVED** [review]
LGTM!

**Review by cfcosta — APPROVED** [review]
LGTM

**Comment by israel-hdez** [comment]
@xeviknal @cfcosta Thanks for your reviews.

**Pull request merged**
