### PR TITLE
support more include/exclude features in namespaces api

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/5516

server PR: https://github.com/kiali/kiali/pull/5521
operator PR: https://github.com/kiali/kiali-operator/pull/574
doc PR: https://github.com/kiali/kiali.io/pull/587

### CODE REVIEW

**Comment by jmazzitelli** [comment]
With this PR and the operator PR, run the molecule tests to see things working.
1. Install minikube and Istio
2. Push the dev images into minikube via `make -e CLUSTER_TYPE=minikube build cluster-push`
3. Run molecule tests: `hack/run-molecule-tests.sh -ce $(which kubectl) -mp ci -ct minikube -udi true`

Results should be:
```
=====================
=== TEST RESULTS: ===
=====================

              accessible-namespaces-test... success [10m 10s]
     affinity-tolerations-resources-test... success [4m 23s]
                      config-values-test... success [3m 22s]
                  default-namespace-test... success [2m 31s]
                            grafana-test... success [4m 25s]
                        header-auth-test... success [2m 21s]
                      instance-name-test... success [3m 41s]
                             jaeger-test... success [3m 28s]
                            metrics-test... success [3m 3s]
                     null-cr-values-test... success [2m 17s]
                only-view-only-mode-test... success [3m 17s]
                             openid-test... success [2m 26s]
                     openshift-auth-test... skipped
                   os-console-links-test... skipped
                 read-certs-secrets-test... success [2m 21s]
                              roles-test... success [6m 36s]
                    rolling-restart-test... success [3m 22s]
                              token-test... success [2m 48s]
```

**Comment by jmazzitelli** [comment]
Some manual testing that I did. First, to set this up:

1. Install minikube and deploy Istio in it.
2. Create 4 namespaces:
- `mazz1`
- `mazz2`
- `mazztest1`
- `mazztest2`
3. `make -e CLUSTER_TYPE=minikube build build-ui cluster-push operator-create kiali-create` to install a default Kiali installed.

The tests will look at what cards are displayed in the Overview page and what namespaces show up in the namespaces drop down menu in the Graph page. The cards and the menu should show the same namespaces in all tests. Note that you always need to include the control plane, so that is always shown. We may want to enhance this PR to always include and never exclude the control plane namespace, but for now, you must include it explicitly.

1. The default Kiali (which uses `deployment.accessible_namespaces: ["**"]`) shows all namespaces (except system namespaces like kube-system).
2. Edit the Kiali CR and set `api.namespaces.include` to only show all "mazz*" namespaces in Kiali
```yaml
  api:
    namespaces:
      include:
      - istio-system
      - mazz.*
  deployment:
    accessible_namespaces:
    - '**'
```
3. Edit the Kiali CR and set `api.namespaces.exclude` to exclude all "mazztest*" namespaces in Kiali - thus, only "mazz1" and "mazz2" namespaces are shown.
```yaml
  api:
    namespaces:
      include:
      - istio-system
      - mazz.*
      exclude:
      - mazztest.*
  deployment:
    accessible_namespaces:
    - '**'
```
4. Edit the mazztest1 and mazztest2 namespace and add the label "customLabel: test" to them both. You know you did it right when this returns both "mazztest1" and "mazztest2" namespaces: `kubectl get ns -l customLabel=test`
5. Edit Kiali CR and set `api.namespaces.label_selector_include` to `customLabel=test`. Thus, only "mazztest1" and "mazztest2" namespaces are shown.
```yaml
  api:
    namespaces:
      include:
      - istio-system
      label_selector_include: "customLabel=test"
  deployment:
    accessible_namespaces:
    - '**'
```
6. Edit Kiali CR and set `api.namespaces.label_selector_exclude` to `customLabel=test`. Remove `api.namespaces.label_selector_include` that you added in the previous step. Include all mazz* namespaces. Now you will exclude those two namespaces with the label - you will only see "mazz1" and "mazz2".
```yaml
  api:
    namespaces:
      include:
      - istio-system
      - mazz.*
      label_selector_exclude: "customLabel=test"
  deployment:
    accessible_namespaces:
    - '**'
```

**Comment by jmazzitelli** [comment]
After that long set of manual tests I ran above, I have realized that we should always include the control plane and not require the user to explicitly specify it in `include` or have it included via a label selector. You should always see the control plane.

**Comment by jmazzitelli** [comment]
New commit will always include the namespace. One interesting side effect I have seen... if you do not have the control plane namespace match the label_selector_include, nothing breaks and the overview page doesn't show the control plane namespace. This is a nice feature - some people might not want the user to see the control plane.

However, if it is not specified in the includes list (and the control plane namespace isn't automatically added for you), an error occurs ("Error fetching Istio deployment status.") due to the fact kiali can't get the control plane namespace (I suppose its trying to get the list of namespaces and the control plane namespace doesn't come back in the results). This is why I had the includes list always include the control plane namespace even if the user didn't explicitly specify it.

What is the end result?

If the kiali admin doesn't want users to see the control plane namespace, you have to use the label_selector_include with accessible_namespaces set to "**". There is no other way to do it (the control plane namespace will be automatically added to the include list and the accessible namespaces list). Even if you specify the control plane ns in the exclude list, that error will occur. I don't know why label_selector_include behaves differently.

**Comment by jmazzitelli** [comment]
For the record, I just ran the molecule tests again with the latest code - all pass on minikube.

**Comment by jmazzitelli** [comment]
In the process of testing on OpenShift 4.10 (which is important because the GetNamespaces has different paths when needing to obtain Projects as opposed to Namespaces). The first main test (accessible-namespaces-test) has passed, so that's a good thing.

**Review by jshaughn — APPROVED** [review]
+1 to the control plane namespace being always accessible.  Let's hope this is good forever now, that long comment should be like gospel.

**Pull request merged**
