### PR TITLE
make sure RegistryConfiguration is initialized with empty arrays.

### PR DESCRIPTION
**Pull request by jshaughn**
Fixes https://github.com/kiali/kiali/issues/4892

@lucasponce I'm not as familiar with this code as you, but this seems to be the root of a UI crash I've been getting, as described in the issue.  Please take a look.  If this is in fact a desierd fix, I think we may need a 1.48 backport.

### CODE REVIEW

**Comment by lucasponce** [comment]
The patch looks good.
But I'm curious how you got to this error. How did you reproduce the error? I can review if there is anything missing in the logic.

**Comment by jshaughn** [comment]
> But I'm curious how you got to this error.

I didn't really try to do anything special, I am running the travel demo against master,, but do not create any gateways (so not the tutorial, just the vanilla travel demo installed by hack script).  I go to the services list view and select the cars service detail.  For me I saw the problem every time.  At first I thought it was due to my PF branch, but then I was able to see it on master as well.  This is why I am thinking we may need a backport.

**Comment by lucasponce** [comment]
> I go to the services list view and select the cars service detail. For me I saw the problem every time. At first I thought it was due to my PF branch, but then I was able to see it on master as well. This is why I am thinking we may need a backport.

Let me investigate this. As commented, patch was ok, but I haven't seen this problem before, so I'd like to see if it's related or there is a hidden problem around.

**Comment by lucasponce** [comment]
Ouch, nice catch @jshaughn!
You're right, we populate the dev environment always the "bookinfo" gateway that this case was completely missed.

**Review by lucasponce — APPROVED** [review]

**Comment by lucasponce** [comment]
I'll prepare a cherry-pick PR for the v1.48

**Pull request merged**
