### PR TITLE
[hack] be able to install in a non-default namespace

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/3714

The problem here is we need to also workaround a bug in istioctl that also doesn't allow us to install in a non-istio-system namespace. We need that bug to be fixed. For now, there is workaround code in here that avoids that istioctl bug.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
@pbajjuri20 see if this works. I implemented a workaround for https://github.com/istio/istio/issues/30897 - I think it is working (pods are starting up on my cluster) but you should test this to see if it works for you.

**Comment by pbajjuri20** [comment]
I have executed in my local with new code change:

Command:
./install-istio-via-istioctl.sh -n istio-system4

error:

the namespace from the provided object "kube-system" does not match the namespace "istio-system4". You must pass '--namespace=kube-system' to perform this operation.
the namespace from the provided object "istio-system44" does not match the namespace "istio-system4". You must pass '--namespace=istio-system44' to perform this operation.
Failed to install Istio with profile [demo]

**Comment by jmazzitelli** [comment]
@pbajjuri20 for now, in order for the workaround that I implemented to work, it looks like you can't have the name of your namespace start with "istio-system" --- so do not call it "istio-system4" --- try something else... like "my-istio-4".

**Comment by jmazzitelli** [comment]
@pbajjuri20 I just committed something that I think should allow you to use "istio-system4" (or any namespace with "istio-system" in the name).

**Comment by pbajjuri20** [comment]
running this command on openshift:

./install-istio-via-istioctl.sh -n istio-system46

It created the istiod, istio-ingress and istio-egress pods on the "istio-system46"  namespace

error:
the namespace from the provided object "kube-system" does not match the namespace "istio-system46". You must pass '--namespace=kube-system' to perform this operation.
Failed to install Istio with profile [demo]

**Comment by jmazzitelli** [comment]
> the namespace from the provided object "kube-system" does not match the namespace "istio-system46". You must pass '--namespace=kube-system' to perform this operation.

The reason for these errors is because when installing on OpenShift we enable CNI and to enable CNI the istioctl generates yaml that has resources with namespace hardcoded to kube-system, for example:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: istio-cni-config
  namespace: kube-system
```

And "op apply" doesn't like this when you specify "-n namespace" on the command line. I think if I take that out, this error goes away. Let me try that.

**Comment by jmazzitelli** [comment]
OK, that is fixed. But now there is another problem - because we are not able to use `istioctl manifest install` but instead are forced to do a `istioctl manifest generate`, we have to create the resources by passing the full generated yaml to `oc apply` and hope all the resources can be created. But that is not possible because it goes too fast - the infrastructure can't come up fast enough and so you will see these errors:

```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.mazz4.svc:443/validate?timeout=30s": service "istiod" not found
```

**Comment by jmazzitelli** [comment]
This works for me on OpenShift now.

`./install-istio-via-istioctl.sh -n istio-system4`

**Comment by pbajjuri20** [comment]
Tested with latest commit, expected pods are running 

Command: 
./install-istio-via-istioctl.sh -n istio-system4

istio-system434

**Review by pbajjuri20 — APPROVED** [review]

**Comment by jmazzitelli** [comment]
@jshaughn since you use this hack script alot, I would like you to review this too. If it is OK, you can merge it in.

**Comment by jmazzitelli** [comment]
@pbajjuri20 After talking to some Istio folks, I found the settings needed to pass to istioctl, so I changed this script to pass the correct settings. However, there is still an istioctl bug that we need to workaround but only if we are not installing in istio-system. This PR has that workaround.

I tested on OpenShift - installing in istio-system and non-istio-system namespaces (as well as uninstalling using the `di true` option). All of that seems to work.

I did NOT yet test on minikube.

@jshaughn I still would like you to test this as well.

**Comment by pbajjuri20** [comment]
Command:
./install-istio-via-istioctl.sh -n istio-system43
./install-istio-via-istioctl.sh -n istio-system123


I have run the script with non-istio-system i..e, istio-system43, istio-system123 on Openshift. it is installing all the pods - no issue found here.


I have tried to run with istio-system namespace: it is not installing, it takes too much time. I have tried a couple of time
command:
./install-istio-via-istioctl.sh 
./install-istio-via-istioctl.sh -n istio-system

error:
Error: failed to install manifests: errors occurred during operation

http://pastebin.test.redhat.com/941106
 
It is installed 3 pods

Istio-system_pods

**Comment by pbajjuri20** [comment]
sorry, it is my cluster issue.

I have tried on another Openshift cluster, it works perfectly with Istio-system and non-istio-system

**Comment by jmazzitelli** [comment]
> I have tried to run with istio-system namespace: it is not installing, it takes too much time. I have tried a couple of time

I see that all the time (even before this PR). The remote cluster can't seem to bring up the system in a short time. I just keep repeating until it installs. That's why I now have that repeating retry in this script in this PR - because that's how I always got it to work before - just had to keep retrying.

Note that when you use istio-system (the default), it is using the same code it used before (nothing changed - the script uses the same command as before) so nothing in this PR would have broken that. Perhaps the issue is trying to use istioctl to install multiple clusters that exist at the same time? That is something we need to verify - is it even possible for istioctl to be able to install multiple Istio control planes so they co-exist together in a cluster??

FWIW: I just tried on minikube installing (and uninstalling) in istio-system and istio-system4 and both worked (but I uninstalled the one before trying to install the second).

I also just tried on OpenShift and it also worked (again, installing only one - making sure I uninstall others):

```
$ oc get pods -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
grafana-784c89f4cf-vrnr8                1/1     Running   0          14s
istio-egressgateway-565d5f7f89-9m2vh    1/1     Running   0          46s
istio-ingressgateway-75fdf7497d-5j99p   1/1     Running   0          45s
istiod-767f4c8f45-q9hq9                 1/1     Running   0          54s
jaeger-7f78b6fb65-2m572                 1/1     Running   0          17s
kiali-dc84967d9-4l8rr                   1/1     Running   0          32s
prometheus-7bfddb8dbf-4b57t             2/2     Running   0          15s
```
```
$ oc get pods -n istio-system4
NAME                                   READY   STATUS    RESTARTS   AGE
grafana-784c89f4cf-wgbpx               1/1     Running   0          33s
istio-egressgateway-949694554-fz7r4    1/1     Running   0          45s
istio-ingressgateway-c8676f9b9-9lj5k   1/1     Running   0          45s
istiod-779f57bff9-bx67k                1/1     Running   0          45s
jaeger-7f78b6fb65-q62l2                1/1     Running   0          37s
kiali-dc84967d9-lzhxp                  1/1     Running   0          41s
prometheus-7bfddb8dbf-769vd            2/2     Running   0          35s
```

I just tried to install TWO Istio control planes together, the first worked, the second one seems to be hanging.
I think it might have to do with the fact that egress/ingress are enabled on both. I wonder if you can't do that - you might only be allowed a single ingress/egress. So on the second attempt, try to disable that via: `-iee false` (I just tried it and it seems to be hanging on waiting for ingress - might need to add an option to turn off ingress, too - I think the script will always attempt to install that).

**Comment by pbajjuri20** [comment]
I have tried a couple of times. with the option 

> "-iee false"

 and without options -- no issues found

```
oc get pods -n istio-system4333
NAME                                    READY   STATUS    RESTARTS   AGE
grafana-784c89f4cf-lnk6x                1/1     Running   0          31s
istio-egressgateway-5c8c98568b-6cvsj    0/1     Running   0          44s
istio-ingressgateway-6c8bbd4b4c-hm6nq   0/1     Running   0          43s
istiod-5799bffbfd-cm6lz                 1/1     Running   1          43s
jaeger-7f78b6fb65-jp5rn                 1/1     Running   0          28s
prometheus-7bfddb8dbf-2sgp6             2/2     Running   0          34s
 oc get pods -n istio-system433
NAME                                    READY   STATUS    RESTARTS   AGE
grafana-784c89f4cf-72n7q                1/1     Running   0          2m51s
istio-ingressgateway-55646cfd45-smptf   0/1     Running   0          3m
istiod-6479c574b9-wvfld                 1/1     Running   0          3m
jaeger-7f78b6fb65-bbbht                 1/1     Running   0          2m48s
prometheus-7bfddb8dbf-mx442             2/2     Running   0          2m54s
```

**Comment by jmazzitelli** [comment]
@pbajjuri20 please pull the latest changes in this PR and try again. I added a new option `-iie` - this allows you to disable the Istio Ingressgateway. It seems like you can only have one ingressgateway (and egressgateway) in the cluster - this let's you turn it off for all the others.

By default, this setting is "true". To turn it off, pass in `-iie false` when you call the script. You do not need to do this for the FIRST control plane you install - but any others you need to turn that off by passing "false". Do the same with `-iee` option.

I tried this on my OpenShift cluster and I was able to install 2 control planes successfully.  I ran:

```
./install-istio-via-istioctl.sh
./install-istio-via-istioctl.sh -n istio-system4 -iie false -iee false
```

This results in:
```
$ oc get pods -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
grafana-784c89f4cf-tvq62                1/1     Running   0          61s
istio-egressgateway-565d5f7f89-pwxbt    1/1     Running   0          73s
istio-ingressgateway-75fdf7497d-4mfpg   1/1     Running   0          72s
istiod-767f4c8f45-fq4wk                 1/1     Running   0          84s
jaeger-7f78b6fb65-mjxz4                 1/1     Running   0          59s
prometheus-7bfddb8dbf-nwwqz             2/2     Running   0          62s

$ oc get pods -n istio-system4
NAME                          READY   STATUS    RESTARTS   AGE
grafana-784c89f4cf-xmcj4      1/1     Running   0          27s
istiod-779f57bff9-slwpc       1/1     Running   0          30s
jaeger-7f78b6fb65-strfn       1/1     Running   0          25s
prometheus-7bfddb8dbf-7sjmb   2/2     Running   0          28s
```

I also tried it by creating the istio-system namespace second (which uses istioctl manifest install, not generate, so it runs the operator - notice this doesn't hang like it did before):

```
./install-istio-via-istioctl.sh -n istio-system4
./install-istio-via-istioctl.sh -iie false -iee false
```

Results:

```
$ oc get pods -n istio-system
NAME                          READY   STATUS    RESTARTS   AGE
grafana-784c89f4cf-tcghw      0/1     Running   0          12s
istiod-767f4c8f45-fw5cx       1/1     Running   0          25s
jaeger-7f78b6fb65-dfn57       1/1     Running   0          9s
prometheus-7bfddb8dbf-lkcpj   2/2     Running   0          13s

$ oc get pods -n istio-system4
NAME                                   READY   STATUS    RESTARTS   AGE
grafana-784c89f4cf-6tn57               1/1     Running   0          2m48s
istio-egressgateway-949694554-wklhn    1/1     Running   0          3m9s
istio-ingressgateway-c8676f9b9-gbc7h   1/1     Running   0          3m9s
istiod-779f57bff9-s2gwm                1/1     Running   0          3m9s
jaeger-7f78b6fb65-xhw7t                1/1     Running   0          2m46s
prometheus-7bfddb8dbf-fs65v            2/2     Running   0          2m49s
```

**Comment by pbajjuri20** [comment]
@jmazzitelli: Tested with the above suggestions on Openshift. It works perfectly.


$ oc get pods -n istio-system4332
NAME                                    READY   STATUS    RESTARTS   AGE
grafana-784c89f4cf-5x8gw                1/1     Running   0          6m27s
istio-egressgateway-8c545cbb-q2b7r      1/1     Running   0          6m39s
istio-ingressgateway-7fcb9bb65c-lptbg   1/1     Running   0          6m38s
istiod-76c59dbc5-snnn2                  1/1     Running   0          6m38s
jaeger-7f78b6fb65-qnd54                 1/1     Running   0          6m24s
prometheus-7bfddb8dbf-jgf8j             2/2     Running   0          6m30s

$ oc get pods -n istio-system
NAME                          READY   STATUS    RESTARTS   AGE
grafana-784c89f4cf-npvfp      1/1     Running   0          73s
istiod-767f4c8f45-mfj5r       1/1     Running   0          105s
jaeger-7f78b6fb65-gsq9j       1/1     Running   0          70s
prometheus-7bfddb8dbf-8tvgv   2/2     Running   0          75s

```

**Review by pbajjuri20 — APPROVED** [review]

**Pull request merged**
