### PR TITLE
[v1.86] Fix the apiVersion of ReferenceGrant in the Kiali wizard (#7464)

### PR DESCRIPTION
**Pull request by ferhoyos**
### Describe the change

Backport PR of #7464 for version v1.86

### CODE REVIEW

**Review by hhovsepy — APPROVED** [review]
lg, istio_config.go does use the beta1, no need to change.

**Comment by aljesusg** [comment]
Then we can close this one and backport is not needed it

**Comment by ferhoyos** [comment]
We still have the wizard issue, we can backport that change. Or maybe is it better to backport https://github.com/kiali/kiali/pull/7405 as well to promote and up to date all Istio `apiVersion` values to the ones defined in Istio version 1.22?

**Comment by aljesusg** [comment]
It seems that the promote is not in 1.86.0 was merged after so yes we should backport that one if is related with istio 1.22

**Comment by ferhoyos** [comment]
Replaced by https://github.com/kiali/kiali/pull/7466 to include backport PR of #7405

**Pull request closed without merging**
