### PR TITLE
Update Kiali to build with Go 1.19

### PR DESCRIPTION
**Pull request by MRafaydev**
** Describe the change **
This change updates the Kiali codebase to use Go 1.19 instead of Go 1.18 as the build environment. The reason for this change is that Go 1.18 is considered deprecated and is no longer receiving patches, making it less stable and compatible than more recent versions of the Go language.

_explanation of what it does_
This pull request updates the Kiali codebase to build with Go 1.19 instead of Go 1.18. Go 1.18 is should be considered as deprecated and no longer receives patches, so updating to a newer and maintained version will ensure stability and compatibility for Kiali.

Changes:
- Update the build scripts to specify Go 1.19 as the target version.
- Test the build process and application functionality with Go 1.19.
- have tested these changes on multiple platforms and confirmed that Kiali builds and works as expected with Go 1.19.

** Issue reference **
this issue is reference to https://github.com/kiali/kiali/issues/5799

### CODE REVIEW

**Review by jmazzitelli — CHANGES_REQUESTED** [review]
the Kiali project team prefers to pin to a z-stream release of Go so the builds are repeatable (1.19 could be 1.19.1 or 1.19.5 or anything in between). Please change to a z-stream release (it looks like the latest is 1.19.5).

**Comment by MRafaydev** [comment]
Dear John,

Thank you for your feedback on my pull request. I am a beginner contributor
to the Kiali project and I appreciate your guidance.I understand the
importance of using a specific z-stream release of Go for repeatable builds
and I have made the necessary updates to the codebase. I have changed the
build environment to use Go 1.19.5, the latest z-stream release, as per
your suggestion.

I have also tested the build process and application functionality with
this new version of Go, and I am confident that everything is working as
expected.I appreciate your support as a beginner contributor and I am open
to any further feedback or changes that may be required. Please let me know
if there is anything else I can do to make my contribution to the Kiali
project as valuable as possible.

Thank you again for your help, and I look forward to your response.

Best regards,
Muhammad Rafay

**Comment by jmazzitelli** [comment]
@leandroberetta with the last move to Go 1.18, I'm pretty sure we removed all the go versions that may have been mentioned in the Github Actions. So there may not be anything necessary to do - but can you confirm that there are no other changes that would need to be made in order to build our releases (other than the change made here to the Makefile)?

@aljesusg Similarly, is there anything we need to worry about for the downstream builds? Do our downstream build scripts have access to Go 1.19.5?

**Review by jmazzitelli — CHANGES_REQUESTED** [review]
@MRafaydev the CI build failed - this PR is incomplete. Something else needs to change in the CI workflows (I do not know which). This PR cannot be merged until the failure is fixed - probably something in the .github workflows or the scripts they use.

The error I see is:

```
Run make -e GO_BUILD_FLAGS=-race -e CGO_ENABLED=1 clean-all build
Cleaning...
Cleaning UI ...
fatal: go version '1.18.10' should be at least '1.19.5'
=> Please take a look at https://golang.org/doc/install to install or upgrade go.
make: *** [make/Makefile.build.mk:26: go-check] Error 1
Error: Process completed with exit code 2.
```

Cleaning...
Cleaning UI ...
fatal: go version '1.1[8](https://github.com/kiali/kiali/actions/runs/4098271412/jobs/7069640879#step:6:9).10' should be at least '1.1[9](https://github.com/kiali/kiali/actions/runs/4098271412/jobs/7069640879#step:6:10).5'
=> Please take a look at https://golang.org/doc/install to install or upgrade go.
make: *** [make/Makefile.build.mk:26: go-check] Error 1
Error: Process completed with exit code 2.

**Comment by aljesusg** [comment]
Hi @MRafaydev, thanks for your contribution. 

You need to perform more things to upgrade this. The problem here is https://github.com/kiali/kiali/blob/master/go.mod#L3 you need to do this 

`go mod edit -go=1.19`
`go mod tidy -v`

**Go mod tidy** will download all the dependencies that are required in your source files and update [go.mod ](https://github.com/kiali/kiali/blob/master/go.mod) file with that dependency. This also change the [go.sum](https://github.com/kiali/kiali/blob/master/go.sum)
This last command With -v flag, go mod tidy will print information of all the unused modules removed from go.mod file if any

The CI fail because this pull the go version in go.mod file and it's different from the one you've got in the makefile

@jmazzitelli 1.19.4 is available in our dowstream build but 1.19.5 not. I don't know when they are going to release it.
Testing now with 1.19.4. our scripts will be updated when 1.19.5 is released. I don't expect changes in minor releases.

**Comment by MRafaydev** [comment]
Noted.

**Comment by jmazzitelli** [comment]
```
you need to do this

go mod edit -go=1.19
go mod tidy -v

Go mod tidy will download all the dependencies that are required
in your source files and update [go.mod ](https://github.com/kiali/kiali/blob/master/go.mod)file
with that dependency. This also change the [go.sum](https://github.com/kiali/kiali/blob/master/go.sum)
This last command With -v flag, go mod tidy will print information
of all the unused modules removed from go.mod file if any.
```

We should document this somewhere - perhaps in one of our .adoc / .md files that we already have in the home directory??

**Comment by MRafaydev** [comment]
I just made the changes. Change to 1.19.4 please review.

**Comment by leandroberetta** [comment]
> @leandroberetta with the last move to Go 1.18, I'm pretty sure we removed all the go versions that may have been mentioned in the Github Actions. So there may not be anything necessary to do - but can you confirm that there are no other changes that would need to be made in order to build our releases (other than the change made here to the Makefile)? (_UPDATE: never mind - I see our github actions did fail due to this - so something else needs to change in this PR_)
> 
> @aljesusg Similarly, is there anything we need to worry about for the downstream builds? Do our downstream build scripts have access to Go 1.19.5?

@jmazzitelli in the workflows, the go job is using go.mod to pick the right version to run

**Pull request merged**
