### PR TITLE
hack script to deploy openshift to ibm cloud

### PR DESCRIPTION
**Pull request by jmazzitelli**

### CODE REVIEW

**Comment by jmazzitelli** [comment]
The ibm cluster does not work all the way with our make targets. I need to find out how to log into the image registry in order to be able to push images to it (`make cluster-push`). The `make cluster-add-users` doesn't work either.

`make cluster-status` does work.

**Comment by leandroberetta** [comment]
I tried this script but I'm getting the following error:

```
[lberetta@fedora kiali]$ ./hack/ibmcloud-openshift.sh 
📄 ==START CONFIG==
command=
NAME_PREFIX=lberetta
OPENSHIFT_VERSION=4.7_openshift
PLUGIN_INSTALL=true
PLUGIN_UPDATE=true
REGION=us-east

...
📄 Plugin [kubernetes-service] already installed
📄 Plugin [container-service] updated
📄 Plugin [container-registry] updated
📄 Plugin [observe-service] updated
📄 Plugin [infrastructure-service] updated
📄 Plugin [kubernetes-service] updated
🚨 ERROR: Invalid command.
```

**Comment by jmazzitelli** [comment]
There is now a "apikey" command that will create an IBM API Key that you can use to log into openshift via `oc login -u apikey -p $(cat ./apikey.txt)` (the key is stored in a "apikey.txt" file).

**Review by leandroberetta — APPROVED** [review]
Tested with my account. Cluster created ok!.

**Comment by jmazzitelli** [comment]
I'll merge this now. Any additional features or updates to it we can do in another PR.

**Pull request merged**
