### PR TITLE
Add Xunzhuo as a new maintainer

### PR DESCRIPTION
**Pull request by Xunzhuo**
**Describe the change**

Add Xunzhuo as a new maintainer

**Issue reference**

refer to: https://github.com/kiali/kiali/discussions/4730

### CODE REVIEW

**Review by jmazzitelli — APPROVED** [review]
+1

**Review by lucasponce — APPROVED** [review]
+1

**Comment by jshaughn** [comment]
+1

**Review by israel-hdez — APPROVED** [review]

**Review by nrfox — APPROVED** [review]

**Review by leandroberetta — APPROVED** [review]
+1

**Comment by Xunzhuo** [comment]
Thank you all for approval ❤️

**Review by aljesusg — APPROVED** [review]
+1 !

**Review by hhovsepy — APPROVED** [review]

**Pull request merged**
