### PR TITLE
test: use `T.Setenv` to set env vars in tests

### PR DESCRIPTION
**Pull request by Juneezee**
**Describe the change**

This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.

Reference: https://pkg.go.dev/testing#T.Setenv

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I ran the tests and all pass. Now that we require Go 1.17, this is OK to merge.

**Review by jmazzitelli — APPROVED** [review]

**Comment by jmazzitelli** [comment]
@Juneezee the CI tests fail due to an [issue](https://github.com/kiali/kiali/issues/5219) that was fixed. You need to rebase this PR on the current master branch, and the tests should re-run and pass. Once all tests pass we can merge this PR.

**Comment by Juneezee** [comment]
@jmazzitelli Rebased. Please take a look again. Thank you

**Review by jmazzitelli — APPROVED** [review]
rebase is done - I re-ran on my box, all tests still pass. When I see the CI tests complete successfully, we can merge.

**Comment by jmazzitelli** [comment]
hmmm.. @hhovsepy , this PR is rebased on master (you can see the PR branch [here](https://github.com/Juneezee/kiali/tree/test/t.Setenv)). So it should have your fix, right? But the [error](https://github.com/kiali/kiali/issues/5219) still happens. Can you confirm that master has this issue fixed?

**Comment by hhovsepy** [comment]
The master has the fix, but the flaky test still is failing, reopened the [issue](https://github.com/kiali/kiali/issues/5219) for further investigation.

**Review by jmazzitelli — APPROVED** [review]
these test failures are unrelated... I reviewed the code and ran the tests locally and all works. I will merge.

**Pull request merged**
