### PR TITLE
2005 support docker and podman with openshift and minikube

### LINKED ISSUE #2005: Dev script podman+minikube
As discussed on mailing, and as podman is the new way to go, I suggested either to better document the deployment steps for a dev environment with podman+minikube, or to have some script helpers. This task is about scripting.

@jmazzitelli has a better idea of the existing scripts we can re-use, but just for the record, here's my current notes / steps:

```bash
# init; do it once ; probably not to be scripted
minikube config set vm-driver kvm2 # or whatever you want
minikube config set memory 8000 # or whatever you want
# start minikube
minikube start
minikube addons enable registry # not sure if it's necessary or enabled by default 
```

(Note, I also tried using cri-o (`minikube start --container-runtime=cri-o`) but didn't work ootb at a later step (ErrPullImage on my deployments), probably nothing serious, I guess some config is necessary to skip TLS verify.)

```bash
# Install istio, e.g. with istio-1.3.1 in `$HOME`
for i in ~/istio-1.3.1/install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done
kubectl apply -f ~/istio-1.3.1/install/kubernetes/istio-demo.yaml
```

create/deploy operator:
```bash
OPERATOR_IMAGE_NAME="localhost:5000/kiali/kiali-operator" make operator-create
```

When the above command is waiting the operator to be ready, open a new terminal and run:

tag:
```bash
podman tag $(podman images | awk '$1$2~/localhost:5000\/kiali\/kiali-operatordev/{print $3}') $(minikube ip):5000/kiali/kiali-operator:dev
```

push:
```bash
podman push $(minikube ip):5000/kiali/kiali-operator:dev --tls-verify=false
```

build / deploy Kiali (with my local console!) :
```bash
DOCKER_NAME=localhost:5000/kiali/kiali CONSOLE_LOCAL_DIR=/work/swsui CONSOLE_VERSION=local make clean build docker-build

podman tag $(podman images | awk '$1$2~/localhost:5000\/kiali\/kialidev/{print $3}') $(minikube ip):5000/kiali/kiali:dev

podman push $(minikube ip):5000/kiali/kiali:dev --tls-verify=false

KIALI_CR_FILE=~/kiali_cr_jaeger.yaml AUTH_STRATEGY=login KIALI_IMAGE_NAME=localhost:5000/kiali/kiali make k8s-deploy
```

Port-forward
```bash
kubectl port-forward svc/kiali 20001:20001 -n istio-system
```

For yarn start, proxy has to be `"https://localhost:20001/kiali"`

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixed #2005 

This PR is bringing up to date the `hack/k8s-minikube.sh` hack script that lets you start up a minikube instance properly configured to work with the makefiles.

This also refactors the Makefiles such that they can allow devs to work with either minikube or OpenShift4 via either `docker` or `podman`.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I have not tested any of this with `podman` and I suspect it will not work just yet.
I seem to have it close to working with docker on minikube and OpenShift 4 but still more testing is needed. I only tested a few things.

**Comment by jmazzitelli** [comment]
I added some notes in #2005 but here's some more.

A quick set of steps you can do to start minikube, install Istio, and then build and install Kiali:

```
hack/k8s-minikube.sh start
hack/k8s-minikube.sh istio
hack/k8s-minikube.sh bookinfo
IS_MINIKUBE=true make clean build test cluster-push operator-create kiali-create
hack/k8s-minikube.sh port-forward
```
At this point you can point your browser to the port-forward URL (something like `https://localhost:20001/kiali/console`) to see Kiali and look at the bookinfo mesh.

The k8s-minikube.sh can start/stop Kubernetes ("delete" command will purge if you want to delete and start over). It can install "istio" and "bookinfo" (that's the commands you pass to the hack script).

The makefiles support OpenShift by default or minikube if you set env var IS_MINIKUBE to true.

The makefiles support docker by default or podman if you set env var DORP to "podman". This needs to be tested - I am unable to test podman.

If you happen to have both "oc" and "kubectl" in your PATH, the make targets will always use "oc". You can force the make targets to use kubectl by either removing "oc" from your PATH or by passing in the full path to your kubectl executable in the OC env variable (e.g. `OC=/usr/bin/kubectl make operator-create`).

Note that the `hack/aws-openshift.sh` script is available to start up an OpenShift 4 cluster on AWS. The makefiles will work with those OS AWS clusters by default.

Run `make help` to see the different make targets available. Here's some of the ones people will use the most:

* clean, build, test, format - all the normal build targets are still there and should be working
* container-build - builds all the container images and tags them with the quay.io/docker.io (to build only kiali or only the operator, use container-build-kiali or container-build-operator)
* container-push - pushes the container images to the public quay.io/docker.io repos (to push only kiali or only the operator, use container-push-kiali or container-push-operator)
* cluster-XYZ - all the "cluster-" targets involve building and pushing images to a development cluster - two are supported: minikube and OpenShift4. IS_MINIKUBE envvar determines which one is to be used.
** cluster-build - builds all containers with the appropriate repos in their tags (to build only kiali or only the operator, use cluster-build-kiali or cluster-build-operator)
** cluster-push - pushes all containers to the remote cluster (such as to minikube or OpenShift 4).  (to push only kiali or only the operator, use cluster-push-kiali or cluster-push-operator)

To deploy an operator and to deploy kiali to your remote cluster, you use these:

* operator-create - just creates an operator in your remote cluster - will not deploy kiali
* operator-delete - this deletes the operator - this also will purge all Kiali CRs and will purge all Kiali resources.
* kiali-create - this only works if you already have an operator (operator-create). This kiali-create will simply create a Kiali CR for you. This will deploy a different CR if you are using Maistra/ServiceMesh as opposed to upstream Istio - both are supported.
* kiali-delete - simply removes the Kiali CR which tells the operator to uninstall Kiali.
* kiali-purge - deletes kiali resources without relying on the operator to do so
* kiali-reload-image - use this if you rebuild Kiali and just want to test your new code. No need to delete the CR or the operator - just push the new kiali image (cluster-push-kiali) and reload the image and the new container image should get loaded (make targets set pull policy to Always by default).

**Comment by jmazzitelli** [comment]
@israel-hdez can you check if there is anything within the Jenkins CI config/scripts that need to change. I'm not sure if some of the make target name changes will affect it or not.

**Comment by jotak** [comment]
Something weird happened while deploying the operator.

When I ran this command the first time `IS_MINIKUBE=true DORP=podman make cluster-push operator-create kiali-create` : as expected, it did:

- Build the operator image as `192.168.39.114:5000/kiali/kiali-operator:dev`
- Pushed it to minikube's registry
- Idem for Kiali
- Deployed the Operator

All the above did work apparently correctly, but then it took a long time before the operator was ready, the script ending in timeout. In the meantime I could see my network bandwidth download and uploading a lot and at equal rates (with a strict symmetry d/l == u/l), for something like maybe 5 minutes at a few MB/s. It seems weird to me, as the images were already built and pushed. Any idea what happened?

So after maybe 5 minutes the operator was up and running correctly. Then I re-ran the same command and it was much faster without this unexpected d/l and u/l.

**Comment by jotak** [comment]
Actually, forget about it: even if I never noticed that when i was using openshift, here there must be a difference with the networking with minikube (probably because of the VM) and indeed when it's downloading from internet (Istio stuff), there's a symmetry with the uploads. Makes sense. :)

**Comment by jotak** [comment]
@jmazzitelli So, this is working like a charm, and nice huge refactoring by the way!
I can tell so far:

- Building with podman works as expected
- Deploying to Minikube with the hack scripts works as expected ; deployed istio & bookinfo through hack scripts as well.
- Deploying to my self-started Minikube instance without hack scripts works as expected

FTR my two fav commands are:

To create op&kiali
`IS_MINIKUBE=true DORP=podman CONSOLE_LOCAL_DIR=/work/swsui CONSOLE_VERSION=local make clean build cluster-push operator-create kiali-create`

and to send code updates:

`IS_MINIKUBE=true DORP=podman CONSOLE_LOCAL_DIR=/work/swsui CONSOLE_VERSION=local make clean build cluster-push-kiali kiali-reload-image`

Note that I'm not overriding the `OC` env, it looks like `oc` is still working nicely with minikube at least for the targets I'm invoking, I'm not sure if there are some pitfalls.

**Comment by jmazzitelli** [comment]
> Note that I'm not overriding the `OC` env, it looks like `oc` is still working nicely with minikube at least for the targets I'm invoking, I'm not sure if there are some pitfalls.

Yes, this should work across all targets. I thought about renaming "OC" env var to something like "CLIENT_TOOL" (because when IS_MINIKUBE=true, OC is really pointing to kubectl) but the refactoring was already huge, so I decided not to do that :)

But, yes, the "OC" env var will be set by the makefile to point to kubectl when appropriate.

**Comment by jotak** [comment]
> But, yes, the "OC" env var will be set by the makefile to point to kubectl when appropriate.

Yes I've just seen that while reviewing the changes

**Comment by israel-hdez** [comment]
@jmazzitelli Yes, the Jenkins build is affected. Let do the needed changes on that side.

**Comment by cfcosta** [comment]
Testing it here, so I'm posting the issues I found.

Arch Linux, Docker ce 19.03.5-ce, go 1.13.5, running the following command: `IS_MINIKUBE=true make clean build test cluster-push operator-create kiali-create`

1. `make clean` is failing on my machine because `${GOPATH}/pkg/*` has `444` on the file permissions. Not sure what is causing that, purged my GOPATH and tried again but the error persisted: https://gist.github.com/cfcosta/6478c7177232810c891e1cdd30834313

This fixes the error and also fixes `rm` when the pkg dir is empty (because of shell substitutions).

```diff
diff --git a/make/Makefile.build.mk b/make/Makefile.build.mk
index fafa58ac..815b6723 100644
--- a/make/Makefile.build.mk
+++ b/make/Makefile.build.mk
@@ -7,7 +7,8 @@ clean:
 	@echo Cleaning...
 	@rm -f kiali
 	@rm -rf ${GOPATH}/bin/kiali
-	@rm -rf ${GOPATH}/pkg/*
+	@[ -d "${GOPATH}/pkg/*" ] && chmod -R +rw "${GOPATH}/pkg/*" || true
+	@rm -rf "${GOPATH}/pkg/*"
 	@rm -rf ${OUTDIR}/docker
 
 ## clean-all: Runs `make clean` internally and remove the _output dir
```

2. I'm getting this error, no idea why:

```
INFO[0002] Operator build complete.
Pushing Kiali operator image to remote cluster using docker: 192.168.99.129:5000/kiali/kiali-operator:dev
docker push 192.168.99.129:5000/kiali/kiali-operator:dev
The push refers to repository [192.168.99.129:5000/kiali/kiali-operator]
Get https://192.168.99.129:5000/v2/: http: server gave HTTP response to HTTPS client
make: *** [make/Makefile.cluster.mk:72: cluster-push-operator] Error 1
```

Any suggestions?

**Comment by jmazzitelli** [comment]
I pushed a commit to update the Makefile as per @cfcosta 

@cfcosta For your 2)... do you have your minikube docker endpoint listed as an insecure registry in your docker daemon config?

**Comment by cfcosta** [comment]
@jmazzitelli yes, you are correct on the insecure registry. It works fine after the changes :)

**Comment by jmazzitelli** [comment]
tested the molecule stuff with the new make files and it is working.

**Comment by israel-hdez** [comment]
See https://github.com/jmazzitelli/kiali/pull/2
It contains the very little changes for the Jenkins stuff to work with these changes.

**Comment by jmazzitelli** [comment]
I also confirmed that the run-operator-playbook target works.

Also merged the jenkins file changes.

This should be good-to-go and ready for merge.

**Comment by cfcosta** [comment]
Tested it again, seems to work fine.

**Pull request merged**
