### PR TITLE
VirtualService#Route validation: one route under 100 weight warning

### PR DESCRIPTION
**Pull request by xeviknal**
** Describe the change **
1. Removing all the outdated validations that Galley takes care of.
2. Adding one warning validation for the following scenario:

```yaml
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: reviews
  namespace: bookinfo
spec:
  hosts:
    - reviews
  http:
    - route:
        - destination:
            host: reviews
            subset: v1
          weight: 80
```
This is the scenario where there is only one destinationRouteWeight but there is a weight different to 100. In this case, Istio assumes the weight to be 100. Independently the value set in the weight field.

The validation message is the following:
`The weight is assumed to be 100 because there is only one route destination`

** Issue reference **
Relates to https://github.com/kiali/kiali/issues/1528

** Screeeenshot **
Screenshot of localhost_8000_api_namespaces_bookinfo_istio_virtualservices_reviews_validate=true

### CODE REVIEW

**Comment by xeviknal** [comment]
@skondkar I realized that the validation scope could be improved. I changed that to point only to the weight field inside the route field.

It should be something like this:
Screenshot of Kiali Console - 2020-01-17T121404 373

Thank you for showing me that!

**Comment by lucasponce** [comment]
@xeviknal do we want to backport this to v1.12 branch ?

**Comment by lucasponce** [comment]
LGTM
Then as it's a galley validation, when trying to save a multiple weights, Galley will send the error in the MessageCenter.

**Comment by xeviknal** [comment]
@lucasponce cherry-picked in here: https://github.com/kiali/kiali/pull/2124
Good to go!

**Pull request merged**
