### PR TITLE
KIALI-927 Don't force externally initiated traffic to generate graph

### PR DESCRIPTION
**Pull request by jshaughn**
The fix for this bug is part of a major refactor of the back-end graph
generation code.  In addition to addressing the fundamental limition presented by
this bug it also:
- solves KIALI-973, set mTLS flag via prom time-series information
- significantly reduces Prometheus querying, moving from order(~N) to order(2)
- replaces the array of trees data structure with a much more natural map of service nodes
- introduces a few more types and type functions to simplify the code

### CODE REVIEW

**Comment by jshaughn** [comment]
@jmazzitelli This is set DNM but that is mainly so I can just do some sanity checking.  It should actually be working so please check it out and play with some real graphs with real options.  I realize this is a big PR, sorry about that.  But there really wasn't a good way to break this up.

**Comment by jshaughn** [comment]
Removing DNM, here is a screenshot of qe circular mesh w/o any external root but showing traffic and the generator as a root:

screenshot

**Comment by jmazzitelli** [comment]
Quick test - I'm not seeing CB or RR badges. Still investigating

**Comment by jmazzitelli** [comment]
I rescind my LGTM :) It does not look good to me

**Pull request merged**
