### PR TITLE
KIALI-1845 - More Params - Debug info

### PR DESCRIPTION
**Pull request by mattmahoneyrh**
API Parms changes.
Debug info.

### CODE REVIEW

**Comment by mattmahoneyrh** [comment]
** DO NOT MERGE **

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#330](https://paste.fedoraproject.org/paste/WYyi9~lVRIjowgaGbThUTA)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1900]](https://paste.fedoraproject.org/paste/dTMtSAu2FwJJ7DWzaJArfw)
  * :heavy_check_mark: Istio-Upstream [#[745]](https://paste.fedoraproject.org/paste/k1dCecDiKQHQEDCYPXqg8g)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2336, 2335]](https://paste.fedoraproject.org/paste/B8dlF9U0lG6gc2k1cYoh1A)
  * :heavy_check_mark: install-bookinfo [#[1287]](https://paste.fedoraproject.org/paste/l2x1PftOiKdBIWciDToooA)
  * :heavy_check_mark: Kiali-on-Openshift [#[1262]](https://paste.fedoraproject.org/paste/NvMSDWl099lENuhklj2aZA)
  * :red_circle: run-kiali-e2e-tests [#[656]](https://paste.fedoraproject.org/paste/NOeDuJhhCQp7c8dMnKq~bQ)


KIALI_NAME=kialicorepr617-istio-system

**Comment by mattmahoneyrh** [comment]
kialiqeci

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#337](https://paste.fedoraproject.org/paste/GJ~BnZOMG7xf9-w1JJYF5g)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1907]](https://paste.fedoraproject.org/paste/rhzbfqo48kKBK1XPIls3XA)
  * :heavy_check_mark: Istio-Upstream [#[752]](https://paste.fedoraproject.org/paste/yxOTx77BnWIQLHsuArma9w)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2347, 2348]](https://paste.fedoraproject.org/paste/b0Zyo93x2QGnKADzcczE4g)
  * :heavy_check_mark: install-bookinfo [#[1293]](https://paste.fedoraproject.org/paste/RdpsmeKqLdKmmNWwZ7ocuA)
  * :heavy_check_mark: Kiali-on-Openshift [#[1268]](https://paste.fedoraproject.org/paste/4vcm6N8PHksQrjXXI7RFLw)
  * :red_circle: run-kiali-e2e-tests [#[662]](https://paste.fedoraproject.org/paste/86JGWklSRjyqQTU-lGh9aQ)


KIALI_NAME=kialicorepr617-istio-system

**Comment by mattmahoneyrh** [comment]
kialiqeci

**Comment by mattmahoneyrh** [comment]
kialiqeci

**Comment by mattmahoneyrh** [comment]
kialiqeci

**Comment by mattmahoneyrh** [comment]
kialiqeci

**Comment by mattmahoneyrh** [comment]
kialiqeci

**Pull request merged**
