### PR TITLE
to support managed control plane topology

### PR DESCRIPTION
**Pull request by feuyeux**
** Describe the change **
1. decouple the interfaces/clients/caches of mesh from kube.
2. use kubeconfig files env running on local.
3. uniform timeout defination.

** Issue reference **

https://github.com/kiali/kiali/issues/3772

** Backwards incompatible? **

- Is your change introducing backwards incompatible changes?

_describe the changes if appropriate_

** Documentation **

* Does your contribution contain user-visible changes like e.g. new or changed configuration settings?
If so, please also update README.adoc

### CODE REVIEW

**Comment by lucasponce** [comment]
@feuyeux 

First of all, thanks a lot for the Pull Request.
I really appreciate the effort to take time to prepare this.
It helps to understand better your proposal.

We are going to review it and keep discussing about it.

From high level, I understand that we want to progress to make Kiali available in muliple control plane deployment strategies.

Perhaps the PR as it is it may require some changes as the support of multiple control planes is in active development and we need to make sure that we don't introduce regressions or choose any design that make block other strategy as well.

But we will work on this with you study a proposal that may help to support all strategies proposed.

**Comment by israel-hdez** [comment]
So, I understand you are breaking the k8sclient into a KubeClient and a MeshClient. I understand the KubeClient is the one that talks to the _data plane_ cluster, while the MeshClient talks to the _control plane_ cluster.

I think this partially solves the Primary-Remote topology, but I'm not sure this is the right way to go because this works when there is only one primary cluster and only one remote cluster. However, the Primary-Remote topology can involve multiple remote clusters managed by a single primary cluster. So, I don't think this can be merged as is.

Also, I've heard that Istio may remove the need to create CRDs in the control plane cluster making it read-only, and allow CRDs to be created in the data plane. Probably, this is something worth to ask in Istio forums. If this is really planned, this may remove the need of splitting the k8sclient.

Anyway, I think I get the idea behind all these changes.

**Comment by lucasponce** [comment]
I like comment from @israel-hdez to adjust the naming to "control plane" or "data plane".
So, in topologies where there is a single "control planes" managing several "data planes", the "data planes" could be better identified.

Perhaps this open the top-down discussion how we want to support this topology.

But in any case I'm in favor to make compatible the code to support multiple scenarios, perhaps @feuyeux you could also to give some info about the plans, from architecture perspective ?

**Comment by feuyeux** [comment]
There's only one control plane and multiple data plane, including vm. And we read/write mesh crd with mesh client. This is our long term design and it's not easy to change. 
But we don't want to use write in kiali, since we have a gui console to do that. 
For kiali perspective, to support multiple is satisfied for us, even considering mesh crd read only.

**Comment by lucasponce** [comment]
Hi @feuyeux sorry for the delay, the deployment models discussion is quite active and we'd like to have your feedback to help us to set up the priorities for this work I've created a discussion to set up a community session around the topic:

https://github.com/kiali/kiali/discussions/4013

**Comment by feuyeux** [comment]
> Hi @feuyeux sorry for the delay, the deployment models discussion is quite active and we'd like to have your feedback to help us to set up the priorities for this work I've created a discussion to set up a community session around the topic:
> 
> #4013

Got it and thanks a lot !

**Comment by lucasponce** [comment]
Hi @feuyeux,

Please, feel free jump on this discussion https://github.com/kiali/kiali/discussions/4081 where we are defining the high level design of the support for multi deployment models.

Probably we'll reuse some of the ideas that you proposed in the PR but I suggest to close it for the moment and we can re-open it and check if we can re-use some of the work.

Let me know what do you think.
Thanks !

**Pull request closed without merging**
