### PR TITLE
Toolbar help and bell icons misaligned

### LINKED ISSUE #5148: Toolbar icons misaligned
The right toolbar icons - The warning bell icon and the help icon, also the username - Are a bit misaligned:

Screenshot from 2022-06-03 13-32-48

Reproduced in FF and Chrome

### PR DESCRIPTION
**Pull request by josunect**
Align toolbar icons Bell and Help from Helpdropdown and MessageCenter.

Fixes #5148 

cc @jshaughn

### CODE REVIEW

**Comment by lucasponce** [comment]
@josunect GitHub has this trick to link a PR with an issue, then when you merge a PR, the issue is automatically moved to a "close" state as well 

https://docs.github.com/es/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

I've updated the description with it, so no need to add the "issuexyz" in the title if you don't want to

**Comment by josunect** [comment]
Please, do not merge yet. I will also add some padding to the warning icon.

**Comment by josunect** [comment]
I've added the change for the padding in the warning button. 
Not sure why CI is failing, there were no changes in the backend.

**Comment by lucasponce** [comment]
> Not sure why CI is failing, there were no changes in the backend.

Sometimes happens that a branch is old compared with the master branch, then you could rebase your branch and push to update the PR.

The CI usually works well but there may be some flaky scenarios, if that happens we can re-run the CI job.

**Comment by josunect** [comment]
I think this could be merged, if passes the review - I cannot update the labels :)

**Review by jshaughn — APPROVED** [review]
Tested, all looks good to me!

**Pull request merged**
