### PR TITLE
no need for these extra permissions anymore due to the use of CNI on OpenShift

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/3731

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I have not tested any of the scripts yet, but I did go through and remove all the `adm policy` calls that create these permissions. Just need to confirm these really are not needed and that the hack scripts all still work.

**Comment by jmazzitelli** [comment]
Confirmed that `install-istio-via-istioct.sh` and `install-bookinfo-demo.sh` work

**Comment by jmazzitelli** [comment]
Confirmed `install-travel-agency-demo.sh` works (I am not testing the 1.6 one - but the same changes were made to it as this newer one. I think we should delete the 1.6 one anyway).

**Comment by jmazzitelli** [comment]
the error rates demo install script works too. So I can confirm all works. We can merge.

**Comment by jmazzitelli** [comment]
@jshaughn do we want to just delete the 1.6 version of the travel agent script?

**Comment by jshaughn** [comment]
> @jshaughn do we want to just delete the 1.6 version of the travel agent script?

I think that's fine at this point as 1.6 is out of support and the documented config for operation_id has changed significantly for the stats filter.  Actually, I'd like for the operation_node support to be configurable as a command line option instead of the way it's done currently with manual edits and support only for a specific version.  I haven't had time to do that, and it would also likely require a different way of updating the stats filter as the patch approach is pretty brittle.

**Comment by jmazzitelli** [comment]
1.6 file has been removed

**Review by jshaughn — APPROVED** [review]
LOK

**Pull request merged**
