### PR TITLE
wait up to five minutes for operator to have its image pulled and start

### PR DESCRIPTION
**Pull request by jmazzitelli**

### CODE REVIEW

**Comment by pilhuhn** [comment]
The title scared me as it did not contain a "up to" :)

**Comment by jmazzitelli** [comment]
fixed title :)

**Comment by jmazzitelli** [comment]
waits at least 5 seconds... and then every 5 seconds thereafter checks.

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#894](https://paste.fedoraproject.org/paste/r2bL63d08Cf5BeJ-opUnZQ)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1693]](https://paste.fedoraproject.org/paste/Htsthz0W6poDxqayx4vAsw)

**Pull request merged**
