### PR TITLE
[hack] 4.2.1 was removed - moving to the latest in the 4.2 z-stream

### PR DESCRIPTION
**Pull request by jmazzitelli**

### CODE REVIEW

**Comment by xeviknal** [comment]
@jmazzitelli I have also the following error:

```
$ ./aws-openshift.sh status -ov 4.2.7
HACK: ===== WARNING =====
HACK: You already have the OpenShift installer but it does not match the version you want.
HACK: This appears incorrect: /home/xcanalma/openshift/4.2.7/openshift-install
HACK: The version of the installer is: 4.2.5
HACK: You asked for version: 4.2.7 (4.2.7)
HACK: ===== WARNING =====
```

I used the following command to create the cluster though:
```
./aws-openshift.sh -p /home/xcanalma/Downloads/pull-secret.txt -ar us-east-2 -kuca true -cn xcanalma create -v -ov 4.2.7
```

However, the script of creating cluster is working properly. All the other commands (i.e. install bookinfo, status, and so on) answer with the warning above.

**Comment by jmazzitelli** [comment]
That means you have the 4.2.5 installer binaries. I've seen this before - its the same thing they did with 4.2.2 vs. 4.2.1. It's the exact same bits, they just labeled the binaries different. Sucks because you think you download one version but the binary (through its "version" cmdline opt) tells you its something different

**Comment by jmazzitelli** [comment]
before I merge, I'll track this down and find out what version we should be using. I bet if we just use 4.2.5 that's the latest bits (even though the label 4.2.7 exists, I bet its still 4.2.5)

**Comment by jmazzitelli** [comment]
just as I thought - the bits are the same, they just (for whatever reason) released new versions with the exact same bits:

```
$ wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.2.7/openshift-install-linux-4.2.7.tar.gz

$ tar zxvf openshift-install-linux-4.2.7.tar.gz 
README.md
openshift-install
$ ./openshift-install version
./openshift-install v4.2.5
built from commit 425e4ff0037487e32571258640b39f56d5ee5572
release image quay.io/openshift-release-dev/ocp-release@sha256:bac62983757570b9b8f8bc84c740782984a255c16372b3e30cfc8b52c0a187b9
```

**Comment by jmazzitelli** [comment]
@aljesusg changed the script to use 4.2.5 so we don't get that warning. 4.2.7 isn't a different release anyway - its all the same as 4.2.5.
Feel free to merge.

**Comment by jmazzitelli** [comment]
@xeviknal if you try this, you should not get that warning anymore.

**Comment by xeviknal** [comment]
@jmazzitelli not working either. Installer for 4.2.5 is not available
```
HACK: Downloading OpenShift installer to /home/xcanalma/openshift/4.2.5
--2019-11-20 16:29:11--  https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.2.5/openshift-install-linux-4.2.5.tar.gz
Resolving mirror.openshift.com (mirror.openshift.com)... 54.172.163.83
Connecting to mirror.openshift.com (mirror.openshift.com)|54.172.163.83|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-11-20 16:29:12 ERROR 404: Not Found.

HACK: ===== WARNING =====
HACK: Could not download the OpenShift installer for the version you want.
HACK: Make sure this is valid: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.2.5/openshift-install-linux-4.2.5.tar.gz
HACK: ===== WARNING =====
```

Something wrong is happening in their end.

**Comment by jmazzitelli** [comment]
> Something wrong is happening in their end.

I have no idea what they are doing. But OK, I just tried to donwloat 4.2.4 and it reports the correct version so this PR moves to that:

```
$ wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.2.4/openshift-install-linux-4.2.4.tar.gz
$ tar zxvf openshift-install-linux-4.2.4.tar.gz 
README.md
openshift-install
$ ./openshift-install version
./openshift-install v4.2.4
built from commit 425e4ff0037487e32571258640b39f56d5ee5572
release image quay.io/openshift-release-dev/ocp-release@sha256:cebce35c054f1fb066a4dc0a518064945087ac1f3637fe23d2ee2b0c433d6ba8
```

**Comment by jmazzitelli** [comment]
@xeviknal ^^^ go ahead and merge this if it works for you

**Comment by xeviknal** [comment]
@jmazzitelli is not working. It says the following:

```
HACK: Downloading OpenShift installer to /home/xcanalma/openshift/4.2.5
--2019-11-20 16:29:11--  https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.2.5/openshift-install-linux-4.2.5.tar.gz
Resolving mirror.openshift.com (mirror.openshift.com)... 54.172.163.83
Connecting to mirror.openshift.com (mirror.openshift.com)|54.172.163.83|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-11-20 16:29:12 ERROR 404: Not Found.

HACK: ===== WARNING =====
HACK: Could not download the OpenShift installer for the version you want.
HACK: Make sure this is valid: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.2.5/openshift-install-linux-4.2.5.tar.gz
```

**Comment by jmazzitelli** [comment]
@xeviknal you sure you got the latest PR change? Your output says:
```
HACK: Downloading OpenShift installer to /home/xcanalma/openshift/4.2.5
```
But this PR should not be downloading 4.2.5 - should be getting 4.2.4 now.

**Pull request merged**
