### PR TITLE
Go Report Card in Readme file

### PR DESCRIPTION
**Pull request by aljesusg**
I think this is interesting to have it

captura de pantalla 2018-02-04 a las 13 30 40

You can check the improves [here](https://goreportcard.com/report/github.com/swift-sunshine/swscore)

### CODE REVIEW

**Comment by theute** [comment]
Before we make such change I would like:
  - To get an agreement on what is acceptable or not... Is a B grade acceptable ? Or needs to be A ? or C ? And documented.
  - The same report is attached to the Pull Requests so that the degradation can be noticed and fixed prior to the commit.
  - I don't know what Editor everyone use, but the support in editor is important. 

Either the grade is important and we need to pay attention, or it's not important and it's just noise (and then we tend to ignore other more important things).

**Comment by jotak** [comment]
IMO it's important to get code quality indicators at least at the beginning since some of us are still learning go. Learning the language is one thing, learning good practices is another.

Maybe later once we'll get more experienced we can get rid of it.

**Comment by aljesusg** [comment]
That depends of the inspector:
golint and gofmt are linters and good practices, with that fix the report card go to level A.

I think that the most improtant is gocycle (cyclomatic complexities)
This report is not attached in each PR, I used travis to make this kind of lints.

About the IDE, I used in my last job goglang of Jetbrains but now you need a license, I am now working with atom. VSCode have plugins for go too.

**Comment by theute** [comment]
@jotak You should have those warnings in your editor, I know I have those in Atom
If we have the indicator on the project it needs to mean something :)

**Comment by theute** [comment]
And it means we all care the same way.

**Comment by jotak** [comment]
"And it means we all care the same way." That's exactly why a global indicator is nice :)

**Comment by theute** [comment]
Not true. See the many failures in Hawkular that were ignored ;)
It can be displayed and you care but someone else don't give a crap. You may do extra mile to get to A but others will not care and move it down to C and frustrate you :)
So if important, let's make this a rule that it needs to be A and let's prove it's A with the badge. It also needs to be in the PR and block the merge if it's not A.

Otherwise it also shows bad quality. I personally don't like to see a project with non-green status stuff on the README, it doesn't make me comfortable. 

I'm not against it, but if we display it, we should care and enforce it.

**Comment by theute** [comment]
So again, I would much rather prefer a notification in the PR if the situation has degraded.

**Comment by aljesusg** [comment]
@theute We can set this "tests" in the travis process like a parallel job.

**Comment by theute** [comment]
@aljesusg ca

**Comment by theute** [comment]
Being discussed here: https://issues.jboss.org/browse/SWS-66

**Comment by aljesusg** [comment]
@theute @jotak What should we do with this?

**Comment by jotak** [comment]
@aljesusg I hit the "update branch" button on github (and I see you did the same previously), but actually it would be better to reset from master and cherry-pick the commit. We would have a cleaner history this way.

**Comment by aljesusg** [comment]
Rdy @jotak I cleaned commits.

**Comment by theute** [comment]
We score very low in golint: https://goreportcard.com/report/github.com/swift-sunshine/swscore#golint
Is that expected ?

We shouldn't commit before we get A+ scoring and make sure we have the tools in place to guarantee that it will remain A+

**Comment by aljesusg** [comment]
So we should add golint to the tasks to have A+ @theute

**Comment by theute** [comment]
I didn't follow all the discussions... And I know nothing about golint ;)
If we don't care about golint, can it be removed from the score card ?

**Comment by aljesusg** [comment]
we can't remove golint from go report card, we should add golint too, it's a good practice and go reprot card is used by most projects

**Comment by jotak** [comment]
+1 for golint.
We could proceed by first merging this PR https://github.com/swift-sunshine/swscore/pull/45 which fixes a good bunch of warnings,
Then merge this one even if we're not A+, we'll be closer to, and we can really start to track progressions / regressions.

**Comment by jotak** [comment]
Actually, @aljesusg what do you mean by "add golint"? Add it where, if it's already in the report card?

**Comment by theute** [comment]
Add golint as a requirement (if we care) and have the tools around it (to validate the code or to help developer with IDE or else...)

**Comment by jmazzitelli** [comment]
If we add golint to the check-in or build requirements, I will vigorously protest. :-P

**Comment by jotak** [comment]
Ok, I didn't want to make it a requirement, just an indicator that we can keep on our radar. Some situations are sometimes ridiculous, like have to put documentation on very obvious getters and setters.
I've also seen sometimes that it forces us to rewrite code in a way that, in the end, is less readable depending on the situation.

**Comment by abonas** [comment]
isn't it a dependency then? if we want go report card, we need go lint. if we do not want go lint, then we should drop go report card, isn't that so?

**Comment by jotak** [comment]
Report card with golint + build requirements without golint... isn't it an option?

**Comment by theute** [comment]
Either we care (make it a requirement and show we comply) or we don't care (not a requirement and not show we don't comply)
I see projects are A+ when they show the report. What's the point of showing that we are *not* compliant ?
As Mazz said, we'll ignore if we degrade and I agree.

**Comment by jotak** [comment]
The report card is not something created to show how beautiful projects are. It's a tool given to developers to track their own code quality. At least this is how I see it. Similar to sonar, for instance.
I've never used sonar to show to the outside world how well we are coding, but to improve ourselves and have a consistent code base.
While I agree that some rules can be dumb, IMO others are good, for instance to have a consistent naming pattern of our variables inside the code base.
So if it's all or nothing I vote for nothing. But I hoped there could be some place in between.

**Comment by jotak** [comment]
For example, prometheus has a gocard but it doesn't show 100% on golint (https://goreportcard.com/report/github.com/prometheus/prometheus) which means it's not a _build requirement_

**Comment by aljesusg** [comment]
But they have 97% when we have 25% ^^

**Comment by theute** [comment]
The report card is not something created to show how beautiful projects are.  --> When you put it on your README it is... If you show me a project that shows indicator that are Orange/Red there is no point...

It's a tool given to developers to track their own code quality. --> No, since it's the project "code quality" if quality. @jmazzitelli said he will not care (which is fine we me if we don't care), but you are not here to fix @jmazzitelli code so who is going to do it ?

Asked differently, who is going to care about that score and what do we do when scores go low (and who) ? If we are not going to do anything, then we should not use that metric, and it blurs the other metrics that we care about.

**Comment by theute** [comment]
I think that Prometheus actually checks the code on each PR.
They use codacy on PRs and they use https://github.com/dominikh/go-tools/tree/master/staticcheck in the makefile.

Why is there still some issues ? (I can't tell, it seems that some files are ignored and maybe card report is somewhat more strict/different ?)

**Comment by jotak** [comment]
So I guess it means we can definitely reject this PR?

We can still have a look at goreportcard.com ( https://goreportcard.com/report/github.com/swift-sunshine/swscore ) to track these metrics if we want, for people who care, even if it's not displayed in card.

Just to mention, getting A+ badge is not a big deal, just merging #45 would make it.

**Comment by theute** [comment]
We didn't answer the legit question: do we care about go lint or not.

@jotak I'm still interested to know what you would do about go lint score if only you or a few care.

**Comment by jotak** [comment]
Personally I definitely _care_ but if the question is "do we target a mandatory 100%" then it seems most developers won't want it (including me). We can start a poll to make it clear.

To answer your other question, if only a few care about it and we decide to show the badge, my feeling is that it's not so difficult to maintain a good rating as long as we agree on some minimal rules for code consistency, like naming patterns, and to have a decent in-code documentation. We could also give it a try and see how it goes PRs after PRs. Nobody wants to spend hours in restyling the whole code day after day. But I'm pretty sure it won't be the case because we're already not so far from the so-called good practices. If it turns out to be wrong, then we can remove the badge later. Does it sound possible?

**Comment by jmazzitelli** [comment]
I won't care. And if some stupid lint tool tells me my variable names are wrong because I used Url and not URL and I can't check in my code until I "fix" it, my head will explode.

**Comment by cfcosta** [comment]
I prefer having the lints in place. They make the code in general better even if by a little bit, by enforcing consistence both within the project and the community at large. We had rubocop as a CI step and while manageiq used some arcane ruby conventions, following them made reading the project code really consistent.

@jmazzitelli imho is the same as reviewing gofmt output on precommit. Same amount of time and work really.

**Comment by theute** [comment]
@jmazzitelli asking for a friend: does your IDE warns you or you would really only know at commit time ? (I would definitely agree that if we don't have the tools it's a PITA).

**Comment by jmazzitelli** [comment]
My IDE is either Eclipse or now I'm using liteide - neither that I know of shows lint errors. At least, I never used such a feature if it exists because I don't use lint. Quite frankly, I can't believe we are actually suggesting that we impose lint on ourselves - that's like serving ourselves rat poison because it tastes good. :-p But that's just me. :)

**Comment by theute** [comment]
As a note: I just checked our score. Even though we are A+ golint is still "random", we were at 54 and after a refresh down to 50.
We can keep that PR open, but unless we get an agreement that that scores is something we all need to care about we shouldn't use it on our README.
We'll revisit later when the project matures

**Comment by jotak** [comment]
@theute the low golint score is essentially due to undocumented exported function (= public methods in java terminology). I doubt it will be improved with project maturity, except if we pay special attention to it.
Personally I'm not shocked by undocumented functions when they're self-explanatory (like "GetServiceXXX" just returning service XXX). Most of the time this is what happens.

**Comment by theute** [comment]
I didn't mean to say that the code will change with maturity :)
I meant to say that we may change our view as the project matures/grow and we decide to pay attention to it (or not).
I agree that stupid comments for self-explanatory functions don't move the needle...

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by abonas** [comment]
@aljesusg what do you mean by verify?
@theute did we eventually get to an agreement to have this? based on the comments above from a month ago it is not so clear to me

**Comment by aljesusg** [comment]
@rhqci I think that @abonas is asking you about

**Pull request closed without merging**
