### PR TITLE
Testpr

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
Build comment file: 
--------------
:red_circle: Jenkins CI: kiali-core-test-pr [#14](https://paste.fedoraproject.org/paste/0LzsfNXzNVb4VkmqaKpLhg)
*  :red_circle: Istio-and-Kiali-on-Openshift [#376](https://paste.fedoraproject.org/paste/LGEHRtaVVKIz07EyBbaGDw)
*  :heavy_check_mark: Kiali-on-Openshift [#78](https://paste.fedoraproject.org/paste/6~C32xOB0LoGReGvYVK0vg)
*  :heavy_check_mark: Bookinfo-traffic-generator [#120](https://paste.fedoraproject.org/paste/PhdTleS-mg8nTI~EyXYjnw)
*  :heavy_check_mark: Kiali-Test-Mesh [#106](https://paste.fedoraproject.org/paste/jW1rNRqgkpEpOURoXG4hGQ)
*  :red_circle: run-python-rest-tests [#85](https://paste.fedoraproject.org/paste/gDoAV6NCr8gIjfS7jC28ug)
*  :red_circle: run-python-ui-tests [#174](https://paste.fedoraproject.org/paste/tN9aWwClEsikyJKYD-fYMQ)
--------------

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
Build comment file: 
--------------
KIALI_HOSTNAME=kialicorepr178-istio-system.openshift3.jonqe.lab.eng.bos.redhat.com

--------------

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Comment by rhqci** [comment]
Build comment file: 
--------------
:red_circle: Jenkins CI: kiali-core-test-pr [#27](https://paste.fedoraproject.org/paste/iM~QdUioalCev7IIDX5FsQ)
  * :red_circle: Istio-and-Kiali-on-Openshift [#495](https://paste.fedoraproject.org/paste/R~ZZtXZaMt23-lp0ncYZTg)
  * :heavy_check_mark: Kiali-on-Openshift [#208](https://paste.fedoraproject.org/paste/URESpABnRQnLP3uoC0zgkQ)
  * :heavy_check_mark: Bookinfo-traffic-generator [#210](https://paste.fedoraproject.org/paste/lGDvf0QEkKSCF2D8Ih6A4g)
  * :heavy_check_mark: Kiali-Test-Mesh [#183](https://paste.fedoraproject.org/paste/kSoU030qam7yh7z5UmMMgw)
  * :red_circle: run-python-rest-tests [#158](https://paste.fedoraproject.org/paste/VayuJPpvayKZVuv8Fd49fg)
  * :red_circle: run-python-ui-tests [#231](https://paste.fedoraproject.org/paste/ucwsHeFGlTxea4e9eyYBaw)
--------------

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
Build comment file: 
--------------
:red_circle: Jenkins CI: kiali-core-test-pr [#28](https://paste.fedoraproject.org/paste/KQNXGgk4pkA0-EITKFMoGg)
  * :red_circle: Istio-and-Kiali-on-Openshift [#504](https://paste.fedoraproject.org/paste/RPtgyGiS8EOrHzS9Bt-tZQ)
  * :heavy_check_mark: Kiali-on-Openshift [#216](https://paste.fedoraproject.org/paste/Mepk1WZuVnW~VcozK9-D0g)
  * :heavy_check_mark: Bookinfo-traffic-generator [#216](https://paste.fedoraproject.org/paste/~BazvxV4AwB~eU3Q1ZUWvg)
  * :heavy_check_mark: Kiali-Test-Mesh [#188](https://paste.fedoraproject.org/paste/ImMzKNevQmA9Y~sEKwwjcA)
  * :red_circle: run-python-rest-tests [#160](https://paste.fedoraproject.org/paste/f2wqXSQy5Z1sI~IgR0R-UA)
  * :red_circle: run-python-ui-tests [#238](https://paste.fedoraproject.org/paste/SD-vyMgP2-qdiuME2gmH8A)
--------------

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
Build comment file: 
--------------
:heavy_check_mark: Jenkins CI: kiali-core-test-pr [#30](https://paste.fedoraproject.org/paste/JsfSMxiMpKoNeC9JJry9oA)
  * :red_circle: Istio-and-Kiali-on-Openshift [#529](https://paste.fedoraproject.org/paste/qkb127yJoL~IRxh~cDDZNQ)
  * :heavy_check_mark: Kiali-on-Openshift [#245](https://paste.fedoraproject.org/paste/GDDRMUvnzYxx3z-A5RAn6A)
  * :heavy_check_mark: Bookinfo-traffic-generator [#239](https://paste.fedoraproject.org/paste/NC1mRLQQSb0wdBx9uonRPw)
  * :red_circle: Kiali-Test-Mesh [#206](https://paste.fedoraproject.org/paste/GrsiVY6-ccqkTFIFxGps2w)
--------------

**Pull request closed without merging**
