### PR TITLE
Remove Mixer + RBAC + 3Scale deps

### PR DESCRIPTION
**Pull request by lucasponce**
Backend changes for https://github.com/kiali/kiali/issues/3341

Frontend PR:
https://github.com/kiali/kiali-ui/pull/1976

Operator PR: 
https://github.com/kiali/kiali-operator/pull/175

### CODE REVIEW

**Comment by lucasponce** [comment]
Also, it will need operator changes.

**Comment by xeviknal** [comment]
I've created this folder with at least one object for each CRD available now on Istio. This way is easier to test the filters and details of each object.
Hope that helps: https://github.com/xeviknal/istio-lab/tree/master/crd-sample-testing

```
k apply -f crd-sample-testing/ -n foo
```

**Review by xeviknal — CHANGES_REQUESTED** [review]
I see that the 3scale configuration structs are still in place. I guess that they should be gone too, right?

https://github.com/kiali/kiali/blob/master/config/config.go#L174-L180
https://github.com/kiali/kiali/blob/master/config/config.go#L190-L193
https://github.com/kiali/kiali/blob/master/config/config.go#L386-L392

On the other side, there are the end-2-end test for the 3scale-related API endpoints:
```
tests/e2e/tests/test_api_methods.py:268:    evaluate_response(kiali_client, method_name='getThreeScaleInfo')
```

This should be gone too.

**Comment by lucasponce** [comment]
@hhovsepy 

how do you suggest to address this comment ?

> On the other side, there are the end-2-end test for the 3scale-related API endpoints:

e2e tests are not something we typically run on local, I can try to update the python code on this PR but I can't test it.

Or I can let you to update the branch with those tests, I see that perhaps there are more refactoring on e2e with missing istio config types.

**Comment by lucasponce** [comment]
Also I'm seeing I haven't removed completely all validations involved Mixer objects, there are a couple to update.

**Review by xeviknal — APPROVED** [review]
LGTM

**Comment by lucasponce** [comment]
Thanks ! I'm going to consolidate this work, I know @jshaughn is also working on removing mixer telemetry and perhaps we may need to solve some conflict in the code, so the sooner is on the repo the better.

Operator PR can be synced later.

**Comment by hhovsepy** [comment]
For e2e tests we need to ask @mattmahoneyrh or @pbajjuri20

**Pull request merged**
