### PR TITLE
KIALI-2102 Fixing service/workload e2e tests

### PR DESCRIPTION
**Pull request by xeviknal**
** Describe the change **
Some e2e test were broken.

** Issue reference **
https://issues.jboss.org/browse/KIALI-2102

### CODE REVIEW

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1040](https://paste.fedoraproject.org/paste/aL4m2tZjIqNugbVd50cIJw)
 :red_circle: PRT Failed, Please Contact QE

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
PRT Failed, Please Contact QE

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1055](https://paste.fedoraproject.org/paste/uT0ODiYKVEMQDN~MUn7tDg)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1950]](https://paste.fedoraproject.org/paste/fmLgIwjiOV~UjotxhDiBMg)

**Comment by xeviknal** [comment]
kialiqeci

**Comment by rhqci** [comment]
PRT Failed, Please Contact QE

**Comment by FilipB** [comment]
kialiqeci

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1059](https://paste.fedoraproject.org/paste/WWNTYtqLvj3MT2vdaKNDEg)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1957]](https://paste.fedoraproject.org/paste/QExUJBzboPmItpDgdzxsew)

**Comment by xeviknal** [comment]
@mattmahoneyrh comments approached. I did change those two methods and also fixed the health endpoint. Let me know if something is broken and I fix it, np.

**Comment by xeviknal** [comment]
kialiqeci

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1060](https://paste.fedoraproject.org/paste/qFvLms1Ohm-ge9lQb9Jx6A)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1960]](https://paste.fedoraproject.org/paste/q~CNZWfQ3y-675AM9OLZ1A)

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1062](https://paste.fedoraproject.org/paste/HwLkT8vG78MgEyWydYNAow)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1962]](https://paste.fedoraproject.org/paste/VELqc7KkUKmbbfTnU6CHGA)

**Comment by xeviknal** [comment]
@mattmahoneyrh any update here? perhaps @gbaufake can check this out?

**Comment by lucasponce** [comment]
Ping @mattmahoneyrh and @gbaufake.
Can we progress this PR ?

**Pull request merged**
