### PR TITLE
Fix Snyk GitHub action

### PR DESCRIPTION
**Pull request by israel-hdez**
The official Snyk action didn't work. Using something that is more close to what was being done in Travis. This is better, because docker is not involved.

Related #3481

### CODE REVIEW

**Comment by israel-hdez** [comment]
@jshaughn Sorry, the actions provided by snyk didn't work.
I'm fixing with the approach used at travis. Here you can see a successful red run (it's red because there is a warn): https://github.com/israel-hdez/swscore/pull/20/checks

**Comment by israel-hdez** [comment]
@jshaughn Can you take a look?
I would like to get rid of those failed CI checks in `master` before I'm the only saturner ;)

**Review by jshaughn — APPROVED** [review]
OK, this looks a good change, thanks.

**Comment by israel-hdez** [comment]
Thanks! Merging...

**Pull request merged**
