### PR TITLE
KIALI-1954 Subset Presence Checker does not invalidate any object

### PR DESCRIPTION
**Pull request by xeviknal**
** Describe the change **
'Subset not found' validations doesn't leave the validation as invalid since it is a warning.

** Issue reference **
https://issues.jboss.org/browse/KIALI-1954

** Backwards incompatible? **
yes

Before:
48569741-d5bdeb00-e902-11e8-9835-36df690d267b

After:
screenshot of https___kiali-istio-system 192 168 42 18 nip io_api_namespaces_bookinfo_istio_virtualservices_reviews_istio_validations

### CODE REVIEW

**Comment by xeviknal** [comment]
Before:
before-1954

After:
after-1954

**Comment by xeviknal** [comment]
@jotak That is a good point. I guess that this field is pretty useful for sorting items in the ui. IMO, it gives a more direct way to compare items by config status. However, the fact that we have a boolean instead of a integer/string is limiting and also adds some extra computing.

**Comment by xeviknal** [comment]
I have also fixed a Gateway Multimatch Checker. It returned a valid = false but it only adds warnings. In the same way as Subset Presence checker, the sort got broken because of it.

**Comment by xeviknal** [comment]
@hhovsepy do you mind check this PR?

**Comment by hhovsepy** [comment]
Verified the solution:
screenshot from 2018-12-06 09-04-34

**Pull request merged**
