### PR TITLE
KIALI-616: Check projects instead of namespaces by default

### PR DESCRIPTION
**Pull request by mwringe**
Initial attempt at removing full cluster access for Kiali. This pr is huge due to addition of openshift api library but the main changes are in only two files.

What this does it check if we have access to project objects in our cluster, which means it either running OpenShift or k8s with kube-projects (https://github.com/openshift/kube-projects). If it can't fetch the project objects, it assumes its running with plain k8s and falls back to using the namespace endpoint. Unfortunately there isn't a nicer way of doing this in k8s itself, so if you are running in k8s you still need the cluster role (since the namespace endpoint requires this to return anything)

Running and Testing:
- run Kiali as normal using mazz's scripts. This will give the kiali service account the 'kiali' cluster role

At this point it will work as normal and you shouldn't see any changes.

Remove the cluster role that Kiali has been granted by default:
`oc adm policy remove-cluster-role-from-user kiali system:serviceaccount:istio-system:kiali`

Grant is specific access to certain namespaces, for instance to give it access to the 'istio-bookinfo' namespace run the following:
'oc adm policy add-role-to-user kiali system:serviceaccount:istio-system:kiali -n istio-bookinfo'

Log into the Kiali and see that you only have access to that specific namespace.

A couple of notes:

- if you are running k8s without kube-project you basically need to give it the cluster privileges. There is no way to fetch from plain k8s the list of project that a user has access to.

- this only prevents access to things like k8s objects via the k8s api endpoint. It doesn't affect things like metrics since those are fetched via p8s (and will require a bunch of other logic to be put in place, but that needs to come in a separate PR)

- the UI needs to better handle when there is an empty list of namespaces that it has access to. Right now it doesn't like it too much.

### CODE REVIEW

**Comment by cfcosta** [comment]
This is good, but I think it's a change that should include some form of documentation, at least a blog post, wiki entry or a mention on the project README.

**Comment by lucasponce** [comment]
Please, could be split this ?
Traditionally we used two PR when importing golang libraries to separate from the logic used with them.
That helps to follow the changes better.

**Comment by mwringe** [comment]
> Please, could be split this ?
Traditionally we used two PR when importing golang libraries to separate from the logic used with them.
That helps to follow the changes better.

Yep, good point. https://github.com/kiali/kiali/pull/224 now just brings in the OpenShift API library

**Comment by mwringe** [comment]
> This is good, but I think it's a change that should include some form of documentation, at least a blog post, wiki entry or a mention on the project README.

Yep, that is needed and is why the 'do not merge' tag is on this. I will update the issue with the doc changes since pulling in the OpenShift API library is in another PR.

**Comment by lucasponce** [comment]
This PR is old. I'm closing it.
We can re-activate anytime in the future with more data but for now I think we can skip it from the list of PR to review.

**Pull request closed without merging**
