### PR TITLE
Enable smoke testing in Cypress

### PR DESCRIPTION
**Pull request by matejnesuta**
** Describe the change **

_explanation of what it does_

** Issue reference **

* If this is a fix for a GH-issue, please link it here

### CODE REVIEW

**Comment by ScriptingShrimp** [comment]
Taking look into changed files, I see some scenarios tagged `@smoke` and also with `@bookinfo-app` or `@error-rates-app`. The smoke testing principle is [defined here](https://www.techtarget.com/searchsoftwarequality/definition/smoke-testing) - so based on that I would recommend to have smoke testing scenarios without other dependencies. Speculating a little bit further, the optimal workflow might be something like:

1. deploy istio 
2. smoke test istio
3. deploy kiali 
4. smoke test kiali
5. if all above passes, execute other layers of tests (functional, nonfunctional etc..)

What do you think?

**Comment by matejnesuta** [comment]
I removed tags with dependencies to demo applications, which shrinked the possible candidates to roughly 10 scenarios. I wonder if the number is not too low. 

>deploy istio
>smoke test istio

I am not sure, what do you mean by this.

**Comment by ScriptingShrimp** [comment]
> I am not sure, what do you mean by this.

Just highlighting importance of smoke testing. For an example in our private pipelines this could serve as gating, we don't want to test Kiali on broken setup of Istio. I like [this definition](https://www.javatpoint.com/smoke-testing)

**Comment by ScriptingShrimp** [comment]
I already annotated some smokes in https://github.com/kiali/kiali/pull/6493, so if its get merged, you can rebase and add some more

**Comment by matejnesuta** [comment]
Closed in favor of #6684.

**Pull request closed without merging**
