### PR TITLE
Added interval refresh on IstioConfigDetails page. Removed content change notifications.

### PR DESCRIPTION
**Pull request by hhovsepy**
RFE https://github.com/kiali/kiali/issues/4936

Screenshot from 2022-05-13 20-39-56

### CODE REVIEW

**Comment by hhovsepy** [comment]
There is an overlap bug:
Screenshot from 2022-05-13 20-41-06

**Comment by hhovsepy** [comment]
The overlap in fixed by css z-index override, please check it:
Screenshot from 2022-05-16 12-04-08

**Comment by lucasponce** [comment]
This one works well for the overlapping.

image

Thanks!

May I ask for a little change?

There is a CSS "trick" to place the "Actions" dropdown aligned in that position, with the PF migration a "border" is missing in that wrapper "div", which creates an effect in the grey line that is used for the tabs.

It sounds it's just a one-liner to add border style to that div, would you mind seeing if can be added to this PR?

image

Thanks !

**Comment by hhovsepy** [comment]
@lucasponce added a workaround here, by adding bottom border on Actions.

**Comment by lucasponce** [comment]
Thanks, @hhovsepy, it works really well :)

image
image

**Comment by lucasponce** [comment]
To me this work looks well, the "do not merge" label is still there waiting for more work on this PR?

**Comment by hhovsepy** [comment]
Removed the do not merge label. Thanks for review Lucas.

**Review by lucasponce — APPROVED** [review]

**Pull request merged**
