### PR TITLE
Instead of BASH_SOURCE[0] use $0

### PR DESCRIPTION
**Pull request by burmanm**
I missed this one since I had it downloaded already.. ${BASH_SOURCE[0]} does not with sh so the hack scripts do not function in Ubuntu. $0 does the same as far as I could test.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
Is it better to change the directive at the top to be `#!/bin/bash`

Though it looks like this change should be safe for our use-cases: https://stackoverflow.com/questions/35006457/choosing-between-0-and-bash-source

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#261](https://paste.fedoraproject.org/paste/NZ9qFZ8iIjX2uI56udoaJA)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1780]](https://paste.fedoraproject.org/paste/oUcIUpweXJ0IXipXQ5Dwnw)
  * :heavy_check_mark: Istio-Upstream [#[625]](https://paste.fedoraproject.org/paste/HAhLjUJlgfQYzPDxjkZsYA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2108, 2109]](https://paste.fedoraproject.org/paste/JNzoRCELNHCuCqhnzSZj8Q)
  * :heavy_check_mark: install-bookinfo [#[1156]](https://paste.fedoraproject.org/paste/9t6BS5DZtaylA5FkUmtebQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[1149]](https://paste.fedoraproject.org/paste/D27mV44t-oUdz8mXSbrIYA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[555]](https://paste.fedoraproject.org/paste/YQ6RUAH9b4nB9e-nwBGVhQ)


KIALI_NAME=kialicorepr597-istio-system

**Comment by burmanm** [comment]
Changed, although I don't really like the use of bashism.

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#276](https://paste.fedoraproject.org/paste/yer9CVdSFLENU1kUukEDbw)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1805]](https://paste.fedoraproject.org/paste/KMdhYrc4mm1aW4fQ5CW-eQ)
  * :heavy_check_mark: Istio-Upstream [#[646]](https://paste.fedoraproject.org/paste/nZkPMMjiDWTIGryFkE1UPg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2158, 2159]](https://paste.fedoraproject.org/paste/DAeBBdnzh0xGpBblTaJNIw)
  * :heavy_check_mark: install-bookinfo [#[1180]](https://paste.fedoraproject.org/paste/OH7JuzKVTNjck0s9pTXdOA)
  * :heavy_check_mark: Kiali-on-Openshift [#[1177]](https://paste.fedoraproject.org/paste/fPMV51pI1uHeCB9mbFnrMw)
  * :heavy_check_mark: run-kiali-e2e-tests [#[579]](https://paste.fedoraproject.org/paste/ilNt3gKdvhqIyG4QFZt6Uw)


KIALI_NAME=kialicorepr597-istio-system

**Pull request merged**
