### PR TITLE
[hack] fix install-bookinfo-demo and other hack scripts for SCC priority

### PR DESCRIPTION
**Pull request by jmazzitelli**
https://docs.openshift.com/container-platform/4.13/authentication/managing-security-context-constraints.html#scc-prioritization_configuring-internal-oauth

The SCC created by the script didn't have a priority, so it defaults to 0, which is the same as all the other restrictive sccs that come out of box. So...

```
If the priorities are equal, the SCCs are sorted from most restrictive to least restrictive.
```

### CODE REVIEW

**Review by jshaughn — COMMENTED** [review]
This change fixed the issue but I think this PR needs to update all of our hack scripts, no?

**Comment by jmazzitelli** [comment]
> This change fixed the issue but I think this PR needs to update all of our hack scripts, no?

Yeah, I can do that.

**Comment by jmazzitelli** [comment]
This priority field was supported at least as far back as OpenShift 4.8 so this should be good for any OpenShift version we care about: https://docs.openshift.com/container-platform/4.8/authentication/managing-security-context-constraints.html#scc-prioritization_configuring-internal-oauth

**Review by jshaughn — APPROVED** [review]
Tested against bookinfo and it workee!  Assuming others will benefit in the same way.

**Pull request merged**
