### PR TITLE
no need for two hack scripts anymore 

### PR DESCRIPTION
**Pull request by jmazzitelli**
combine so its easy for people to just download it and run it

### CODE REVIEW

**Comment by jmazzitelli** [comment]
Once this is merged, we can tell people:

```
This is how you can quickly install Kiali to play with it.
$ wget https://raw.githubusercontent.com/kiali/kiali/master/hack/cluster-openshift.sh
$ sh cluster-openshift.sh --kiali-enabled true
```
This will download everything you need, and will start OpenShift, Istio, and Kiali.

NOTE: there is an issue with istiooc and its kiali support. That should be fixed soon.

**Comment by jmazzitelli** [comment]
This PR now, by default, installs Istio 0.7.1.

Side effect is Kiali cannot be installed automatically here (that is only supported by the latest istiooc binary).

There appears to be an --istio-version option in the latest istiooc, I will see if I can use that

**Comment by josejulio** [comment]
> This PR now, by default, installs Istio 0.7.1.

Still need to update the docs, it says that the default is 0.8

**Comment by pilhuhn** [comment]
Who is the target audience? If that is kiali-developers, it would be good to concentrate on 0.8 and not invest in 0.7.1

**Comment by jmazzitelli** [comment]
i'll update the readme. I'm also going to commit a new feature: --cluster-options <opts> so you can pass in other options. This should let us switch istio versions while stil using the latest istiooc

**Comment by jmazzitelli** [comment]
> Who is the target audience? If that is kiali-developers, it would be good to concentrate on 0.8 and not invest in 0.7.1

It really is for devs, but because it is simple, and because it can install everything, we can tell people "wget and run the script and you can have Kiali running." The user doesn't have to download istiooc, doesn't have to know how to install OpenShift, or Istio, or Kiali. So it could be useful other than devs.

But right now, Kiali isn't working nicely with 0.8.0 anyway - so devs that are working on, say, the UI look and feel will probably want to use 0.7.1 for now until we get it more stable with 0.8.0

**Comment by lucasponce** [comment]
I would prefer to work with 0.8.0 in master for all scenarios.
For 0.7.1 people can use the past release, I think.
Using both 0.7.1/0.8.0 could lead in some complexity.
In any case, this 0.7.1 -> 0.8.0 should take a matter of couple of days IMHO.

**Pull request merged**
