### PR TITLE
e2e removal, deleting swagger

### PR DESCRIPTION
**Pull request by hhovsepy**
RFE https://github.com/kiali/kiali/issues/4826
Removing legacy python e2e tests.
Remove swagger and related things.

### CODE REVIEW

**Comment by lucasponce** [comment]
I've started to review this work.

I've found a problem in my environment, like if needs the "oc" client in the PATH

```
{"level":"error","time":"2022-05-11T11:00:06+02:00","message":"exec: \"oc\": executable file not found in $PATH"}
```

I'm reviewing the CI and using Kind, do you still need the "oc" client or it's using the "kubectl" ?

I wonder if we could keep the flag to choose between "oc"/"kubectl" in the integration tests as well, I'd like that those can be executed easily by every developer

**Comment by lucasponce** [comment]
I'm trying to run the tests on minikube following https://github.com/kiali/kiali/tree/master/tests/integration#minikube but I have these issues:

```
=== RUN   TestKialiConfig
    kiali_urls_test.go:29: 
        	Error Trace:	kiali_urls_test.go:29
        	Error:      	Should NOT be empty, but was { }
        	Test:       	TestKialiConfig
    kiali_urls_test.go:30: 
        	Error Trace:	kiali_urls_test.go:30
        	Error:      	Should NOT be empty, but was 
        	Test:       	TestKialiConfig
--- FAIL: TestKialiConfig (0.01s)
=== RUN   TestIstioPermissions
--- PASS: TestIstioPermissions (0.00s)
=== RUN   TestJaeger
    kiali_urls_test.go:51: 
        	Error Trace:	kiali_urls_test.go:51
        	Error:      	Should NOT be empty, but was 
        	Test:       	TestJaeger
--- FAIL: TestJaeger (0.00s)
=== RUN   TestGrafana
    kiali_urls_test.go:70: 
        	Error Trace:	kiali_urls_test.go:70
        	Error:      	Status code should be '200' but was: 503 and error: %!s(<nil>)
        	Test:       	TestGrafana
--- FAIL: TestGrafana (0.00s)
```

I know it's not directly related to this PR, but I think that it's a good moment to check that the integration tests run well in all environments.

I use a clean minikube server with the demos installed using the hack script "install-testing-demos.sh".

I install Kiali in the minikube cluster and open a port-forward to the 20001 port as suggested.

**Comment by nrfox** [comment]
> I've found a problem in my environment, like if needs the "oc" client in the PATH

Yes the integration tests require `oc`. iirc the original python ones being removed here also required `oc` so the two suites were largely kept the same in terms of requirements. The GH actions VMs have `oc` installed by default. That being said I'd be happy if the tests could use either one.

> I use a clean minikube server with the demos installed using the hack script "install-testing-demos.sh".

The integration tests also require you to set the `url` field for both grafana and jaeger. The url doesn't actually need to be resolvable but in order for the tests to see an API response to test the integration, those fields need to be set since there's not a good way to default the url field: https://github.com/kiali/kiali/issues/5030. These requirements should be documented if they are not already.

**Comment by lucasponce** [comment]
> That being said I'd be happy if the tests could use either one.
+1

> The url doesn't actually need to be resolvable but in order for the tests to see an API response to test the integration
I think there are more cases, like the cluster Ids, that are not working well.

But it seems there are just a couple of tests and most of the work should work with one or another environment without big changes of the existing effort (thanks again!).

So I'd prefer that before removing the existing tests we can make this work robust with these couple of changes.

My goal here: is to be sure that any developer must run cypress and integration tests within their local environment and all is clear, so we don't need to chase the author of these changes, and anyone can maintain them.

**Comment by nrfox** [comment]
> My goal here: is to be sure that any developer must run cypress and integration tests within their local environment and all is clear, so we don't need to chase the author of these changes, and anyone can maintain them.

Yes! And being able to use `kubectl` or `oc` depending on which one is available is probably a small change. I'm not sure what we can do about the grafana/jaeger configuration other than document it as a requirement since setting that field will depend on how you've deployed kiali which is different in each environment these tests run in.

**Comment by lucasponce** [comment]
> I'm not sure what we can do about the grafana/jaeger configuration other than document it as a requirement since setting that field will depend on how you've deployed kiali which is different in each environment these tests run in.

No, it's fine, I think a test that checks that the URLs are populated (even if not available because it's a test env) it's perfectly OK.

Perhaps I was more curious about the other URLs about the cluster-mesh-id that seems missing, as probably there is some assumption about the configuration that doesn't work in all the cases.

**Comment by hhovsepy** [comment]
@lucasponce , the support of `kubectl` (or any other `oc` replacement) command can be added in a follow-up tasks.
Here the scope is to remove the legacy e2e tests and swagger json.

**Review by lucasponce — APPROVED** [review]
LGTM

I put some comments checking that these tests can be executed without "oc" dependencies.
But as discussed, I'm +1 if those can be added in a follow-up task.

Thanks @hhovsepy

**Pull request merged**
