### PR TITLE
run-kiali.sh now works if Istio is installed with an unset cluster name

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/6742

### CODE REVIEW

**Comment by jmazzitelli** [comment]
@josunect you use this script alot - can you test this and see if it breaks how you use it? Jay needed this set, but I wonder if this new default will break other environments?

**Review by jshaughn — DISMISSED** [review]
This works for my setup where Istio is installed without a cluster name, and therefore defaults to "Kubernetes".  For users of `run-kiali.sh` that have a non-default cluster name, and wher (I assum) `run-kiali.sh` was working, they may need to now set the new `-cn` option.

**Comment by jmazzitelli** [comment]
> I want to make sure that weren't not covering up a problem with cluster name handling here. I don't think you should need to set `cluster_name` when using `run-kiali.sh`.

I'll put a DNM label on here until you give it a thumbs up.

**Comment by josunect** [comment]
> I want to make sure that weren't not covering up a problem with cluster name handling here. I don't think you should need to set `cluster_name` when using `run-kiali.sh`.

I think the issue was related that the istio cluster name was "" (In the istio install hack script). 
I will also test it.

**Comment by josunect** [comment]
I have tested it and in the graph page I still have the same error message: 
image

When cluster_name is not set in the config. 
In the run-kiali I can see the cluster_name is set: 

image

If I set the cluster_name in the config I'm able to see the graph: 

image

**Comment by EdisonFu** [comment]
I have met same question. Cluster name should be set into istio operator. 
Kiali read it from istio config.

**Comment by josunect** [comment]
I've installed istio with the istio hack script: 

`istio/install-istio-via-istioctl.sh -c kubectl`

`MANIFEST_CONFIG_SETTINGS_TO_APPLY= --set hub=gcr.io/istio-release  --set values.meshConfig.enableAutoMtls=true --set values.pilot.env.ENABLE_NATIVE_SIDECARS=false  --set values.gateways.istio-egressgateway.enabled=true --set values.gateways.istio-ingressgateway.enabled=true --set values.global.meshID= --set values.global.multiCluster.clusterName= --set values.global.network= --set values.meshConfig.accessLogFile=/dev/stdout`

**Comment by EdisonFu** [comment]
@josunect This error is due to kiali reading  metrics from prometheus, and prometheus get cluster name from istio. If istio's cluster name is not set, prometheus will set a default value "Kubernetes" for its metrics label. If the "Kubernetes" is not set in kiali, then the error will appear like what you got. 
All we need to do is match kiali's cluster name to istio's.

**Comment by nrfox** [comment]
@josunect can you try with: https://github.com/kiali/kiali/pull/6746?

@jmazzitelli FWIW we can still add the cluster name opt to that run-kiali hack script but we shouldn't _need_ to do that. It might be nice to leave it off by default to test that the defaults work.


> @josunect This error is due to kiali reading metrics from prometheus, and prometheus get cluster name from istio. If istio's cluster name is not set, prometheus will set a default value "Kubernetes" for its metrics label. If the "Kubernetes" is not set in kiali, then the error will appear like what you got.
All we need to do is match kiali's cluster name to istio's.

@EdisonFu that's right only I believe that if you don't set `values.global.multiCluster.clusterName` then istio, not prometheus, will set a default value of `Kubernetes`. Kiali gets this by looking at the istiod deployment and looking for an env var named `CLUSTER_ID`. The steps are:

1. If `config.KuberentesConfig.ClusterName` has been set, use that since that is set by the user.
2. Try to auto-detect the cluster name from the istiod deployment's env var.
3. Fallback to `Kubernetes` if auto-detect fails.

Are you seeing problems with the cluster id not being set properly? If so, we can open a separate issue and discuss there to better track the issue/discussion. It could be that step 3 is too lenient and Kiali should fail to start if 1 and 2 fails.

**Comment by jmazzitelli** [comment]
let me figure out how get this to only show up if that cmd line argument isn't specified

**Comment by jmazzitelli** [comment]
> we can still add the cluster name opt to that run-kiali hack script but we shouldn't _need_ to do that. It might be nice to leave it off by default to test that the defaults work.

I changed this PR so that now the cluster_name setting is only put in the config IF the user sets a cluster name to run-kiali.sh via `--cluster-name`. It leaves it undefined in the config (like it was before) if you do not specify that option.

**Review by nrfox — APPROVED** [review]

**Pull request merged**
