### PR TITLE
Include ControlPlane workloads to KIA0302 no matching workload

### PR DESCRIPTION
**Pull request by xeviknal**
Fixes https://github.com/kiali/kiali/issues/3265#

Goal: include istio-system workloads to the look up for workloads in the gateways selector checker.

I have several thoughts regarding this change:
1. It breaks the cross-namespace validation rule. Security-wise, bad-intended users without access to istio-system could gain information about workloads in the istio-system that match that specific selector. Is it that bad?
2. I think it might be different kinds of deployments where the ingress/egress are going to be in different namespaces than the control plane. Therefore, the validation will keep failing.
3. Because of the previous thoughts, I am wondering if we should remove the warning at all. 

Thoughts?

### CODE REVIEW

**Comment by lucasponce** [comment]
> It breaks the cross-namespace validation rule. Security-wise, bad-intended users without access to istio-system could gain information about workloads in the istio-system that match that specific selector. Is it that bad?

We assume that Istio users can access to the control plane, to have access in read mode to the names of the workloads in the control plane for validation purposes seems to me a scenario under control.

Indeed we have more like this inside kiali.

Write operations are always done under the user's privileges, but some read operations have granularity of the namespace.

**Comment by lucasponce** [comment]
> I think it might be different kinds of deployments where the ingress/egress are going to be in different namespaces than the control plane. Therefore, the validation will keep failing.

Well, note that we have all this info cached, so accessing to it is faster. And kiali has access to this info. There should be a corner case that may fall if there are some tricky combination of permissions on two namespaces userA -> namespaceA, and userB -> namespaceB but namespaceA has a gateway defined in namespaceB ... something in that sense, but it seems a tweak scenario in this validation context.

**Comment by lucasponce** [comment]
> Because of the previous thoughts, I am wondering if we should remove the warning at all.

Not sure if remove it but perhaps iterate on them.

I guess that Kiali is doing good validation within the mesh (VS/DR) but it seems users need help on these Ingress/Egress scenarios.

So, if this validation is useful I'd keep it even if that means some change in the background.

If there is an unbalance tradeoff between feature and implementation perhaps we can reconsider.

**Comment by hhovsepy** [comment]
Before:
Screenshot from 2020-11-04 11-41-46

After:
Screenshot from 2020-11-04 11-56-02

But in list still warning is displayed.
Screenshot from 2020-11-04 11-56-15

**Comment by xeviknal** [comment]
I've updated this validation to consider all the available workloads. This way, only false-positive when one user doesn't have access to the namespace with ingress/egress.

Nevertheless, I am concerned in the scenario where a user goes to the istio config list page for several namespaces, plus each namespace has hundreds of services each. Since the API calls in the list are per namespace, each call will fetch from cache the workloads of all the available ns. Should we implement a booster here? Like a shared variable for both requests?

**Comment by lucasponce** [comment]
> Should we implement a booster here? Like a shared variable for both requests?

Perhaps we can see later, but `GetNamespaces` and `GetWorkloadList` queries are already cached, so it shouldn't have any additional backend call on regular scenario.

**Review by lucasponce — APPROVED** [review]

**Pull request merged**
