### PR TITLE
Make Multicluster CI use snapshot version and not release version

### PR DESCRIPTION
**Pull request by matejnesuta**
Related to #6547.

To test this:
- build Kiali locally 
- run the `./hack/run-integration-tests.sh --test-suite frontend-multi-cluster -so true` command
- open the Kiali page and check that it uses SNAPSHOT version and not release

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I'm getting failures - it can't start everything successfully:
```
$ ./hack/run-integration-tests.sh --test-suite frontend-multi-cluster -so true
=== SETTINGS ===
SETUP_ONLY=true
TEST_SUITE=frontend-multi-cluster
=== SETTINGS ===
[INFO] Running frontend-multi-cluster integration tests
/home/jmazzite/source/kiali/kiali
=== SETTINGS ===
AUTH_STRATEGY="anonymous
DORP=podman
ISTIO_VERSION=
KIND_NODE_IMAGE=kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
MULTICLUSTER=true
TARGET_BRANCH=master
=== SETTINGS ===
[INFO] Make sure everything exists
[INFO] Downloading istio
Output Directory: /home/jmazzite/source/kiali/kiali/_output
Will use the latest Istio version: 1.19.0
Will look for Istio here: /home/jmazzite/source/kiali/kiali/_output/istio-1.19.0
Istio is found here: /home/jmazzite/source/kiali/kiali/_output/istio-1.19.0
client version: 1.19.0
control plane version: 1.19.0
data plane version: 1.19.0 (2 proxies)
istioctl is found here: /home/jmazzite/source/kiali/kiali/_output/istio-1.19.0/bin/istioctl
[INFO] Downloading istio
Output Directory: /home/jmazzite/source/kiali/kiali/_output
Will use the latest Istio version: 1.19.0
Will look for Istio here: /home/jmazzite/source/kiali/kiali/_output/istio-1.19.0
Istio is found here: /home/jmazzite/source/kiali/kiali/_output/istio-1.19.0
client version: 1.19.0
control plane version: 1.19.0
data plane version: 1.19.0 (2 proxies)
istioctl is found here: /home/jmazzite/source/kiali/kiali/_output/istio-1.19.0/bin/istioctl
[INFO] Cloning kiali helm-charts...
Cloning into '/tmp/tmp.tnVAKTNJfu'...
remote: Enumerating objects: 1314, done.
remote: Counting objects: 100% (230/230), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 1314 (delta 172), reused 194 (delta 155), pack-reused 1084
Receiving objects: 100% (1314/1314), 1.33 MiB | 8.40 MiB/s, done.
Resolving deltas: 100% (792/792), done.
make: Entering directory '/tmp/tmp.tnVAKTNJfu'
The binary will be downloaded to /tmp/tmp.tnVAKTNJfu/_output/helm-install/helm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.8M  100 13.8M    0     0  6809k      0  0:00:02  0:00:02 --:--:-- 6812k
Will use this helm executable: /tmp/tmp.tnVAKTNJfu/_output/helm-install/helm
Building Helm Chart for Kiali operator
==> Linting /tmp/tmp.tnVAKTNJfu/_output/charts/kiali-operator

1 chart(s) linted, 0 chart(s) failed
Successfully packaged chart and saved it to: /tmp/tmp.tnVAKTNJfu/_output/charts/kiali-operator-1.74.0-SNAPSHOT.tgz
Building Helm Chart for Kiali server
==> Linting /tmp/tmp.tnVAKTNJfu/_output/charts/kiali-server

1 chart(s) linted, 0 chart(s) failed
Successfully packaged chart and saved it to: /tmp/tmp.tnVAKTNJfu/_output/charts/kiali-server-1.74.0-SNAPSHOT.tgz
make: Leaving directory '/tmp/tmp.tnVAKTNJfu'
[INFO] Kind cluster to be created with name [ci]
Istio is found here: /home/jmazzite/source/kiali/kiali/hack/../_output/istio-1.19.0
istioctl is found here: /home/jmazzite/source/kiali/kiali/hack/../_output/istio-1.19.0/bin/istioctl
client version: 1.19.0
control plane version: 1.19.0
data plane version: 1.19.0 (2 proxies)
Makefile is found here: /home/jmazzite/source/kiali/kiali/hack/../_output/istio-1.19.0/tools/certs/Makefile.selfsigned.mk
The cluster client executable is found here: /home/jmazzite/bin/kubectl
Cluster type = Kubernetes
=== SETTINGS ===
BOOKINFO_ENABLED=true
BOOKINFO_NAMESPACE=bookinfo
CLIENT_EXE_NAME=kubectl
CLUSTER1_CONTEXT=kind-east
CLUSTER1_NAME=east
CLUSTER1_PASS=kiali
CLUSTER1_USER=kiali
CLUSTER2_CONTEXT=kind-west
CLUSTER2_NAME=west
CLUSTER2_PASS=kiali
CLUSTER2_USER=kiali
CROSSNETWORK_GATEWAY_REQUIRED=true
DORP=docker
IS_OPENSHIFT=false
ISTIO_DIR=/home/jmazzite/source/kiali/kiali/hack/../_output/istio-1.19.0
ISTIO_NAMESPACE=istio-system
ISTIO_TAG=
KIALI_AUTH_STRATEGY=openid
KIALI_CREATE_REMOTE_CLUSTER_SECRETS=true
KIALI_ENABLED=true
KIALI_USE_DEV_IMAGE=false
KIALI1_WEB_FQDN=
KIALI1_WEB_SCHEMA=
KIALI2_WEB_FQDN=
KIALI2_WEB_SCHEMA=
MANAGE_KIND=true
MANAGE_MINIKUBE=false
MANUAL_MESH_NETWORK_CONFIG=false
MINIKUBE_CPU=
MINIKUBE_DISK=
MINIKUBE_DRIVER=kvm2
MINIKUBE_MEMORY=
MESH_ID=mesh-hack
NETWORK1_ID=network-east
NETWORK2_ID=network-west
SINGLE_KIALI=true
=== SETTINGS ===
Starting kind instances
==== START KIND FOR CLUSTER #1 [east] - kind-east
Kind executable: /home/jmazzite/bin/kind
Kubectl executable: /home/jmazzite/bin/kubectl
[INFO] No external image registry will be configured for use by the KinD instance.
[INFO] Kind cluster to be created with name [east]
Creating cluster "east" ...
 ✓ Ensuring node image (kindest/node:v1.27.3) 🖼
 ✓ Preparing nodes 📦 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✓ Joining worker nodes 🚜 
Set kubectl context to "kind-east"
You can now use your cluster with:

kubectl cluster-info --context kind-east

Have a nice day! 👋
[INFO] Creating Kind LoadBalancer via MetalLB
namespace/metallb-system created
customresourcedefinition.apiextensions.k8s.io/addresspools.metallb.io created
customresourcedefinition.apiextensions.k8s.io/bfdprofiles.metallb.io created
customresourcedefinition.apiextensions.k8s.io/bgpadvertisements.metallb.io created
customresourcedefinition.apiextensions.k8s.io/bgppeers.metallb.io created
customresourcedefinition.apiextensions.k8s.io/communities.metallb.io created
customresourcedefinition.apiextensions.k8s.io/ipaddresspools.metallb.io created
customresourcedefinition.apiextensions.k8s.io/l2advertisements.metallb.io created
serviceaccount/controller created
serviceaccount/speaker created
role.rbac.authorization.k8s.io/controller created
role.rbac.authorization.k8s.io/pod-lister created
clusterrole.rbac.authorization.k8s.io/metallb-system:controller created
clusterrole.rbac.authorization.k8s.io/metallb-system:speaker created
rolebinding.rbac.authorization.k8s.io/controller created
rolebinding.rbac.authorization.k8s.io/pod-lister created
clusterrolebinding.rbac.authorization.k8s.io/metallb-system:controller created
clusterrolebinding.rbac.authorization.k8s.io/metallb-system:speaker created
configmap/metallb-excludel2 created
secret/webhook-server-cert created
service/webhook-service created
deployment.apps/controller created
daemonset.apps/speaker created
validatingwebhookconfiguration.admissionregistration.k8s.io/metallb-webhook-configuration created
[INFO] Wait for MetalLB controller to be ready
Waiting for deployment "controller" rollout to finish: 0 of 1 updated replicas are available...
deployment "controller" successfully rolled out
[INFO] LoadBalancer IP Address pool: 172.18.255.70-172.18.255.84
ipaddresspool.metallb.io/config created
l2advertisement.metallb.io/l2config created
[INFO] Kind cluster 'east' created successfully with metallb loadbalancer
==== START KIND FOR CLUSTER #2 [west] - kind-west
Kind executable: /home/jmazzite/bin/kind
Kubectl executable: /home/jmazzite/bin/kubectl
[INFO] No external image registry will be configured for use by the KinD instance.
[INFO] Kind cluster to be created with name [west]
Creating cluster "west" ...
 ✓ Ensuring node image (kindest/node:v1.27.3) 🖼
 ✓ Preparing nodes 📦 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✓ Joining worker nodes 🚜 
Set kubectl context to "kind-west"
You can now use your cluster with:

kubectl cluster-info --context kind-west

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
[INFO] Creating Kind LoadBalancer via MetalLB
namespace/metallb-system created
customresourcedefinition.apiextensions.k8s.io/addresspools.metallb.io created
customresourcedefinition.apiextensions.k8s.io/bfdprofiles.metallb.io created
customresourcedefinition.apiextensions.k8s.io/bgpadvertisements.metallb.io created
customresourcedefinition.apiextensions.k8s.io/bgppeers.metallb.io created
customresourcedefinition.apiextensions.k8s.io/communities.metallb.io created
customresourcedefinition.apiextensions.k8s.io/ipaddresspools.metallb.io created
customresourcedefinition.apiextensions.k8s.io/l2advertisements.metallb.io created
serviceaccount/controller created
serviceaccount/speaker created
role.rbac.authorization.k8s.io/controller created
role.rbac.authorization.k8s.io/pod-lister created
clusterrole.rbac.authorization.k8s.io/metallb-system:controller created
clusterrole.rbac.authorization.k8s.io/metallb-system:speaker created
rolebinding.rbac.authorization.k8s.io/controller created
rolebinding.rbac.authorization.k8s.io/pod-lister created
clusterrolebinding.rbac.authorization.k8s.io/metallb-system:controller created
clusterrolebinding.rbac.authorization.k8s.io/metallb-system:speaker created
configmap/metallb-excludel2 created
secret/webhook-server-cert created
service/webhook-service created
deployment.apps/controller created
daemonset.apps/speaker created
validatingwebhookconfiguration.admissionregistration.k8s.io/metallb-webhook-configuration created
[INFO] Wait for MetalLB controller to be ready
Waiting for deployment "controller" rollout to finish: 0 of 1 updated replicas are available...
deployment "controller" successfully rolled out
[INFO] LoadBalancer IP Address pool: 172.18.255.85-172.18.255.98
ipaddresspool.metallb.io/config created
l2advertisement.metallb.io/l2config created
[INFO] Kind cluster 'west' created successfully with metallb loadbalancer
/tmp/istio-multicluster-certs ~/source/kiali/kiali
generating root-key.pem
generating root-cert.csr
generating root-cert.pem
Certificate request self-signature ok
subject=O = Istio, CN = Root CA
generating east/ca-key.pem
generating east/cluster-ca.csr
generating east/ca-cert.pem
Certificate request self-signature ok
subject=O = Istio, CN = Intermediate CA, L = east
generating east/cert-chain.pem
Intermediate inputs stored in east/
done
rm east/cluster-ca.csr east/intermediate.conf
generating west/ca-key.pem
generating west/cluster-ca.csr
generating west/ca-cert.pem
Certificate request self-signature ok
subject=O = Istio, CN = Intermediate CA, L = west
generating west/cert-chain.pem
Intermediate inputs stored in west/
done
rm west/intermediate.conf west/cluster-ca.csr
~/source/kiali/kiali
==== CREATE CERTS FOR CLUSTER #1 [east] - kind-east
Switched to context "kind-east".
Error from server (NotFound): namespaces "istio-system" not found
namespace/istio-system created
Error from server (NotFound): secrets "cacerts" not found
secret/cacerts created
==== CREATE CERTS FOR CLUSTER #2 [west] - kind-west
Switched to context "kind-west".
Error from server (NotFound): namespaces "istio-system" not found
namespace/istio-system created
Error from server (NotFound): secrets "cacerts" not found
secret/cacerts created
Switched to context "kind-east".
namespace/istio-system labeled
Istio is found here: /home/jmazzite/source/kiali/kiali/hack/../_output/istio-1.19.0
istioctl is found here: /home/jmazzite/source/kiali/kiali/hack/../_output/istio-1.19.0/bin/istioctl
Creating the control plane namespace: istio-system
NAME           STATUS   AGE
istio-system   Active   0s
Labeling namespace with network name [network-east]
namespace/istio-system not labeled
CONFIG_PROFILE=demo
MANIFEST_CONFIG_SETTINGS_TO_APPLY= --set hub=gcr.io/istio-release  --set values.meshConfig.enableAutoMtls=true  --set values.gateways.istio-egressgateway.enabled=true --set values.gateways.istio-ingressgateway.enabled=true --set values.global.meshID=mesh-hack --set values.global.multiCluster.clusterName=east --set values.global.network=network-east --set values.meshConfig.accessLogFile=/dev/stdout    --set values.pilot.env.EXTERNAL_ISTIOD=true
Installing Istio...
✔ Istio core installed                                                                                                                       
✔ Istiod installed                                                                                                                           
✔ Egress gateways installed                                                                                                                  
✔ Ingress gateways installed                                                                                                                 
✔ Installation complete                                                                                                                      Made this installation the default for injection and validation.
Installing Addons: [prometheus grafana jaeger]
Installing addon: [prometheus]
serviceaccount/prometheus created
configmap/prometheus created
clusterrole.rbac.authorization.k8s.io/prometheus created
clusterrolebinding.rbac.authorization.k8s.io/prometheus created
service/prometheus created
deployment.apps/prometheus created
Installing addon: [grafana]
serviceaccount/grafana created
configmap/grafana created
service/grafana created
deployment.apps/grafana created
configmap/istio-grafana-dashboards created
configmap/istio-services-grafana-dashboards created
Installing addon: [jaeger]
deployment.apps/jaeger created
service/tracing created
service/zipkin created
service/jaeger-collector created
Gateway API Version is not specified, taking the latest released version
Installing Gateway API version v0.8.0
customresourcedefinition.apiextensions.k8s.io/gatewayclasses.gateway.networking.k8s.io created
customresourcedefinition.apiextensions.k8s.io/gateways.gateway.networking.k8s.io created
customresourcedefinition.apiextensions.k8s.io/httproutes.gateway.networking.k8s.io created
customresourcedefinition.apiextensions.k8s.io/referencegrants.gateway.networking.k8s.io created
✔ Ingress gateways installed                                                                                                                 
✔ Installation complete                                                                                                                      gateway.networking.istio.io/istiod-gateway created
virtualservice.networking.istio.io/istiod-vs created
gateway.networking.istio.io/cross-network-gateway created
Installing Kiali in a single cluster.
/home/jmazzite/bin/helm
==== DEPLOY KIALI TO CLUSTER #1 [east] - kind-east (keycloak is at east)
Switched to context "kind-east".
error: error reading /tmp/istio-multicluster-certs/keycloak/root-ca.pem: no such file or directory
secret/kiali created
clusterrolebinding.rbac.authorization.k8s.io/kiali-user-viewer created
Preparing remote cluster secret for single Kiali install in multicluster mode.
INFO: === SETTINGS ===
INFO: CLIENT_EXE=/home/jmazzite/bin/kubectl
INFO: PROCESS_KIALI_SECRET=true
INFO: PROCESS_REMOTE_RESOURCES=true
INFO: DELETE=false
INFO: DRY_RUN=false
INFO: HELM=helm
INFO: KIALI_CLUSTER_CONTEXT=kind-east
INFO: KIALI_CLUSTER_NAMESPACE=istio-system
INFO: KIALI_VERSION=latest
INFO: REMOTE_CLUSTER_CONTEXT=kind-west
INFO: REMOTE_CLUSTER_NAME=west
INFO: REMOTE_CLUSTER_NAMESPACE=kiali-access-ns
INFO: REMOTE_CLUSTER_URL=https://172.18.0.4:6443
INFO: VIEW_ONLY=false
INFO: EXEC_AUTH_JSON=
INFO: REMOTE_CLUSTER_NAME=west
INFO: Create the remote cluster namespace [kiali-access-ns] if it doesn't exist
namespace/kiali-access-ns created
INFO: Create the remote cluster resources with the appropriate permissions for Kiali (view_only=false)
serviceaccount/kiali-remote-access created
clusterrole.rbac.authorization.k8s.io/kiali-remote-access created
clusterrolebinding.rbac.authorization.k8s.io/kiali-remote-access created
secret/kiali-remote-access created
INFO: Create the remote cluster secret in the Kiali cluster
INFO: remote_cluster_server_url=https://172.18.0.4:6443
secret/kiali-remote-cluster-secret-west created
INFO: A remote cluster secret named [kiali-remote-cluster-secret-west] has been created in the Kiali cluster namespace [istio-system]. It can be used by Kiali to access the remote cluster.
virtualservice.networking.istio.io/kiali created
Error: unknown shorthand flag: 'p' in -p
Switched to context "kind-west".
namespace/istio-system annotated
namespace/istio-system labeled
✔ Istiod remote installed                                                                                                                    
✔ Installation complete                                                                                                                      Made this installation the default for injection and validation.
serviceaccount/prometheus created
configmap/prometheus created
clusterrole.rbac.authorization.k8s.io/prometheus created
clusterrolebinding.rbac.authorization.k8s.io/prometheus created
service/prometheus created
deployment.apps/prometheus created
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-sidecar-injector patched
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-sidecar-injector patched
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-sidecar-injector patched
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-sidecar-injector patched
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-revision-tag-default patched
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-revision-tag-default patched
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-revision-tag-default patched
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-revision-tag-default patched
Error: unknown flag: --name
error: no objects passed to apply
- Processing resources for Ingress gateways. Waiting for Deployment/istio-system/istio-eastwestgateway                                       
```

**Comment by matejnesuta** [comment]
The last error is related to #6608. Not sure about `Error: unknown shorthand flag: 'p' in -p`. It happens way before ./deploy_kiali.sh gets executed.

**Review by jmazzitelli — APPROVED** [review]
even though I saw those errors in the output, the clusters started up and I do see the dev image deployed for the kiali pod:

```
$ kubectl --context=kind-east get pods -n istio-system -l app=kiali -o jsonpath='{.items..spec.containers..image}{"\n"}'
localhost/kiali/kiali:dev
```

```
$ kubectl --context=kind-east logs -n istio-system -l app=kiali --tail=-1 | head -n 2
{"level":"info","time":"2023-09-13T15:44:44Z","message":"Adding a RegistryRefreshHandler"}
2023-09-13T15:44:44Z INF Kiali: Version: v1.74.0-SNAPSHOT, Commit: 1c499a511cb1343be869c3786cd1446a5c74fbac, Go: 1.20.5
```

**Comment by jmazzitelli** [comment]
I created another issue for those `Error: unknown` messages (there were 2 of them): https://github.com/kiali/kiali/issues/6612

**Pull request merged**
