### PR TITLE
KIALI-2780 workaround for the operator sdk "bug" that breaks dashboard installs

### PR DESCRIPTION
**Pull request by jmazzitelli**
@jotak what do you think of this as a temporary workaround? We'll remove this once our operator pulls in the operator sdk bug fix, but for now, I think this works.

### CODE REVIEW

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#996](https://paste.fedoraproject.org/paste/MS93kMHjGyBKEU0AyMGHtA)
 :red_circle: PRT Failed, Please Contact QE

**Comment by jotak** [comment]
Do you have any idea when is the next operator-sdk release? If it's in a few days I think we can skip that temporary workaround, but if it's weeks or months or we don't know, then +1 for this one.

**Comment by jmazzitelli** [comment]
> Do you have any idea when is the next operator-sdk release?

I just inquired about this - I was told 0.8.0 will be released in about 2 weeks.

**Comment by jmazzitelli** [comment]
operator-sdk 0.8.0 has been released, we should not need this PR anymore... testing needs to be done to make sure. See: https://github.com/operator-framework/operator-sdk/releases/tag/v0.8.0

**Comment by jotak** [comment]
So @jmazzitelli , since the operator bump did not solve this issue, should we merge that?

**Comment by jmazzitelli** [comment]
> So @jmazzitelli , since the operator bump did not solve this issue, can we merge that? (it must be rebased... conflicting)

I'll rebase. This is now what we are waiting for: https://github.com/operator-framework/operator-sdk/pull/1473

**Comment by jmazzitelli** [comment]
Doesn't look like the operator-sdk "problem" is going to be fixed - we are going to need to make this change a permanent change. The user must know to install the runtime dashboard CRD first, before installing the operator. See: https://github.com/operator-framework/operator-sdk/pull/1473

**Comment by jmazzitelli** [comment]
I'm going to close this and create another PR. Since we need to re-think our CRD management, I will need to have the script create the CRD but also I will need to remove the CRD creation from the operator itself. All of that should go in a single PR.

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#1042](https://paste.fedoraproject.org/paste/ProHKx0CqVMzTDzEd5feDQ)
 :red_circle: PRT Failed, Please Contact QE

**Pull request closed without merging**
