### PR TITLE
Show time controls in a modal from mini-graph card

### PR DESCRIPTION
**Pull request by israel-hdez**
**This only affects the kiosk=parent mode**

The _refresh interval_ and _duration_ controls are currently not available in the kiosk mode, because toolbars are not visible.

When Kiali is running under in kiosk mode, the title of the mini-graph card (i.e. the time range) will become clickable. When clicking, a modal dialog will appear offering the missing time controls.

Since this is done in the mini-graph card component, these changes are reflected in all detail pages (apps, workloads, services).

Related to kiali/openshift-servicemesh-plugin#42

### CODE REVIEW

**Comment by lucasponce** [comment]
Thanks, @israel-hdez; I'm going to test it.

One comment; changes that are sent to the kiali repo are considered generic to the "kiosk" mode is whatever mode a user can use (the "simple" default one or the "advanced" with the communication enabled between parent/iframe.

In other words, let's avoid adding "OpenShift Plugin" or any other reference in the main kiali repo. Otherwise, that may bring confusion to other users. Just use the "kiosk" mode instead.

(I see comments needing to be changed in the commit message and PR).

**Comment by lucasponce** [comment]
I have a first comment about the style: in the kiosk mode is introducing some padding that breaks the line alignment:
image
vs 
image

Another comment about style, if you look to the other "icons" all of them are aligned to the "right," so it looks "weird" to align the "time" icon to the left in this context.

Also, the font sizes:
image

I would keep that long text in "font 14px".

The modal is ok from a style point of view; I understand the tradeoff, and probably this location may change if the "parent" of the iframe provides any helper for this scenario.

I think the other tabs may show just the icon (aligned to the right, similar to the graph offers) to invoke the modal similarly.

But that can be performed in a different PR if it makes this work longer.

**Comment by israel-hdez** [comment]
@lucasponce Thanks for the review!
I pushed changes to fix the font and paddings. It should be good now.

About the other tabs, yes I'm planning to open new PRs to add the dialog on them.

**Comment by israel-hdez** [comment]
> let's avoid adding "OpenShift Plugin

OK, I changed the main description :-)

**Review by lucasponce — APPROVED** [review]
From the kiosk=parent:
image

Modal:
image

From standalone:
image

**Comment by israel-hdez** [comment]
Thanks for the review, @lucasponce.
Merging!

**Pull request merged**
