### PR TITLE
issue #1034 - have cluster-openshift.sh use the new operator deploy script

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixed issue #1034

### CODE REVIEW

**Comment by jmazzitelli** [comment]
To test this, shutdown your openshift cluster, then start a new one with the hack script and tell it to install kiali at the same time:

`hack/cluster-openshift.sh -ke true up`

**Comment by rhqci** [comment]
PRT Failed, Please Contact QE

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by rhqci** [comment]
Jenkins CI: kiali-core-pr-e2e-test [#978](https://paste.fedoraproject.org/paste/Hsd1QcBAtqbScdbedSrkLA)
  * :heavy_check_mark: run-kiali-e2e-tests [#[1792]](https://paste.fedoraproject.org/paste/eC8TlmV6UteQo0m5Sgbl6w)

**Pull request merged**
