### PR TITLE
[1.48] Upgrade go to 1.20

### PR DESCRIPTION
**Pull request by aljesusg**
Fix https://github.com/kiali/kiali/issues/6218

### CODE REVIEW

**Comment by aljesusg** [comment]
No idea why this fail with warnings I'll clean it

```bash
agutierr@agutierr:~/kiali/kiali (upgrade_go_1_48)$/home/agutierr/go/bin/swagger validate ./swagger.json
2023/05/31 17:24:07 
The swagger spec at "./swagger.json" is valid against swagger specification 2.0
2023/05/31 17:24:07 
The swagger spec at "./swagger.json" showed up some valid but possibly unwanted constructs.
2023/05/31 17:24:07 See warnings below:
2023/05/31 17:24:07 - WARNING: response "#/responses/workloadHealthResponse" is not used anywhere
2023/05/31 17:24:07 - WARNING: response "#/responses/serviceHealthResponse" is not used anywhere
2023/05/31 17:24:07 - WARNING: response "#/responses/appHealthResponse" is not used anywhere
agutierr@agutierr:~/kiali/kiali (upgrade_go_1_48)
```

**Comment by jmazzitelli** [comment]
@aljesusg We can merge this whenever you clean this up.

**Comment by aljesusg** [comment]
I am out now I wanted to add the upgrade of k8s client too but I don't know if we should backport it

**Comment by jmazzitelli** [comment]
no need to backport that. not sure we even needed to backport go to 1.20 for this version.

**Review by jshaughn — APPROVED** [review]
The backport looks OK, although there may be the need for a swagger update.  Since @aljesusg is out, I'm going to merge this and we can deal with any remaining issues in another PR.

**Pull request merged**
