### PR TITLE
[v1.89] Update webpack to version 5.94.0

### PR DESCRIPTION
**Pull request by ferhoyos**
Backport of PR #7675 to version 1.89

### CODE REVIEW

**Comment by aljesusg** [comment]
Why we need to backport the webpack upgrade?

**Comment by ferhoyos** [comment]
Due to https://issues.redhat.com/browse/OSSM-8021. We need to backport the webpack upgrade to v1.89, 1.73 and 1.65 branches.

**Comment by aljesusg** [comment]
Ok. Thanks I added it to the description the JIRA in  https://github.com/kiali/kiali/pull/7675 . So we need to backport this to 1.73 too

**Review by aljesusg — APPROVED** [review]
LGFM

**Pull request merged**
