### PR TITLE
KIALI-1661 Fetch Kiali permissions with Istio resources

### PR DESCRIPTION
**Pull request by jotak**
Fetch permissions only while looking for istio object details - not lists, as it heavily impacts performances

JIRA: https://issues.jboss.org/browse/KIALI-1661 and https://issues.jboss.org/browse/KIALI-1809

### CODE REVIEW

**Comment by jotak** [comment]
This time I didn't see obvious performance drop. And if there's any, it would be contained in istio details page, so much more manageable than in the previous attempt for KIALI-1661

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#240](https://paste.fedoraproject.org/paste/YpZ8K9JH7CZwiOYFb-QNWw)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1735]](https://paste.fedoraproject.org/paste/6V8c9CqBUD~qGaOB0BePvw)
  * :heavy_check_mark: Istio-Upstream [#[582]](https://paste.fedoraproject.org/paste/U64F8G3OLTipS38rwdSKdw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2018]](https://paste.fedoraproject.org/paste/HPGc~R3VfZNFF98Wafcgmg)
  * :red_circle: install-bookinfo [#[1108]](https://paste.fedoraproject.org/paste/dOjFig-Yq95AQsIYhu0DVA)


KIALI_NAME=kialicorepr583-istio-system

**Comment by lucasponce** [comment]
> This time I didn't see obvious performance drop. And if there's any, it would be contained in istio details page, so much more manageable than in the previous attempt for KIALI-1661

+1

I've started to review it locally, to validate that my smoke tests run ok.
I see travis is complaining about non updated swagger.

**Comment by jotak** [comment]
@lucasponce updated with swagger

**Comment by lucasponce** [comment]
Ok, in terms of performance there is not an obvious penalty now.
On some testing, I can get a 90% of 20-40ms latency with a 10% around 200-400ms.
Also, to restrict permission on details only, it doesn't impact into graph generation.

So I think this is reasonable, we can work with more improvements in the future, but in terms of performance sounds ok to me.

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#241](https://paste.fedoraproject.org/paste/9ql~GmQuG8wy03Ri3oUDdQ)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[1738]](https://paste.fedoraproject.org/paste/V9Yo33Pq~qZYRCAtmaYKfA)
  * :heavy_check_mark: Istio-Upstream [#[585]](https://paste.fedoraproject.org/paste/-ujNFbqwFNiRZ9GIUJ5sfQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2022]](https://paste.fedoraproject.org/paste/D2dN1vMPCLcUFw4murr-Kw)
  * :red_circle: install-bookinfo [#[1112]](https://paste.fedoraproject.org/paste/rS5DGFxdz7Bfg-epZAV7hA)


KIALI_NAME=kialicorepr583-istio-system

**Comment by rhqci** [comment]
:heavy_check_mark: Jenkins CI: kiali-core-pr-e2e-test [#243](https://paste.fedoraproject.org/paste/t2Cl3p9sJyPNyRaaeNNDJA)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[1740]](https://paste.fedoraproject.org/paste/JcFR9xw3AxCbEW33qYBZ2w)
  * :heavy_check_mark: Istio-Upstream [#[587]](https://paste.fedoraproject.org/paste/IZEwPMr6~0XAbM2-oKeGFg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2025, 2026]](https://paste.fedoraproject.org/paste/iL1ePgVGCHf7fjwBDT2vBg)
  * :heavy_check_mark: install-bookinfo [#[1114]](https://paste.fedoraproject.org/paste/CtjLn3hTYsjjrEhyuoeOtQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[1105]](https://paste.fedoraproject.org/paste/H0qpRvuPMy2DsZ~MJaw9xg)
  * :heavy_check_mark: run-kiali-e2e-tests [#[514]](https://paste.fedoraproject.org/paste/aVM4tMayIQCkd5MSbqiEqQ)


KIALI_NAME=kialicorepr583-istio-system

**Comment by jshaughn** [comment]
+1 to this approach.

**Pull request merged**
