### PR TITLE
change  observability name  GetApp

### PR DESCRIPTION
**Pull request by wangzhipeng**
change  observability name  GetAppList to   GetApp

### CODE REVIEW

**Comment by jmazzitelli** [comment]
@nrfox I added you as reviewer - can you just do a real quick scan to see if anything else like this happened in that new tracing code? Best to check it all now and fix anything else we find in this one PR.

**Review by nrfox — APPROVED** [review]
Good eye!

**Comment by nrfox** [comment]
> @nrfox I added you as reviewer - can you just do a real quick scan to see if anything else like this happened in that new tracing code? Best to check it all now and fix anything else we find in this one PR.

Just saw your comment before I approved. Sure I'll look over the rest of the tracing names.

**Review by Xunzhuo — APPROVED** [review]
lgtm:)

**Comment by nrfox** [comment]
> @nrfox I added you as reviewer - can you just do a real quick scan to see if anything else like this happened in that new tracing code? Best to check it all now and fix anything else we find in this one PR.

Scanning through I didn't find any others. Merging this.

**Pull request merged**
