### PR TITLE
Remote cluster configs validation

### PR DESCRIPTION
**Pull request by hhovsepy**
RFE https://github.com/kiali/kiali/issues/5967
Subtask: https://github.com/kiali/kiali/issues/6056

Istio config list and details shows validations from remote clusters.

Screenshot from 2023-06-06 19-40-51
Screenshot from 2023-06-06 19-40-38

### CODE REVIEW

**Comment by hhovsepy** [comment]
The failing test is not related to changes.

**Review by jshaughn — APPROVED** [review]
I didn't run this but it visually looks good.

I wish we had adopted a convention to always have `cluster, namespace` in parameter lists and so forth, I don't like that `cluster` shows up in random places in arg lists, but it's obviously not a blocker, just a personal preference.

**Comment by jshaughn** [comment]
@hhovsepy I approved visually, but obviously the Cypress tests need to pass.

**Review by leandroberetta — APPROVED** [review]
LGTM.

**Pull request merged**
