### PR TITLE
[1.73] Add absolute script dir path in setup-kind-ci.sh script (#6755)

### LINKED ISSUE #6750: setup-kind-ci.sh script fails if it is not executed from root folder
The script setup-kind-ci.sh fails if it is executed from any folder except kiali root:

image

Path to hack/istio/download-istio.sh should be absolute and not relative.

### PR DESCRIPTION
**Pull request by ferhoyos**
**Describe the change**

Backport of #6755 to version 1.73. There are more changes than in referenced PR because there are previous PRs modifying this file that have not been backported. For this reason I have pushed the latest version of the hack script into v1.73.

**Issue reference**

Closes #6750

### CODE REVIEW

**Review by jmazzitelli — APPROVED** [review]

**Comment by aljesusg** [comment]
Sorry but Why we need to backport this? It's not a bug in the product. Do we need it to test something?

**Comment by jmazzitelli** [comment]
> Sorry but Why we need to backport this? It's not a bug in the product. Do we need it to test something?

I assumed it was to be able to run the tests within this branch (??)

**Comment by ferhoyos** [comment]
Actually the bug does not break the tests, it is just only for developers. I set the backport label to this bug by mistake. Anyway, since it is done and reviewed, there is no harm to backport this change, right?

**Comment by jmazzitelli** [comment]
no harm.

**Pull request merged**
