### PR TITLE
Disable cache on mocked api_test

### PR DESCRIPTION
**Pull request by lucasponce**
Related to #2508 

Not sure if it fixed completely, but I'm preparing one PR with my findings.

### CODE REVIEW

**Comment by lucasponce** [comment]
Note, this one is not yet finished, there are a lot of tests that create a custom conf and it requires additional checking.

**Comment by israel-hdez** [comment]
Throwing an idea.
Like other config variables, perhaps it would be OK to read a `CACHE_ENABLED` environment value? The difference is that this would need to be done in the NewConfig method.
If it exists, the value is set to the envvar. If not, then `true` by default.

That way we could set the envvar in the Makefile targets (see https://github.com/kiali/kiali/blob/master/make/Makefile.build.mk#L53-L65) with minimum changes to the code and tests.

**Comment by jmazzitelli** [comment]
> Like other config variables, perhaps it would be OK to read a `CACHE_ENABLED` environment variable?

Several months ago, we ripped out the code to have all the config settings to be read from env. variables. It made the code complex, and hard to understand where the values were coming from. So the ONLY settings we pass through via env vars today are security related (so, for example, you can pass credential or signing key values via env. vars - usually used in combination with secrets).

I would avoid re-introducing more env. variables that are un-related to security values unless we have a good reason to do so. For this particular test issue, isn't there a way we can pass in test config .yaml?

**Comment by israel-hdez** [comment]
@jmazzitelli 

> For this particular test issue, isn't there a way we can pass in test config .yaml

In unit tests, we are not reading a yaml :-(
It's just the hardcoded defaults and tests customize the defaults depending on the goals of the tests.
Not sure really how we could avoid that.

**Pull request merged**
