### PR TITLE
Return 403 instead 500 for accessible_namespaces filtered queries

### LINKED ISSUE #1906: Incorrect Error Code Returned
There are a few API automation tests that fail when run against the master branch due to the unexpected error codes being returned for some negative tests. The three examples below return the error of 404 in the 1.0 branch, though in master they return an error 500.

api/namespaces/invalid/workloads/details-v1
api/namespaces/invalid/apps/ratings
api/namespaces/invalid/istio/rules/promtcp

E2E Test:  test_api_methods -> test_engative_404

### PR DESCRIPTION
**Pull request by lucasponce**
Ignore a namespace included in accessible_namespaces that does not exist

Fix #1906

### CODE REVIEW

**Comment by lucasponce** [comment]
@mattmahoneyrh if you can test this one against the i-tests and validate it looks ok, that would be great.

Thanks.

**Comment by jshaughn** [comment]
@mattmahoneyrh Yes, I think that is the new, anticipated status code.  403 means Forbidden.  We can't distinguish between a namespace that doesn't exist or is simply inaccessible.  So 403/Forbidden seems to make sense.

**Comment by mattmahoneyrh** [comment]
@ jshaughn, that's fine - just sanity checking - good to merge from my testing.

**Comment by lucasponce** [comment]
@jshaughn thanks for the feedback.

> /api/namespaces/invalid/health. That one still returns a 500.

Let me address this, as this one fetches from p8s perhaps something else was missing in my fix.

> This is probably unrelated and maybe has to do with cache refresh? But when sitting on the Overview page, and configuring a new, valid namespace, it generates errors for a while before settling down. For example, I added bookinfo and the bookinfo card appeared, but it was unable to fill in the card for about 30-45 seconds I think. During that time I repeatedly got the same toast messages [...]

I'm going to investigate this. Can you give me more details ? Did you enabled caching ? In which environment you tested ? And, what steps did you follow to add a new namespace (I guess you added into the ServiceMeshMemberRoll entry, and next you changed the Kiali CR) ?

I'm going to try to reproduce it locally. I will update this thread.

**Comment by lucasponce** [comment]
I've address the health enpoints.

About your last comment @jshaughn I'd like to investigate more, but I need more details. 
Caching is disabled by default, so unless you explicictly enabled it, we may be hitting a different thing here (i.e. wondering if it's the case where Kiali pod is being recreated and the UI is again constantly hitting).

Perhaps one thing we can do in Kiali is to have a general poll to kiali backend, if that /status query doesn't respond, just to block all queries to the backend and re-enable them when the basic health is up again.

Then, Kiali UI would handle nicely when pod is down like "backend is not available" instead to fill the UI with error messages.

This is not a minor thing so it would require a separate issue as it would need a non small refactoring in the code.

**Comment by jshaughn** [comment]
@lucasponce OK, it doesn't sound like caching, then, because I did not enable anything.  Basically I did the following:
1. created OS 4.2 env on AWS with Istio 1.4
2. build/push/install Kiali operator/kiali built from master

At this point bookinfo doesn't exist and is not an accessible namespace

3, install bookinfo (but I think this could just be the creation of any new namespace)
4. leave kiali UI refreshing at 10s interval on Overview page
5. edit Kiali CR and add:
```
deployment:
  accessible_namespaces:
  - default
  - istio-system
  - bookinfo
```

Go back and watch overview page while kiali operator applies the CR change.  Bookinfo card appears but is not filled in, errors generate/repeat for a while, then it settles down.

**Comment by lucasponce** [comment]
Ok, @jshaughn that info is good to start, I suspect where it could be

**Comment by lucasponce** [comment]
@jshaughn ok, I think I found the problem.
accessible_namespaces is not used in OpenShift environments for the GetNamespaces() query.
But we use to filter the access in general.

So, it looks there is a mismatch here, that affects in scenarios as you point.

**Comment by jshaughn** [comment]
> accessible_namespaces is not used in OpenShift environments for the GetNamespaces() query.

interesting

**Comment by lucasponce** [comment]
If userA can see ns1, ns2 and ns3 projects, but accessible_namespaces is ns1, and ns2 only.
Then GetNamespaces() returns [ns1, ns2 and n3] BUT a GetNamespace() is filtering the accessible_namespaces.

So, on this case, probably a ns3 based query can lead in the issues you are facing there.

**Comment by lucasponce** [comment]
I understand that how this was designed, was that if ** is set, then all ns1, ns2 and ns3 should be shown. But if accessible_namespaces is set, it should also be filtered by that.

Am I right here @jshaughn ?

**Comment by jmazzitelli** [comment]
> (I guess you added into the ServiceMeshMemberRoll entry, and next you changed the Kiali CR) ?

FYI: you should never do this. If you are using Kiali with Service Mesh, you should never edit Kiali CR. You ONLY edit ServiceMeshMemeberRole CR and ServiceMesh will manage Kiali CR for you (just like it manages any other resource Service Mesh operator creates like Deployments, ConfigMaps, etc). If you edit Kiali CR, you will clash with the ServiceMesh operator making its own edits in the Kiali CR. The only time you edit Kiali CR yourself is if you installed Kiali operator yourself (i.e. it was not a dependency of another operator) -  such as is the case with upstream Istio today. If you install upstream Istio and you install Kiali operator, then you can edit the Kiali CR.

> I understand that how this was designed, was that if ** is set, then all ns1, ns2 and ns3 should be shown. But if accessible_namespaces is set, it should also be filtered by that.

If accessible_namespaces is set to "**" then it is assumed Kiali has been given cluster role access to every namespace that exists, and new namespaces that might be created in the future. If accessible_namespaces is set to something other than **, then only those namespaces are assumed to be accessible to Kiali so only those should be shown (if they do not exist, Kiali should ignore them -- but I actually thought the Kiali Operator will strip those out and not put them in accessible_namespaces (see [this code](https://github.com/kiali/kiali/blob/v1.9.1/operator/roles/kiali-deploy/tasks/main.yml#L332-L344)) - but there is nothing stopping a user from editing the ConfigMap and putting bad/non-existence namespaces in the ConfigMap - this is another reason why operators are good - they help to ensure correct/valid data only shows up in the ConfigMap.

**Pull request merged**
