### PR TITLE
Added missing clusterName param in graph sidepanel 'Show Traces' button

### PR DESCRIPTION
**Pull request by hhovsepy**
Issue https://github.com/kiali/kiali/issues/6815

Added missing clusterName param, added tests.

### CODE REVIEW

**Review by josunect — CHANGES_REQUESTED** [review]
Thanks for the PR, @hhovsepy !

When I click in the "Show Span" button, it is still missing the clusterName:

image

image

I think it is related to: https://github.com/kiali/kiali/blob/master/frontend/src/pages/Graph/SummaryPanelTraceDetails.tsx#L223

**Comment by hhovsepy** [comment]
Thank you @josunect , I did added also into the "Trace" url above.

**Review by josunect — APPROVED** [review]
LGTM! 
Now the Show traces button redirects correctly to the trace: 

image

I can see the trace is not pre-visualized, but probably it can be addressed on a new issue. 

Code looks good. 
Thanks, @hhovsepy

**Comment by hhovsepy** [comment]
I see the trace is more blueish, but details are not loaded, probably another issue.

**Pull request merged**
